Repository cdapio/cdap, pull requests merged in 2018-04, with the labels that each got.

#10003 (CDAP-13234) Refactoring DistributedProgramRunnableModule
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnableModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/guice/DistributedProgramRunnableModuleTest.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: 5.0

#10000 [CDAP-12898] add Reports Customizer section
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/AppTypeSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/ColumnsSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/Customizer.scss
  cdap-ui/app/cdap/components/Reports/Customizer/TimeRangeSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/index.js
  cdap-ui/app/cdap/components/Reports/Reports.scss
  cdap-ui/app/cdap/components/Reports/index.js
  cdap-ui/app/cdap/components/Reports/store/ReportsStore.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10012 Add Dropdown for Control Center
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/ControlCenterDropdown.scss
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/index.js
  cdap-ui/app/cdap/components/Header/Header.scss
  cdap-ui/app/cdap/components/Header/MetadataDropdown/index.js
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10015 [CDAP-13213] Fixes select widget to use the property widget attribute from the spec
  cdap-ui/app/cdap/components/AbstractWidget/MemorySelectWidget/index.js
  cdap-ui/app/cdap/components/AbstractWidget/SelectWidget/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/sample-view-spec.json
Labels: 5.0, UI

#10016 [CDAP-13279][UI] Renames grid-item to grid-row for better readability
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/DetailedViewModelsTable.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/ListView.scss
  cdap-ui/app/cdap/components/Experiments/ListView/ListViewWrapper.js
  cdap-ui/app/cdap/components/NamespaceDetails/ComputeProfiles/ComputeProfiles.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsTable/RunsTable.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsTable/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/Reports/ReportsList/ReportsList.scss
  cdap-ui/app/cdap/components/Reports/ReportsList/index.js
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/styles/common.less
Labels: 5.0, UI

#10013 (CDAP-13234) Added a common base class for consuming messages from TMS
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/package-info.java
Labels: 5.0

#9701 [CDAP-12426] Enable update keytab location and reload keytab file of namespace
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceConfig.java
  cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceMeta.java
Labels: 5.0

#10020 (CDAP-13234) Group factoring commits
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/EntityVerifierModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AuthorizationHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramMessagePublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/InMemoryEntityExistenceVerifier.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRunnerTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/entity/EntityExistenceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-common/pom.xml
  cdap-common/src/main/java/co/cask/cdap/common/entity/DefaultEntityExistenceVerifier.java
  cdap-common/src/main/java/co/cask/cdap/common/transaction/MultiThreadTransactionAware.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/MultiThreadDatasetCache.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/AbstractMessagePublisher.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/BasicMessageFetcher.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/BasicMessagePublisher.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/BasicMessagingAdmin.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/BasicMessagingContext.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/DirectMessagePublisher.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/MessageIterator.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/MultiThreadMessagingContext.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/context/package-info.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 5.0

#10024 (CDAP-13234) Emits data access lineage to TMS in distributed mode
  cdap-api-common/src/main/java/co/cask/cdap/api/common/Bytes.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnableModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/meta/RemoteLineageWriterHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/meta/RemoteSystemOperationsServiceModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/remote/RemoteLineageWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/remote/RemoteLineageWriterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/service/Retries.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/DefaultAuditPublisher.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/DefaultLineageStoreReader.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStoreReader.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageStoreWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/DataAccessLineage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/metrics/TransactionManagerMetricsCollector.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriterTest.java
  cdap-docs/admin-manual/build.sh
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/co/cask/cdap/master/startup/ConfigurationCheck.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/MessagingServices.java
Labels: 5.0

#10006 [CDAP-13236] Allows editing of keytabURI of a namespace in UI
  cdap-ui/app/cdap/api/namespace.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/GeneralInfoStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/MappingStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/PreferencesStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/SecurityStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/index.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStoreActions.js
  cdap-ui/app/cdap/components/NamespaceDetails/NamespaceDetails.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Security/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/index.js
  cdap-ui/app/cdap/components/Wizard/index.js
  cdap-ui/app/cdap/services/WizardStores/AddNamespace/ActionCreator.js
  cdap-ui/app/cdap/services/WizardStores/AddNamespace/AddNamespaceActions.js
  cdap-ui/app/cdap/services/WizardStores/AddNamespace/AddNamespaceStore.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 5.0, UI

#10029 (CDAP-13234) Emits dataset usage information to TMS in distributed mode
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnableModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/stream/DefaultStreamWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/meta/RemoteSystemOperationsServiceModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/meta/RemoteUsageRegistryHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/ConsumerSupplier.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/messaging/TopicMessageIdStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/remote/RemoteRuntimeUsageRegistry.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/remote/RemoteRuntimeUsageRegistryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataMessage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/BasicUsageRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/DatasetUsage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/DefaultUsageRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/MessagingUsageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/transaction/stream/FileStreamAdmin.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/registry/UsageRegistryTest.java
  cdap-docs/admin-manual/build.sh
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Labels: 5.0

#10009 [CDAP-13212] Adds Profile Preview for historical runs of pipelines.
  cdap-ui/app/cdap/api/cloud.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/Preview.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/RunComputeProfile.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/index.js
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/components/RulesEngineHome/RuleBook/RuleBook.scss
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
  cdap-ui/app/cdap/styles/mixins.scss
Labels: 5.0, UI

#10025 [CDAP-13208] Allow users to add profiles to schedules in pipeline
  cdap-ui/app/cdap/components/PipelineScheduler/AdvancedView.js
  cdap-ui/app/cdap/components/PipelineScheduler/BasicView/IntervalOption.js
  cdap-ui/app/cdap/components/PipelineScheduler/BasicView/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/PipelineScheduler.scss
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/ProfilesForSchedule.scss
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/ViewContainer.js
  cdap-ui/app/cdap/components/PipelineScheduler/index.js
Labels: 5.0, UI

#10005 Adding server for polling client
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/handler/RuntimeHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorConsumeRequest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/RuntimeServer.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 5.0

#10037 (CDAP-13240) Added a config for default tx control
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerDriver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/CustomActionExecutor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-master/src/main/java/co/cask/cdap/master/startup/ConfigurationCheck.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/service/SparkHttpServiceServer.java
Labels: 5.0

#10032 Added the ProvisionerHttpHandler to app-fabric service
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProvisionerHttpHandler.java
Labels: 5.0

#10040 (CDAP-13300) Avoid recursive call when getting lineage dataset
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetCache.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/LineageWriterDatasetFramework.java
Labels: 5.0

#10036 (CDAP-13234) Refactor Guice modules used in various program TwillRunnable
  cdap-app-fabric-tests/pom.xml
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/app/runtime/spark/distributed/SparkTwillRunnableModuleTest.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedArtifactManagerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnableModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/FlowletTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/ServiceTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WebappTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/guice/DistributedProgramRunnableModuleTest.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/stream/hbase/HBaseStreamConsumerTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricDistributedModule.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
Labels: 5.0

#10008 Feature/cdap 13149 fll platform api
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/EndPoint.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/InputField.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/LineageRecorder.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/Operation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/OperationType.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/ReadOperation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/TransformOperation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/WriteOperation.java
Labels: 5.0

#10052 (CDAP-13234) Refactor Runtime Monitor server to be Guice ready
  cdap-api/src/main/java/co/cask/cdap/api/messaging/MessagingContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-security/src/main/java/co/cask/cdap/security/tools/KeyStores.java
Labels: 5.0

#10057 (CDAP-13316) Fix SingleThreadDatasetCache invalidation logic
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/cache/DynamicDatasetCacheTest.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkTransactional.java
  cdap-spark-core-base/src/main/scala/co/cask/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
Labels: 5.0

#10058 update lock file
  cdap-ui/yarn.lock
Labels: 5.0, UI

#10034 CDAP-13266 Field Level Lineage plugin API.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/EndPoint.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/FieldOperationEmitter.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/Operation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/OperationType.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/ReadOperation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/TransformOperation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/lineage/field/WriteOperation.java
Labels: 5.0

#10065 Fix preferences levels in UI to not default to system
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/AdminConfigTabContent.scss
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/SystemPrefsAccordion/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
Labels: 5.0, Bug, UI

#10056 [CDAP-13113][MMDS] New experiment/model create flow integration with backend
  cdap-ui/app/cdap/api/experiments.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/DetailedViewModelsTable.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/app/cdap/components/PieChart/index.js
Labels: 5.0, UI

#10059 [CDAP-13276] Adds import/export/delete profile functionality in UI
  cdap-ui/app/cdap/api/cloud.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/SystemProfilesAccordion/SystemProfilesAccordion.scss
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/SystemProfilesAccordion/index.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/ComputeProfiles/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10074 Fix a bug in key removal during deprovision
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
Labels: 5.0

#10075 (CDAP-13234) Runtime Monitor improvements
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
Labels: 5.0

#10083 (CDAP-13234) Better management of TMS subscriber threads.
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 5.0

#9966 [CDAP-13211] Ops Dashboard Report Generation App
  cdap-app-templates/cdap-program-report/pom.xml
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/ReportGenerationApp.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/ReportGenerationSpark.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/package-info.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/Filter.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/FilterDeserializer.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/RangeFilter.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportContent.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportGenerationInfo.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportGenerationRequest.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportList.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportStatus.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportStatusInfo.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/Sort.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ValueFilter.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/util/Constants.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/util/ProgramRunMetaFileUtil.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/util/ReportField.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/util/ReportIds.java
  cdap-app-templates/cdap-program-report/src/main/scala/co/cask/cdap/report/Record.scala
  cdap-app-templates/cdap-program-report/src/main/scala/co/cask/cdap/report/RecordAggregator.scala
  cdap-app-templates/cdap-program-report/src/main/scala/co/cask/cdap/report/RecordBuilder.scala
  cdap-app-templates/cdap-program-report/src/main/scala/co/cask/cdap/report/ReportGenerationHelper.scala
  cdap-app-templates/cdap-program-report/src/test/java/co/cask/cdap/report/ReportGenerationAppTest.java
  cdap-app-templates/pom.xml
  cdap-explore/pom.xml
  cdap-integration-test/src/main/java/co/cask/cdap/test/IntegrationTestManager.java
  cdap-test/src/main/java/co/cask/cdap/test/TestManager.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/UnitTestManager.java
Labels: 5.0

#10088 (CDAP-13370) Local data-fabric must be using local transaction manager.
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricLevelDBModule.java
Labels: 5.0

#10089 [CDAP-13347] Also shows system profiles in Namespace Details page
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
Labels: 5.0, UI

#10084 [CDAP-13209] Integrates profiles with pipeline triggers
  cdap-ui/app/cdap/components/CollapsibleSidebar/CollapsibleSidebar.scss
  cdap-ui/app/cdap/components/ConfigurableTab/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/PayloadConfigModal.scss
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineTriggersRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgs.scss
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsStore.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/ComputeConfigTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/ScheduleRuntimeTabStyling.scss
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/TabConfig.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/index.js
  cdap-ui/app/cdap/components/Tabs/TabGroup/TabGroup.scss
  cdap-ui/app/cdap/components/Tabs/TabGroup/index.js
  cdap-ui/app/cdap/components/Tabs/TabHead/TabHead.scss
  cdap-ui/app/cdap/components/Tabs/TabHead/index.js
  cdap-ui/app/cdap/components/Tabs/TabHeaders/TabHeaders.scss
  cdap-ui/app/cdap/components/Tabs/TabHeaders/index.js
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/styles/common.less
Labels: 5.0, UI

#10096 Label change from Provider to Provisioner
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/RuntimeArgsTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/ScheduleRuntimeTabStyling.scss
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/StagePropertiesTab/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10048 CDAP-13314 Added validations and checksum for the Lineage graph.
  cdap-app-fabric/src/main/java/co/cask/cdap/lineage/field/FieldLineageInfo.java
  cdap-app-fabric/src/main/java/co/cask/cdap/lineage/field/codec/OperationTypeAdapter.java
  cdap-app-fabric/src/test/java/co/cask/cdap/lineage/field/FieldLineageInfoTest.java
Labels: 5.0

#10100 fix application name in dashboard
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
Labels: 5.0, Bug, UI

#10101 (CDAP-13395) Fix Spark guice modules
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/app/runtime/spark/distributed/SparkTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/ClusterMode.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramStreamModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: 5.0

#10086 (CDAP-13234) Move the fetching of messageId to regular iteration to a…
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 5.0

#10105 fix unauthorized metrics search call in pipeline
  cdap-ui/app/cdap/api/metric.js
  cdap-ui/app/cdap/services/PipelineMetricsStore/ActionCreator.js
Labels: 5.0, Bug, UI

#10106 (CDAP-13234) Save 10 seconds on (de)provisioning
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionTask.java
Labels: 5.0

#10094 (CDAP-13370) Fix the metrics collection for transaction manager
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricDistributedModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricInMemoryModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricLevelDBModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/HDFSTransactionStateStorageProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/TransactionManagerProvider.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TransactionServiceTwillRunnable.java
Labels: 5.0

#10102 fix overflow of body in collapsible sidebar
  cdap-ui/app/cdap/components/CollapsibleSidebar/CollapsibleSidebar.scss
Labels: 4.3, Bug, UI
