Repository cdapio/cdap, pull requests merged in 2018-06, with the labels that each got.

#10159 [CDAP-13484] Fixes profile customization in pipeline detailed view.
  cdap-ui/app/cdap/components/Accordion/AccordionTitle/index.js
Labels: 5.0, Bug, UI

#10123 [CDAP-13079] Adds error handling in UI for MMDS
  cdap-ui/app/cdap/components/Alert/Alert.scss
  cdap-ui/app/cdap/components/Alert/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/MLAlgorithmSelection/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/SplitDataStep/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/DeleteExperimentBtn/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/DeleteModelBtn/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/DetailedView.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentMetricsDropdown/AlgorithmDistribution.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/HyperParamsPopover/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelStatusIndicator/ModelStatusIndicator.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelStatusIndicator/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/DetailedViewModelsTable.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/ListViewWrapper.js
  cdap-ui/app/cdap/components/Experiments/ListView/index.js
  cdap-ui/app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/ExperimentDetailActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/ExperimentsListActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/SharedActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/createExperimentStore.js
  cdap-ui/app/cdap/components/Experiments/store/experimentDetailStore.js
  cdap-ui/app/cdap/components/Experiments/store/index.js
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
Labels: 5.0, UI

#10179 REST api with mock data and relavant classes in the proto.
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHandler.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldLineageDetails.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldLineageSummary.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldLineageSummaryRecord.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldOperationInfo.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldOperationInput.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/FieldOperationOutput.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/ProgramFieldOperationInfo.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/ProgramInfo.java
Labels: 5.0

#10183 [CDAP-13388] Updates the profile property lock/unlock tooltips text
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/PropertyLock/index.js
Labels: 5.0, Bug, UI

#10185 [MMDS][Cloud][UI] Fix language in MMDS and Profiles in pipelines
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataProcProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gce-dataproc.json
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateProfileBtn/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateProfileMetadata/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfilesListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/ProfilesForSchedule.scss
Labels: 5.0, Bug, UI

#10180 [CDAP-13455][CDAP-13515] Fixes choosing profile for schedule
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/Provisioners.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/ConfigModelessSaveBtn.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfilesListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/ViewContainer.js
Labels: 5.0, Bug, UI

#10107 Metadata Plugin API
  cdap-app-templates/cdap-data-quality/src/test/java/co/cask/cdap/dq/testclasses/StreamBatchSource.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/StageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/AbstractTransformContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/action/MockActionContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/transform/MockTransformContext.java
Labels: 5.0

#10151 [CDAP-13461] Cloud/pipeline cleanup
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/PropertiesTab.js
  cdap-ui/app/cdap/components/DatasetDetailedView/Tabs/PropertiesTab.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/index.js
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineScheduleButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/RunComputeProfile.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLogs.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/components/StreamDetailedView/Tabs/PropertiesTab.js
  cdap-ui/app/cdap/components/Tags/Tag/Tag.scss
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/Tags.scss
  cdap-ui/app/cdap/components/Tags/index.js
  cdap-ui/app/cdap/services/fast-action-message-helper.js
  cdap-ui/app/cdap/styles/mixins.scss
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/adapters.less
Labels: 5.0, Bug, UI

#10172 [CDAP-13469] collapse status STOPPED to STOPPED and KILLED
  cdap-ui/app/cdap/components/Reports/ReportsList/ActionPopover.js
  cdap-ui/app/cdap/components/Reports/store/ActionCreator.js
Labels: 5.0, UI

#10184 Field Lineage List
  cdap-ui/app/cdap/api/metadata.js
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/Fields.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
Labels: 5.0, UI

#10178 [CDAP-13457][CDAP-13470][CDAP-13476] Bugfixes/improvements in Reports UI
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/StatusPopover.js
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/StatusSelector.scss
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/StatusViewer.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Runs/Runs.scss
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Runs/index.js
  cdap-ui/app/cdap/components/Reports/ReportsList/ReportsList.scss
  cdap-ui/app/cdap/components/Reports/store/ReportsStore.js
Labels: 5.0, Bug, UI

#10192 [CDAP-13390] Adds visual feedback on View link in profiles list
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfilesListViewInPipeline.scss
Labels: 5.0, Bug, UI

#10191 [CDAP-13474][CDAP-13475] Adds i18n for Ops Dashboard and Reports
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/NamespacesPicker/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/Legends/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsTable/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/ToggleRunsList.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/TypeSelector/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/ActionButtons/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/AppTypeSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/ColumnsSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/StatusPopover.js
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/StatusViewer.js
  cdap-ui/app/cdap/components/Reports/Customizer/StatusSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/TimeRangeSelector/TimeRangePopover.js
  cdap-ui/app/cdap/components/Reports/Customizer/TimeRangeSelector/index.js
  cdap-ui/app/cdap/components/Reports/Customizer/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Expiry/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Runs/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/SaveButton/SaveModal.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/SaveButton/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Summary/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/index.js
  cdap-ui/app/cdap/components/Reports/ReportsList/ActionPopover.js
  cdap-ui/app/cdap/components/Reports/ReportsList/index.js
  cdap-ui/app/cdap/components/Reports/ReportsServiceControl/index.js
  cdap-ui/app/cdap/components/Reports/index.js
  cdap-ui/app/cdap/components/Reports/store/ActionCreator.js
  cdap-ui/app/cdap/components/TimeRangePicker/index.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10195 (CDAP-13532) Fix the workflow resources setting to honor runtime arguments
  cdap-api/src/main/java/co/cask/cdap/api/common/RuntimeArguments.java
  cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowActionNode.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowTestApp.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/program/Programs.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/DefaultProgramWorkflowRunner.java
  cdap-docs/developer-manual/source/advanced/configuring-resources.rst
Labels: 5.0

#10194 add fll search capability
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/Fields.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/Search.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
Labels: 5.0, UI

#10206 [CDAP-13509] fll operations modal
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/LineageSummary.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/Navigation.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsModal.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsTable.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
Labels: 5.0, UI

#10209 [CDAP-13510] add basic time range picker
  cdap-ui/app/cdap/components/FieldLevelLineage/FieldLevelLineage.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/TimePicker/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10188 (CDAP-13252) Enabling two-ways HTTPS authentication for runtime monitor
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorClient.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/StandaloneAppFabricServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ClusterInfo.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/DefaultSSHContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerNotifier.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/SecureKeyInfo.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/ssh/DefaultSSHSession.java
  cdap-common/src/main/java/co/cask/cdap/common/ssh/SSHConfig.java
  cdap-common/src/test/java/co/cask/cdap/common/ssh/SSHSessionTest.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/ssh/SSHSession.java
  cdap-security/src/main/java/co/cask/cdap/security/tools/HttpsEnabler.java
  cdap-security/src/main/java/co/cask/cdap/security/tools/KeyStores.java
  cdap-security/src/main/java/co/cask/cdap/security/tools/SSLHandlerFactory.java
  cdap-security/src/test/java/co/cask/cdap/security/tools/HttpsEnablerTest.java
  cdap-security/src/test/java/co/cask/cdap/security/tools/KeyStoresTest.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: 5.0

#10199 [MMDS][CDAP-13385] Improve representation of model metrics
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 5.0, Bug, UI

#10200 [MMDS][CDAP-13383] Fix directives representation for a model consistent
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
Labels: 5.0, Bug, UI

#10202 [MMDS][CDAP-13547] Fix button label while creating experiment vs adding a model in MMDS
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/Popovers/ExperimentPopovers.scss
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/store/createExperimentStore.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
Labels: 5.0, Bug, UI

#10208 [CDAP-13536] CDAP UI Header and Footer Changes
  cdap-ui/app/cdap/components/Footer/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10196 [MMDS][CDAP-13128] UX fixes in experiment detailed view in MMDS
  cdap-ui/app/cdap/components/CopyableID/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentMetricsDropdown/ModelStatusesDistribution.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentMetricsDropdown/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/MetricChartWithLegend/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelStatusIndicator/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/DetailedViewModelsTable.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/TopPanel/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/ExperimentsListBarChart/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/ListView.scss
  cdap-ui/app/cdap/components/Experiments/ListView/ListViewWrapper.js
  cdap-ui/app/cdap/components/IconSVG/index.js
  cdap-ui/app/cdap/styles/variables.scss
  cdap-ui/webpack.config.cdap.js
Labels: 5.0, UI

#10217 CDAP-13567: Fix cdap-spark-scala and cdap-mapreduce archetype
  cdap-archetypes/cdap-mapreduce-archetype/src/main/resources/archetype-resources/src/main/java/MapReduceApp.java
  cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansProgram.scala
Labels: 4.3

#10219 Updates yarn.lock file for moment-timezone
  cdap-ui/yarn.lock
Labels: 5.0, Bug, UI

#10216 (CDAP-13342) Process metrics from TMS on SDK
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MessagingMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/DistributedMetricsClientModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsClientRuntimeModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsStoreModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/MetricsTestBase.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/collect/MessagingMetricsCollectionServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTestBase.java
Labels: 5.0

#10229 [CDAP-13482] Updates defaults for master and worker node configurations for datapr…
  cdap-runtime-ext-dataproc/src/main/resources/gce-dataproc.json
Labels: 5.0, Bug, UI

#10221 CDAP-13391 log provisioner messages in program context
  cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/preview/PreviewHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerNotifier.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisioningTask.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramRunCluster.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramRunClusterStatus.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/context/LoggingContextHelper.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/AbstractLogHandler.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/ProgramStore.java
Labels: 5.0

#10204 Metrics integration
  cdap-app-fabric-tests/pom.xml
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithMapReduceUsingAvroDynamicPartitioner.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/batch/DynamicPartitionerWithAvroTest.java
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorConsumeRequest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorMessage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorSchemas.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorClient.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/resources/schema/v1/MonitorConsumeRequest.avsc
  cdap-app-fabric/src/main/resources/schema/v1/MonitorResponse.avsc
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
Labels: 5.0

#10235 CDAP-13088 Make metadata version independent
  cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataKey.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataKeyTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/EntityId.java
  cdap-proto/src/test/java/co/cask/cdap/proto/id/EntityIdTest.java
Labels: 5.0

#10241 [CDAP-13613] Fixes bower registry to be the new one
  cdap-ui/.bowerrc
  cdap-ui/pom.xml
Labels: 4.3, Bug, UI

#10198 Change default spark version
  cdap-app-fabric/src/test/resources/cdap-site.xml
  cdap-cli-tests/pom.xml
  cdap-client-tests/pom.xml
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-examples/Purchase/src/test/resources/cdap-site.xml
  cdap-master/src/test/resources/cdap-site.xml
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-unit-test-spark2_2.11/src/main/resources/cdap-site.xml
  cdap-unit-test/src/main/resources/cdap-site.xml
Labels: 5.0

#10236 [CDAP-13263] Consume Metadata Changes from TMS
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/StreamSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ViewSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataMessage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataOperation.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataWriter.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java
Labels: 5.0

#10244 [CDAP-13351] UI fix non existing status field for future scheduled run
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
Labels: 5.0, UI

#10233 CDAP-13358 rename 'default' profile to 'native'
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultEntityEnsurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/config/UserPreferencesStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/SystemArgumentsTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/ProfileId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/profile/Profile.java
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 5.0

#10246 [CDAP-13613] Fixes bower registry to be the new one
  cdap-ui/.bowerrc
  cdap-ui/pom.xml
Labels: 5.0, Bug, UI

#10245 CDAP-13338 restrict profile program types
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/SystemArgumentsTest.java
Labels: 5.0

#10232 [CDAP-13556] add link to field level lineage
  cdap-ui/app/cdap/components/DatasetDetailedView/DatasetDetailedView.scss
  cdap-ui/app/cdap/components/DatasetDetailedView/Tabs/LineageTab.js
  cdap-ui/app/tracker/controllers/lineage-ctrl.js
  cdap-ui/app/tracker/templates/lineage.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.0, UI

#10228 Feature/adding program options state writer
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/MessagingProgramStatePublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/ProgramStatePublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/RunRecordCorrectorService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/program/ProgramStateWriterWithHeartBeatTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-proto/src/main/java/co/cask/cdap/proto/Notification.java
Labels: 5.0

#10226 [CDAP-13473] Adds pagination to Reports detail view in UI
  cdap-ui/app/cdap/components/PaginationWithTitle/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/RunsPagination/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/index.js
  cdap-ui/app/cdap/components/Reports/store/ActionCreator.js
  cdap-ui/app/cdap/components/Reports/store/ReportsStore.js
Labels: 5.0, UI

#10239 [CDAP-13609] fix flaky MessagingMetricsProcessorServiceTest
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
Labels: 5.0

#10237 CDAP-13601 Added rules for field lineage endpoints in RouterPathLookup.
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathLookupTest.java
Labels: 5.0

#10223 CDAP-13432 publish event to tms to update profile metadata
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/PreferencesHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DistributedNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/LocalNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/AdminEventPublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataMessageProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/config/UserConfigStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetadataTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/EntityIdKeyHelper.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataMessage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/NamespaceMDS.java
  cdap-proto/src/main/java/co/cask/cdap/proto/element/EntityTypeSimpleName.java
Labels: 5.0

#10250 [CDAP-13624] Improve code quality in router lookup
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathLookupTest.java
Labels: 5.0

#10247 CDAP-13297 implement program stop during provisioning
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/RunRecordCorrectorService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningOp.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/MockProvisioner.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
Labels: 5.0

#10252 [CDAP-13472] Adds pagination to Reports list view in UI
  cdap-ui/app/cdap/components/Reports/ReportsList/ReportsList.scss
  cdap-ui/app/cdap/components/Reports/ReportsList/ReportsPagination.js
  cdap-ui/app/cdap/components/Reports/ReportsList/index.js
  cdap-ui/app/cdap/components/Reports/store/ActionCreator.js
  cdap-ui/app/cdap/components/Reports/store/ReportsStore.js
Labels: 5.0, UI

#10253 [CDAP-13269] fix api change for field level lineage
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/SummaryRow.js
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/Navigation.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsTable.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
Labels: 5.0, UI

#10251 [CDAP-13555] add custom time range picker for field level lineage
  cdap-ui/app/cdap/components/FieldLevelLineage/FieldLevelLineage.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/TimePicker/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
  cdap-ui/app/cdap/components/TimeRangePicker/ExpandableTimeRange.js
  cdap-ui/app/cdap/components/TimeRangePicker/TimeRangePicker.scss
  cdap-ui/app/cdap/components/TimeRangePicker/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10255 (CDAP-13288)(CDAP-13333) Added stop program and shared threadpool
  cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillControllerFactory.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MessagesBodyProducer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorClient.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/service/AbstractRetryableScheduledService.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/co/cask/cdap/common/service/RetryableScheduledServiceTest.java
  cdap-docs/admin-manual/build.sh
  cdap-security/src/main/java/co/cask/cdap/security/tools/KeyStores.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 5.0

#10230 CDAP-13261 Support reading metadata in program (in-prem only) Part 1
  cdap-api-spark-base/src/main/java/co/cask/cdap/api/spark/JavaSparkExecutionContextBase.java
  cdap-api-spark-base/src/main/scala/co/cask/cdap/api/spark/SparkExecutionContextBase.scala
  cdap-api/src/main/java/co/cask/cdap/api/customaction/CustomActionContext.java
  cdap-api/src/main/java/co/cask/cdap/api/flow/flowlet/FlowletContext.java
  cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataException.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataReader.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataWriter.java
  cdap-api/src/main/java/co/cask/cdap/api/service/http/HttpServiceContext.java
  cdap-api/src/main/java/co/cask/cdap/api/spark/SparkClientContext.java
  cdap-api/src/main/java/co/cask/cdap/api/worker/WorkerContext.java
  cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/customaction/BasicCustomActionContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/BasicFlowletContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowletProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/BasicWorkerContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataReaderWriterModules.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/RemoteMetadataClient.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/RemoteMetadataReader.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/guice/AppFabricTestModule.java
  cdap-app-templates/cdap-data-quality/src/test/java/co/cask/cdap/dq/testclasses/StreamBatchSource.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/co/cask/cdap/etl/api/StageContext.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/BasicSparkClientContext.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/scala/co/cask/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/co/cask/cdap/app/runtime/spark/DefaultJavaSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/co/cask/cdap/app/runtime/spark/SerializableSparkExecutionContext.scala
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithMetadataPrograms.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 5.0

#10213 [CDAP-13267]Add implementation of the FieldLineageDataset and subscriber of FieldLineage info from TMS which writes to it.
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/InputField.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/Operation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/ReadOperation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/TransformOperation.java
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/WriteOperation.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/DefaultFieldLineageReader.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDatasetDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDatasetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageReader.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/ProgramRunOperations.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/FieldLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MetadataMessage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/NoOpLineageWriter.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/OperationTypeAdapter.java
Labels: 5.0

#10231 CDAP-13268 Ability for the user to consolidate field operations at Workflow level.
  cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceContext.java
  cdap-api/src/main/java/co/cask/cdap/api/spark/SparkClientContext.java
  cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowContext.java
  cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowNodeState.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/WorkflowAppWithScopedParameters.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/WorkflowDataProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramController.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/DefaultProgramWorkflowRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramInfo.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/BasicSparkClientContext.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramController.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java
Labels: 5.0
