Repository cdapio/cdap, pull requests merged in 2018-02, with the labels that each got.

#9913 Upgrade react-timeago module to 3.3.0
  cdap-ui/dll/cdap-vendor-manifest.json
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.0, Bug, UI

#9907 [CDAP-13077] Adds Configure button to top panel, and initializes PipelineConfigurations component and store
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/ScheduleButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/cdap/components/PipelineDetails/store/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/PipelineScheduler.scss
  cdap-ui/app/cdap/components/PipelineScheduler/Store/index.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/module.js
  cdap-ui/app/hydrator/toppanel.less
Labels: 5.0, UI

#9914 [CDAP-13110] Fix dataset class loading in some places
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminService.java
  cdap-explore/src/main/java/co/cask/cdap/explore/executor/ExploreExecutorHttpHandler.java
  cdap-explore/src/main/java/co/cask/cdap/explore/service/ExploreTableManager.java
Labels: 5.0, Bug

#9908 [CDAP-13077] Adds side panel of config modeless, and implements PipelineConfig tab
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/AlertsTabContent/AlertsTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineConfigTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/BatchInterval.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Checkpointing.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Instrumentation.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/PipelineConfigTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/StageLogging.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PreviewConfigTabContent/PreviewConfigTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ResourcesTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgumentsTabContent/RuntimeArgumentsTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsSidePanel/ConfigurationsSidePanel.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsSidePanel/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/cdap/components/PipelineScheduler/PipelineScheduler.scss
  cdap-ui/app/cdap/components/PipelineScheduler/index.js
  cdap-ui/app/cdap/components/ToggleSwitch/ToggleSwitch.scss
  cdap-ui/app/cdap/components/ToggleSwitch/index.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.less
  cdap-ui/app/directives/my-pipeline-configurations/my-pipeline-configurations.less
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config.less
  cdap-ui/app/directives/widget-container/widget-toggle-switch/widget-toggle-switch.less
  cdap-ui/app/hydrator/toppanel.less
  cdap-ui/app/styles/common.less
Labels: 5.0, UI

#9926 Fixes add entity modal height + text change in MMDS
  cdap-ui/app/cdap/components/Experiments/CreateView/SplitDataStep/index.js
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
  cdap-ui/app/cdap/components/PlusButtonModal/index.js
Labels: 5.0, UI

#9912 [CDAP-13100] Add BigQuery Connection
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/BigQueryBrowser.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/DatasetList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/DisplaySwitch/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/TableList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/ActionCreator.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/commons.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/database.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/kafka.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/AddToPipelineModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/CreateDatasetBtn/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/AddConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/BigQueryConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#9909 [CDAP-13077] Implements Engine Config and Resources tabs of PipelineConfig modeless
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStoreActions.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/Backpressure.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/CustomConfig.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineConfigTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineRadioInput.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/NumExecutors.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ClientResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/DriverResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ResourcesTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/components/PipelineResources/index.js
  cdap-ui/app/cdap/components/ToggleSwitch/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#9858 Feature release 4.1/backport metrics control
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/source/operations/metrics.rst
  cdap-test/src/main/java/co/cask/cdap/test/MetricsManager.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/DatasetWithMRApp.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 4.1
