Repository cdapio/cdap, pull requests merged in 2018-12, with the labels that each got.

#10853 (CDAP-13135) Remove some usages of the deprecated InputSupplier and OutputSupplier
  cdap-app-fabric/src/main/java/co/cask/cdap/app/deploy/ConfigResponse.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ApplicationSpecificationAdapter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/DefaultConfigResponse.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/SandboxConfigurator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/ContainerLauncherGenerator.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/LocalizationUtilsTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/AppWithLocalFiles.java
  cdap-cli/src/main/java/co/cask/cdap/cli/CLIConfig.java
  cdap-common/src/main/java/co/cask/cdap/common/lang/InterceptableClassLoader.java
  cdap-common/src/main/java/co/cask/cdap/common/lang/jar/BundleJarUtil.java
  cdap-common/src/test/java/co/cask/cdap/common/lang/jar/BundleJarUtilTest.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java
  cdap-unit-test-spark2_2.11/src/test/java/co/cask/cdap/spark/app/SparkAppUsingLocalFiles.java
Labels: 6.0

#10852 Fixes lint/build errors for ts
  cdap-ui/app/cdap/components/BtnWithLoading/BtnWithLoading.stories.tsx
  cdap-ui/app/cdap/components/Heading/Heading.stories.tsx
  cdap-ui/app/cdap/components/Heading/index.tsx
  cdap-ui/app/cdap/components/Modal/Modal.stories.tsx
  cdap-ui/app/cdap/components/Popover/Popover.stories.tsx
  cdap-ui/app/cdap/components/Popover/Tooltip.stories.tsx
  cdap-ui/app/cdap/components/SortableStickyGrid/SortableStickyGrid.stories.tsx
  cdap-ui/app/cdap/services/cdapavscwrapper/index.ts
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config-ctrl.js
  cdap-ui/package.json
  cdap-ui/tsconfig.json
  cdap-ui/yarn.lock
Labels: 6.0, Bug, UI

#10851 [CDAP-14533][CDAP-14534] Pipeline List View
  cdap-ui/app/cdap/api/app.js
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/ActionsPopover/ActionsPopover.scss
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/EntityListView/EntityListHeader/EntityListHeader.scss
  cdap-ui/app/cdap/components/EntityListView/EntityListHeader/index.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/HttpExecutor/InputPath/index.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedPipelineView.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/LastStart/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/PipelineCount.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTable.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTags/PipelineTags.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTags/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/RunsCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/Status/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/index.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/types.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftPipelineView.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTable.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/index.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/types.ts
  cdap-ui/app/cdap/components/PipelineList/PipelineList.scss
  cdap-ui/app/cdap/components/PipelineList/index.tsx
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/index.js
  cdap-ui/app/cdap/services/cdapavscwrapper/index.ts
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/services/redux-helpers/index.ts
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/hydrator/templates/list.html
Labels: 6.0, UI

#10857 [CDAP-14553] [CDAP-14599] Adds generic plugin function widget
  cdap-docs/developer-manual/source/pipelines/developing-plugins/presentation-plugins.rst
  cdap-ui/Gulpfile.js
  cdap-ui/app/cdap/components/EntityListView/EntityListHeader/index.js
  cdap-ui/app/cdap/components/Modal/Modal.stories.tsx
  cdap-ui/app/directives/plugin-functions/functions/get-property-value/get-property-value-modal.html
  cdap-ui/app/directives/plugin-functions/functions/get-property-value/get-property-value.html
  cdap-ui/app/directives/plugin-functions/functions/get-property-value/get-property-value.js
  cdap-ui/app/directives/plugin-functions/functions/get-property-value/get-property-value.less
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.js
  cdap-ui/app/directives/plugin-functions/plugin-functions-factory.js
  cdap-ui/app/directives/plugin-functions/plugin-functions.js
  cdap-ui/app/directives/widget-container/widget-radio-group/widget-radio-group.html
  cdap-ui/app/directives/widget-container/widget-radio-group/widget-radio-group.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-properties-template.html
Labels: 6.0, Bug, UI

#10861 [CDAP-14614] separate link for deployed and drafts pipelines list
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/index.js
  cdap-ui/app/cdap/components/Header/EntitiesLink/index.tsx
  cdap-ui/app/cdap/components/Header/PipelinesLink/index.tsx
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/PipelineList.scss
  cdap-ui/app/cdap/components/PipelineList/index.tsx
  cdap-ui/app/cdap/globals.ts
  cdap-ui/app/cdap/main.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/list-ctrl.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/templates/list.html
Labels: 6.0, UI

#10871 Feature/cdap 14626 remove metrics migration
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/CombinedHBaseMetricsTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/CombinedMetricsScanner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTable.java
  cdap-docs/admin-manual/build.sh
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/DataMigrator.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsTableDeleter.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsTableMigration.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MigrationTableHelper.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTest.java
Labels: 6.0

#10872 [CDAP-14632] Remove Metadata upgrade code
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/UpgradeHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataMigrator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataMigratorTest.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/MetadataConstants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsHistoryKey.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MdsKey.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataEntries.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataV1.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SearchResults.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/DefaultValueIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/MetadataEntityTypeIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/indexer/DefaultValueIndexerTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreMigrationTest.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/NamespacedIdCodec.java
Labels: 6.0

#10870 CDAP-14596 add profile to mapreduce and spark modes
  cdap-api/src/main/java/co/cask/cdap/api/app/ApplicationSpecification.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/DefaultApplicationSpecification.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ForwardingApplicationSpecification.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/SystemArgumentsTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetadataTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramType.java
Labels: 6.0

#10884 (CDAP-14664) Fix incorrect implementation of the RuntimeArguments.toPosixArray
  cdap-api/src/main/java/co/cask/cdap/api/common/RuntimeArguments.java
  cdap-api/src/test/java/co/cask/cdap/api/common/RuntimeArgumentsTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/BasicArguments.java
  cdap-unit-test/src/test/java/co/cask/cdap/RuntimeArgumentsTest.java
Labels: 6.0

#10878 [CDAP-14635] change UI usage of metadata API
  cdap-ui/app/cdap/api/app.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/NamespacesAccordion/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/DatasetStreamCards/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/ActionCreator.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
  cdap-ui/app/cdap/components/Overview/AppOverview/index.js
  cdap-ui/app/cdap/components/Overview/index.js
  cdap-ui/app/cdap/components/ProgramCards/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/index.js
  cdap-ui/app/cdap/services/metadata-parser/EntityType.js
  cdap-ui/app/cdap/services/metadata-parser/__tests__/metadata-parser.test.js
  cdap-ui/app/cdap/services/metadata-parser/index.js
  cdap-ui/app/tracker/controllers/metadata-ctrl.js
  cdap-ui/app/tracker/controllers/results-ctrl.js
  cdap-ui/app/tracker/tracker.less
Labels: 6.0, UI

#10885 (CDAP-14592) Remove some flow tests
  cdap-app-fabric/src/test/java/co/cask/cdap/ArgumentCheckApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/InvalidFlowOutputApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/queue/SimpleQueueSpecificationGeneratorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/flow/FlowletProcessEntryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/verification/FlowVerificationTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/runtime/FlowTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/runtime/MultiConsumerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/runtime/app/MultiApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/runtime/app/PendingMetricTestApp.java
  cdap-common/src/test/java/co/cask/cdap/common/queue/QueueNameTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/LocalQueueTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/QueueTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBaseQueueTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/inmemory/InMemoryQueueTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/transaction/queue/leveldb/LevelDBQueueTest.java
  cdap-hbase-compat-0.96/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase96QueueTest.java
  cdap-hbase-compat-0.98/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase98QueueTest.java
  cdap-hbase-compat-1.0-cdh/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10CDHQueueTest.java
  cdap-hbase-compat-1.0-cdh5.5.0/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10CDH550QueueTest.java
  cdap-hbase-compat-1.0/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase10QueueTest.java
  cdap-hbase-compat-1.1/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase11QueueTest.java
  cdap-hbase-compat-1.2-cdh5.7.0/src/test/java/co/cask/cdap/data2/transaction/queue/hbase/HBase12CDH570QueueTest.java
  cdap-master/src/test/java/co/cask/cdap/data/tools/HBaseQueueDebuggerTest.java
  cdap-master/src/test/java/co/cask/cdap/data/tools/flow/FlowQueuePendingCorrectorTest.java
  cdap-unit-test/src/test/java/co/cask/cdap/flow/stream/FlowStreamIntegrationTestRun.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/base/TestFrameworkTestSuite.java
Labels: 6.0

#10886 remove testFlowStreamAuth
  cdap-unit-test/src/test/java/co/cask/cdap/security/AuthorizationTest.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/StreamAuthApp.java
Labels: 6.0, Bug

#10874 CDAP-14637 Storage SPI to decouple CDAP from underlying storage
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/InvalidFieldException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableId.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSpecification.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Field.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/FieldType.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Fields.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Range.java
Labels: 6.0

#10881 [CDAP-14654] make pipeline list rows clickable
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/LastStart/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTable.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTags/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/RunsCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/Status/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTable.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/EmptyList/EmptyList.scss
  cdap-ui/app/cdap/components/PipelineList/PipelineList.scss
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/index.js
Labels: 6.0, UI

#10875 CDAP-14628 add concurrent write for fact table
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
Labels: 6.0

#10891 (CDAP-14592) Remove some Flows implementation in tests
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTxTimeoutTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/WebCrawlApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/TriggeringScheduleInfoAdapterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/verification/ApplicationVerificationTest.java
  cdap-integration-test/src/test/java/co/cask/cdap/test/IntegrationTestBaseTest.java
  cdap-integration-test/src/test/java/co/cask/cdap/test/TestApplication.java
  cdap-integration-test/src/test/java/co/cask/cdap/test/TestFlow.java
  cdap-unit-test/src/test/java/co/cask/cdap/admin/AdminApp.java
  cdap-unit-test/src/test/java/co/cask/cdap/admin/AdminAppTestRun.java
  cdap-unit-test/src/test/java/co/cask/cdap/batch/stream/TestBatchStreamIntegrationApp.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithCustomTx.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/GenSinkApp2.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/JoinMultiStreamApp.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 6.0

#10880 [CDAP-14620] New app header implementation
  cdap-ui/app/cdap/components/AbstractWizard/index.js
  cdap-ui/app/cdap/components/Administration/index.js
  cdap-ui/app/cdap/components/AppHeader/AboutPageModal/AboutPageModal.scss
  cdap-ui/app/cdap/components/AppHeader/AboutPageModal/index.tsx
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/DrawerFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ToolBarFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/BrandImage.tsx
  cdap-ui/app/cdap/components/AppHeader/ExtendedLinkButton.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/AppHeader/ListItemLink.tsx
  cdap-ui/app/cdap/components/AppHeader/NamespaceLinkContext.tsx
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/components/Heading/index.tsx
  cdap-ui/app/cdap/components/HttpExecutor/index.js
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
  cdap-ui/app/cdap/components/PipelineList/PipelineList.scss
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/NamespaceStore/index.ts
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/styles/variables.scss
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/styles/variables.less
  cdap-ui/package.json
  cdap-ui/tsconfig.json
  cdap-ui/typings/declarations.d.ts
  cdap-ui/webpack.config.cdap.js
  cdap-ui/yarn.lock
Labels: 6.0, UI

#10883 [UI][CDAP-14659] Compile node application to remove node_modules folder
  cdap-common/bin/functions.sh
  cdap-standalone/src/main/java/co/cask/cdap/UserInterfaceService.java
  cdap-ui/.gitignore
  cdap-ui/package.json
  cdap-ui/pom.xml
  cdap-ui/server/config/parser.js
  cdap-ui/server/express.js
  cdap-ui/yarn.lock
Labels: 6.0, UI

#10877 CDAP-14629 add cache to track latest ts
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/timeseries/FactTableTest.java
Labels: 6.0

#10897 fix flaky preview test due to recent metrics change
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
Labels: 6.0, Bug

#10903 short term fix the metadata auth test
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataAdminAuthorizationTest.java
Labels: 6.0, Bug

#10902 (CDAP-14702) Use a standard java class to store secret key.
  cdap-api/src/main/java/co/cask/cdap/api/security/store/SecureStoreMetadata.java
  cdap-security/src/main/java/co/cask/cdap/security/store/FileSecureStore.java
  cdap-security/src/main/java/co/cask/cdap/security/store/KeyStoreEntry.java
  cdap-security/src/test/java/co/cask/cdap/security/store/FileSecureStoreTest.java
Labels: 6.0

#10906 (CDAP-14702) Use a standard java class to store secret key.
  cdap-api/src/main/java/co/cask/cdap/api/security/store/SecureStoreMetadata.java
  cdap-security/src/main/java/co/cask/cdap/security/store/FileSecureStore.java
  cdap-security/src/main/java/co/cask/cdap/security/store/KeyStoreEntry.java
  cdap-security/src/test/java/co/cask/cdap/security/store/FileSecureStoreTest.java
Labels: 5.1

#10907 (CDAP-14592) Remove command line tools related to Flow and Stream
  cdap-data-fabric/src/main/java/co/cask/cdap/data/stream/StreamTailer.java
  cdap-docs/admin-manual/source/operations/tx-maintenance.rst
  cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/SimpleHBaseQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/flow/FlowQueuePendingCorrector.java
Labels: 6.0

#10908 (CDAP-14663) Refactoring LogAppender guice module
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/LogAppenderLogProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RemoteExecutionLogProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/guice/AppFabricTestModule.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ExploreServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/LogSaverTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MessagingServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/StreamHandlerRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TransactionServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseTableExporter.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/guice/KafkaLogAppenderModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/guice/LocalLogAppenderModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/guice/LoggingModules.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/guice/TMSLogAppenderModule.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/KafkaTestBase.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/LocalLogAppenderResilientTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/CDAPLogAppenderTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/LogFileManagerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/FileMetadataCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/LogCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/plugins/RollingLocationLogAppenderTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/read/FileMetadataTest.java
Labels: 6.0
