Repository cdapio/cdap, pull requests merged in 2018-08, with the labels that each got.

#10487 CDAP-13609 fix metrics processor flaky test
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
Labels: 5.1

#10486 (CDAP-13653) Fix to support Spark 2.3
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
Labels: 5.1

#10488 (CDAP-13653) (4.3) Fix to support Spark 2.3
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
Labels: 4.3

#10498 (CDAP-13653) Update compatibility matrix
  cdap-docs/admin-manual/source/hadoop-compatibility.rst
Labels: 5.1

#10499 (CDAP-13653) Update compatibility matrix
  cdap-docs/admin-manual/source/hadoop-compatibility.rst
Labels: 4.3

#10504 Feature ui/cdap 14073 upgrade lodash
  cdap-ui/dll/dll.shared.vendor.development.js
  cdap-ui/dll/dll.shared.vendor.js
  cdap-ui/dll/shared-vendor-development-manifest.json
  cdap-ui/dll/shared-vendor-manifest.json
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.1, UI

#10494 [CDAP-12957] use plugin display name for node config header
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 5.1, Bug, UI

#10501 [CDAP-12996] add minimum version check when dataprep service already running
  cdap-ui/app/cdap/components/DataPrep/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/DataPrepHome/index.js
Labels: 5.1, Bug, UI

#10496 CDAP-13997 remove tracker from sandbox startup
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-standalone/src/main/java/co/cask/cdap/TrackerAppCreationService.java
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: 5.1

#10507 [CDAP-14079] Rename and fix flaky test
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
Labels: 5.1, Bug

#10485 [CDAP-13956] [CDAP-13971] Fixes kafka connection to pass in right schema to pipeline
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/DatasetList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/commons.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/GCSPath/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/S3Path/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/IngestDataFromDataPrep.scss
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/HostPortEditor/HostPortEditor.scss
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 5.1, Bug, UI

#10489 [CDAP-11379][CDAP-13900]Bugfixes in Dataprep
  cdap-ui/app/cdap/components/DataPrep/DataPrepCLI/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingPositions/CutDirective.js
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
Labels: 5.1, Bug, UI

#10491 [CDAP-13767] [CDAP-13890] Fixes surfacing profile information for historical runs in pipelines
  cdap-ui/app/cdap/components/AbstractWidget/SecureKeyTextarea/index.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/SystemProfilesAccordion/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/ProfileStatusToggle.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/PredictionDatasetExploreModal/index.js
  cdap-ui/app/cdap/components/FastAction/DeleteAction/index.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/ExploreModal.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/index.js
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/components/Overview/AppOverview/index.js
  cdap-ui/app/cdap/components/Overview/DatasetOverview/index.js
  cdap-ui/app/cdap/components/Overview/StreamOverview/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/EditProperty/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/index.js
  cdap-ui/app/cdap/components/StreamDetailedView/index.js
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/index.js
  cdap-ui/app/cdap/services/NamespaceStore/index.js
  cdap-ui/app/cdap/services/ServiceEnablerUtilities.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/services/metadata-parser/index.js
Labels: 5.1, Bug, UI

#10495 [CDAP-13961][CDAP-13770] Fixes profile name overflow issues
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/ListView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/ConfirmationModal/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfilesListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/RunComputeProfile.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/ProfilesForSchedule.scss
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/styles/common.less
Labels: 5.1, Bug, UI

#10500 [CDAP-13993] Fixes page titles across CDAP UI
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/index.js
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/index.js
  cdap-ui/app/cdap/components/Administration/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/PageTitle/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/index.js
  cdap-ui/app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  cdap-ui/app/cdap/components/DataPrep/store/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentDetailPageTitle/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/index.js
  cdap-ui/app/cdap/components/Experiments/ExperimentsServiceControl/index.js
  cdap-ui/app/cdap/components/Experiments/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/NamespaceDetailsPageTitle/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10518 (CDAP-13598) Synchronize correctly with the class loader lock
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/classloader/SparkRunnerClassLoader.java
  cdap-spark-core-base/src/test/java/co/cask/cdap/app/runtime/spark/classloader/SparkRunnerClassLoaderTest.java
Labels: 5.1

#10514 [CDAP-14067] Fixes weird gap above namespace dropdown
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
Labels: 5.1, Bug, UI

#10516 CDAP-13853 remove data pipeline requirement for a time schedule
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/DataPipelineApp.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/preview/PreviewDataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/co/cask/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/co/cask/cdap/etl/proto/v2/ETLBatchConfig.java
Labels: 5.1

#10509 [CDAP-14085] Center search box in metadata home page
  cdap-ui/app/tracker/templates/main.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.1, UI

#10508 [CDAP-13165][CDAP-14077] remove preview tab and action button from metadata
  cdap-ui/app/tracker/controllers/entity-ctrl.js
  cdap-ui/app/tracker/controllers/preview-ctrl.js
  cdap-ui/app/tracker/directives/jump/jump.html
  cdap-ui/app/tracker/directives/jump/jump.js
  cdap-ui/app/tracker/directives/jump/jump.less
  cdap-ui/app/tracker/routes.js
  cdap-ui/app/tracker/services/my-jump-factory.js
  cdap-ui/app/tracker/templates/entity.html
  cdap-ui/app/tracker/templates/preview.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.1, UI

#10523 [CDAP-14105] Do not correct run records in unit tests
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/NoopRunRecordCorrectorService.java
Labels: 5.1, Bug

#10522 (CDAP-13249) Use an explicit Factory class implementation to avoid warning from Guice
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/ServiceStoreModules.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewHttpModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/route/store/LocalRouteStoreTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DefaultDatasetDefinitionRegistryFactory.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/InMemoryDefinitionRegistryFactory.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryMetricsTableTest.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
Labels: 5.1

#10524 Changes UI theme back to default
  cdap-ui/server/config/ui-settings.json
Labels: 5.1, Bug, UI

#10519 CDAP-14095 Enable GC logging for Sandbox.
  cdap-common/bin/functions.sh
Labels: 5.1

#10512 [CDAP-8546] Fix backend behavior to show right message when appropriate services fail
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/server/express.js
Labels: 5.1, Bug, UI

#10510 [CDAP-14084] fix dropdown menu for time range picker in fll not opening
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
Labels: 5.1, Bug, UI

#10526 [CDAP-14071] Upgrades datavoyager to make sure it works in react 16 environment
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.1, Bug, UI

#10515 [CDAP-14066] Fixes CopyableId component to show tooltip
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/CollapsibleWrapper/index.js
  cdap-ui/app/cdap/components/CopyableID/CopyableID.scss
  cdap-ui/app/cdap/components/CopyableID/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/AddModelToPipelineBtn/index.js
  cdap-ui/app/cdap/components/Popover/Popover.scss
  cdap-ui/app/cdap/components/Popover/index.js
Labels: 5.1, Bug, UI

#10527 [CDAP-14120] Fixes http executor styling to show proper input group label
  cdap-ui/app/cdap/components/HttpExecutor/InputPath/index.js
  cdap-ui/app/cdap/components/RulesEngineHome/RuleBooksTab/RulesBooksTab.scss
Labels: 5.1, Bug, UI

#10531 [CDAP-14134] Reads theme file once when starting up node server, instead of every time user uses UI
  cdap-ui/server/config/parser.js
  cdap-ui/server/express.js
Labels: 5.1, Bug, UI

#10532 [CDAP-14105] Fix run records in sandbox only once after startup
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/LocalRunRecordCorrectorService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ScheduledRunRecordCorrectorService.java
Labels: 5.1, Bug

#10537 [CDAP-14135] More trace logging for RemoteDatasetOpExecutor
  cdap-common/src/test/resources/logback-test.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/RemoteDatasetOpExecutor.java
Labels: 5.1

#10511 [CDAP-13386] Fixes model training logs to open in logviewer
  cdap-ui/app/cdap/components/Experiments/CreateView/SplitDataStep/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/createExperimentStore.js
  cdap-ui/app/directives/log-viewer/log-viewer.html
  cdap-ui/app/directives/log-viewer/log-viewer.js
  cdap-ui/app/directives/log-viewer/log-viewer.less
  cdap-ui/app/logviewer/controllers/home-ctrl.js
  cdap-ui/app/logviewer/logviewer.less
  cdap-ui/app/logviewer/routes.js
  cdap-ui/app/logviewer/templates/home.html
  cdap-ui/app/services/logsApi/my-logs-api.js
Labels: 5.1, Bug, UI

#10536 [CDAP-12674] Fixes showing duration or start time of a program in UI only when it is available
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesRecordsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/Store/PipelineSummaryActions.js
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/hydrator/controllers/list-ctrl.js
Labels: 5.1, Bug, UI

#10542 [CDAP-14145] Reverts back api datasource change recently made when backend goes down
  cdap-ui/app/cdap/services/datasource/index.js
Labels: 5.1, Bug, UI

#10533 CDAP-13924 Add Capability Annotations APIs
  cdap-api/src/main/java/co/cask/cdap/api/annotation/Requirements.java
Labels: 5.1

#10548 [CDAP-14135] More trace logging for dataset instance handler
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
  cdap-explore/src/test/resources/logback-test.xml
Labels: 5.1

#10547 Update functions.sh to give more memory for Docker and VM installs of Sandbox
  cdap-common/bin/functions.sh
Labels: 5.1

#10545 [CDAP-14076] Fix deadlock in Hadoop's Shell class
  cdap-app-fabric/src/test/java/org/apache/hadoop/util/Shell.java
  suppressions.xml
Labels: 5.1, Bug

#10543 CDAP-13924 Capture and store plugin requirements
  cdap-api/src/main/java/co/cask/cdap/api/plugin/PluginClass.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/app/inspection/InspectionApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/PluginClassDeserializer.java
Labels: 5.1

#10546 Remove ngCapsules Dependency
  cdap-ui/Gulpfile.js
  cdap-ui/app/directives/cask-angular-confirmable/confirm-modal.html
  cdap-ui/app/directives/cask-angular-confirmable/confirmable.js
  cdap-ui/app/directives/cask-angular-dropdown-text-combo/dropdown-text-combo.html
  cdap-ui/app/directives/cask-angular-dropdown-text-combo/dropdown-text-combo.js
  cdap-ui/app/directives/cask-angular-dropdown-text-combo/dropdown-text-combo.less
  cdap-ui/app/directives/cask-angular-focus/focus-service.js
  cdap-ui/app/directives/cask-angular-focus/focus.js
  cdap-ui/app/directives/cask-angular-json-edit/jsonedit.js
  cdap-ui/app/directives/cask-angular-json-edit/jsonedit.less
  cdap-ui/app/directives/cask-angular-password/click2show.html
  cdap-ui/app/directives/cask-angular-password/password.js
  cdap-ui/app/directives/cask-angular-progress/bar.html
  cdap-ui/app/directives/cask-angular-progress/progress.js
  cdap-ui/app/directives/cask-angular-promptable/prompt-modal.html
  cdap-ui/app/directives/cask-angular-promptable/prompt.js
  cdap-ui/app/directives/cask-angular-sortable/sortable.js
  cdap-ui/app/directives/cask-angular-sortable/sortable.less
  cdap-ui/app/filters/cask-angular-capitalize/capitalize.js
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/services/cask-angular-dispatcher/dispatcher.js
  cdap-ui/app/services/cask-angular-eventpipe/eventpipe.js
  cdap-ui/app/services/cask-angular-observable-promise/observable-promise.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/app/services/cask-angular-socket-datasource/socket.js
  cdap-ui/app/services/cask-angular-theme/theme.js
  cdap-ui/app/services/cask-angular-window-manager/wm.js
  cdap-ui/app/tracker/main.js
  cdap-ui/bower.json
Labels: 5.1, UI

#10544 Fix wording in README
  README.rst
Labels: 5.0, Docs

#10552 Merge release/5.0 to develop
  README.rst
  cdap-common/bin/functions.sh
  cdap-distributions/bin/docs_bucket_current_develop.sh
  cdap-examples/resources/weblog-service.txt
  pom.xml
Labels: 5.1

#10540 Creating a PartitionedFileSet dataset without the appropriate properties (partitioning) should return a 400
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandler.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminOpHTTPHandler.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetDefinition.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetInstanceHandlerTest.java
Labels: 5.1

#10557 CDAP-14156 fix flaky preview test
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewRunner.java
Labels: 5.1, Bug

#10525 CDAP-13894 fix for sandbox metrics
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricStore.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
Labels: 5.1

#10554 CDAP-14154 enforce profile program type restrictions
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
Labels: 5.1

#10520 CDAP-14102:Bind http services to localhost in sandbox
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-ui/server/config/development/cdap.json
Labels: 5.1

#10556 CDAP-13924 Reset system property correctly
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceProgramRunnerTest.java
Labels: 5.1

#10550 CDAP-13924:Support filtering based on cdap-site.xml configuration
  cdap-api/src/main/java/co/cask/cdap/api/annotation/Requirements.java
  cdap-api/src/main/java/co/cask/cdap/api/plugin/PluginClass.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/app/inspection/InspectionApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/AppScheduleUpdateTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/PluginExclusionTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
Labels: 5.1

#10564 [UI-Lint] Add eslint back to properly catch js errors
  cdap-ui/.eslintignore
  cdap-ui/.eslintrc.json
  cdap-ui/app/cdap/components/Experiments/CreateView/SplitDataStep/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/store/createExperimentStore.js
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/index.js
  cdap-ui/app/cdap/components/Header/NamespaceLinkContext.js
  cdap-ui/package.json
  cdap-ui/tsconfig.json
  cdap-ui/tslint.json
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.login.js
  cdap-ui/yarn.lock
Labels: 5.1, Bug, UI

#10562 [CDAP-13996] Disables Ingest Data option for uploaded file in DataPrep
  cdap-ui/app/cdap/components/DataPrep/TopPanel/TopPanel.scss
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10570 [CDAP-13862][CDAP-13883][CDAP-13846] UI Text Changes
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/graphRenderer.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10568 (CDAP-13988) Improve TMS StoreRequest to allow reuse
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/MessagingProgramStatePublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/ScheduleTaskPublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/MessagingWorkflowStateWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerNotifier.java
  cdap-app-fabric/src/test/java/co/cask/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/DefaultAuditPublisher.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingLineageWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/writer/MessagingMetadataPublisher.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/MessagingUsageWriter.java
  cdap-notifications/src/main/java/co/cask/cdap/notifications/service/kafka/MessagingNotificationService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/StoreRequest.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/client/StoreRequestBuilder.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/server/StoreHandler.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/service/PendingStoreRequest.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/service/StoreRequestWriter.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/distributed/LeaderElectionMessagingServiceTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/server/MessagingHttpServiceTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/service/ConcurrentMessageWriterTest.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MessagingMetricsCollectionService.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTestBase.java
Labels: 5.1

#10534 CDAP-14044 use prefix to delete metrics
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/CubeDeleteQuery.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowUtils.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/cube/AbstractCubeTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricDeleteQuery.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
Labels: 5.1

#10555 [CDAP-12895][Part-1] Fix inconsistencies in CDAP modal in UI
  cdap-ui/app/cdap/components/BtnWithLoading/BtnWithLoading.scss
  cdap-ui/app/cdap/components/BtnWithLoading/index.js
  cdap-ui/app/cdap/components/CardActionFeedback/index.js
  cdap-ui/app/cdap/components/ConfirmationModal/ConfirmationModal.scss
  cdap-ui/app/cdap/components/ConfirmationModal/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Calculate/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ColumnActions/Bulkset/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ColumnActions/ReplaceColumns/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingDelimiterModal/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingPatternsModal/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Filter/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/CSVModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/ExcelModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/LogModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/SimpleDateModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/SingleFieldModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/ParseDirective.scss
  cdap-ui/app/cdap/components/DataPrep/TopPanel/AddToPipelineModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/IngestDataFromDataPrep.scss
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/TopPanel.scss
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/WorkspaceTabs.scss
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/BigQueryConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/GCSConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/KafkaConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/S3Connection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/cdap/styles/modals.scss
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/styles/common.less
  cdap-ui/app/styles/modals.less
  cdap-ui/app/styles/variables.less
Labels: 5.1, UI

#10581 Fix UI build failing due to eslint validations
  cdap-ui/app/cdap/components/BtnWithLoading/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/SampleTSXComponent/index.tsx
Labels: 5.1, Bug, UI

#10565 [CDAP-14088] Add NUX Framework
  cdap-ui/app/cdap/components/Footer/Footer.scss
  cdap-ui/app/cdap/components/Footer/index.js
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/index.js
  cdap-ui/app/cdap/components/Header/DataPrepLink/index.tsx
  cdap-ui/app/cdap/components/Header/Tour/index.ts
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/components/OverlayFocus/OverlayFocus.scss
  cdap-ui/app/cdap/components/OverlayFocus/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/GuidedTour/GuidedTour.scss
  cdap-ui/app/cdap/services/GuidedTour/index.ts
  cdap-ui/app/hydrator/bottompanel.less
  cdap-ui/app/logviewer/logviewer.less
  cdap-ui/app/styles/common.less
  cdap-ui/app/styles/themes/cdap.less
  cdap-ui/app/tracker/tracker.less
  cdap-ui/package.json
  cdap-ui/tslint.json
  cdap-ui/yarn.lock
Labels: 5.1, UI

#10584 [CDAP-14189] Reduce the number of scheduler threads in unit tests
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetDefinition.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/Schedulers.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ConstraintCheckerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetsUtil.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
Labels: 5.1

#10559 [CDAP-14146] Fixes pipeline summary to use starting time of a run instead of start time to include provisioning time
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineStopButton/PipelineStopPopover.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunDuration.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunNumErrors.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunNumWarnings.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunStartTime.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunningRunsPopover/index.js
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesRecordsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/Store/PipelineSummaryActions.js
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/cdap/components/ProgramTable/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/controllers/list-ctrl.js
Labels: 5.1, Bug, UI

#10576 CDAP-13924:Refactor ProgramSpecification to store Plugin information
  cdap-api/src/main/java/co/cask/cdap/api/AbstractProgramSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/ProgramSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/mapreduce/MapReduceSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/service/ServiceSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/service/http/HttpServiceHandlerSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/spark/SparkSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/worker/WorkerSpecification.java
  cdap-api/src/main/java/co/cask/cdap/api/workflow/WorkflowSpecification.java
  cdap-api/src/main/java/co/cask/cdap/internal/flow/DefaultFlowSpecification.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ForwardingFlowSpecification.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/ServiceSpecificationCodec.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/mapreduce/DefaultMapReduceConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/InMemoryWorkerRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/DefaultHttpServiceHandlerConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/spark/DefaultSparkConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/DefaultWorkerConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
  cdap-app-fabric/src/test/java/co/cask/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/MapReduceSpecificationCodec.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/SparkSpecificationCodec.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkerSpecificationCodec.java
  cdap-proto/src/main/java/co/cask/cdap/proto/codec/WorkflowSpecificationCodec.java
Labels: 5.1

#10583 [CDAP-14138] Fixes switching between dataprep connections
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/commons.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/database.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/kafka.js
Labels: 5.1, Bug, UI

#10585 [CDAP-14191] Fix to not show 404 when creating a workspace from File System in DataPrep
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
Labels: 5.1, UI

#10586 [CDAP-12402] add popover nux tour
  cdap-ui/app/cdap/components/Header/Header.scss
  cdap-ui/app/cdap/components/Header/HubButton/index.tsx
  cdap-ui/app/cdap/components/Header/MetadataLink/index.tsx
  cdap-ui/app/cdap/components/Header/PipelinesLink/index.tsx
  cdap-ui/app/cdap/components/Header/Tour/index.ts
  cdap-ui/app/cdap/services/GuidedTour/index.ts
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
  cdap-ui/app/cdap/styles/img/nux/Control_Center_NUX.png
  cdap-ui/app/cdap/styles/img/nux/Dataprep_NUX.png
  cdap-ui/app/cdap/styles/img/nux/Hub_NUX.png
  cdap-ui/app/cdap/styles/img/nux/Metadata_NUX.png
  cdap-ui/app/cdap/styles/img/nux/Pipeline_NUX.png
  cdap-ui/app/cdap/styles/img/nux/welcome-header-background.png
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10574 [CDAP-14025] Fix DataPrep UI change for environment specific connector types
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/components/Alert/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserTopPanel/DataPrepBrowserTopPanel.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserTopPanel/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/AddConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionType.ts
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
  cdap-ui/app/cdap/components/DataPrepConnections/NoDefaultConnection/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/DataPrepHome/index.js
  cdap-ui/app/cdap/components/EmptyMessageContainer/EmptyMessageContainer.scss
  cdap-ui/app/cdap/components/EmptyMessageContainer/index.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10538 (CDAP-14132) Fix all examples and deployment pom
  BUILD.rst
  cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankApp.java
  cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/main/java/SparkPageRankProgram.java
  cdap-archetypes/cdap-spark-java-archetype/src/main/resources/archetype-resources/src/test/java/SparkPageRankAppTest.java
  cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/main/scala/SparkKMeansProgram.scala
  cdap-archetypes/cdap-spark-scala-archetype/src/main/resources/archetype-resources/src/test/java/SparkKMeansAppTest.java
  cdap-examples/ClicksAndViews/pom.xml
  cdap-examples/CountRandom/pom.xml
  cdap-examples/CubeService/pom.xml
  cdap-examples/DataCleansing/pom.xml
  cdap-examples/DecisionTreeRegression/pom.xml
  cdap-examples/FileSetExample/pom.xml
  cdap-examples/HelloWorld/pom.xml
  cdap-examples/LogAnalysis/pom.xml
  cdap-examples/LogAnalysis/src/test/java/co/cask/cdap/examples/loganalysis/LogAnalysisAppTest.java
  cdap-examples/Purchase/pom.xml
  cdap-examples/SpamClassifier/pom.xml
  cdap-examples/SpamClassifier/src/main/scala/co/cask/cdap/examples/sparkstreaming/SpamClassifierProgram.scala
  cdap-examples/SpamClassifier/src/test/java/co/cask/cdap/examples/sparkstreaming/SpamClassifierTest.java
  cdap-examples/SparkKMeans/pom.xml
  cdap-examples/SparkKMeans/src/main/scala/co/cask/cdap/examples/sparkkmeans/SparkKMeansProgram.scala
  cdap-examples/SparkKMeans/src/test/java/co/cask/cdap/examples/sparkkmeans/SparkKMeansAppTest.java
  cdap-examples/SparkPageRank/pom.xml
  cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankProgram.java
  cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java
  cdap-examples/SportResults/pom.xml
  cdap-examples/StreamConversion/pom.xml
  cdap-examples/UserProfiles/pom.xml
  cdap-examples/WebAnalytics/pom.xml
  cdap-examples/WikipediaPipeline/pom.xml
  cdap-examples/WikipediaPipeline/src/main/scala/co/cask/cdap/examples/wikipedia/ClusteringUtils.scala
  cdap-examples/WikipediaPipeline/src/main/scala/co/cask/cdap/examples/wikipedia/ScalaSparkKMeans.scala
  cdap-examples/WikipediaPipeline/src/test/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineAppTest.java
  cdap-examples/WordCount/pom.xml
  cdap-examples/deploy_pom.xml
  cdap-examples/pom.xml
Labels: 5.1

#10590 [CDAP-14206][CDAP-14213] Fixes clicking on BQ dataset taking user to File System instead
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/commons.js
Labels: 5.1, Bug, UI

#10577 CDAP-13924:Register plugin at program level and store plugin info wit…
  cdap-api/src/main/java/co/cask/cdap/api/macro/MacroFunction.java
  cdap-api/src/main/java/co/cask/cdap/api/macro/Macros.java
  cdap-api/src/main/java/co/cask/cdap/api/plugin/PluginProperties.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AbstractConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/mapreduce/DefaultMapReduceConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/spark/DefaultSparkConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/worker/DefaultWorkerConfigurer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/DataPipelineApp.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/ExternalSparkProgram.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/common/PipelinePhase.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/batch/ETLSpark.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 5.1

#10592 (CDAP-14201) Upgrade netty-http library
  pom.xml
Labels: 5.1

#10593 [CDAP-12895][Part-2] Fix modals to be consistent
  cdap-ui/app/cdap/components/ConfirmationModal/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/ExploreModal.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10588 [CDAP-9226] Makes font family the same in both React and Angular apps
  cdap-ui/app/cdap/components/Header/DropdownStyling.scss
  cdap-ui/app/styles/common.less
  cdap-ui/app/styles/variables.less
Labels: 5.1, Bug, UI

#10589 [CDAP-12402] add welcome modal and saving state to user store
  cdap-ui/app/cdap/components/Header/Tour/index.ts
  cdap-ui/app/cdap/components/Header/Welcome/Welcome.scss
  cdap-ui/app/cdap/components/Header/Welcome/index.tsx
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10601 [CDAP-14146] Fixes the usage of start time vs starting time in pipelines view
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunDuration.js
  cdap-ui/app/hydrator/controllers/list-ctrl.js
Labels: 5.1, Bug, UI

#10594 [CDAP-14085] Add search tips to metadata home page
  cdap-ui/app/tracker/controllers/main-ctrl.js
  cdap-ui/app/tracker/templates/main.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.1, UI

#10582 CDAP-13924 Perform Provisioner checks for plugin capability before pr…
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/pipeline/PluginRequirement.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/NativeProvisioner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/MockProvisioner.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/IncapableSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/IncapableSource.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/test/HydratorTestBase.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataProcProvisioner.java
  cdap-runtime-ext-emr/src/main/java/co/cask/cdap/runtime/spi/provisioner/emr/ElasticMapReduceProvisioner.java
  cdap-runtime-ext-remote-hadoop/src/main/java/co/cask/cdap/runtime/spi/provisioner/remote/RemoteHadoopProvisioner.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/provisioner/Provisioner.java
Labels: 5.1

#10598 [CDAP-13778] Disable deleting profile if its still enabled in profile action popover
  cdap-ui/app/cdap/components/Cloud/Profiles/ActionsPopover/ActionsPopover.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/ActionsPopover/index.js
  cdap-ui/app/cdap/components/ConfirmationModal/ConfirmationModal.scss
  cdap-ui/app/cdap/components/ConfirmationModal/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI
