Repository cdapio/cdap, pull requests merged in 2018-09, with the labels that each got.

#10610 CDAP-13924 Change Requirement specification
  cdap-api/src/main/java/co/cask/cdap/api/annotation/Requirements.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/CounterTimeseriesTable.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/FileSet.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedObjectStore.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/KeyValueTable.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ObjectMappedTable.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/ObjectStore.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/PartitionedFileSet.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimePartitionedFileSet.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/TimeseriesDataset.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/cube/Cube.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/table/Table.java
  cdap-api/src/main/java/co/cask/cdap/api/plugin/PluginClass.java
  cdap-api/src/main/java/co/cask/cdap/api/plugin/Requirements.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/pipeline/PluginRequirement.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/NativeProvisioner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/app/inspection/InspectionApp.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/PluginExclusionTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/MockProvisioner.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/IncapableSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/co/cask/cdap/etl/mock/batch/IncapableSource.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/PluginClassDeserializer.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/external/ExternalDatasetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/file/FileSetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/CoreDatasetsModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/CubeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/ObjectMappedTableModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/LineageDatasetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/registry/UsageDatasetModule.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataProcProvisioner.java
  cdap-runtime-ext-emr/src/main/java/co/cask/cdap/runtime/spi/provisioner/emr/ElasticMapReduceProvisioner.java
  cdap-runtime-ext-remote-hadoop/src/main/java/co/cask/cdap/runtime/spi/provisioner/remote/RemoteHadoopProvisioner.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/provisioner/Capabilities.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/provisioner/Provisioner.java
Labels: 5.1

#10560 Feature/cdap 13975 add run count
  cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/MetadataStoreDataset.java
  cdap-proto/src/main/java/co/cask/cdap/proto/BatchProgramCount.java
  cdap-proto/src/main/java/co/cask/cdap/proto/RunCountResult.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/store/AppMetadataStore.java
Labels: 5.1

#10578 CDAP-13924:use boolean as beta in Provisioner
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerConfig.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProvisionerHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/provisioner/ProvisionerDetail.java
Labels: 5.1

#10622 CDAP:13924 add stream in supported capability for native provisioner
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/NativeProvisioner.java
Labels: 5.1

#10602 CDAP-14221 Use - instead of _ for logical types
  cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/co/cask/cdap/internal/io/SchemaTypeAdapter.java
  cdap-common/pom.xml
  cdap-common/src/test/java/co/cask/cdap/io/SchemaTest.java
Labels: 5.1

#10606 [CDAP-13994] Removes the ability to create stream from ResourceCenter modal
  cdap-ui/app/cdap/components/ResourceCenter/index.js
Labels: 5.1, Bug, UI

#10605 [CDAP-8555] Fixes tooltip contents to be left aligned + tooltip flickering bug
  cdap-ui/app/cdap/components/FastAction/SendEventAction/SendEventAction.scss
  cdap-ui/app/cdap/components/Overview/Tabs/SchemaTab/index.js
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
Labels: 5.1, Bug, UI

#10608 [CDAP-12895] Fixes send and view events modals to be consistent
  cdap-ui/app/cdap/components/ConfirmationModal/ConfirmationModal.scss
  cdap-ui/app/cdap/components/FastAction/SendEventAction/SendEventAction.scss
  cdap-ui/app/cdap/components/FastAction/SendEventAction/SendEventModal.js
  cdap-ui/app/cdap/components/FastAction/ViewEventsAction/ViewEventsModal.js
  cdap-ui/app/cdap/components/FastAction/ViewEventsAction/ViewEventsModal.scss
Labels: 5.1, Bug, UI

#10621 CDAP-14168: API Change for Lineage getFields
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/FieldLineageAdminTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/lineage/Field.java
Labels: 5.1

#10629 (CDAP-14062) Fix report generation app flaky test
  cdap-app-templates/cdap-program-report/cdap-program-report-base/src/main/java/co/cask/cdap/report/ReportGenerationSpark.java
  cdap-app-templates/cdap-program-report/cdap-program-report-base/src/main/scala/co/cask/cdap/report/ReportGenerationHelper.scala
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/classloader/SparkRunnerClassLoader.java
  cdap-spark-core-base/src/test/java/co/cask/cdap/app/runtime/spark/classloader/SparkRunnerClassLoaderTest.java
Labels: 5.1

#10628 [CDAP-14153] Fix UI to not break with js error while reading a database table
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10612 [CDAP-14068][UI] Excludes *development* dll files from being copied during SDK build
  cdap-ui/Gulpfile.js
  cdap-ui/package.json
  cdap-ui/pom.xml
  cdap-ui/server/express.js
Labels: 5.1, Bug, UI

#10632 [CDAP-13778] Fixes disabled delete link in profile actions popover
  cdap-ui/app/cdap/components/Cloud/Profiles/ActionsPopover/ActionsPopover.scss
Labels: 5.1, Bug, UI

#10631 CDAP-14161 fix cancel provisioning task
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/BootstrapStep.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisioningTask.java
Labels: 5.1

#10620 [CDAP-14028] add support for avro logical types
  cdap-ui/app/cdap/components/Experimental/index.js
  cdap-ui/app/cdap/components/SchemaEditor/ArraySchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/RecordSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/SchemaEditor.scss
  cdap-ui/app/cdap/components/SchemaEditor/SchemaHelpers.js
  cdap-ui/app/cdap/components/SchemaEditor/index.js
  cdap-ui/app/cdap/services/cdapavscwrapper/AbstractLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/DateLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/LogicalTypes.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/TimeMicrosLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/TimestampMicrosLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/index.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/complex-schema/array-schema/array-schema.js
  cdap-ui/app/directives/complex-schema/complex-schema-helpers.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/complex-schema/complex-schema.less
  cdap-ui/app/directives/complex-schema/map-schema/map-schema.js
  cdap-ui/app/directives/complex-schema/union-schema/union-schema.js
  cdap-ui/app/lib/global-lib.js
Labels: 5.1, UI

#10623 CDAP-14168: Include dataset schema with field lineage
  cdap-api/src/main/java/co/cask/cdap/api/lineage/field/EndPoint.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/FieldLineageAdminTest.java
Labels: 5.1

#10625 CDAP-14022 add more bootstrap step types
  cdap-api/src/main/java/co/cask/cdap/api/artifact/ArtifactSummary.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/BootstrapHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProfileHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/FileBootstrapConfigProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/AppCreator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/ProgramStarter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/SystemPreferenceSetter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/SystemProfileCreator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/guice/BootstrapModules.java
  cdap-app-fabric/src/test/java/co/cask/cdap/config/UserConfigStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/AppCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/NativeProfileCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/ProgramStarterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/SystemPreferencesSetterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/SystemProfileCreatorTest.java
  cdap-common/src/main/resources/bootstrap/distributed.json
  cdap-common/src/main/resources/bootstrap/sandbox.json
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterPathLookup.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathLookupTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/artifact/AppRequest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/profile/ProfileCreateRequest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/provisioner/ProvisionerInfo.java
  cdap-proto/src/main/java/co/cask/cdap/proto/provisioner/ProvisionerPropertyValue.java
  cdap-standalone/src/main/java/co/cask/cdap/AbstractAppCreationService.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-standalone/src/main/java/co/cask/cdap/WranglerAppCreationService.java
  cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java
Labels: 5.1

#10596 CDAP-13526 'DataProc'->'Dataproc'.
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/resources/META-INF/services/co.cask.cdap.runtime.spi.provisioner.Provisioner
  cdap-runtime-ext-dataproc/src/test/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: 5.1

#10599 CDAP-14203 Add more logging when RemoteProcessController encounters uncommon failure scenarioes
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/SSHRemoteProcessController.java
Labels: 5.1

#10645 (CDAP-14276) Fix flaky KafkaTester
  cdap-data-fabric/src/test/java/co/cask/cdap/kafka/KafkaTester.java
Labels: 5.1

#10639 [CDAP13978] Makes Hub left panel scrollable
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 5.1, Bug, UI

#10642 [CDAP-14278] Fixes creating a pipeline for uploaded file
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
Labels: 5.1, Bug, UI

#10636 [CDAP-14144] Fix showing duration in UI to be consistent
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/ProfileAssociations.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 5.1, Bug, UI

#10633 [CDAP-14263][MMDS] Fix Analytics based on Dataprep connection changes.
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/CreateView.scss
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/store/createExperimentStore.js
Labels: 5.1, Bug, UI

#10640 [CDAP-13909] Fixes deleting connection in Dataprep to fallback to default connection
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 5.1, Bug, UI

#10643 [CDAP-10164] Makes button styling in pipeline naming modal same as others
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/app/hydrator/toppanel.less
Labels: 5.1, UI

#10646 [CDAP-13879] Changes icon color and shape for Pending status in pipelines
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunStatus.js
  cdap-ui/app/cdap/services/StatusMapper.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/services/status-mapper.js
  cdap-ui/app/hydrator/templates/list.html
Labels: 5.1, UI

#10637 [CDAP-14198] Makes product name configurable across UI
  cdap-ui/app/cdap/cdap.html
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/index.js
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/PageTitle/index.js
  cdap-ui/app/cdap/components/DataPrep/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/DataPrepHome/index.js
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/ActionCreator.js
  cdap-ui/app/cdap/components/EntityListView/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentDetailPageTitle/index.js
  cdap-ui/app/cdap/components/Experiments/ExperimentsServiceControl/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/Header/BrandSection/index.tsx
  cdap-ui/app/cdap/components/Header/ProductDropdown/AboutPageModal/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/components/Header/Tour/index.ts
  cdap-ui/app/cdap/components/Header/Welcome/index.tsx
  cdap-ui/app/cdap/components/LoadingIndicator/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/NamespaceDetailsPageTitle/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/Reports/ReportsServiceControl/index.js
  cdap-ui/app/cdap/components/Reports/index.js
  cdap-ui/app/cdap/components/RulesEngineHome/index.js
  cdap-ui/app/cdap/components/StreamDetailedView/index.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/logviewer/logviewer.html
  cdap-ui/app/logviewer/routes.js
  cdap-ui/app/styles/variables.less
  cdap-ui/app/tracker/routes.js
  cdap-ui/server/config/themes/default.json
Labels: 5.1, UI

#10650 [CDAP-14087] Fix metadata filters not working
  cdap-ui/app/tracker/controllers/results-ctrl.js
Labels: 5.1, Bug, UI

#10641 [CDAP-14121] Fixes 404 and 500 pages to look consistent.
  cdap-ui/app/cdap/components/404/404.scss
  cdap-ui/app/cdap/components/404/index.js
  cdap-ui/app/cdap/components/500/500.scss
  cdap-ui/app/cdap/components/500/index.js
  cdap-ui/app/cdap/styles/mixins.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10638 [CDAP-14208] Fixes instances of spark executor instances property to be consistent
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/NumExecutors.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigConstants.tsx
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 5.1, Bug, UI

#10649 [CDAP-14085] update styling of metadata landing page
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/styles/common.less
  cdap-ui/app/tracker/templates/main.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.1, Bug, UI

#10648 [CDAP-14007] Adds UI support for bi-directional field level lineage
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/FieldRow.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/Fields.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/Search.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Fields/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/Lineage/Lineage.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/Lineage/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/Directions.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/IncomingLineage.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/LineageSummary.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/OutgoingLineage.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/SummaryRow.js
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/Navigation.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsTable.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/TopPanel/TopPanel.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/TopPanel/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10655 [CDAP-13904] Fixes reloading dataprep on clicking on navbar
  cdap-ui/app/cdap/components/DataPrepHome/index.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.1, Bug, UI

#10657 (CDAP-13566) Part 1: Implement classes for dynamic socks proxy using SSH tunneling
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitorClient.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/SSHSessionProvider.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/proxy/MonitorSocksProxy.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/proxy/SocksServerConnectHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/proxy/SocksServerHandler.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/monitor/proxy/MonitorSocksProxyTest.java
  cdap-common/src/main/java/co/cask/cdap/common/http/Channels.java
  cdap-common/src/main/java/co/cask/cdap/common/ssh/DefaultPortForwarding.java
  cdap-common/src/main/java/co/cask/cdap/common/ssh/DefaultSSHSession.java
  cdap-common/src/test/java/co/cask/cdap/common/ssh/SSHSessionTest.java
  cdap-common/src/test/java/co/cask/cdap/common/ssh/TestSSHServer.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/HttpRequestRouter.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/OutboundHandler.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/ssh/PortForwarding.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/ssh/SSHSession.java
  cdap-security/src/main/java/co/cask/cdap/security/tools/HttpsEnabler.java
  cdap-security/src/test/java/co/cask/cdap/security/tools/HttpsEnablerTest.java
Labels: 5.1

#10600 Updating hadoop compatibility matrix
  cdap-docs/admin-manual/source/cdap-hadoop-compatibility.rst
  cdap-docs/developer-manual/build.sh
Labels: 5.0

#10654 CDAP-14003: Support outgoing connection lookup for field
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/DefaultFieldLineageReader.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: 5.1

#10660 Hive integration for date/time
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/partitioned/FieldTypes.java
  cdap-explore/src/main/java/co/cask/cdap/explore/table/SchemaConverter.java
  cdap-explore/src/main/java/co/cask/cdap/hive/datasets/DatasetInputFormat.java
  cdap-explore/src/main/java/co/cask/cdap/hive/datasets/DatasetSerDe.java
  cdap-explore/src/main/java/co/cask/cdap/hive/serde/ObjectDeserializer.java
  cdap-explore/src/main/java/co/cask/cdap/hive/serde/ObjectSerializer.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTestRun.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreTableTestRun.java
  cdap-explore/src/test/java/co/cask/cdap/explore/table/CreateStatementBuilderTest.java
  cdap-explore/src/test/java/co/cask/cdap/explore/table/SchemaConverterTest.java
Labels: 5.0

#10667 CDAP-14308 fix flaky SparkTest
  cdap-test/src/main/java/co/cask/cdap/test/AbstractProgramManager.java
  cdap-test/src/main/java/co/cask/cdap/test/ProgramManager.java
  cdap-unit-test/src/test/java/co/cask/cdap/spark/SparkTest.java
Labels: 5.1

#10664 [CDAP-14222] Show property name if label is not present
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/index.js
Labels: 5.1, Bug, UI

#10666 [CDAP-14184] Fix footer default text
  cdap-ui/app/login/text/text-en.yaml
Labels: 5.1, Bug, UI

#10676 CDAP-14310: Make Lineage Store return field for sources too
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDataset.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageDatasetTest.java
Labels: 5.1, Bug

#10609 [CDAP-14189] Fewer appfabric and dataset threads in tests
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
Labels: 5.1

#10618 [CDAP-14211] Batches runs count API in UI
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/cask-angular-sortable/sortable.js
  cdap-ui/app/hydrator/controllers/list-ctrl.js
  cdap-ui/app/hydrator/templates/list.html
  cdap-ui/app/services/constants.js
  cdap-ui/app/services/hydrator/my-pipeline-api.js
Labels: 5.1, UI

#10659 [CDAP-14230] Fixes runs in pending to show the right marks in run summary view
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/RunsHistoryGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/Store/PipelineSummaryStore.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10662 Fixes deleting schedules/triggers when pipeline is updated
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
Labels: 5.1, Bug, UI

#10663 [CDAP-14274] Fixes hover area for showing tooltips in profile creation page
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
Labels: 5.1, Bug, UI

#10670 [CDAP-14228] New user experience improvements
  cdap-ui/app/cdap/components/EntityListView/Tour/index.ts
  cdap-ui/app/cdap/components/EntityListView/Welcome/Welcome.scss
  cdap-ui/app/cdap/components/EntityListView/Welcome/index.tsx
  cdap-ui/app/cdap/components/EntityListView/index.js
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/services/GuidedTour/GuidedTour.scss
Labels: 5.1, UI

#10668 [CDAP-14239][CDAP-14277] Disable change data type directive for avro logical time
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/DataType/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ChangeDataType/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10679 [CDAP-14293] Get theme properties from cdap-site.xml instead of ui-settings.json
  cdap-common/src/main/resources/cdap-default.xml
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/server/config/parser.js
  cdap-ui/server/express.js
Labels: 5.1, UI

#10683 [CDAP-14294] Add options for entity top panel
  cdap-ui/app/cdap/components/EntityTopPanel/EntityTopPanel.scss
  cdap-ui/app/cdap/components/EntityTopPanel/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/index.js
Labels: 5.1, UI

#10661 [CDAP-14171] Fixes the font size of headings to be consistent
  cdap-ui/app/cdap/components/EntityCard/EntityCardHeader/EntityCardHeader.scss
  cdap-ui/app/cdap/components/EntityCard/EntityCardHeader/index.js
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/directives/complex-schema/complex-schema.less
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/plugin-templates/plugin-templates.html
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/templates/create/popovers/leftpanel-plugin-popover.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/app/styles/common.less
  cdap-ui/app/styles/variables.less
Labels: 5.1, Bug, UI

#10689 [CDAP-13812] Adds ability to navigate to specific run from stop runs popover
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineStopButton/PipelineStopPopover.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineStopButton/PipelineStopPopover.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineStopButton/index.js
Labels: 5.1, UI

#10692 (CDAP-14203) Starts runtime monitor after starting the remote process
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
Labels: 5.1

#10691 Fix failing doc build
  cdap-docs/admin-manual/build.sh
  cdap-docs/vars
Labels: 5.1, Docs

#10684 [CDAP-14207] Fixes typo and case for labels show in directives in dataprep
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10693 [CDAP-14051] CDAP documentation url change in UI
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
Labels: 5.1, UI

#10682 [CDAP-8555] Fixes tooltip to show right in schema tab in entity's overview and detailed view
  cdap-ui/app/cdap/components/AppDetailedView/AppDetailedView.scss
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/Overview/Overview.scss
  cdap-ui/app/cdap/components/Overview/Tabs/OverviewTab.scss
Labels: 5.1, Bug, UI

#10688 [CDAP-14266] Fixes deleting system profile to not use namespace based API
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
Labels: 5.1, Bug, UI

#10694 [CDAP-14329] Fix to not hide last tab every time realtime pipeline config modeless is opened
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
Labels: 5.1, Bug, UI

#10697 [CDAP-14164] Fixes the send-to-error condition labels to be consistent
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10685 Updates ui.theme.file property in cdap-default.xml to use relative path
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
Labels: 5.1, UI

#10686 [CDAP-14272] Fixes deleting empty custom config causing broken UI
  cdap-ui/app/cdap/components/KeyValuePairs/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
Labels: 5.1, Bug, UI

#10696 [CDAP-14315] Fixes surfacing error while deleting connection in dataprep
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/AccessTokenModal/index.js
  cdap-ui/app/cdap/services/redirect-to-login.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10703 [CDAP-14341] make metadata optional and add license info in market
  cdap-ui/app/cdap/components/MarketPlaceEntity/LicenseRow.tsx
  cdap-ui/app/cdap/components/MarketPlaceEntity/index.js
  cdap-ui/app/cdap/components/MarketPlaceUsecaseEntity/LicenseRow.tsx
  cdap-ui/app/cdap/components/MarketPlaceUsecaseEntity/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10698 CDAP-13008 fix alert publisher
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/PipelinePluginInstantiator.java
Labels: 5.1, Bug

#10711 [CDAP-14354] Fix lineage operations table overflow
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsModal.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsTable.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/index.js
Labels: 5.1, Bug, UI

#10709 [CDAP-14359] Fixes unnecessary horizontal scroll while adding kafka connection in UI
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/KafkaConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/UploadFile/index.js
Labels: 5.1, Bug, UI

#10704 [CDAP-14322] Fix dataprep column types checking
  cdap-ui/app/cdap/components/DataPrep/Directives/Calculate/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ChangeDataType/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Format/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/MarkAsError/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/MaskData/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/SetCharacterEncoding/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/SetCounter/index.js
  cdap-ui/app/cdap/components/DataPrep/store/index.js
  cdap-ui/app/cdap/components/ScrollableList/index.js
Labels: 5.1, Bug, UI

#10713 [CDAP-14211] Fix runs count in pipeline detail view
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/CurrentRunIndex.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLogs.js
  cdap-ui/app/cdap/components/PipelineDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/store/index.js
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: 5.1, Bug, UI

#10706 [CDAP-14331] Makes favicon customizable
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/server/config/themes/default.json
  cdap-ui/server/express.js
Labels: 5.1, UI

#10714 [CDAP-14374] Add the ability to build UI in non-parallel fashion for restricted environments
  cdap-ui/package.json
  cdap-ui/pom.xml
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.login.js
  cdap-ui/webpack.config.shared.dll.js
  cdap-ui/yarn.lock
Labels: 5.1, UI

#10690 Add jvm option to kill CDAP if there is an OOM
  cdap-common/bin/functions.sh
Labels: 5.1

#10712 [CDAP-14361] Modifies header product dropdown to not show cdap mode for now
  cdap-ui/app/cdap/components/Header/ProductDropdown/ProductDropdown.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/services/redirect-to-login.js
Labels: 5.1, Bug, UI

#10718 (CDAP-14116) Copy required third party sources and licenses
  cdap-distributions/src/third-party-licenses/cco.license
  cdap-distributions/src/third-party-licenses/glassfish.license
  pom.xml
Labels: 5.1

#10716 [CDAP-14373] Naive fix for not showing scrollbar for plugin names in pipeline studio left panel
  cdap-ui/app/hydrator/leftpanel.less
Labels: 5.1, Bug, UI

#10720 [CDAP-14352] Add placeholders to dataprep connections modals
  cdap-ui/app/cdap/components/BtnWithLoading/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, UI

#10719 [CDAP-14377] Gets cdap config from cConf, instead of API call
  cdap-ui/server/config/development/cdap.json
  cdap-ui/server/config/parser.js
  cdap-ui/server/express.js
Labels: 5.1, Bug, UI

#10721 [CDAP-14374] Fixes npm script to run both react and angular side of code
  cdap-ui/package.json
  cdap-ui/webpack.config.common.js
Labels: 5.1, Bug, UI

#10717 [CDAP-14365] Fixes showing 'Pending' state as 'Provisioning' state in UI for pipelines
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/index.js
  cdap-ui/app/cdap/services/StatusMapper.js
  cdap-ui/app/cdap/styles/variables.scss
  cdap-ui/app/hydrator/controllers/list-ctrl.js
Labels: 5.1, Bug, UI

#10728 [CDAP-14383] Fix text in Field Level Lineage operations modal
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10729 Add access control header
  cdap-ui/app/cdap/services/StatusFactory.js
Labels: 5.1, UI

#10726 [CDAP-14380] Style changes to navbar for product dropdown
  cdap-ui/app/cdap/components/Header/Header.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/ProductDropdown.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/components/Header/index.js
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
  cdap-ui/webpack.config.common.js
Labels: 5.1, UI

#10730 [CDAP-14396] [CDAP-14391] Fix to navigate to right path in gcs when the file is in root folder
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 5.1, Bug, UI

#10732 [CDAP-14389] Fixes pipeline drafts to show correct status
  cdap-ui/app/hydrator/controllers/list-ctrl.js
  cdap-ui/app/hydrator/templates/list.html
Labels: 5.1, Bug, UI

#10737 CDAP-14326 Return once dataset is invalidated from cache
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/SingleThreadDatasetCache.java
Labels: 5.1

#10739 [CDAP-14413] Makes Hub and Add Entity modal headers consistent with other modals
  cdap-ui/app/cdap/components/Header/ProductDropdown/ProductDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
  cdap-ui/app/cdap/components/PlusButtonModal/index.js
Labels: 5.1, Bug, UI

#10699 [CDAP-14205] Fix "No tables" message flashing when loading tables in Spanner
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/DatasetList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/database.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/kafka.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/spanner.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/InstanceList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/server/config/ui-settings.json
Labels: 5.1, Bug, UI

#10735 [CDAP-14402][CDAP-14386] make projectId and bucket optional
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
Labels: 5.1, Bug, UI

#10742 [CDAP-14411] Updates user interface service down message
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10736 [CDAP-14412] Add tooltip for plugin description in plugin modal header
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 5.1, Bug, UI

#10743 [CDAP-14369] Updates tracker search tips message based on updated design
  cdap-ui/app/tracker/controllers/main-ctrl.js
  cdap-ui/app/tracker/templates/main.html
  cdap-ui/app/tracker/tracker.less
Labels: 5.1, UI

#10740 [CDAP-14416] Fixes KeyvaluePairs component to update properly on user interaction
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/index.js
Labels: 5.1, Bug, UI

#10733 [CDAP-14362] Use categories from backend in market
  cdap-ui/app/cdap/api/market.js
  cdap-ui/app/cdap/components/ConfigurableTab/ConfigurableTab.scss
  cdap-ui/app/cdap/components/ConfigurableTab/TabIcon.tsx
  cdap-ui/app/cdap/components/ConfigurableTab/index.js
  cdap-ui/app/cdap/components/Market/CategoryMap.ts
  cdap-ui/app/cdap/components/Market/TabConfig.js
  cdap-ui/app/cdap/components/Market/index.js
Labels: 5.1, UI

#10715 CDAP-13964 fix using a non-thread safe class
  cdap-watchdog/src/main/java/co/cask/cdap/logging/read/KafkaLogReader.java
Labels: 5.1, Bug

#10734 [CDAP-14211] Fixes runs navigation in pipeline detailed view for pipelines with more than 100 runs
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/CurrentRunIndex.js
  cdap-ui/app/cdap/components/PipelineDetails/store/ActionCreator.js
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: 5.1, Bug, UI

#10746 [CDAP-14423] Makes Welcome modal body text configurable
  cdap-ui/app/cdap/components/EntityListView/Welcome/index.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/server/config/themes/default.json
Labels: 5.1, UI

#10745 [CDAP-14420] reorder global navbar
  cdap-ui/app/cdap/components/EntityListView/Tour/index.ts
  cdap-ui/app/cdap/components/Header/index.js
Labels: 5.1, UI

#10744 [CDAP-14399] Make lineage cell clickable
  cdap-ui/app/cdap/components/FieldLevelLineage/LineageSummary/LineageSummary.scss
Labels: 5.1, Bug, UI

#10748 [CDAP-14394] Add auth refresher iframe
  cdap-ui/app/cdap/components/AuthRefresher/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/logviewer/logviewer.html
  cdap-ui/app/tracker/tracker.html
  cdap-ui/server/express.js
Labels: 5.1, UI

#10747 CDAP-14407 Make fll case insensitive
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/FieldLineageAdminTest.java
Labels: 5.1
