Repository cdapio/cdap, pull requests merged in 2018-05, with the labels that each got.

#10093 [CDAP-12898] add namespace picker to reports
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/NamespacesPicker/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/Reports/Reports.scss
  cdap-ui/app/cdap/components/Reports/ReportsList/ActionPopover.js
  cdap-ui/app/cdap/components/Reports/ReportsList/index.js
  cdap-ui/app/cdap/components/Reports/store/ActionCreator.js
  cdap-ui/app/cdap/components/Reports/store/ReportsStore.js
Labels: 5.0, UI

#10109 [CDAP-13187] Tags improvements/bugfixes
  cdap-ui/app/cdap/components/Overview/OverviewMetaSection/OverviewMetaSection.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/PipelineDetailsActionsButton.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/Tags/Tag/Tag.scss
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/Tags.scss
  cdap-ui/app/cdap/components/Tags/index.js
  cdap-ui/app/cdap/styles/variables.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, Bug, UI

#10055 transfer data from tms to fileset
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/ReportGenerationSpark.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/MessageUtil.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/Notification.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/ProgramDescriptor.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/ProgramRunInfo.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/ProgramRunInfoSerializer.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/ProgramStartInfo.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/RunMetaFileManager.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/RunMetaFileOutputStream.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/SampledLogging.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/SparkPersistRunRecordMain.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/main/TMSSubscriber.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/proto/ReportGenerationRequest.java
  cdap-app-templates/cdap-program-report/src/main/java/co/cask/cdap/report/util/Constants.java
Labels: 5.0

#10122 fix ui pack version
  cdap-ui/pom.xml
Labels: 4.3, Bug, UI

#10120 (CDAP-13411) Fix flaky tests related to async dataset write
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/FilterAppWithNewFlowAPI.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 5.0

#10126 Fix compilation error
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
  cdap-examples/DecisionTreeRegression/src/test/java/co/cask/cdap/examples/dtree/DecisionTreeRegressionAppTest.java
Labels: 5.0

#10129 (CDAP-13234) Record the program starting state immediately
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/TestFrameworkTestRun.java
Labels: 5.0

#10131 (CDAP-13418) Handle message replay correctly.
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 5.0

#10111 [CDAP-13361] Admin page updates (Remove Component Overview and Operational stats)
  cdap-ui/app/cdap/components/AdminOverviewPane/AdminOverviewPane.scss
  cdap-ui/app/cdap/components/AdminOverviewPane/index.js
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/AdminManagementTabContent.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/PlatformsDetails/PlatformDetails.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/PlatformsDetails/index.js
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/ServicesTable.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/index.js
  cdap-ui/app/cdap/components/Administration/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/components/OverviewPaneCard/OverviewPaneCard.scss
  cdap-ui/app/cdap/components/OverviewPaneCard/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#10124 (CDAP-12907) Update JVM options for Java 8
  BUILD.rst
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/ExternalSparkProgram.java
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/co/cask/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/batch/ETLSpark.java
  cdap-common/bin/functions.sh
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/bin/tx-debugger.bat
  cdap-distributions/src/packer/scripts/fill-maven-cache.sh
  cdap-docs/admin-manual/build.sh
  cdap-docs/admin-manual/source/_includes/installation/configuration.txt
  cdap-docs/build.sh
  cdap-docs/developer-manual/source/getting-started/dev-env.rst
  cdap-docs/developer-manual/source/testing/testing.rst
  cdap-docs/faqs/source/applications.txt
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-examples/SpamClassifier/src/main/scala/co/cask/cdap/examples/sparkstreaming/SpamClassifierProgram.scala
  cdap-examples/SparkPageRank/src/main/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankApp.java
  cdap-examples/WikipediaPipeline/src/main/java/co/cask/cdap/examples/wikipedia/SparkWikipediaClustering.java
  cdap-examples/deploy_pom.xml
  cdap-standalone/bin/cdap.bat
  pom.xml
Labels: 5.0

#10141 CDAP-13430 run sinks in parallel for spark pipelines
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/SparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/streaming/DStreamCollection.java
Labels: 4.3

#10145 [CDAP-13450] Cleaning UI for minor details
  cdap-runtime-ext-dataproc/src/main/resources/gce-dataproc.json
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/PropertyLock/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/ProvisionerSelection.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Experiments/ExperimentsServiceControl/index.js
  cdap-ui/app/cdap/styles/img/MMDS_preview1.png
  cdap-ui/app/cdap/styles/img/MMDS_preview2.png
Labels: 5.0, UI

#10147 [CDAP-13387] Fixes showing default profile at run level in pipeline detailed view
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunComputeProfile/index.js
Labels: 5.0, Bug, UI

#10134 [CDAP-13382] Uses Provisioner label for all profile references in UI
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/BasicInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/DetailsInfo.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/index.js
Labels: 5.0, UI

#10146 [CDAP-13302] dashboard reports improvements
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/DataParser.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/RunsList.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/Runs/index.js
Labels: 5.0, UI
