Repository cdapio/cdap, pull requests merged in 2018-03, with the labels that each got.

#9937 fix build break
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetAdminService.java
Labels: 4.3, Bug

#9934 [CDAP-13111] - Fix performance issue with pipeline detailed view
  cdap-ui/app/directives/node-metrics/node-metrics.html
  cdap-ui/app/directives/node-metrics/node-metrics.js
  cdap-ui/app/filters/comma-separated-number.js
  cdap-ui/app/filters/number-with-ellipsis.js
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/templates/partial/metrics-popover.html
Labels: 4.3, Bug, UI

#9939 update momentJS
  cdap-ui/dll/cdap-vendor-manifest.json
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.0, UI

#9922 [CDAP-13077] Finishes up rewrite of Configure modeless in Pipeline detail view
  cdap-ui/app/cdap/api/artifact.js
  cdap-ui/app/cdap/components/DSVEditor/index.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePairs.scss
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStoreActions.js
  cdap-ui/app/cdap/components/KeyValuePairs/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/AlertsTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsActionButtons/ConfigurationsActionButtons.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsActionButtons/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigurationsContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/CustomConfig.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/BatchInterval.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Checkpointing.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Instrumentation.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/StageLogging.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ClientResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/DriverResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/ProvidedPopover.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/RuntimeArgsPairs.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/RuntimeArgsTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsSidePanel/ConfigurationsSidePanel.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.js
  cdap-ui/app/cdap/components/PipelineDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/store/index.js
  cdap-ui/app/cdap/components/PostRunActions/PostRunActions.scss
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/cdap/components/PostRunActions/index.js
  cdap-ui/app/cdap/components/RadioGroup/index.js
  cdap-ui/app/cdap/services/AvailablePluginsStore/index.js
  cdap-ui/app/cdap/services/HydratorPluginConfigFactory.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.less
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
  cdap-ui/app/hydrator/controllers/detail/canvas-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/available-plugins-store.js
Labels: 5.0, UI

#9941 [CDAP-13146] Fixes height of cask market body to be the same as parent for auto scrolling
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 5.0, Bug, UI

#9946 Minor js error fix while transitioning from shortid to node-uuid/v4
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/PieChart/index.js
  cdap-ui/app/cdap/components/UncontrolledComponents/Popover.js
Labels: 5.0, Bug, UI

#9949 [RulesEngine] Fix error message during the start of Rules engine
  cdap-ui/app/cdap/components/Experiments/ExperimentsServiceControl/index.js
  cdap-ui/app/cdap/components/FastAction/DeleteAction/index.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/ExploreModal.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/index.js
  cdap-ui/app/cdap/components/FastAction/SendEventAction/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/index.js
  cdap-ui/app/cdap/components/FastAction/TruncateAction/index.js
  cdap-ui/app/cdap/components/Overview/OverviewMetaSection/index.js
  cdap-ui/app/cdap/components/ProgramTable/index.js
  cdap-ui/app/cdap/components/RulesEngineHome/RulesEngineServiceControl/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, Bug, UI

#9940 [CDAP-12849][CDAP-12865] OpsDashboard Graph and List View Interaction
  cdap-ui/app/cdap/api/operations.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/OpsDashboard/OpsDashboard.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/DataParser.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsGraph.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/ToggleRunsList.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/graphRenderer.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/RunsList.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsList/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
  cdap-ui/dll/cdap-vendor-manifest.json
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 5.0, UI

#9952 [CDAP-13171] Only set group on namespace directories if the group was explicitly configured
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
  cdap-docs/reference-manual/source/http-restful-api/namespace.rst
Labels: 4.3, Bug, Docs

#9948 (CDAP-13158) Fix a race condition when running concurrent spark in wo…
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtils.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/test/java/co/cask/cdap/app/runtime/spark/SparkRuntimeUtilsTest.java
Labels: 4.3

#9955 [CDAP-12554] Adds labels to stage properties name while selecting the payload
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsActions.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsStore.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/Tabs/StagePropertiesTab/StagePropertiesRow.js
Labels: 5.0, Bug, UI

#9950 Fix references of node-uuid used for id for DOM elements
  cdap-ui/app/cdap/components/FastAction/DeleteAction/index.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/ExploreModal.js
  cdap-ui/app/cdap/components/FastAction/ExploreAction/index.js
  cdap-ui/app/cdap/components/FastAction/SendEventAction/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/index.js
  cdap-ui/app/cdap/components/FastAction/TruncateAction/index.js
  cdap-ui/app/cdap/components/Overview/OverviewMetaSection/index.js
  cdap-ui/app/cdap/components/ProgramTable/index.js
  cdap-ui/app/cdap/components/UncontrolledComponents/Popover.js
  cdap-ui/app/tracker/directives/jump/jump.less
Labels: 4.3, Bug, UI

#9947 [CDAP-13117] Adds sorting to experiments list and models list view in MMDS
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentMetricsDropdown/AlgorithmDistribution.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ExperimentMetricsDropdown/ModelStatusesDistribution.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/DetailedViewModelsTable.scss
  cdap-ui/app/cdap/components/Experiments/DetailedView/ModelsTable/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/index.js
  cdap-ui/app/cdap/components/Experiments/ListView/ListView.scss
  cdap-ui/app/cdap/components/Experiments/ListView/ListViewWrapper.js
  cdap-ui/app/cdap/components/Experiments/ListView/index.js
  cdap-ui/app/cdap/components/Experiments/store/ActionCreator.js
  cdap-ui/app/cdap/components/Experiments/store/experimentDetailStore.js
  cdap-ui/app/cdap/components/Experiments/store/index.js
  cdap-ui/app/cdap/components/PieChart/index.js
Labels: 5.0, Bug, UI

#9960 [CDAP-13162] Retain code editors if macro'd
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.html
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.js
Labels: 4.3, Bug, UI

#9942 Allowing apps in system namespace
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/AuthorizationArtifactRepository.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/PluginFinderTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DefaultDatasetTypeService.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DynamicDatasetCache.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceMeta.java
  cdap-security/src/main/java/co/cask/cdap/security/impersonation/DefaultOwnerAdmin.java
  cdap-standalone/src/test/java/co/cask/cdap/StandaloneTester.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/system/CDAPLogAppender.java
Labels: 5.0

#9959 [CDAP-12849] add graph interaction with legends and app types
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/DataParser.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/Legends/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsGraph.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/TypeSelector/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/graphRenderer.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/OpsDashboard/store/ActionCreator.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
  cdap-ui/app/cdap/services/datasource/index.js
Labels: 5.0, UI

#9945 log user who executes the program
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 4.3

#9956 (CDAP-13179) Integrates TWILL-61 changes for AM resilience
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedFlowProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/LongRunningDistributedProgramRunner.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  pom.xml
Labels: 4.3

#9967 fix overflow of body in collapsible sidebar
  cdap-ui/app/cdap/components/CollapsibleSidebar/CollapsibleSidebar.scss
Labels: 5.0, Bug, UI

#9977 (CDAP-13218) Distinguish program state based on user actions
  cdap-app-fabric/src/main/java/co/cask/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
Labels: 4.3

#9971 [CDAP-13180] Initial PR for Namespace Details page
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Description/Description.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Description/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/EntityCounts/EntityCounts.scss
  cdap-ui/app/cdap/components/NamespaceDetails/EntityCounts/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Mapping/Mapping.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Mapping/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/NamespaceDetails.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/Preferences.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Security/Security.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Security/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/TopPanel/TopPanel.scss
  cdap-ui/app/cdap/components/NamespaceDetails/TopPanel/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/index.js
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/CustomConfig.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/index.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#9973 CDAP-13154 Use just the username and not kerberos principal for auth…
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/DatasetServiceClient.java
  cdap-security/src/main/java/co/cask/cdap/security/authorization/AuthorizationUtil.java
  cdap-security/src/test/java/co/cask/cdap/security/authorization/AuthorizationUtilTest.java
Labels: 4.3

#9972 [CDAP-13213][Cloud] Adds presentation layer for Create Profile view
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.js
  cdap-ui/app/cdap/components/AbstractWidget/MemorySelectWidget/MemorySelectWidget.scss
  cdap-ui/app/cdap/components/AbstractWidget/MemorySelectWidget/index.js
  cdap-ui/app/cdap/components/AbstractWidget/MemoryTextbox/MemoryTextbox.scss
  cdap-ui/app/cdap/components/AbstractWidget/MemoryTextbox/index.js
  cdap-ui/app/cdap/components/AbstractWidget/NumberTextbox/NumberTextbox.scss
  cdap-ui/app/cdap/components/AbstractWidget/NumberTextbox/index.js
  cdap-ui/app/cdap/components/AbstractWidget/SelectWidget/SelectWidget.scss
  cdap-ui/app/cdap/components/AbstractWidget/SelectWidget/index.js
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/AbstractWidget/WidgetVars.scss
  cdap-ui/app/cdap/components/AbstractWidget/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateView.scss
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/sample-view-spec.json
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/SelectWithOptions/index.js
Labels: 5.0, UI

#9981 CDAP-2388 Upgrade guice version to 4.2.0.
  pom.xml
Labels: 5.0

#9988 Update release notes
  cdap-docs/reference-manual/source/release-notes.rst
Labels: 4.3

#9979 [CDAP-12849][CDAP-12869] Ops Dashboard Navigation
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPicker.scss
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/NamespacesPicker/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsGraph.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/graphRenderer.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/index.js
  cdap-ui/app/cdap/components/OpsDashboard/index.js
  cdap-ui/app/cdap/components/OpsDashboard/store/ActionCreator.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
Labels: 5.0, UI

#9965 (CDAP-13143) Supports recursive Schema correctly
  cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/Schema.java
  cdap-common/src/test/java/co/cask/cdap/io/SchemaTest.java
Labels: 5.0

#9957 Adding first draft of polling service
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorConsumeRequest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/MonitorMessage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-client/src/main/java/co/cask/cdap/client/util/RESTClient.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 5.0

#9989 Update MD5
  cdap-docs/admin-manual/build.sh
  cdap-docs/integrations/build.sh
Labels: 4.3

#9976 CDAP-13096 move scheduler out of program lifecycle service
  cdap-api/src/main/java/co/cask/cdap/api/schedule/Trigger.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/Schedulers.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ProgramScheduleService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramType.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 5.0

#9985 [CDAP-12849] add table view for ops dashboard
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsGraph.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsTable/RunsTable.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/RunsTable/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/index.js
  cdap-ui/app/cdap/components/OpsDashboard/store/DashboardStore.js
Labels: 5.0, UI

#9987 [CDAP-13180] Highlight newly added/edited prefs, and adds View All/View Less prefs labels in Namespace Details page
  cdap-ui/app/cdap/components/Administration/index.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Mapping/Mapping.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Mapping/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/Preferences.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Security/Security.scss
  cdap-ui/app/cdap/components/NamespaceDetails/Security/index.js
  cdap-ui/app/cdap/components/NamespaceDropdown/index.js
  cdap-ui/app/cdap/services/WizardStores/AddNamespace/ActionCreator.js
  cdap-ui/app/cdap/services/global-events.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#9984 [CDAP-13207][Cloud] Allow users to select a profile while manually running a pipeline
  cdap-ui/app/cdap/api/cloud.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStore.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStoreActions.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ListViewInPipeline.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/ConfigModelessRuntimeArgsCount.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/RuntimeArgsTabContent/RuntimeArgsPairs.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsSidePanel/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/components/PipelineDetails/store/ActionCreator.js
  cdap-ui/app/cdap/styles/variables.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.0, UI

#9998 Feature/cdap 13088 metadata custom entity
  cdap-api/src/main/java/co/cask/cdap/api/metadata/Metadata.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataEntity.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataReaderContext.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataScope.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataWriterContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataUpgrader.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataAuditPublishTest.java
  cdap-cli/src/main/java/co/cask/cdap/cli/DefaultCompleters.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataPropertiesCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataTagsCommand.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/LineageTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/AbstractMetadataClient.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataRecord.java
  cdap-common/src/test/java/co/cask/cdap/common/metadata/MetadataRecordTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/payload/builder/MetadataPayloadBuilder.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/SystemMetadataWriter.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/MetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriterTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/writer/BasicLineageWriterTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/audit/payload/metadata/MetadataPayload.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/ApplicationId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/ArtifactId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/DatasetId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/EntityId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/NamespaceId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/ProgramId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/StreamId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/StreamViewId.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResultRecord.java
  cdap-proto/src/test/java/co/cask/cdap/proto/audit/AuditMessageTest.java
Labels: 5.0

#10004 [CDAP-13213] Fixes backend integration mis-match while listing profiles in pipeline detailed view
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ComputeTabContent/ProfilesListView.js
Labels: 5.0, Bug, UI
