Repository cdapio/cdap, pull requests merged in 2018-10, with the labels that each got.

#10750 [CDAP-14425] Fix UI to use connection id while redirecting to default connection
  cdap-ui/app/cdap/components/DataPrepConnections/NoDefaultConnection/index.tsx
Labels: 5.1, Bug, UI

#10754 CDAP-14433 change kafka log level sandbox
  cdap-standalone/src/main/resources/logback.xml
Labels: 5.1, Bug

#10741 CDAP-8559: Improve metadata error message
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-common/src/main/java/co/cask/cdap/common/InvalidMetadataException.java
  cdap-common/src/test/java/co/cask/cdap/common/InvalidMetadataExceptionTest.java
Labels: 5.1

#10753 CDAP-14435 fix profile metrics deletion
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/ProfileHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowStatsSLAHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/AbstractNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/flow/FlowUtils.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileServiceTest.java
  cdap-test/src/main/java/co/cask/cdap/test/MetricsManager.java
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricStore.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsQueryHelper.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
Labels: 5.1, Bug

#10756 [CDAP-14437] Fix dll build NODE_ENV value
  cdap-ui/package.json
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/webpack.config.shared.dll.js
  cdap-ui/yarn.lock
Labels: 5.1, Bug, UI

#10757 CDAP-14078 Changed log level for any errors during field lineage recording to DEBUG.
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/workflow/WorkflowDriver.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/LineageOperationsProcessor.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/co/cask/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/LineageOperationProcessorTest.java
Labels: 5.1

#10760 CDAP-14314 fix upgrade tool
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDataset.java
Labels: 5.1, Bug

#10758 [CDAP-14441] Fixes pipeline properties to be stored as strings
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/CustomConfig.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config-ctrl.js
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config.html
  cdap-ui/app/hydrator/controllers/list-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 5.1, Bug, UI

#10764 [CDAP-14445] Check property existence before checking length
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
Labels: 5.1, Bug, UI

#10765 [CDAP-14453] Fixes pressing ENTER in wrangler plugin config modal to always open wrangler modal
  cdap-ui/app/directives/widget-container/widget-wrangler-directives/widget-wrangler-directives.html
Labels: 5.1, Bug, UI

#10767 CDAP-14456 drop mapr 4.1 support
  cdap-docs/admin-manual/source/cdap-hadoop-compatibility.rst
  cdap-docs/vars
Labels: 5.1, Docs

#10777 CDAP-14168 Update FLL doc for ds schema and outgoing operations
  cdap-docs/reference-manual/source/http-restful-api/metadata.rst
Labels: 5.1, Docs

#10771 [CDAP-14458] Fixes navigation in namespace details view to show correct information when using browser navigation
  cdap-ui/app/cdap/components/NamespaceDetails/index.js
Labels: 5.1, Bug, UI

#10778 CDAP-13974 plugin requirement docs
  cdap-docs/developer-manual/source/pipelines/developing-plugins/plugin-basics.rst
Labels: 5.1, Docs

#10775 [CDAP-14454] add workspace id to query parameters
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
Labels: 5.1, Bug, UI

#10776 [CDAP-14463] Remove author and company info from market entity
  cdap-ui/app/cdap/components/MarketPlaceEntity/MarketPlaceEntity.scss
  cdap-ui/app/cdap/components/MarketPlaceEntity/index.js
  cdap-ui/app/cdap/components/MarketPlaceUsecaseEntity/index.js
Labels: 5.1, Bug, UI

#10768 [Dataprep] [UI] Fixes dataprep landing page to properly navigate to dataprep when service is running
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/api/experiments.js
  cdap-ui/app/cdap/api/reports.js
  cdap-ui/app/cdap/api/rulesengine.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepServiceControl/index.js
  cdap-ui/app/cdap/services/ServiceEnablerUtilities.js
Labels: 5.1, Bug, UI

#10766 CDAP-14443 Add documentation for date and time support
  cdap-docs/developer-manual/source/pipelines/developing-plugins/plugin-basics.rst
  cdap-docs/user-guide/source/data-preparation/directives/index.rst
  cdap-docs/user-guide/source/data-preparation/directives/parse-timestamp.rst
Labels: 5.1, Docs

#10774 CDAP-14462 add docs for cdap env
  cdap-docs/developer-manual/source/getting-started/start-stop-cdap.rst
Labels: 5.1, Docs

#10763 [CDAP-14446] Fixes S3 & GCS browsers in dataprep UI for large amount of data
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/ListingInfo/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/ListingInfo/ListingInfo.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/ListingInfo/index.js
  cdap-ui/app/cdap/components/EmptyMessageContainer/index.js
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 5.1, Bug, UI

#10782 [UI] [Theme] Fixes about product page to be visible by default
  cdap-ui/server/config/themes/default.json
Labels: 5.1, Bug, UI

#10780 [CDAP-14479]Fixes dataprep connection to show upload section when going from dataprep to connections
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 5.1, Bug, UI

#10781 [CDAP-14472] Remove stream default query for homepage
  cdap-ui/app/cdap/components/EntityListView/SearchStore/SearchConstants.js
Labels: 5.1, Bug, UI

#10785 [CDAP-14487] fix truncate fast action success styling
  cdap-ui/app/cdap/components/FastAction/TruncateAction/index.js
Labels: 5.1, Bug, UI

#10784 Bugfix release ui/cdap 14485 add property modal
  cdap-ui/app/cdap/components/DataPrep/TopPanel/UpgradeModal.js
  cdap-ui/app/cdap/components/PropertiesEditor/AddPropertyModal/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/EditProperty/index.js
  cdap-ui/app/cdap/components/Reports/ReportsDetail/SaveButton/SaveModal.js
Labels: 5.1, Bug, UI

#10783 [CDAP-14483] Minor navbar changes
  cdap-ui/app/cdap/components/Header/Header.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/ProductDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
Labels: 5.1, UI

#10789 [CDAP-14499] Remove global padding for tooltip bottom placement
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
Labels: 5.1, Bug, UI

#10787 [CDAP-14492] Fix profile node hours in UI to fix to 2 decimal
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
Labels: 5.1, Bug, UI

#10794 [CDAP-14491] Fix log viewer display status
  cdap-ui/app/directives/log-viewer/log-viewer.html
  cdap-ui/app/directives/log-viewer/log-viewer.js
  cdap-ui/app/logviewer/controllers/home-ctrl.js
  cdap-ui/app/logviewer/templates/home.html
  cdap-ui/app/services/StatusMapper.js
Labels: 5.1, Bug, UI

#10788 CDAP-14498 improve app deployment failure messages
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/runtime/WorkflowTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/pipeline/SynchronousPipeline.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/spec/PipelineSpecGenerator.java
Labels: 5.1

#10796 add 5.1.0 release notes
  cdap-docs/reference-manual/source/release-notes.rst
Labels: 5.1

#10803 [CDAP-14516] suppress chatty UI build logs
  cdap-ui/package.json
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.login.js
  cdap-ui/webpack.config.shared.dll.js
  cdap-ui/yarn.lock
Labels: 5.2, UI

#10801 CDAP-14515 Update doc to drop java 7 from requirements
  cdap-docs/admin-manual/source/system-requirements.rst
  cdap-docs/developer-manual/source/getting-started/sandbox/index.rst
  cdap-docs/faqs/source/general.rst
  cdap-docs/vars
Labels: 5.0, 5.1

#10805 [CDAP-14519] Fix dashboard theme default spelling
  cdap-ui/app/cdap/services/ThemeHelper.ts
Labels: 5.1, Bug, UI

#10779 [CDAP-14465] Adds UI customization docs
  cdap-docs/_common/_themes/cdap-bootstrap/static/cdap-bootstrap.css_t
  cdap-docs/admin-manual/source/operations/cdap-ui.rst
Labels: 5.1, Docs, UI

#10806 CDAP-14524 fix single input output
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceContextConfig.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/dataset/output/MultipleOutputsMainOutputWrapper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/dataset/output/AppWithSingleInputOutput.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/dataset/output/ConfigVerifyingInputFormat.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/dataset/output/ConfigVerifyingOutputFormat.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/dataset/output/MapReduceConfigTest.java
Labels: 5.1, Bug

#10815 [CDAP-14291] Exclude storybook-static generated folder from pom ui build
  cdap-ui/pom.xml
Labels: 5.2, Bug, UI
