Repository cdapio/cdap, pull requests merged in 2019-12, with the labels that each got.

#11760 Fix FLL v2 e2e test
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.1, Bug, UI, cla: yes

#11745 (CDAP-16116) Update input field dropdown, select, multiselect and GetSchema
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
Labels: 6.1, UI, cla: yes

#11758 [CDAP-16114] Homepage cards links enhancement
  cdap-ui/app/cdap/components/Home/HomeActions/ActionCard.tsx
Labels: 6.1, Bug, UI, cla: yes

#11752 [CDAP-16133] Fix UI to stop polling on tabs/windows not active
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/SystemServicesStore.js
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: 6.1, UI, cla: yes

#11767 (CDAP-16128) Speed up SQL query
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
Labels: cla: yes

#11757 [CDAP-16076] removing checkboxes for provided arguments
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePairs.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineRunButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsKeyValuePairWrapper.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/RuntimeArgsModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cla: yes

#11766 Merge 6.1 to develop
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/SplitterTransform.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReducePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/WrappedSplitterTransform.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/transform/NullFieldSplitterTransform.java
  cdap-common/src/main/java/io/cdap/cdap/common/runtime/DaemonMain.java
  cdap-common/src/test/java/io/cdap/cdap/common/runtime/DaemonMainExceptionTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllMenu/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/widget-container/widget-complex-schema-editor/widget-complex-schema-editor.js
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/logviewer/logviewer.html
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: cla: yes

#11770 [CDAP-16152] Upgrade webpack, plugins, and loaders
  cdap-ui/.storybook/webpack.config.js
  cdap-ui/package.json
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.login.js
  cdap-ui/yarn.lock
Labels: 6.2, UI, cla: yes

#11776 [UI][BUGFIX] Fix stop & starting system services properly
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/SystemServicesStore.js
Labels: 6.1, Bug, UI, cla: yes

#11778 (CDAP-16147) Properly close resources for ES metadata storage
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
Labels: 6.1, cla: yes

#11779 Merge release 6.1 into develop
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/Home/HomeActions/ActionCard.tsx
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePairs.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineRunButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsKeyValuePairWrapper.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/RuntimeArgsModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/SystemServicesStore.js
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: cla: yes

#11775 Upgrade fuse.js to the latest version
  cdap-ui/app/cdap/components/DataPrep/AutoComplete/index.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.2, UI, cla: yes

#11784 Feature ui/fll v2 flip
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/cypress/integration/fieldlevellineage.spec.ts
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.1, UI, cla: yes

#11781 (CDAP-16158) Additional Charges Flag in hub
  cdap-ui/app/cdap/components/ExperimentalBanner/ExperimentalBanner.scss
  cdap-ui/app/cdap/components/MarketPlaceEntity/MarketPlaceEntity.scss
  cdap-ui/app/cdap/components/MarketPlaceEntity/index.js
  cdap-ui/app/cdap/components/PaidBanner/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/colors.ts
  cdap-ui/app/cdap/styles/colors.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, UI, cla: yes

#11786 Revert "Revert "Feature ui/fll v2 flip""
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/OperationsTable.tsx
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/cypress/integration/fieldlevellineage.spec.ts
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.1, UI, cla: yes

#11789 allow cdap upgrade
  cdap-docs/admin-manual/source/index.rst
  cdap-docs/admin-manual/source/installation/replication.rst
  cdap-docs/admin-manual/source/operations/cdap-ui.rst
  cdap-docs/admin-manual/source/security/authorization.rst
  cdap-docs/admin-manual/source/table-of-contents.rst
  cdap-docs/admin-manual/source/upgrading/ambari.rst
  cdap-docs/admin-manual/source/upgrading/cloudera.rst
  cdap-docs/admin-manual/source/upgrading/index.rst
  cdap-docs/admin-manual/source/upgrading/mapr.rst
  cdap-docs/admin-manual/source/upgrading/packages.rst
  cdap-docs/developer-manual/source/metadata/audit-logging.rst
  cdap-docs/developer-manual/source/pipelines/running-pipelines.rst
  cdap-docs/faqs/source/cdap.rst
  cdap-docs/reference-manual/source/http-restful-api/metadata.rst
  cdap-docs/reference-manual/source/http-restful-api/monitor.rst
  cdap-docs/user-guide/source/pipelines/running-pipelines.rst
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/test/java/io/cdap/cdap/data/tools/UpgradeToolTest.java
  cdap-ui/README.rst
Labels: 6.1, cla: yes

#11787 CDAP-15785 remove redundant check for fll
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/FieldLineageProcessor.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/StageOperationsValidator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/StageOperationsValidatorTest.java
Labels: 6.1, cla: yes

#11759 (CDAP-16094) DLP Widget
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DLPCustomWidget/DLPRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DLPCustomWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DLPCustomWidget/utilities/index.ts
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, UI, cla: yes

#11783 Fix post run actions in pipeline e2e test
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.2, Bug, UI, cla: yes

#11749 [CDAP-14284] Adds basic pipeline integration tests
  cdap-ui/.gitignore
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/group-side-panel/group-side-panel.html
  cdap-ui/cypress.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
  cdap-ui/cypress/plugins/index.js
  cdap-ui/cypress/snapshots/base/pipeline.studio.spec.ts/pipeline_with_condition-base.png
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/support/index.js
  cdap-ui/cypress/tsconfig.json
  cdap-ui/cypress/typings/index.d.ts
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.2, UI, cla: yes

#11798 (CDAP-16128) Introduce simple multi-scan to StructuredTable
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/CloseableIterator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordMeta.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: cla: yes

#11744 [CDAP-14284] Adds initial prototype for dag in react
  cdap-ui/app/cdap/components/DAG/DAGProvider.tsx
  cdap-ui/app/cdap/components/DAG/DAGRenderer.tsx
  cdap-ui/app/cdap/components/DAG/JSPlumbSettings.ts
  cdap-ui/app/cdap/components/DAG/Nodes/Default/index.tsx
  cdap-ui/app/cdap/components/DAG/index.tsx
  cdap-ui/app/cdap/components/Modal/Modal.stories.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/VersionStore/index.js
  cdap-ui/package.json
  cdap-ui/tsconfig.json
  cdap-ui/webpack.config.cdap.js
  cdap-ui/yarn.lock
Labels: 6.2, UI, cla: yes

#11797 [CDAP-16189] Fixes Create Profile form to not reset to default when s…
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateProfileActionCreator.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
  cdap-ui/app/cdap/main.js
Labels: 6.1, Bug, UI, cla: yes

#11796 [CDAP-16182] Fixes correctly setting active connection when switching…
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 6.1, Bug, UI, cla: yes

#11799 (CDAP-16128) Added batch get app details endpoint
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/DefaultOwnerStore.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/OwnerTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/security/impersonation/InMemoryOwnerStoreTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/store/DefaultOwnerStoreTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/store/OwnerStoreTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/store/SqlOwnerStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/BatchApplicationDetail.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/DefaultOwnerAdmin.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/InMemoryOwnerStore.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/NoOpOwnerAdmin.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/OwnerAdmin.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/OwnerStore.java
Labels: 6.1, cla: yes

#11803 (CDAP-16125) Allow passing in JVM options
  cdap-common/bin/functions.sh
Labels: 6.1, cla: yes

#11802 Batch the application info and status call for control center; limit …
  cdap-ui/app/cdap/api/app.js
  cdap-ui/app/cdap/components/EntityCard/ApplicationMetrics/index.js
  cdap-ui/app/cdap/components/EntityCard/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/EntityListView/ListView/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/index.js
  cdap-ui/server/aggregator.js
Labels: 6.1, UI, cla: yes
