Repository cdapio/cdap, pull requests merged in 2019-03, with the labels that each got.

#11146 [CDAP-15001] Fix race condition in profile message processing
  cdap-app-fabric/src/main/java/co/cask/cdap/config/ConfigTable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesTable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/AdminEventPublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataMessageProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetadataTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
Labels: 6.0, Bug

#11150 [CDAP-14962] Fix preview logs not showing up in UI
  cdap-ui/app/directives/timeline-preview/timeline-ctrl-preview.js
Labels: 6.0, Bug, UI

#11151 [CDAP-14917] Only calculate node position after position has been set
  cdap-ui/app/directives/dag-minimap/dag-minimap-utilities.js
Labels: 6.0, Bug, UI

#11158 (CDAP-14648) Improve K8s environment
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/co/cask/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: 6.0

#11135 CDAP-14996 remove transactional from subscriber service
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 6.0

#11160 CDAP-15017 fix flaky MetricsClientTest
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetricsClientTestRun.java
Labels: 6.0, Bug

#11156 CDAP-15023 fix nested transactions in subscriber service
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/task/ProvisioningTask.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/provision/ProvisioningServiceTest.java
Labels: 6.0, Bug

#11154 [CDAP-15013] Fix handling of versions in Metadata storage
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataEntity.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataUtil.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataKey.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0, Bug

#11153 [CDAP-15007] Make MetadataAdmin and HttpHandler uniformly return Metadata objects
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/MetadataCompatibility.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Read.java
Labels: 6.0

#11147 [CDAP-14988] Adding LogSaverServiceMain
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/LogSaverTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/LogsServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/distributed/DistributedAppenderContext.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/guice/DistributedLogFrameworkModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/handler/LogBufferHandler.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/framework/distributed/DistributedLogFrameworkTest.java
Labels: 6.0

#11162 Fixes the bug to actually return the theme config from themewrapper
  cdap-common/src/main/resources/cdap-default.xml
  cdap-ui/server/config/development/cdap.json
  cdap-ui/server/express.js
Labels: 6.0, Bug, UI

#11165 (CDAP-14929) Fix remote runtime
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.0

#11148 [CDAP-15012] [CDAP-14786] Bug fixes in UI
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/index.ts
  cdap-ui/app/cdap/components/Tags/Tags.scss
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.0, Bug, UI

#11161 [CDAP-14643] fix checkpoint pipeline config
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Checkpointing.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
Labels: 6.0, Bug, UI

#11149 [CDAP-14877] migrate metadata api
  cdap-ui/app/cdap/api/__mocks__/metadata.js
  cdap-ui/app/cdap/api/metadata.js
  cdap-ui/app/cdap/api/search.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/NamespacesAccordion/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/DatasetCards/index.js
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/EntityCard/EntityCardHeader/index.js
  cdap-ui/app/cdap/components/EntityCard/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/ActionCreator.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/PredictionDatasetExploreModal/index.js
  cdap-ui/app/cdap/components/FastAction/DeleteAction/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
  cdap-ui/app/cdap/components/Overview/AppOverview/index.js
  cdap-ui/app/cdap/components/Overview/DatasetOverview/index.js
  cdap-ui/app/cdap/components/ProgramCards/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/AddPropertyModal/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/DeleteConfirmation/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/EditProperty/index.js
  cdap-ui/app/cdap/components/PropertiesEditor/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/index.js
  cdap-ui/app/cdap/components/Tags/Tag/index.js
  cdap-ui/app/cdap/components/Tags/__tests__/__snapshots__/Tags.test.js.snap
  cdap-ui/app/cdap/components/Tags/index.js
  cdap-ui/app/cdap/services/entity-icon-map/index.js
  cdap-ui/app/cdap/services/metadata-parser/__tests__/metadata-parser.test.js
  cdap-ui/app/cdap/services/metadata-parser/index.js
  cdap-ui/app/tracker/controllers/metadata-ctrl.js
  cdap-ui/app/tracker/controllers/results-ctrl.js
  cdap-ui/app/tracker/services/my-tracker-api.js
Labels: 6.0, UI

#11159 [CDAP-15015] make WebSocket to be more resilient
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/cdap/services/socket/index.js
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/logviewer.less
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/app/services/cask-angular-socket-datasource/socket.js
  cdap-ui/app/tracker/main.js
Labels: 6.0, UI

#11164 Implement checkpointing on GCS.
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/co/cask/cdap/datastreams/DataStreamsApp.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/co/cask/cdap/datastreams/DataStreamsPipelineSpec.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/co/cask/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/co/cask/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/co/cask/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/co/cask/cdap/datastreams/DataStreamsSparkSinkTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/co/cask/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/co/cask/cdap/datastreams/preview/PreviewDataStreamsTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/co/cask/cdap/etl/spark/StreamingCompat.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/co/cask/cdap/etl/spark/StreamingCompat.java
Labels: 6.0

#11066 CDAP-14905 Added main class for system app service programs
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedArtifactManagerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/InMemoryProgramRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactFinder.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/LocalPluginFinder.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/k8s/ServiceOptions.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/k8s/UserServiceProgramMain.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/DefaultMasterEnvironmentContext.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/MasterEnvironmentExtensionLoader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/k8s/EnvironmentOptions.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/ServiceWithPluginApp.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/UserProgramServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/plugin/ConstantCallable.java
Labels: 6.0

#11169 [CDAP-15033] Handle concurrent mutations in MetadataStorage
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataConflictException.java
  cdap-elastic/pom.xml
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/Config.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/RequestAndChange.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/VersionedMetadata.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticConfigurationTest.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-metadata-spi/pom.xml
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0

#11166 CDAP-13326 consolidate prepare logic into a common class
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/ETLMapReduce.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/co/cask/cdap/etl/batch/mapreduce/MapReducePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/co/cask/cdap/etl/batch/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/batch/ETLSpark.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/co/cask/cdap/etl/spark/batch/SparkPreparer.java
Labels: 6.0

#11131 CDAP-14905 add a kubernetes twill runner
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/PodInfo.java
  cdap-master-spi/pom.xml
  cdap-master-spi/src/main/java/co/cask/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/MockMasterEnvironment.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/NoopTwillController.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/NoopTwillPreparer.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/NoopTwillRunnerService.java
Labels: 6.0

#11170 [CDAP-14877] handle pagination and cursor in home page
  cdap-ui/app/cdap/components/EntityListView/EntityListInfo/EntityListInfo.scss
  cdap-ui/app/cdap/components/EntityListView/EntityListInfo/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/ActionCreator.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/index.js
  cdap-ui/app/cdap/components/PaginationStepper/index.tsx
Labels: 6.0, UI

#11179 (CDAP-15043) Propagate config mounts from app-fabric
  cdap-hbase-compat-base/src/main/java/co/cask/cdap/data2/util/hbase/HBaseVersion.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/PodInfo.java
Labels: 6.0

#11171 [CDAP-14812] update styling of field level lineage operation modal
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsModal.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsTable.js
  cdap-ui/app/cdap/components/Heading/index.tsx
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/styles/common.less
Labels: 6.0, UI

#11175 [CDAP-14798] [5.1] Fixes pipeline nodes to have _ in name
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/hydrator/adapters.less
Labels: 5.1, Bug, UI

#11173 [CDAP-14798] Fixes pipeline nodes to have _ in name
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/hydrator/adapters.less
Labels: 6.0, Bug, UI

#11177 [CDAP-15042] Fix dataset lineage not showing up
  cdap-ui/app/tracker/services/my-lineage-service.js
  cdap-ui/app/tracker/services/my-tracker-api.js
Labels: 6.0, Bug, UI

#11152 CDAP-14964 stop tx service if using sql
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/TransactionServiceManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/AbstractTransactionSystemClientProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/ConstantTransactionSystemClient.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricDistributedModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricInMemoryModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricLevelDBModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterTwillApplication.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
Labels: 6.0

#11172 CDAP-15011 add metrics to Structured table for better debugging
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/NoSqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/SqlJobQueueTableTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/nosql/NoSqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/nosql/NoSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/jdbc/DataSourceProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/jdbc/MetricsDataSource.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/lineage/NoSqlLineageTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/sql/SqlStructuredTableConcurrencyTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/sql/SqlStructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/sql/jdbc/DataSourceProviderTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/store/DefaultOwnerStoreTest.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
Labels: 6.0

#11188 CDAP-14958 log sql state and throw exception if not transaction conflict
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlTransactionException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlTransactionRunner.java
Labels: 6.0, Bug

#11193 (CDAP-15059) Added support to default projectId from system conf
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/DefaultSystemProvisionerContext.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-spi/src/main/java/co/cask/cdap/runtime/spi/provisioner/ProvisionerSystemContext.java
Labels: 6.0

#11184 Removes width of the logo to allow for better resolution
  cdap-ui/app/cdap/components/AppHeader/BrandImage.tsx
Labels: 6.0, Bug, UI

#11187 [CDAP-15049] fix runtime args bad state in pipeline detail
  cdap-ui/app/cdap/components/Popover/index.js
Labels: 6.0, Bug, UI

#11185 [CDAP-15005] add ability to add or omit properties from getSchema
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema-modal.html
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.js
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.less
Labels: 6.0, UI

#11189 [CDAP-14872] ability to hide schedules, triggers, lineage, and realti…
  cdap-ui/app/cdap/components/DataPrep/TopPanel/AddToPipelineModal.js
  cdap-ui/app/cdap/components/DatasetDetailedView/Tabs/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineScheduleButton.js
  cdap-ui/app/cdap/components/PipelineTriggersSidebars/index.js
  cdap-ui/app/cdap/services/PipelineErrorFactory.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/tracker/controllers/entity-ctrl.js
  cdap-ui/app/tracker/templates/entity.html
  cdap-ui/server/config/themes/default.json
Labels: 6.0, UI

#11176 [CDAP-14873] add ability to modify checkpoint directory
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Checkpointing.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config-ctrl.js
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config.html
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/server/express.js
Labels: 6.0, UI

#11192 [CDAP-13030] Add search capability on pipeline list
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/SearchBox/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/index.ts
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.0, UI

#11183 CDAP-15047 improve bootstrap steps
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/ProgramStarter.java
Labels: 6.0

#11190 [CDAP-15054] Adding service to load additional log appender
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/extension/AbstractExtensionLoader.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/loader/LogAppenderExtensionLoader.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/loader/LogAppenderLoaderService.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/CDAPLogAppenderTest.java
Labels: 6.0

#11198 [CDAP-15056] add config to show or hide native profile
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/FeatureHeading.tsx
  cdap-ui/app/cdap/components/Cloud/Profiles/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/server/config/themes/default.json
Labels: 6.0, UI

#11194 CDAP-14975 make structured table creation idempotent
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/SqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/NoSqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/SqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/SqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/SqlDefaultSecretStoreTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/nosql/NoSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-data-fabric/src/test/java/co/cask/cdap/store/DefaultOwnerStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/store/SqlOwnerStoreTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/CDAPLogAppenderTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/LogFileManagerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/FileMetadataCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/LogCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/read/FileMetadataTest.java
Labels: 6.0

#11191 [CDAP-15053] Store CDAP version in Elasticsearch index metadata
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/Config.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/resources/index.mapping.json
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticConfigurationTest.java
Labels: 6.0

#11200 [CDAP-15058] Ability to limit concurrent runs
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/ProgramStateWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/constraint/LastRunConstraint.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ConstraintCheckerService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/AppWithServicesAndWorker.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/NoOpProgramStateWriter.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/utils/Checksums.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/VersionInfo.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramRunStatus.java
  cdap-ui/app/cdap/components/OpsDashboard/OpsDashboard.scss
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/DataParser.js
  cdap-ui/app/cdap/services/StatusMapper.js
  cdap-ui/app/cdap/services/global-constants.js
Labels: 6.0

#11202 Fixes favicon path to be absolute path
  cdap-ui/server/config/themes/default.json
  cdap-ui/server/express.js
Labels: 6.0, Bug, UI

#11199 CDAP-15067 add metrics to metadata storage
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/AuditMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/nosql/NoSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/jdbc/MetricsDataSource.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/AuditMetadataStorageTest.java
Labels: 6.0

#11157 Feature/cdap 14937 logs recovery service
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/ConcurrentLogBufferWriter.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferFileOffset.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferService.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferWriter.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/cleaner/LogBufferCleaner.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/handler/LogBufferHandler.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/recover/LogBufferReader.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/recover/LogBufferRecoveryService.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/ConcurrentLogBufferWriterTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/LogBufferWriterTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/MockCheckpointManager.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/cleaner/LogBufferCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/handler/LogBufferHandlerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/recover/LogBufferRecoveryServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/logbuffer/LogBufferProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/logbuffer/LogBufferReaderTest.java
Labels: 6.0

#11207 [CDAP-15073] fix log meta cleaner to avoid keep looping in case numbe…
  cdap-watchdog/src/main/java/co/cask/cdap/logging/clean/FileMetadataCleaner.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/FileMetadataCleanerTest.java
Labels: 6.0

#11208 (CDAP-15080) Applies default properties for all Dataproc calls
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: 6.0

#11201 [CDAP-14471] Filter out datapack from market packages list
  cdap-ui/app/cdap/components/Market/CategoryMap.ts
  cdap-ui/app/cdap/components/Market/index.js
Labels: 6.0, UI

#11204 [CDAP-15071] fix copy paste requiring clipboard permission
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.0, Bug, UI

#11205 [CDAP-15072] fix preparation connections edit
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/database.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/kafka.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/spanner.js
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
Labels: 6.0, Bug, UI

#11206 UI styling fixes
  cdap-ui/app/directives/my-pipeline-configurations/my-pipeline-configurations.less
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/app/hydrator/toppanel.less
Labels: 6.0, Bug, UI

#11211 Modifies favicon path path validation to be fs.existsSync instead of require.resolve
  cdap-ui/server/express.js
Labels: 6.0, Bug, UI

#11209 [CDAP-15081] Fixes focus on comment nodes to be draggable when clicked outisde the node (in canvas)
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.0, Bug, UI

#11210 Fixes focus on comment nodes to be draggable when clicked outisde the node (in canvas)
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
Labels: 5.1, Bug, UI

#11212 Removes hardcoding header color for navbar in logviewer
  cdap-ui/app/logviewer/logviewer.less
Labels: 6.0, Bug, UI

#11213 Modifies welcome banner image to be configurable via theme
  cdap-ui/app/cdap/components/EntityListView/Welcome/Welcome.scss
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/cdap/styles/variables.scss
Labels: 6.0, UI

#11214 Bugfix ui/cdap couple ui fixes
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/directives/dag-minimap/dag-minimap-ctrl.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.html
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, Bug, UI

#11215 [CDAP-15091] reload log appender property
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.0

#11216 (CDAP-15095) Added a Dataproc property for enable/disable Stackdriver
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.0

#11195 (CDAP-15046) Use deployment watch to enforce correct state change
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/common/ResourceChangeListener.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/DeploymentWatcher.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillControllerFactory.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: 6.0

#11217 (CDAP-15106) Fix the LevelDB table cache in TMS
  cdap-tms/src/main/java/co/cask/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBPayloadTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBTableFactory.java
Labels: 6.0

#11225 CDAP-15112 fix delete in artifact store
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
Labels: 6.0, Bug

#11228 (CDAP-15106) Fix TMS overlapping lock issue with LevelDB
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBPayloadTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBTableFactory.java
Labels: 6.0

#11227 CDAP-15109 Use all active run states to determine concurrency constraint for schedules
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraint.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/constraint/ConstraintContext.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraintTest.java
Labels: 6.0

#11218 Add more show/hide capability from theme
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/AdminManagementTabContent.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/ServicesTable.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/index.js
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/ComputeProfiles/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/EntityCounts/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Mapping/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Preferences/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/Security/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/index.js
  cdap-ui/app/cdap/components/ResourceCenter/index.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/services/WizardConfigs/AddNamespaceWizardConfig.js
  cdap-ui/server/config/themes/default.json
Labels: 6.0, UI

#11219 Reduces the welcome screen header font size + pipeline studio nux step fixes
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/EntityListView/Tour/index.ts
  cdap-ui/app/cdap/components/EntityListView/Welcome/Welcome.scss
  cdap-ui/app/cdap/services/GuidedTour/GuidedTour.scss
  cdap-ui/app/cdap/styles/img/nux/Pipeline_studio_NUX.png
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.0, Bug, UI

#11220 [CDAP-15017] fix connection to error collector and alerts
  cdap-ui/app/cdap/services/PipelineErrorFactory.js
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.0, Bug, UI

#11221 [CDAP-15098] fix closing NUX making app drawer stuck
  cdap-ui/app/cdap/components/EntityListView/Tour/index.ts
  cdap-ui/app/cdap/services/GuidedTour/index.ts
Labels: 6.0, Bug, UI

#11223 [CDAP-15084] fix showing error when adding a connection with same name
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
Labels: 6.0, Bug, UI

#11226 [CDAP-15111] fix overflow of axis label in pipeline metrics graphs
  cdap-ui/app/cdap/components/PipelineNodeGraphs/PipelineNodeMetricsGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
Labels: 6.0, Bug, UI

#11229 Add product edition option in theme file
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ProductEdition.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
Labels: 6.0, UI

#11224 [CDAP-15065] Fix race condition in schedule profile assignment
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/AdminEventPublisher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-tms/src/main/java/co/cask/cdap/messaging/service/CoreMessagingService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 6.0, Bug

#11233 [CDAP-15116] remove stop time from system logs
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/index.js
Labels: 6.0, Bug, UI

#11234 [CDAP-15120] fix overflow scroll on node configuration modal
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.0, Bug, UI

#11237 CDAP-15126 fix metrics query due to minimum interval change
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsQueryHelper.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/query/MetricQueryParserTest.java
Labels: 6.0, Bug

#11230 CDAP-15076 make sure only one cleaner thread is added
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferWriter.java
Labels: 6.0

#11232 [CDAP-15114] fix typo on saving plugin template alert
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/controllers/create/popovers/plugin-templates-create-edit-ctrl.js
Labels: 6.0, Bug, UI

#11236 [CDAP-15118] Fix dataset detail view styling
  cdap-ui/app/cdap/components/DatasetDetailedView/DatasetDetailedView.scss
Labels: 6.0, Bug, UI

#11239 [CDAP-15123] adding delay after deleting an entity
  cdap-ui/app/cdap/components/FastAction/DeleteAction/index.js
Labels: 6.0, Bug, UI

#11231 [CDAP-15093] Add CloudSQL and SAP HANA database option in dataprep
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseOptions.js
  cdap-ui/app/cdap/styles/img/db-sprite.png
Labels: 6.0, UI

#11238 Bugfix ui/cdap fixes 2
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
  cdap-ui/app/cdap/components/EntityListView/Welcome/Welcome.scss
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/hydrator/bottompanel.less
Labels: 6.0, Bug, UI

#11240 CDAP-15131 fix metrics deletion on k8s
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MetricsServiceMainTest.java
Labels: 6.0, Bug

#11235 [CDAP-14385] disable default connection popover menu
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
Labels: 6.0, UI

#11243 Bugfix ui/cdap bugfixes 3
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/NamespacesAccordion/index.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/ReloadSystemArtifacts.js
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/SystemProfilesAccordion/index.js
  cdap-ui/app/cdap/components/AppHeader/BrandImage.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/store/ActionCreator.js
  cdap-ui/app/cdap/components/FieldLevelLineage/store/Store.js
  cdap-ui/app/cdap/components/NamespaceDetails/ComputeProfiles/index.js
  cdap-ui/app/cdap/components/NamespaceDetails/EntityCounts/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/TypeSelector/index.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/styles/themes/cdap/theme.less
  cdap-ui/server/config/themes/default.json
Labels: 6.0, Bug, UI

#11248 Bugfix ui/cdap many ui fixes
  cdap-ui/Gulpfile.js
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/PipelineScheduler/ProfilesForSchedule/index.js
  cdap-ui/app/cdap/components/PlusButtonModal/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/dag-plus/color-constants.less
  cdap-ui/app/directives/dag-plus/my-dag.less
  cdap-ui/app/directives/plugin-templates/plugin-templates-ctrl.js
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
Labels: 6.0, Bug, UI

#11249 CDAP-15158 fix profile metadata due to instance level pref
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesTable.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetadataTest.java
Labels: 6.0, Bug

#11250 [CDAP-15164] fix wrong zIndex for plus button modal
  cdap-ui/app/cdap/components/PlusButtonModal/index.js
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
Labels: 6.0, Bug, UI
