Repository cdapio/cdap, pull requests merged in 2019-08, with the labels that each got.

#11510 [CDAP-15704] updating type for options
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11505 [CDAP-15676] Multi-select widget react migration
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI, cla: yes

#11507 Removes all unnecessary files/directories from UI project
  cdap-ui/.editorconfig
  cdap-ui/.eslintrc.json
  cdap-ui/.jshintrc
  cdap-ui/.stylelintignore
  cdap-ui/app/cdap/components/500/__tests__/500.test.js
  cdap-ui/app/cdap/components/500/__tests__/__snapshots__/500.test.js.snap
  cdap-ui/app/cdap/components/Tags/__tests__/Tags.test.js
  cdap-ui/app/cdap/components/Tags/__tests__/__snapshots__/Tags.test.js.snap
  cdap-ui/app/lib/c3.js
  cdap-ui/test/config.js
  cdap-ui/test/karma-conf.js
  cdap-ui/test/unit/filters/bytes-test.js
  cdap-ui/test/unit/filters/ellipsis-test.js
  cdap-ui/test/unit/filters/number-test.js
  cdap-ui/test/unit/filters/title-test.js
  cdap-ui/test/unit/helpers-test.js
Labels: 6.1, UI, cla: yes

#11472 [CDAP-15618] join type component react migration
  cdap-ui/app/cdap/components/AbstractWidget/JoinTypeWidget/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI, cla: yes

#11482 [CDAP-14850] Update react-calendar to latest version to fix bug
  cdap-ui/app/cdap/components/FieldLevelLineage/FieldLevelLineage.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/Lineage/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/TimePicker/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineRunButton.js
  cdap-ui/app/cdap/components/TimeRangePicker/TimeRangePicker.scss
  cdap-ui/cypress/fixtures/airports.csv
  cdap-ui/cypress/fixtures/fll_airport_pipeline2.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/fieldlevellineage.spec.ts
  cdap-ui/cypress/integration/pipeline.plugin.multipleendpoints.spec.ts
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI, cla: yes

#11512 [CDAP-15678] Input field selector widget in React
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
  cdap-ui/cypress/integration/fieldlevellineage.spec.ts
Labels: 6.1, UI, cla: yes

#11508 Feature/cdap 15699 add schedule restart
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/NoOpScheduler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/ProgramScheduleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/Scheduler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
Labels: cla: yes

#11504 [CDAP-15682] migrate dataset-selector widget to react
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DatasetSelectorWidget/index.tsx
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-complex-schema-editor/widget-complex-schema-editor.js
  cdap-ui/app/directives/widget-container/widget-factory.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.1, UI, cla: yes

#11519 Fix the wrong scm urls
  pom.xml
Labels: cla: yes

#11515 Fix error message when non-string plugin property is null or empty
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: 6.1, cla: yes

#11492 [CDAP-15623] Sql conditions widget in react
  cdap-ui/app/cdap/components/AbstractWidget/SqlConditionsWidget/Rule.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlConditionsWidget/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI, cla: yes

#11481 [CDAP-15624] sql selector widget in react
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/FieldRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI, cla: yes

#11521 Add reEnable to schedule client
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ScheduleClientTestRun.java
  cdap-client/src/main/java/io/cdap/cdap/client/ScheduleClient.java
Labels: cla: yes

#11522 update to latest ubuntu iso
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: cla: yes

#11523 update to latest ubuntu iso
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: cla: yes

#11524 update to latest ubuntu iso
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: cla: yes

#11525 update to latest ubuntu iso
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: cla: yes

#11526 update ubuntu iso md5sum
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: cla: yes

#11509 [CDAP-15703] Added QueryParser searchType and comparison support
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/QueryParser.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/QueryTerm.java
  cdap-common/src/test/java/io/cdap/cdap/common/metadata/QueryParserTest.java
Labels: cla: yes

#11517 [CDAP-15685] Added basic functionality for numeric metadata search
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/main/resources/index.mapping.json
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: cla: yes

#11530 (CDAP-15722) Add logs for runtime monitor to provide more visibilty
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
Labels: 6.1, cla: yes

#11520 Add restart for programs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
Labels: cla: yes

#11527 [CDAP-15656] plugin validation apis
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/FailureCollector.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/MultiInputStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/MultiOutputStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/CauseAttributes.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InvalidConfigPropertyException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InvalidStageException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidationException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidationFailure.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BatchPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultPipelineConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockPipelineConfigurer.java
Labels: cla: yes

#11532 Add client method for restart
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
Labels: cla: yes

#11534 Make StageConfigurer api changes backwards compatible
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/FailureCollector.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockPipelineConfigurer.java
Labels: 6.1, cla: yes

#11533 CDAP-15723 Add support for shared vpc in Dataproc Provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.0, 6.1, cla: yes

#11539 Merge release 6.0 to develop
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-ui/yarn.lock
Labels: cla: yes

#11529 [CDAP-15720] CLI supports space-separated queries
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLIMainTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/AbstractMetadataClient.java
Labels: cla: yes

#11545 (CDAP-15743) Remove assertion in finally block in ProgramLifecycleHttpHandlerTest
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
Labels: 6.1, cla: yes

#11544 Bugfix release/cdap 15599 log dataproc warnings
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#11516 Add HSTS header for TLS enabled CDAP environments
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/server/url-helper.js
  cdap-ui/yarn.lock
Labels: 6.1, UI, cla: yes

#11541 [CDAP-15729] fix navigating to /pipelines
  cdap-ui/app/hydrator/home-ctrl.js
  cdap-ui/app/hydrator/routes.js
Labels: 6.1, Bug, UI, cla: yes

#11540 [CDAP-15728] Add ConfigurationGroup component
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/ConfigurationGroup/KitchenSync.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/__tests__/configuration-group-utilities.test.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/types.d.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, UI, cla: yes

#11547 Adds frameguard to add x-frame-options for any iframe requests
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI, cla: yes

#11548 CDAP-15747 fix a race when cancelling a KeyedExecutor task
  cdap-common/src/main/java/io/cdap/cdap/common/async/KeyedExecutor.java
Labels: 6.1, cla: yes

#11549 [CDAP-15659]Add link to navigate to pipeline from control center pipeline card
  cdap-ui/app/cdap/components/EntityCard/EntityCard.scss
  cdap-ui/app/cdap/components/EntityCard/index.js
Labels: 6.1, UI, cla: yes

#11543 [CDAP-15499] Throw error when plugin artifact does not contain provided class
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ArtifactClientTestRun.java
Labels: cla: yes

#11538 Add post upgrade job to restart schedules and pipelines.
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/PostUpgradeJobMain.java
Labels: 6.1, cla: yes

#11550 CDAP-15206 remove local datasets in lineage
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageAdminTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/LineageTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/Relation.java
Labels: 6.1, cla: yes

#11553 CDAP-15770 fixed a bug with encoding nullable byte buffers
  cdap-formats/src/main/java/io/cdap/cdap/format/io/StructuredRecordDatumWriter.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordStringConverterTest.java
Labels: cla: yes

#11552 (CDAP-14376) Use regional endpoint for Dataproc
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: 6.1, cla: yes

#11546 Deny connection to websocket coming from different origin in Nodejs server
  cdap-ui/app/cdap/components/AppHeader/AccessTokenModal/index.tsx
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/SessionTokenStore.ts
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/resource-helper/index.js
  cdap-ui/app/cdap/services/socket/index.js
  cdap-ui/app/cdap/services/upload-file.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/login/login.html
  cdap-ui/app/logviewer/routes.js
  cdap-ui/app/services/cask-angular-socket-datasource/socket.js
  cdap-ui/app/services/file-uploader.js
  cdap-ui/app/services/namespace.js
  cdap-ui/app/tracker/routes.js
  cdap-ui/graphql/graphql.js
  cdap-ui/pom.xml
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/config/development/session_secret.key
  cdap-ui/server/express.js
  cdap-ui/server/token.js
  cdap-ui/server/token_test.js
  cdap-ui/server/uiThemeWrapper.js
Labels: 6.1, UI, cla: yes

#11555 (CDAP-15505) Added logs for error in runtime monitor
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
Labels: 6.0, cla: yes

#11531 [CDAP-15690] Metadata Date Search Implementation
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/QueryParser.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/QueryTerm.java
  cdap-common/src/test/java/io/cdap/cdap/common/metadata/QueryParserTest.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/main/resources/index.mapping.json
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: cla: yes

#11396 [CDAP-15439] Add Password widget react component and share with Angular side
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Password/index.tsx
Labels: 6.1, UI, cla: yes

#11556 [CDAP-15776] Metadata search supports "=" syntax
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/QueryParser.java
  cdap-common/src/test/java/io/cdap/cdap/common/metadata/QueryParserTest.java
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: cla: yes

#11559 (CDAP-15778) Use the actual IP instead of localhost for the SSH port forwarding
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitorServerInfo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManagerTest.java
Labels: cla: yes

#11537 [CDAP-15620-3] FLL backend integration: Change target dataset
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TimeRangePicker/index.tsx
Labels: 6.1, UI, cla: yes

#11560 (CDAP-15778) Use the actual IP instead of localhost for the SSH port …
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitorServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitorServerInfo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManagerTest.java
Labels: cla: yes

#11561 Fixes default values for authtoken while validating session
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/navbar.spec.ts
  cdap-ui/cypress/integration/wrangler.bigquery.spec.ts
  cdap-ui/cypress/integration/wrangler.gcs.spec.ts
  cdap-ui/cypress/integration/wrangler.spanner.spec.ts
  cdap-ui/server/express.js
  cdap-ui/server/token.js
Labels: 6.1, Bug, UI, cla: yes

#11564 Ensure workflows are stopped first
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
Labels: 6.1, cla: yes

#11565 fix import
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
Labels: 6.1, cla: yes

#11566 ordering
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
Labels: 6.1, cla: yes

#11558 CDAP-14167 fix field lineage for joiner
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/StageOperationsValidator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/StageOperationsValidatorTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
Labels: 6.1, cla: yes

#11511 CDAP-15677 restore preview status
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/preview/PreviewStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStoreTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: 6.1, cla: yes

#11575 Cleanup old hbase compact modules
  cdap-common/bin/functions.sh
  cdap-distributions/bin/build_parcel.sh
  pom.xml
Labels: cla: yes

#11577 (CDAP-15803) Fix flaky DistributedKeyManagerTest test
  cdap-security/src/main/java/io/cdap/cdap/security/auth/DistributedKeyManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
Labels: 6.1, cla: yes

#11576 Adding display names for logical type schemas
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: 6.1, cla: yes
