Repository cdapio/cdap, pull requests merged in 2019-05, with the labels that each got.

#11304 [CDAP-15185] Removes hardlimit on the number of characters plugin name can have before showing ellipsis
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, Bug, UI

#11307 [CDAP-15147] Fixes settings menu to appear below the gearbox instead of overlapping on top
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
Labels: 6.0, Bug, UI

#11314 CDAP-14772 remove plugin endpoints
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/EndpointPluginContext.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginClass.java
  cdap-api/src/test/java/io/cdap/cdap/api/plugin/PluginClassTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/DefaultEndpointPluginContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginEndpoint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/endpointtest/MockEndpointPluginContext.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/endpointtest/PluginEndpointContextTestPlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/endpointtest/TestEndpointPluginContext.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/invalid/InvalidPlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/invalid2/InvalidPluginMethodParams.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/invalid3/InvalidPluginMethodParamType.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/p3/CallablePlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/p4/CallingPlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/p5/PluginWithPojo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/p5/TestData.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ArtifactClientTestRun.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/ExpectedNumberOfAuditPolicyPaths.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/PluginInfo.java
Labels: 6.0

#11316 [CDAP-14999] Adds validation checks for input stages in joiner plugin to not have specific special characters
  cdap-ui/app/directives/widget-container/widget-sql-conditions/widget-sql-conditions.html
  cdap-ui/app/directives/widget-container/widget-sql-conditions/widget-sql-conditions.js
  cdap-ui/app/directives/widget-container/widget-sql-conditions/widget-sql-conditions.less
Labels: 6.0, Bug, UI

#11319 (CDAP-14943) Has all services started by preview listen on localhost
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
Labels: 6.0

#11318 (CDAP-15332) Fix SSH session manager bug
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHSessionManagerTest.java
Labels: 6.0

#11313 CDAP-13362 handle wrong class when writing records
  cdap-formats/src/main/java/io/cdap/cdap/format/RecordPutTransformer.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/JsonStructuredRecordDatumWriter.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/StructuredRecordDatumWriter.java
Labels: 6.0

#11321 CDAP-15335 fix a bug in program state for provision failures
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: 6.0, Bug

#11309 [CDAP-15305] Introduce MutationOptions to control synchronous Metadata Storage
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/AuditMetadataStorage.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/metadata/noop/NoopMetadataStorage.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/AuditMetadataStorageTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/Config.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-metadata-spi/pom.xml
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MetadataStorage.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MutationOptions.java
  cdap-metadata-spi/src/test/java/io/cdap/cdap/spi/metadata/MetadataStorageTest.java
Labels: 6.0

#11322 [CDAP-7230] Fix lineage for streaming sources
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/external/ExternalDataset.java
Labels: 6.0, Bug

#11323 [CDAP-14955] Mark the storage SPI as @Beta
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/InvalidFieldException.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredRow.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTableAdmin.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTableContext.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTableInstantiationException.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/TableAlreadyExistsException.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/TableNotFoundException.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/StructuredTableId.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/StructuredTableRegistry.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/StructuredTableSchema.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/StructuredTableSpecification.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/Field.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldType.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/Fields.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/Range.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/transaction/TransactionException.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/transaction/TransactionRunner.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/transaction/TransactionRunners.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/transaction/TxCallable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/transaction/TxRunnable.java
Labels: 6.0

#11320 [CDAP-14952] Updates cdap-ui pom.xml to include cdap-ui-upgrade while building sdk
  cdap-ui/pom.xml
Labels: 6.0, Bug, UI

#11311 [CDAP-11754] Fix navigation in dataset button in sink when pipeline contains macros
  cdap-ui/app/directives/my-link-button/my-link-button.html
  cdap-ui/app/directives/my-link-button/my-link-button.js
  cdap-ui/app/directives/my-link-button/my-link-button.less
Labels: 6.0, Bug, UI

#11317 [CDAP-15213] Change urls to say /wrangler instead of /dataprep
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/TableList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/TableList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/WorkspaceTab/index.js
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
  cdap-ui/app/cdap/components/DataPrepHome/index.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/ui-utils/url-generator.js
Labels: 6.0, Bug, UI

#11326 [CDAP-14640] Fixes profile association list to not show undefined for creation time
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/ProfileAssociations/index.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.0, Bug, UI

#11327 [CDAP-15238] Enhances close behavior for secure keys list to close on esc or clicking anywhere outside
  cdap-ui/app/cdap/components/AbstractWidget/SecureKey/SecureKeyTextarea.scss
  cdap-ui/app/cdap/components/AbstractWidget/SecureKey/index.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.0, Bug, UI

#11334 [CDAP-15316] Reduces the text used to show triggers in UI
  cdap-ui/app/cdap/components/CollapsibleSidebar/CollapsibleSidebar.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.0, Bug, UI

#11330 [CDAP-15346] Fixes creating remote hadoop cluster from failing with a js error
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
Labels: 6.0, Bug, UI

#11332 Turn directives caret into button with tooltip
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/ColumnActionsDropdown.scss
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
Labels: 6.0, UI

#11328 [CDAP-15337] Fixes last modified date for gcs browser to show right d…
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
Labels: 6.0, Bug, UI

#11324 [UI]Fix rules engine after package rename update
  cdap-ui/app/cdap/components/RulesEngineHome/RuleBooksTab/index.js
  cdap-ui/app/cdap/components/RulesEngineHome/RulesEngineWrapper.scss
  cdap-ui/app/cdap/components/RulesEngineHome/RulesTab/Rule/Rule.scss
  cdap-ui/app/directives/widget-container/widget-rulesengine-editor/rules-engine-modal.less
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/dll/dll.shared.vendor.js
  cdap-ui/dll/shared-vendor-manifest.json
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.0, Bug, UI

#11340 [UI] Adds better source maps during development for typescript
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
Labels: 6.0, UI

#11339 [CDAP-15363] Fixes driver upload artifact to correctly parse driver jar names for name and version
  cdap-ui/app/cdap/services/WizardStores/ArtifactUpload/ActionCreator.js
Labels: 6.0, Bug, UI

#11343 [CDAP-15359] Fixes vertical alignment of plugin icon and plugin name to prevent cutting off plugin name on the top
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, Bug, UI

#11333 [CDAP-15339] Adds support for decimal logical type for avro schemas in UI
  cdap-ui/app/cdap/components/SchemaEditor/SchemaHelpers.js
  cdap-ui/app/cdap/services/cdapavscwrapper/DecimalLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/LogicalTypes.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/index.ts
  cdap-ui/app/directives/complex-schema/complex-schema-helpers.js
Labels: 6.0, UI

#11337 Renames all occurrence of caskdata to cdapio
  cdap-docs/_common/common-build.sh
  cdap-docs/_common/common_conf.py
  cdap-docs/admin-manual/source/operations/logging.rst
  cdap-docs/admin-manual/source/security/authorization.rst
  cdap-docs/developer-manual/build-pipelines.sh
  cdap-docs/developer-manual/build.sh
  cdap-docs/developer-manual/source/ingesting-tools/cdap-flume.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-java.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-python.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-ruby.rst
  cdap-docs/developer-manual/source/metadata/audit-logging.rst
  cdap-docs/developer-manual/source/security/custom-authentication.rst
  cdap-docs/examples-manual/build.sh
  cdap-docs/examples-manual/source/_includes/apps-packs.txt
  cdap-docs/examples-manual/source/_includes/tutorials-index.txt
  cdap-docs/examples-manual/source/tutorials/wise.rst
  cdap-docs/integrations/build.sh
  cdap-docs/reference-manual/licenses-pdf/cdap-ui-dependencies.pdf
  cdap-docs/reference-manual/source/java-client-api.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/cdap-default/cdap-xml-sdl-files.txt
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-docs/vars
Labels: Docs

#11345 [CDAP-15213] Fixes dataprep browser url path on wrangler a file in wrangler
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 6.0, Bug, UI

#11346 CDAP-15369 Disable oslogin for provisioned Dataproc cluster VMs.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.0

#11350 (CDAP-15375) Exclude LZ4 library from cdap
  pom.xml
Labels: 6.1

#11351 [CDAP-15366] Remove parse as xml from UI in wrangler
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/widget-container/widget-wrangler-directives/wrangler-modal.less
Labels: 6.0, Bug, UI

#11341 Shorten discoverable name.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/services/AbstractServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/runtime/OpenCloseDataSetTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/ZKDiscoveryModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/ServiceDiscoverable.java
  cdap-common/src/test/java/io/cdap/cdap/common/guice/ZKDiscoveryModuleTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/service/ServiceDiscoverableTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RouterPathLookupTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ProgramType.java
Labels: 6.0

#11344 CDAP-15326 Remove usages of streams and views from docs.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/flow/package-info.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/app/BaseBatchCommand.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
  cdap-docs/admin-manual/source/index.rst
  cdap-docs/admin-manual/source/operations/index.rst
  cdap-docs/admin-manual/source/operations/preferences.rst
  cdap-docs/admin-manual/source/operations/scaling-instances.rst
  cdap-docs/admin-manual/source/upgrading/cloudera.rst
  cdap-docs/admin-manual/source/upgrading/packages.rst
  cdap-docs/developer-manual/source/building-blocks/applications.rst
  cdap-docs/developer-manual/source/building-blocks/datasets/fileset.rst
  cdap-docs/developer-manual/source/building-blocks/datasets/overview.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/batch-execution.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/connecting-flowlets.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/flowlets-instances.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/flowlets.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/flows.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/index.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/input-context.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/partitioning-strategies.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/stream-event.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/tick-methods.rst
  cdap-docs/developer-manual/source/building-blocks/flows-flowlets/type-projection.rst
  cdap-docs/developer-manual/source/building-blocks/index.rst
  cdap-docs/developer-manual/source/building-blocks/mapreduce-programs.rst
  cdap-docs/developer-manual/source/building-blocks/namespaces.rst
  cdap-docs/developer-manual/source/building-blocks/spark-programs.rst
  cdap-docs/developer-manual/source/building-blocks/streams.rst
  cdap-docs/developer-manual/source/building-blocks/transactional-messaging-system.rst
  cdap-docs/developer-manual/source/building-blocks/views.rst
  cdap-docs/developer-manual/source/building-blocks/workers.rst
  cdap-docs/developer-manual/source/data-exploration/index.rst
  cdap-docs/developer-manual/source/overview/anatomy.rst
  cdap-docs/examples-manual/source/examples/introduction-to-cdap.rst
  cdap-docs/reference-manual/source/glossary.rst
  cdap-docs/reference-manual/source/http-restful-api/index.rst
  cdap-docs/reference-manual/source/http-restful-api/lifecycle.rst
  cdap-docs/reference-manual/source/http-restful-api/namespace.rst
  cdap-docs/reference-manual/source/http-restful-api/stream.rst
  cdap-docs/reference-manual/source/http-restful-api/views.rst
  cdap-docs/user-guide/source/overview.rst
  cdap-standalone/src/main/resources/logback-container.xml
  cdap-unit-test/src/test/java/io/cdap/cdap/flow/stream/package-info.java
Labels: Docs

#11355 update release notes for 6.0.0 release
  cdap-docs/reference-manual/source/release-notes.rst
Labels: 6.0

#11357 [CDAP-15389] Improves plugin reference section to adhere to material spec.
  cdap-ui/app/cdap/components/Heading/index.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownHeading.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownImplExample.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownTable.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownToReactMapping.tsx
  cdap-ui/app/cdap/components/Markdown/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/styles/common.scss
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/reference-tab.html
  cdap-ui/package.json
  cdap-ui/server/config/themes/default.json
  cdap-ui/server/config/themes/light.json
  cdap-ui/yarn.lock
Labels: 6.1, UI

#11360 CDAP-15393 handle empty checkpoint dir for streaming pipelines
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfigTest.java
Labels: 6.0, Bug

#11359 [UI] Upgrade react to 16.8
  cdap-ui/cypress/fixtures/null_splitter_pipeline-cdap-data-pipeline.json
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, UI

#11363 Fix docs build to remove reference of validator transform markdown table
  cdap-docs/developer-manual/build-pipelines.sh
  cdap-docs/developer-manual/source/_includes/plugins/shared-plugins/core.rst
  cdap-docs/user-guide/source/pipelines/plugins/_includes/validator-extract.txt
  cdap-docs/user-guide/source/pipelines/plugins/shared-plugins/core.rst
Labels: 6.0, Docs

#11352 [CDAP-15377] Remove cdap-app-archetype from doc
  cdap-docs/developer-manual/source/getting-started/dev-env.rst
  cdap-docs/developer-manual/source/getting-started/sandbox/virtual-machine.rst
  cdap-docs/developer-manual/source/security/authorization-extensions.rst
Labels: 6.0, Docs

#11361 [CDAP - 15395] Fixes call-to-action for actions performed from plus button in studio
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/UploadStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/LibraryUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/PluginUploadWizard.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/index.js
  cdap-ui/app/cdap/components/PlusButton/index.js
  cdap-ui/app/cdap/components/ResourceCenterButton/index.js
  cdap-ui/app/cdap/components/Wizard/index.js
  cdap-ui/app/cdap/services/global-events.js
Labels: 6.0, Bug, UI

#11358 modify cdap hadoop compatibility matrix
  cdap-docs/admin-manual/source/cdap-hadoop-compatibility.rst
Labels: 6.0, Docs

#11342 [CDAP-14038] Remove docs & references to CDAP Tracker
  cdap-docs/_common/common-build.sh
  cdap-docs/_common/common_conf.py
  cdap-docs/developer-manual/source/_images/metadata/tracker-audit-log.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-dictionary.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-first-search.png.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-home-search.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-integration-configuration.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-lineage.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-metadata.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-preview.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-tags-upload.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-tags.png
  cdap-docs/developer-manual/source/_images/metadata/tracker-usage.png
  cdap-docs/developer-manual/source/metadata/index.rst
  cdap-docs/developer-manual/source/metadata/metadata-ui.rst
  cdap-docs/developer-manual/source/pipelines/how-cdap-pipelines-work.rst
  cdap-docs/reference-manual/source/http-restful-api/index.rst
  cdap-docs/reference-manual/source/http-restful-api/metadata-management.rst
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
Labels: 6.0, Docs

#11353 [CDAP-15315] Add list of incompatibilities
  cdap-docs/admin-manual/source/incompatibilities.rst
  cdap-docs/admin-manual/source/index.rst
  cdap-docs/admin-manual/source/table-of-contents.rst
Labels: 6.0, Docs

#11364 (CDAP-15029) Excludes dependencies that causes failure on later Hadoo…
  cdap-common/pom.xml
  cdap-master/pom.xml
  pom.xml
Labels: 6.0

#11366 [CDAP-15378] Remove upgrade tool documentation
  cdap-docs/admin-manual/source/index.rst
  cdap-docs/admin-manual/source/installation/replication.rst
  cdap-docs/admin-manual/source/operations/cdap-ui.rst
  cdap-docs/admin-manual/source/security/authorization.rst
  cdap-docs/admin-manual/source/table-of-contents.rst
  cdap-docs/admin-manual/source/upgrading/ambari.rst
  cdap-docs/admin-manual/source/upgrading/cloudera.rst
  cdap-docs/admin-manual/source/upgrading/index.rst
  cdap-docs/admin-manual/source/upgrading/mapr.rst
  cdap-docs/admin-manual/source/upgrading/packages.rst
  cdap-docs/developer-manual/source/metadata/audit-logging.rst
  cdap-docs/developer-manual/source/pipelines/running-pipelines.rst
  cdap-docs/faqs/source/cdap.rst
  cdap-docs/reference-manual/source/http-restful-api/metadata.rst
  cdap-docs/reference-manual/source/http-restful-api/monitor.rst
  cdap-docs/user-guide/source/pipelines/running-pipelines.rst
  cdap-ui/README.rst
Labels: 6.0, Docs

#11368 [CDAP-15403] throw exception when upgrade tool is executed
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/test/java/io/cdap/cdap/data/tools/UpgradeToolTest.java
Labels: 6.0

#11301 CDAP-15277 Update references to cask market in docs
  cdap-docs/_common/_source/guides.rst
  cdap-docs/_common/common_conf.py
  cdap-docs/integrations/source/hub.rst
  cdap-docs/integrations/source/index.rst
  cdap-docs/integrations/source/table-of-contents.rst
  cdap-docs/vars
Labels: Docs

#11370 Remove stage profile id
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  pom.xml
Labels: 6.0

#11373 Fix/stage profile
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  pom.xml
Labels: 6.0

#11371 [UI] Enable hiding experimental features in production version of CDAP
  cdap-ui/app/cdap/main.js
  cdap-ui/server/express.js
Labels: 6.1, UI

#11380 Modifies the 'save' button to be 'ok' while updating pipeline name
  cdap-ui/app/hydrator/templates/create/toppanel.html
Labels: 6.1, Bug, UI

#11367 [CDAP-15368] Modifies the way to programmatically navigate to different parts of the app
  cdap-ui/app/cdap/components/CaskWizards/MicroserviceUpload/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/TableList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/DatabaseList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/InstanceList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/TableList/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/Experiments/DetailedView/DeleteExperimentBtn/index.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/history.ts
  cdap-ui/dll/cdap-vendor-manifest.json
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/dll/dll.shared.vendor.js
  cdap-ui/dll/shared-vendor-manifest.json
  cdap-ui/package.json
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI

#11379 [CDAP-15410]Port ace editor widget in plugin config from angular to react
  cdap-ui/app/cdap/components/AceEditor/index.tsx
  cdap-ui/app/cdap/components/SampleTSXComponent/index.tsx
  cdap-ui/app/cdap/globals.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-container.js
  cdap-ui/app/directives/widget-container/widget-factory.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, UI

#11382 [CDAP-15410] Honoring disabled state in CodeEditor
  cdap-ui/app/cdap/components/AppHeader/ListItemLink.tsx
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
  cdap-ui/app/cdap/components/SampleTSXComponent/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI

#11381 (CDAP-15375) Exclude LZ4 library from cdap
  pom.xml
Labels: 6.0

#11386 [CDAP-15416] Migrates json-editor from angular to react in plugin configuration
  cdap-ui/Gulpfile.js
  cdap-ui/app/cdap/components/CodeEditor/JSONEditor.tsx
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, UI

#11365 [CDAP-15400] Adds optional information icon for plugin configuration groups if provided
  cdap-ui/app/cdap/components/InformationIcon/index.tsx
  cdap-ui/app/cdap/components/Popover/index.js
  cdap-ui/app/cdap/components/SampleTSXComponent/ChildTSXComponent/index.tsx
  cdap-ui/app/cdap/components/SampleTSXComponent/index.tsx
  cdap-ui/app/cdap/services/HydratorPluginConfigFactory.js
  cdap-ui/app/hydrator/bottompanel.less
  cdap-ui/app/hydrator/services/plugin-config-factory.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-properties-template.html
Labels: 6.1, UI

#11388 [CDAP-15434] Fixes splitter plugin popover for ports to be dynamic
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
  cdap-ui/app/directives/splitter-popover/splitter-popover.html
  cdap-ui/app/directives/splitter-popover/splitter-popover.less
Labels: 6.1, Bug, UI

#11391 CDAP-15221 fix artifact version comparison
  cdap-api/src/main/java/io/cdap/cdap/api/artifact/ArtifactVersion.java
  cdap-api/src/test/java/io/cdap/cdap/api/artifact/ArtifactVersionTest.java
Labels: 6.1, Bug

#11397 Fixes the way we lazy experimental feature in UI
  cdap-ui/app/cdap/components/Markdown/MarkdownImplExample.tsx
  cdap-ui/app/cdap/main.js
Labels: 6.1, Bug, UI

#11395 [CDAP-15425] Add Textbox widget react component and share with Angular side
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/TextBox/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.html
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI

#11393 [CDAP-15420] Migrate number textbox from angular to react in plugin configuration
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Number/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI
