Repository cdapio/cdap, pull requests merged in 2019-10, with the labels that each got.

#11673 Fix Dynamic Plugin Filters to properly handle simple condition objects
  cdap-ui/app/cdap/components/ConfigurationGroup/types.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/__tests__/DynamicPluginFilters.test.ts
Labels: 6.1, Bug, UI, cla: yes

#11676 [CDAP-15974] Fix macro row indicator
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11677 Update homepage wordings
  cdap-ui/app/cdap/components/Home/HomeActions/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cla: yes

#11490 CDAP-15631: added a search option in market hub popup to search plugins.
  cdap-ui/app/cdap/components/Market/AllTab/AllTabContents.scss
  cdap-ui/app/cdap/components/Market/AllTab/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, UI, cla: yes

#11678 Add search to hub
  cdap-ui/app/cdap/components/Market/AllTab/AllTabContents.scss
  cdap-ui/app/cdap/components/Market/AllTab/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, UI, cla: yes

#11679 [CDAP-15982] add loading indicator to validate and get schema button
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 6.1, Bug, UI, cla: yes

#11680 [CDAP-15990] Send to error and Mask data directives are disabled when…
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
Labels: 6.1, Bug, UI, cla: yes

#11682 [CDAP-15994] Fix stage level metrics API usage to use pipeline start …
  cdap-ui/app/cdap/components/PipelineNodeGraphs/PipelineNodeMetricsGraph.js
Labels: 6.1, Bug, UI, cla: yes

#11684 [CDAP-15998] add specificity to styling of program cards in detailed …
  cdap-ui/app/cdap/components/AppDetailedView/AppDetailedView.scss
Labels: 6.1, Bug, UI, cla: yes

#11685 [CDAP-15997] Fix bug where schema doesn't display in details view
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
Labels: 6.1, Bug, UI, cla: yes

#11687 Merge release/6.1 back to develop
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/cdap/components/AppDetailedView/AppDetailedView.scss
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/types.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/__tests__/DynamicPluginFilters.test.ts
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DatasetDetailedView/index.js
  cdap-ui/app/cdap/components/Home/HomeActions/index.tsx
  cdap-ui/app/cdap/components/Market/AllTab/AllTabContents.scss
  cdap-ui/app/cdap/components/Market/AllTab/index.js
  cdap-ui/app/cdap/components/PipelineNodeGraphs/PipelineNodeMetricsGraph.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/create/canvas-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 6.1, cla: yes

#11686 [CDAP-15952] Shift metrics to prevent overlap with Properties button in node
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: cla: yes

#11683 CDAP-15973 log cluster creation failures in dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
Labels: 6.1, cla: yes

#11690 CDAP-16027 fix NPE when stage artifact is not configured
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLPlugin.java
Labels: 6.1, cla: yes

#11691 [CDAP-16026] Fix import pipeline to refetch backend properties and wi…
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.1, Bug, UI, cla: yes

#11692 [CDAP-16033] make Datasource resilient when subscriber do not define …
  cdap-ui/app/cdap/services/datasource/index.js
Labels: 6.1, Bug, UI, cla: yes

#11694 [CDAP-15983] Set spark as the default executor engine in batch pipeline
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.1, UI, cla: yes

#11695 add allowed origin from cdap-site
  cdap-ui/server.js
Labels: 6.1, Bug, UI, cla: yes

#11700 Merge 6.1 back to develop
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLPlugin.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/directives/dag-plus/my-dag.less
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/server.js
Labels: cla: yes

#11704 Bugfix release/merge 6.0
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#11705 Merge 6.1 back to develop
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/app/services/cask-angular-socket-datasource/socket.js
  cdap-ui/server/aggregator.js
Labels: cla: yes

#11703 [CDAP-16045] Change View details from pipeline to go to metadata summary
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/my-link-button/my-link-button.html
  cdap-ui/app/directives/my-link-button/my-link-button.js
  cdap-ui/app/ui-utils/url-generator.js
Labels: 6.1, UI, cla: yes

#11698 [CDAP-16041] Adjust colors and fonts in field level lineage v2
  cdap-ui/app/cdap/components/EntityTopPanel/EntityTopPanel.scss
  cdap-ui/app/cdap/components/EntityTopPanel/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TimeRangePicker/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11701 [CDAP-16044] Change styling for fields and datasets related to target field
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
Labels: 6.1, UI, cla: yes

#11706 (CDAP-16056) Fix firewall rule check in Dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: cla: yes

#11707 Merge Release 6.1 to Develop
  cdap-ui/app/cdap/components/EntityTopPanel/EntityTopPanel.scss
  cdap-ui/app/cdap/components/EntityTopPanel/index.js
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/ModalContent.js
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TimeRangePicker/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/my-link-button/my-link-button.html
  cdap-ui/app/directives/my-link-button/my-link-button.js
  cdap-ui/app/ui-utils/url-generator.js
Labels: 6.2, cla: yes

#11708 supporting filename ending with verison and no dash in between
  cdap-ui/app/cdap/services/__tests__/helpers.test.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.1, UI, cla: yes

#11709 [CDAP-16054] Add cookie-based experiment access to field level lineage v2 UI
  cdap-ui/app/cdap/components/ExperimentWrapper/ExperimentToggle.tsx
  cdap-ui/app/cdap/components/ExperimentWrapper/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/cypress/fixtures/fll_airport_pipeline2.json
  cdap-ui/cypress/fixtures/fll_wrangler-test-pipeline.json
  cdap-ui/cypress/fixtures/null_splitter_pipeline-cdap-data-pipeline.json
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
  cdap-ui/cypress/integration/fieldlevellineage.spec.ts
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.1, UI, cla: yes

#11714 update dataproc
  cdap-runtime-ext-dataproc/pom.xml
Labels: 6.1, Bug, cla: yes

#11715 CDAP-16069 fix FLL performance
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
Labels: cla: yes
