Repository cdapio/cdap, pull requests merged in 2019-02, with the labels that each got.

#11003 Remove unused package variable
  cdap-ui/server/express.js
Labels: 6.0, Bug, UI

#11002 CDAP-14771 bootstrap the system pipeline app
  cdap-common/src/main/resources/bootstrap/distributed.json
  cdap-common/src/main/resources/bootstrap/sandbox.json
Labels: 6.0

#11005 [CDAP-14716] Add minimap interaction
  cdap-ui/app/directives/dag-minimap/dag-minimap-ctrl.js
  cdap-ui/app/directives/dag-minimap/dag-minimap-utilities.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.html
  cdap-ui/app/directives/dag-minimap/dag-minimap.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.less
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
Labels: 6.0, UI

#11001 (CDAP-14646) Introduce the cdap-kubernetes module
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/ImpersonatedTwillRunnerService.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/DefaultServiceDiscovered.java
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/test/java/co/cask/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/server/MessagingHttpService.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/server/MessagingHttpServiceTest.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsProcessorStatusService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsQueryService.java
  pom.xml
Labels: 6.0

#11000 [CDAP-14834] Remove dependency on dataset framework
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/NoSqlArtifactStoreTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataFabricDistributedModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/AbstractTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlTransactionRunner.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableTest.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSpecificationRegistry.java
Labels: 6.0

#11013 CDAP-14851 Sort returned rows in storage SPI
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
Labels: 6.0

#11024 (CDAP-14869) Remove direct metric store usage
  cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/DistributedMRJobInfoFetcher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/mapreduce/LocalMRJobInfoFetcher.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/WorkflowStatsSLAHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/namespace/DefaultNamespaceResourceDeleter.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/ProfileService.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/metrics/NoOpMetricsSystemClient.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/MetricHBaseTableUtilTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/co/cask/cdap/master/startup/ConfigurationCheck.java
  cdap-master/src/test/java/co/cask/cdap/master/startup/ConfigurationCheckTest.java
  cdap-operational-stats-core/src/main/java/co/cask/cdap/operations/cdap/CDAPLoad.java
  cdap-operational-stats-core/src/main/java/co/cask/cdap/operations/cdap/CDAPTransactions.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingPollingService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricDeleteQuery.java
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/metrics/MetricsSystemClient.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/DistributedMetricsClientModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsClientRuntimeModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/DirectMetricsSystemClient.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsAdminMessage.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsAdminSubscriberService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MetricsConsumerMetaTable.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/RemoteMetricsSystemClient.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/LocalMetricsDatasetFactory.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsAdminSubscriberServiceTest.java
Labels: 6.0

#11019 [CDAP-15584] Add an Elasticsearch Metadata Storage Provider
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataScope.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/Metadata.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataKind.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/ScopedName.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/ScopedNameOfKind.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/noop/NoopMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/MetadataStorageTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/Cursor.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ScopedNameTypeAdapter.java
  cdap-elastic/src/main/resources/index.mapping.json
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: 6.0

#11025 (CDAP-14646) Create isolated main classes for TMS and Metrics services
  cdap-common/src/main/java/co/cask/cdap/common/conf/CConfigurationUtil.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/co/cask/cdap/common/conf/CConfigurationMapTest.java
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/resources/META-INF/services/META-INF/services/co.cask.cdap.master.spi.environment.MasterEnvironment
  cdap-master-spi/pom.xml
  cdap-master-spi/src/main/java/co/cask/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/co/cask/cdap/master/spi/environment/MasterEnvironmentContext.java
  cdap-master/pom.xml
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MessagingServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/DefaultMasterEnvironmentContext.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/MasterEnvironmentExtensionLoader.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/MockMasterEnvironment.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterMainTestBase.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MessagingServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MetricsServiceMainTest.java
  cdap-master/src/test/resources/META-INF/services/co.cask.cdap.master.spi.environment.MasterEnvironment
  cdap-tms/src/main/java/co/cask/cdap/messaging/server/MessagingHttpService.java
  pom.xml
Labels: 6.0

#10993 CDAP-14827 Added admin call to get namespace information
  cdap-api/src/main/java/co/cask/cdap/api/Admin.java
  cdap-api/src/main/java/co/cask/cdap/api/NamespaceSummary.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/NamespaceHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/DefaultAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/bootstrap/executor/DefaultNamespaceCreator.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricClient.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
  cdap-common/src/main/java/co/cask/cdap/common/namespace/NamespaceAdmin.java
  cdap-common/src/test/java/co/cask/cdap/common/test/NoopAdmin.java
  cdap-operational-stats-core/src/test/java/co/cask/cdap/operations/cdap/CDAPOperationalStatsTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/NamespaceMeta.java
  cdap-security/src/main/java/co/cask/cdap/security/authorization/DefaultAuthorizationContext.java
  cdap-unit-test/src/test/java/co/cask/cdap/admin/AdminApp.java
  cdap-unit-test/src/test/java/co/cask/cdap/admin/AdminAppTestRun.java
Labels: On-hold

#11027 CDAP-14673 Create a NoSQL schema registry
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/namespace/StorageProviderNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/NoSqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/SqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/NoSqlDefaultSecureStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/SqlDefaultSecureStoreTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/dataset/EntityTableDatasetContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/dataset/NoSQLTransactionals.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/dataset/TableDatasetSupplier.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/DatasetFrameworkTestUtil.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/sql/SqlStructuredTableTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/StructuredTableRegistry.java
  cdap-storage-spi/src/test/java/co/cask/cdap/spi/data/table/StructuredTableRegistryTest.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 6.0

#11029 (CDAP-14886) Remove user service custom route config
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/RouteConfigHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/route/store/LocalRouteStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/route/store/RouteConfig.java
  cdap-app-fabric/src/main/java/co/cask/cdap/route/store/RouteStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/route/store/ZKRouteStore.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/RouteConfigHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/route/store/LocalRouteStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/route/store/ZKRouteStoreTest.java
  cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/DeleteRouteConfigCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/GetRouteConfigCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/SetRouteConfigCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/commandset/ServiceCommands.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/ServiceClientTestRun.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/developer-manual/source/building-blocks/services.rst
  cdap-docs/reference-manual/source/http-restful-api/index.rst
  cdap-docs/reference-manual/source/http-restful-api/routeconfig.rst
  cdap-gateway/src/main/java/co/cask/cdap/gateway/discovery/RouteFallbackStrategy.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/discovery/UserServiceEndpointStrategy.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/ExceptedNumberOfAuditPolicyPaths.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterMain.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterServiceLookup.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/discovery/InMemoryRouteStore.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/discovery/RouteFallbackStrategyTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/discovery/UserServiceEndpointStrategyTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/AuditLogTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/AuthServerAnnounceTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterHttpTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/NettyRouterHttpsTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterAuditLookUpTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterMainTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterResource.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RoutingToDataSetsTest.java
Labels: 6.0

#11010 CDAP-14810 Add scan using index API to storage SPI
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTable.java
  cdap-api/src/main/java/co/cask/cdap/api/dataset/lib/IndexedTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/dataset/EntityTableDatasetContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/dataset/TableDatasetSupplier.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlTransactionRunner.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSchema.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSpecification.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/field/FieldType.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/table/field/Fields.java
  cdap-storage-spi/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
Labels: 6.0

#11033 [CDAP-14896] Refactor to eliminate code duplication in DefaultMetadataStore
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
Labels: 6.0

#11014 [CDAP-14710] NUX for new navbar design
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/DrawerFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/EntityListView/Tour/index.ts
  cdap-ui/app/cdap/components/EntityListView/Welcome/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/GuidedTour/GuidedTour.scss
  cdap-ui/app/cdap/services/GuidedTour/index.ts
Labels: 6.0, Bug, UI

#11030 [CDAP-14796] Change dataprep API usage to use system service
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/api/experiments.js
  cdap-ui/app/cdap/api/reports.js
  cdap-ui/app/cdap/api/rulesengine.js
  cdap-ui/app/cdap/components/DataPrep/AutoComplete/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/TableList/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/bigquery.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/database.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/file.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/gcs.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/kafka.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/s3.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/spanner.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/KafkaBrowser.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/TableList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/TopPanel.scss
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
  cdap-ui/app/cdap/components/DataPrep/helper.js
  cdap-ui/app/cdap/components/DataPrep/index.js
  cdap-ui/app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseOptions.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/UploadFile/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/DataPrepHome/index.js
  cdap-ui/app/cdap/components/Experiments/CreateView/index.js
  cdap-ui/app/cdap/components/Experiments/store/CreateExperimentActionCreator.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
  cdap-ui/app/cdap/services/ServiceEnablerUtilities.js
Labels: 6.0, UI

#11038 CDAP-14673 Fix schema registry cache to read from storage whenever table is not found
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableRegistry.java
Labels: 6.0

#11037 (CDAP-14646) Guice modules refactoring
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/MonitorHandlerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/ServiceStoreModules.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/DatasetServiceStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/DistributedTimeSchedulerService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/namespace/StorageProviderNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/guice/AppFabricTestModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataAuditPublishTest.java
  cdap-common/src/main/java/co/cask/cdap/common/service/RetryOnStartFailureService.java
  cdap-common/src/test/java/co/cask/cdap/common/service/RetryOnStartFailureServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/AuditModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/InMemoryNamespaceStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/NamespaceStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/guice/NamespaceStoreModule.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/audit/AuditTestModule.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/audit/InMemoryAuditPublisher.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/AbstractDatasetFrameworkTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStoreTest.java
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/InMemoryExploreServiceTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ExploreServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/LogSaverTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MetricsTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/TransactionServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/distributed/DistributedLogFramework.java
Labels: 6.0

#11028 [CDAP-14864] Support sort by creation time and add tests
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/MetadataConstants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SortInfo.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/SystemMetadataProvider.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/MetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/main/resources/index.mapping.json
Labels: 6.0

#11032 [CDAP-14864] Enable and test metadata search on description
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/MetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
Labels: 6.0

#11039 CDAP-14673 Make schema registry table non-transactional
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryMetricsTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTableDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableRegistry.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
Labels: 6.0

#11040 (CDAP-14646) Added AppFabricServiceMain
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/ConstantTransactionSystemClient.java
  cdap-common/src/main/java/co/cask/cdap/common/discovery/ResolvingDiscoverable.java
  cdap-common/src/main/java/co/cask/cdap/common/runtime/DaemonMain.java
  cdap-master/pom.xml
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/MockMasterEnvironment.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterMainTestBase.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MessagingServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MetricsServiceMainTest.java
Labels: 6.0

#11042 [CDAP-14867] Correct behavior for configuring and adjusting Elasticsearch max_result_window
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticConfigurationTest.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: 6.0

#11045 [CDAP-14862] Add tests for search on TTL
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/MetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/main/resources/index.mapping.json
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: 6.0

#11054 [CDAP-14802] Move metadata SPI to separate module
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataValidator.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SortInfo.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/DefaultValueIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/MetadataEntityTypeIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/AppSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ArtifactSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/DatasetSystemMetadataProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/ProgramSystemMetadataWriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/system/SystemMetadataProvider.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/indexer/DefaultValueIndexerTest.java
  cdap-elastic/pom.xml
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
  cdap-metadata-spi/pom.xml
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Metadata.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataChange.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataConstants.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataDirective.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataKind.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataMutation.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataRecord.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataStorage.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Read.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/ScopedName.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/ScopedNameOfKind.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchRequest.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchResponse.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Sorting.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/id/ProgramId.java
  pom.xml
Labels: 6.0

#11051 CDAP-14770 Migrate profile dataset to storage SPI
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/profile/ProfileDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/profile/ProfileStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/NoSqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/SqlProfileServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-storage-spi/src/main/java/co/cask/cdap/spi/data/transaction/TransactionRunners.java
Labels: 6.0

#11053 [CDAP-14734] increase z-index of node popover action dropdown
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, Bug, UI

#11052 [CDAP-14975] Prevent automatic refresh on pipeline studio
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/hydrator/main.js
Labels: 6.0, UI

#11046 [CDAP-14870] Pipeline System App - getSchema for Transforms
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema-modal.html
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.js
  cdap-ui/app/services/hydrator/my-pipeline-api.js
Labels: 6.0, UI

#11058 Add support for CSP in CDAP UI
  cdap-ui/Gulpfile.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/app/logviewer/logviewer.html
  cdap-ui/app/tracker/tracker.html
  cdap-ui/dll/cdap-vendor-manifest.json
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/dll/dll.shared.vendor.js
  cdap-ui/dll/shared-vendor-manifest.json
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.shared.dll.js
  cdap-ui/yarn.lock
Labels: 6.0, UI

#11064 Revert "[CDAP-14799] Implement and test clean semantics for cursors, offsets, limits and total results"
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/Cursor.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/noop/NoopMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/Cursor.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchResponse.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0, Bug

#11063 CDAP-14904 Set temp directory for EmbeddedPostgres in ProgramScheduleStoreDataset
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/store/SqlProgramScheduleStoreDatasetTest.java
Labels: 6.0

#11055 CDAP-14882 Adding log buffer writer
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferEvent.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferFileOffset.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferWriter.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/LogBufferWriterTest.java
Labels: 6.0

#11070 [CDAP-14919] Mark all Metadata API/SPI as @Beta
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataEntity.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataException.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataReader.java
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataWriter.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Metadata.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataChange.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataConstants.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataDirective.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataKind.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataMutation.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataRecord.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataStorage.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Read.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/ScopedName.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/ScopedNameOfKind.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchRequest.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchResponse.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Sorting.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0

#11067 [CDAP-14863] Support metadata search on schema
  cdap-api-common/pom.xml
  cdap-api-common/src/main/java/co/cask/cdap/api/data/schema/SchemaWalker.java
  cdap-api-common/src/main/test/java/co/cask/cdap/api/data/schema/SchemaWalkerTest.java
  cdap-api-common/src/main/test/java/co/cask/cdap/api/data/schema/package-info.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexer.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/indexer/SchemaIndexerTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/MetadataDocument.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/MetadataDocumentTest.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0

#11062 [CDAP-14912] Make noSql metadata storage independent of dataset framework
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataServiceModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/inmemory/InMemoryTableService.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetDefinition.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/noop/NoopMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableServiceTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/AbstractMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticConfigurationTest.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/HiveExploreServiceFileSetTestRun.java
  cdap-explore/src/test/java/co/cask/cdap/hive/context/ContextManagerTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataStorage.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 6.0

#11031 CDAP-14883 Changes for time queue processor abstraction
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/Checkpoint.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/CheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/CheckpointManagerFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/DefaultCheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/KafkaOffset.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipeline.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/kafka/KafkaOffsetResolver.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/ProcessedEventMetadata.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/ProcessorEvent.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueue.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueueProcessor.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/framework/distributed/DistributedLogFrameworkTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaOffsetResolverTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueueProcessorTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueueTest.java
Labels: 6.0

#11074 [CDAP-14921] Remove legacy DefaultMetadataStore
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataAuditPublishTest.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/SystemDatasetRuntimeModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/AbstractMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0

#11077 [CDAP-14806] Test and fix search on custom entities
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataAdminAuthorizationTest.java
  cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
  cdap-cli/src/main/java/co/cask/cdap/cli/DefaultCompleters.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/SearchMetadataCommand.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/AbstractMetadataClient.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SearchRequest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/indexer/MetadataEntityTypeIndexer.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/AbstractMetadataStoreTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/resources/logback-test.xml
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/element/EntityTypeSimpleName.java
Labels: 6.0

#11083 [CDAP-14934] Fix flaky MetadataSubscriberServiceTest
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
Labels: 6.0, Bug

#11088 Implement strict csp policy for CDAP UI
  cdap-ui/app/cdap/cdap.html
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/login/login.html
  cdap-ui/app/logviewer/logviewer.html
  cdap-ui/app/tracker/tracker.html
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.login.js
  cdap-ui/yarn.lock
Labels: 6.0, UI

#11089 [CDAP-14928] Make metadata storage provider configurable via cdap-site
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataServiceModule.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
Labels: 6.0

#11078 CDAP-14770 JobQueueDataset migration
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/AppFabricDatasetModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/Job.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobKey.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueue.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetDefinition.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueTable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/queue/SimpleJob.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/schedule/store/Schedulers.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ConstraintCheckerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/DelayConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/LastRunConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/TimeRangeConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueDatasetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/NoSqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/SqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlTransactionException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
Labels: 6.0

#11095 [CDAP-14938] Fix rerouting to pipeline list view after pipeline delet…
  cdap-ui/app/ui-utils/url-generator.js
Labels: 6.0, Bug, UI

#11097 CDAP-14770 Fix race condition in JobQueueTableTest
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/queue/JobQueueTableTest.java
Labels: 6.0

#11081 CDAP-14929 Define all tables before starting services in Cloud Runtime.
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
Labels: 6.0

#11085 [CDAP-14933] fix logs not being fetch from UI
  cdap-ui/app/directives/timeline/timeline-ctrl.js
Labels: 6.0, Bug, UI

#11075 [CDAP-14723] Add node select behavior to pipeline studio
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, UI

#11087 (CDAP-14646) Added MetadataServiceMain and RouterServiceMain for the K8s
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/mapreduce/LocalMRJobInfoFetcherTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteRuntimeTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/store/DatasetBasedTimeScheduleStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/co/cask/cdap/common/service/RetryOnStartFailureService.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetServiceModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetService.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetOpExecutor.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/LocalDatasetOpExecutor.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/RemoteDatasetOpExecutor.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/executor/YarnDatasetOpExecutor.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/executor/DatasetOpExecutorServiceTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/datafabric/dataset/service/executor/InMemoryDatasetOpExecutor.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/BaseHiveExploreServiceTest.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/ExploreDisabledTest.java
  cdap-explore/src/test/java/co/cask/cdap/explore/service/InMemoryExploreServiceTest.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/RouterModules.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/log/LogHandlerTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-master/pom.xml
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMainTest.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MetadataServiceMainTest.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTest.java
Labels: 6.0

#11105 [CDAP-14948] Fixes login path to point to the right sub directory like (login_asse…
  cdap-ui/server/express.js
Labels: 6.0, Bug, UI

#11080 [CDAP-14882] Adding log buffer processor pipeline
  cdap-app-fabric/src/test/java/co/cask/cdap/security/NoSqlDefaultSecretStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/SqlDefaultSecretStoreTest.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/LogPipelineLoader.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/LogPipelineSpecification.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/distributed/DistributedLogFramework.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/local/LocalLogAppender.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/ConcurrentLogBufferWriter.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferEvent.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferFileOffset.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/logbuffer/LogBufferWriter.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/AbstractCheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/CheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/CheckpointManagerFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/DefaultCheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/KafkaCheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/LogBufferCheckpointManager.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/LoggingStoreTableUtil.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipeline.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/logbuffer/LogBufferPipelineConfig.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/logbuffer/LogBufferProcessorPipeline.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueue.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueueProcessor.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/read/DistributedLogReader.java
  cdap-watchdog/src/main/resources/cdap-log-pipeline.xml
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/TestDistributedLogReader.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/framework/distributed/DistributedLogFrameworkTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/logbuffer/LogBufferWriterTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/LogPipelineTestUtil.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/MockAppender.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/logbuffer/LogBufferProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/queue/TimeEventQueueProcessorTest.java
Labels: 6.0

#11117 [CDAP-14960] Change search target api for application
  cdap-ui/app/cdap/components/Administration/AdminConfigTabContent/NamespacesAccordion/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/EntityListView/ListViewHeader/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/SearchConstants.js
  cdap-ui/app/cdap/components/NamespaceDetails/store/ActionCreator.js
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
Labels: 6.0, Bug, UI

#11119 CDAP-14961 make sql connection pool size configurable
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/jdbc/DataSourceInstantiator.java
Labels: 6.0

#11120 (CDAP-14646) Fixes and added packaing for isolated master services for running in K8s
  cdap-common/src/main/java/co/cask/cdap/common/guice/FileContextProvider.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/dataset2/lib/table/hbase/MetricHBaseTableUtilTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/lib/table/hbase/HBaseMetricsTableDefinition.java
  cdap-gateway/src/main/java/co/cask/cdap/gateway/router/handlers/HttpRequestRouter.java
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/co/cask/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-master/pom.xml
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/NoopTwillController.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/NoopTwillPreparer.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/NoopTwillRunnerService.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageCreationService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/guice/MetricsClientRuntimeModule.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/LocalMetricsDatasetFactory.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaOffsetResolverTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsAdminSubscriberServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTestBase.java
  pom.xml
Labels: 6.0

#11118 [CDAP-14756] Refactor all APIs to use Metadata SPI directly
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataCodec.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataValidator.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataAdminAuthorizationTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataCodecTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/LineageHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/AbstractMetadataClient.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceClientTest.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/AuditMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/MetadataCompatibility.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SearchResults.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/AuditMetadataStorageTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/AbstractMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/StorageProviderMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageCreationService.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/SearchRequest.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/Sorting.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/SortingTest.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithMetadataPrograms.java
Labels: 6.0

#11125 (CDAP-14977) Introduce a better directory structure for loading JDBC driver
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/sql/jdbc/DataSourceInstantiator.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/sql/jdbc/DataSourceInstantiatorTest.java
Labels: 6.0

#11123 (CDAP-14974) Create store init step
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageCreationService.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/MasterServiceMainTestBase.java
Labels: 6.0

#11121 [CDAP-14868] Deterministic behavior for batch of non-disjoint metadata mutations
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
Labels: 6.0

#11122 [CDAP-14963] Test and fix behavior when Elasticsearch scroll times out
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceClientTest.java
  cdap-data-fabric-tests/src/test/java/co/cask/cdap/data2/transaction/distributed/TransactionServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/SearchResults.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/AuditMetadataStorageTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-metadata-spi/src/test/java/co.cask.cdap.spi.metadata/MetadataStorageTest.java
  cdap-unit-test/src/test/java/co/cask/cdap/test/app/AppWithMetadataPrograms.java
Labels: 6.0

#11115 [CDAP-14907] log file meta table migration
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/store/StoreDefinition.java
  cdap-docs/admin-manual/source/conf.py
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-watchdog-api/pom.xml
  cdap-watchdog-api/src/main/java/co/cask/cdap/api/logging/AppenderContext.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/clean/FileMetadataCleaner.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/clean/LogCleaner.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/AbstractAppenderContext.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/LocalAppenderContext.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/LogPipelineLoader.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/distributed/DistributedAppenderContext.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/framework/local/LocalLogAppender.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/FileMetaDataReader.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/FileMetaDataWriter.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/LoggingStoreTableUtil.java
  cdap-watchdog/src/main/resources/cdap-log-pipeline.xml
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/file/TestFileLogging.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/CDAPLogAppenderTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/appender/system/LogFileManagerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/FileMetadataCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/clean/LogCleanerTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/framework/distributed/DistributedLogFrameworkTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/pipeline/kafka/KafkaLogProcessorPipelineTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/plugins/RollingLocationLogAppenderTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/read/FileMetadataTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/logging/write/FileMetaDataManager.java
Labels: 6.0

#11126 [CDAP-14978] Make keyring id configurable
  cdap-securestore-ext-cloudkms/src/main/java/co/cask/cdap/securestore/gcp/cloudkms/CloudKMSClient.java
Labels: 6.0

#11127 (CDAP-14985) Add the missing MonitorHandler
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/test/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMainTest.java
Labels: 6.0

#11128 (CDAP-14974) Fix the storage initialization step
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
Labels: 6.0

#11129 (CDAP-14989) Preview injector should always use NoSQL storage engine
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
Labels: 6.0

#11132 (CDAP-14645) Couple fixes for the Kubernetes runtime
  cdap-master/pom.xml
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/StorageMain.java
Labels: 6.0

#11136 (CDAP-14645) Fix the dependency copy for Hadoop yarn classes
  cdap-common/bin/cdap
  cdap-common/bin/functions.sh
  cdap-master/pom.xml
Labels: 6.0

#11137 [CDAP-14992] Ensure MetadataStorage is always closed
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/runtime/WorkflowTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/config/NoSqlUserConfigStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/NoSqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/SqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/SystemArtifactsAuthorizationTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/batch/MapReduceRunnerTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/entity/EntityExistenceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/schedule/constraint/LastRunConstraintTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/worker/WorkerProgramRunnerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/AppFabricServerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/DefaultSecureStoreServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramLifecycleServiceAuthorizationTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/NoSqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/NoSqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/preview/DefaultPreviewStoreTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/remote/RemoteNamespaceQueryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/store/remote/RemotePrivilegesTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/BootstrapServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/AppCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/DefaultNamespaceCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/NativeProfileCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/ProgramStarterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/SystemPreferencesSetterTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/bootstrap/executor/SystemProfileCreatorTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/NoSqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetricServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/SqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataAdminAuthorizationTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataAuditPublishTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/reporting/NoSqlProgramHeartBeatTableTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/runtime/OpenCloseDataSetTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/NoSqlDefaultSecretStoreTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/DataSetsModules.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/GatewayTestBase.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-metadata-spi/src/main/java/co.cask.cdap.spi.metadata/MetadataStorage.java
  cdap-operational-stats-core/src/test/java/co/cask/cdap/operations/cdap/CDAPOperationalStatsTest.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 6.0

#11139 [CDAP-14976] Attempt to fix flaky ProfileMetadataTest
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/profile/ProfileMetadataTest.java
Labels: Bug

#11140 CDAP-15002 Close scan iterators
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/store/WorkflowTable.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/datafabric/dataset/service/mds/DatasetInstanceTable.java
  cdap-storage-spi/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
Labels: 6.0

#11133 [CDAP-14993] Implement consistent cursor semantics
  cdap-common/src/main/java/co/cask/cdap/common/metadata/Cursor.java
  cdap-common/src/test/java/co/cask/cdap/common/metadata/CursorTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/Cursor.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/Cursor.java
  cdap-elastic/src/main/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: 6.0

#11141 CDAP-14998 fix DatasetRuntimeContext leak
  cdap-api/src/main/java/co/cask/cdap/internal/dataset/DatasetRuntimeContext.java
  cdap-common/src/main/java/co/cask/cdap/common/dataset/DatasetClassRewriter.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/dataset2/DefaultDatasetRuntimeContext.java
Labels: 6.0

#11138 (CDAP-14645) Filter out fasterxml classes in Spark classloader
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-common/bin/functions.sh
  cdap-common/pom.xml
  cdap-master/pom.xml
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  pom.xml
Labels: 6.0

#11143 (CDAP-15003) Fix preview log endpoint
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewHttpModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/gateway/handlers/preview/PreviewHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/AbstractLogHandler.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/gateway/handlers/LogHandler.java
  cdap-watchdog/src/main/java/co/cask/cdap/logging/meta/FileMetaDataReader.java
Labels: 6.0

#11144 (CDAP-14984) Introduce master environment task
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/PodKillerTask.java
  cdap-kubernetes/src/test/java/co/cask/cdap/master/environment/k8s/PodKillerTaskTest.java
  cdap-master-spi/src/main/java/co/cask/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/co/cask/cdap/master/spi/environment/MasterEnvironmentTask.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MasterTaskExecutorService.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/master/environment/k8s/RouterServiceMain.java
Labels: 6.0

#11145 (CDAP-14986) Correctly setup singleton bindings for storage module
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
Labels: 6.0

#11142 CDAP-15004 provide RetryingSqlTransactionRunner
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/StorageModule.java
Labels: 6.0, Bug

#11109 [CDAP-14944] fix z-index of minimap vs node
  cdap-ui/app/directives/dag-minimap/dag-minimap.less
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, Bug, UI
