Repository cdapio/cdap, pull requests merged in 2019-06, with the labels that each got.

#11402 [CDAP-15469] Fix proptypes and add onchange to widget JSON
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Number/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/TextBox/index.tsx
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, Bug, UI

#11403 [CDAP-15468] Fix metadata serialization regression
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: 6.1, Bug

#11400 Migrate csv, keyvalue, and keyvalue-encoded widgets to React component
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/Container.tsx
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/CSVWidget/CSVRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/CSVWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueWidget/KeyValueRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueWidget/index.tsx
  cdap-ui/app/cdap/components/Experimental/index.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI

#11401 [CDAP-15450] Migrate select widget to react component
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI

#11292 Change documentation theme to dark
  cdap-docs/_common/_static/cdap_logo.svg
  cdap-docs/_common/_static/favicon.ico
  cdap-docs/_common/_themes/cdap-bootstrap/cdap-navbar.html
  cdap-docs/_common/_themes/cdap-bootstrap/static/cdap-bootstrap.css_t
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/cdap-bootstrap-fonts.css
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.woff2
  cdap-docs/_common/_themes/cdap/layout.html
Labels: 5.1

#11291 Change documentation theme to dark
  cdap-docs/_common/_static/cdap_logo.svg
  cdap-docs/_common/_static/favicon.ico
  cdap-docs/_common/_themes/cdap-bootstrap/cdap-navbar.html
  cdap-docs/_common/_themes/cdap-bootstrap/static/cdap-bootstrap.css_t
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/cdap-bootstrap-fonts.css
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Bold.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-BoldItalic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Italic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Medium.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-MediumItalic.woff2
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.eot
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.ttf
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.woff
  cdap-docs/_common/_themes/cdap-bootstrap/static/css/fonts/GoogleSans-Regular.woff2
  cdap-docs/_common/_themes/cdap/layout.html
Labels: 4.3

#11408 [CDAP-15483] Adds back user information to navbar dropdown
  cdap-ui/app/cdap/components/AppHeader/AccessTokenModal/AccessTokenModal.scss
  cdap-ui/app/cdap/components/AppHeader/AccessTokenModal/index.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbarMenu.tsx
Labels: 6.0, Bug, UI

#11410 [CDAP-15488] Minor layout issue fix for joiner plugin UI
  cdap-ui/app/directives/widget-container/widget-sql-select-fields/widget-sql-select-fields.less
Labels: 6.1, Bug, UI

#11411 [CDAP-15497] Fixes minified UI build to not break at runtime
  cdap-ui/Gulpfile.js
  cdap-ui/dll/dll.cdap.vendor.js
  cdap-ui/dll/dll.shared.vendor.js
  cdap-ui/package.json
  cdap-ui/webpack.config.cdap.dll.js
  cdap-ui/webpack.config.cdap.js
  cdap-ui/webpack.config.common.js
  cdap-ui/webpack.config.login.js
  cdap-ui/webpack.config.shared.dll.js
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI

#11412 Revert "[CDAP-15488] Minor layout issue fix for joiner plugin UI"
  cdap-ui/app/directives/widget-container/widget-sql-select-fields/widget-sql-select-fields.less
Labels: 6.0, Bug, UI

#11415 (CDAP-15505) Added logs for error in runtime monitor
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
Labels: 6.1

#11413 [CDAP-15488] Fixes minor layout issue fix for joiner plugin UI
  cdap-ui/app/directives/widget-container/widget-sql-select-fields/widget-sql-select-fields.less
Labels: 6.1, Bug, UI

#11409 [CDAP-15476] migrate ds-multiplevalues widget to react
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/MultipleValuesWidget/MultipleValuesRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/MultipleValuesWidget/index.tsx
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.1, UI

#11406 [CDAP-15433] FLL graphical representation of datasets
  cdap-ui/app/cdap/components/Experiments/FieldLevelLineage/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/sample_response.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, UI

#11422 adding connectionid to dataprep tab
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
Labels: 6.1, UI

#11423 Updates BUILD.rst file in cdap-ui
  cdap-ui/BUILD.rst
Labels: Bug, Docs, UI

#11414 [CDAP-15490] Fixes pipeline resources layout for realtime pipeline
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ClientResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/DriverResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ResourcesTabContent.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/index.js
Labels: 6.0, Bug, UI

#11428 [UI] [Test] Fix e2e integration tests for UI to run successfully in bamboo
  cdap-ui/app/cdap/components/Footer/index.js
  cdap-ui/cypress.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/login.spec.ts
  cdap-ui/cypress/integration/navbar.spec.ts
  cdap-ui/cypress/integration/pipeline.plugin.multipleendpoints.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.upgrade.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI

#11430 Update apache-rat plugin version
  pom.xml
Labels: 6.1

#11431 Move colors from ThemeWrapper into separate file
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ProductEdition.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ToolBarFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/colors.ts
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/app/cdap/styles/colors.scss
Labels: 6.1, UI

#11416 CDAP-15482 add new FLL api
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DatasetFieldLineageSummary.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldRelation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FakeFieldLineageReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FieldLineageAdminTest.java
Labels: 6.1

#11432 use auto if resolution is not specified
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsHandlerTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryHelper.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/query/MetricsQueryHelperTest.java
Labels: 6.1, Bug

#11426 [CDAP-15534] Fix log saver status endpoint
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/LogsServiceMainTest.java
Labels: 6.0

#11425 [CDAP-15433] Part 2: Edges between fields for FLL
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/sample_response.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
Labels: 6.1, UI

#11438 [CDAP-15539] removing capitalization filter for splitter popover
  cdap-ui/app/directives/splitter-popover/splitter-popover.html
Labels: 6.1, Bug, UI

#11434 (CDAP-15562) Added initial proxy support
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSSHContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/SSHConfig.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/Networks.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.1

#11427 [CDAP-15097] artifact version defaults to 1.0.0-SNAPSHOT, if not present
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/ConfigureStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/UploadStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/LibraryUpload/ConfigureStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/LibraryUpload/UploadStep/index.js
  cdap-ui/app/cdap/services/WizardConfigs/ArtifactUploadWizardConfig.js
  cdap-ui/app/cdap/services/WizardConfigs/LibraryUploadWizardConfig.js
  cdap-ui/app/cdap/services/WizardStores/ArtifactUpload/ActionCreator.js
  cdap-ui/app/cdap/services/WizardStores/ArtifactUpload/ArtifactUploadActions.js
  cdap-ui/app/cdap/services/WizardStores/ArtifactUpload/ArtifactUploadStore.js
  cdap-ui/app/cdap/services/__tests__/helpers.test.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI

#11447 updating tests to remove -snapshot from default version
  cdap-ui/app/cdap/services/__tests__/helpers.test.js
Labels: 6.1, Bug

#11439 [CDAP-15569] update multi row widget to be able to get updated on asy…
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/index.tsx
Labels: 6.1, UI

#11452 CDAP-15590 do not copy if artifact exists
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: 6.1, Bug

#11451 fixed issue with hub being cutoff in logviewer
  cdap-ui/app/logviewer/logviewer.html
Labels: 6.1, Bug, UI

#11441 [CDAP-15489] Log level selection overhaul
  cdap-ui/app/directives/log-viewer/log-viewer.html
  cdap-ui/app/directives/log-viewer/log-viewer.js
  cdap-ui/app/directives/log-viewer/log-viewer.less
Labels: 6.1, Bug, UI

#11449 [CDAP-12820] Splitter popover is centered and hairline removed
  cdap-ui/app/directives/splitter-popover/splitter-popover.less
Labels: 6.1, Bug, UI

#11436 [CDAP-15553] fixed issue with connections going down at origin for splitter
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
Labels: 6.1, UI

#11300 #[CDAP-15294] | Addition of ADLS connection in CDAP-UI
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/ADLSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/ActionCreator.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/Actions/adls.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserStore/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/IngestDataFromDataPrep/index.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ADLSConnection/ADLSConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/ADLSConnection/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/AddConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionType.ts
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
Labels: 6.1, UI

#11460 CDAP-15601 Fixed javadocs linking to obsolete methods
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/MetadataDocument.java
Labels: 6.1

#11459 CDAP-15581 modifying error message in MetadataHttpHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: 6.1
