Repository cdapio/cdap, pull requests merged in 2019-11, with the labels that each got.

#11718 [CDAP-16038] optimize graphql queries
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedPipelineView.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/LastStart/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTags/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/RunsCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/Status/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/graphqlHelper.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/index.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/types.ts
  cdap-ui/graphql/Query/applicationsResolver.js
  cdap-ui/graphql/Query/namespacesResolver.js
  cdap-ui/graphql/Query/pipelinesResolver.js
  cdap-ui/graphql/graphql.js
  cdap-ui/graphql/helpers/BatchEndpoints/programRuns.js
  cdap-ui/graphql/helpers/BatchEndpoints/totalRuns.js
  cdap-ui/graphql/helpers/createLoaders.js
  cdap-ui/graphql/resolvers-common.js
  cdap-ui/graphql/resolvers.js
  cdap-ui/graphql/schema/metadataSchema.graphql
  cdap-ui/graphql/schema/namespaceSchema.graphql
  cdap-ui/graphql/schema/pipelineRecordSchema.graphql
  cdap-ui/graphql/schema/programRecordSchema.graphql
  cdap-ui/graphql/schema/rootSchema.graphql
  cdap-ui/graphql/types/ApplicationDetail/programsResolver.js
  cdap-ui/graphql/types/PipelineRecord/common.js
  cdap-ui/graphql/types/PipelineRecord/pipelineRunsResolver.js
  cdap-ui/graphql/types/PipelineRecord/resolvers.js
  cdap-ui/graphql/types/PipelineRecord/totalRunsResolver.js
  cdap-ui/graphql/types/ProgramRecord/runsResolver.js
  cdap-ui/graphql/types/ProgramRecord/totalRunsResolver.js
  cdap-ui/graphql/types/ScheduleDetail/nextRuntimesResolver.js
  cdap-ui/graphql/types/Workflow/runsResolver.js
  cdap-ui/graphql/types/Workflow/schedulesResolver.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI, cla: yes

#11717 UI integration test pipeline artifact version upgrade
  cdap-ui/cypress/fixtures/fll_airport_pipeline2.json
  cdap-ui/cypress/fixtures/fll_wrangler-test-pipeline.json
  cdap-ui/cypress/fixtures/null_splitter_pipeline-cdap-data-pipeline.json
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
Labels: 6.1, Bug, UI, cla: yes

#11719 (CDAP-16085) Fix run records for programs that stuck in STARTING state
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorService.java
Labels: 6.1, cla: yes

#11720 (CDAP-16087) Reduce load on app-fabric on monitor call
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/NonHadoopAppFabricServiceManager.java
Labels: 6.1, cla: yes

#11721 (CDAP-16057) Allow customizing service account for Dataproc
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.1, cla: yes

#11689 [CDAP-16006] Add loading indicator to FLL v2 UI
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/index.tsx
  cdap-ui/app/cdap/components/TimeRangePicker/ExpandableTimeRange.js
Labels: 6.1, Bug, UI, cla: yes

#11688 Add integration test for postrun actions configuration groups and validation
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.html
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.1, UI, cla: yes

#11722 [CDAP-16093] Add Feature Flag for CDAP SQL Pipelines
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/graphql/Query/pipelinesResolver.js
  cdap-ui/graphql/types/PipelineRecord/common.js
Labels: UI, cla: yes

#11716 [CDAP-16073] Add ellipses for long dataset names
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11681 Add unit tests for constructErrors (stage level validation)
  cdap-ui/app/cdap/components/ConfigurationGroup/__tests__/configuration-group-utilities.test.ts
Labels: 6.1, UI, cla: yes

#11724 [UI] [FAVICON] Adds profiles to head tag to define favicon
  cdap-ui/app/cdap/cdap.html
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/tracker/tracker.html
Labels: 6.1, UI, cla: yes

#11726 CDAP-16102 support fll for error transform
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/WrappedErrorTransform.java
Labels: cla: yes

#11725 Removing extra horizontal scrollbar
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11728 Field level lineage tweaks: Add cursor pointer and move date picker
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TimeRangePicker/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11729 [CDAP-16105] [CDAP-16080] [CDAP-15103] validation messaging display changes
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/services/plugin-config-factory.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 6.1, UI, cla: yes

#11734 [UI] [Market] Fix beta tag to be preview in hub modal
  cdap-ui/app/cdap/components/ExperimentalBanner/ExperimentalBanner.scss
  cdap-ui/app/cdap/components/ExperimentalBanner/index.js
  cdap-ui/app/cdap/components/Market/UsecaseTab/index.js
  cdap-ui/app/cdap/components/MarketPlaceUsecaseEntity/MarketPlaceUsecaseEntity.scss
Labels: 6.1, UI, cla: yes

#11732 [UI] Bugfixes for pipelines list & Triggers view
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizePopover.scss
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cla: yes

#11736 Fix scrolling edges
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllMenu/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TimeRangePicker/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/TopPanel/index.tsx
  cdap-ui/app/cdap/components/TimeRangePicker/ExpandableTimeRange.js
  cdap-ui/app/cdap/components/TimeRangePicker/TimeRangePicker.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cla: yes

#11738 (CDAP-16056) Fix firewall rule check in Dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.1, cla: yes

#11737 (CDAP-16112) Introduce multiRead to Storage SPI
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: 6.1, cla: yes

#11740 [UI][Wrangler]Fixes wrangler in pipeline to properly populate schema on clicking ap…
  cdap-ui/app/cdap/components/AbstractWidget/WranglerEditor/index.tsx
  cdap-ui/app/directives/widget-container/widget-complex-schema-editor/widget-complex-schema-editor.js
Labels: 6.1, Bug, UI, cla: yes

#11730 CDAP-16110 limit reads for batch pipeline previews
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/TransformRunner.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatProvider.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/ValidatedPipeline.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/BatchSourceFunction.java
Labels: 6.1, cla: yes

#11742 [UI][FAVICON] Fixes logviewer to have proper favicon
  cdap-ui/app/logviewer/logviewer.html
Labels: 6.1, Bug, UI, cla: yes

#11743 [CDAP-16115] Fix horizontal scroll when last target field is selected
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllMenu/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11747 Code cleanup of AppMetadataStore
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
Labels: 6.1, cla: yes

#11727 Introduce wrangler-datamodel-viewer flag and target tab ui
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/TargetTab/DataModelViewer.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/TargetTab/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/index.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
Labels: cla: yes

#11731 [CDAP-16100] Reduce the number of backend calls in pipeline studio
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.1, Bug, UI, cla: yes

#11746 [CDAP-16117] Refactored UI to Allow Triggering on Non-Batch Pipelines
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggerRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineTriggersRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActions.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersStore.js
  cdap-ui/app/cdap/components/PipelineTriggersSidebars/index.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/hydrator/templates/detail.html
Labels: 6.2, UI, cla: yes

#11751 [CDAP-16119] Fix for avro schema parsing error for union splitter
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/widget-container/widget-complex-schema-editor/widget-complex-schema-editor.js
Labels: 6.1, Bug, UI, cla: yes

#11748 (CDAP-16122) Add prepareRun to SplitterTransform
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/SplitterTransform.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReducePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/WrappedSplitterTransform.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/transform/NullFieldSplitterTransform.java
Labels: cla: yes

#11753 [CDAP-16137] Fixes UI to fetch cdap version before navigating to pipeline studio
  cdap-ui/app/hydrator/routes.js
Labels: 6.1, UI, cla: yes

#11754 [CDAP-16136] hiding plugin functions in deploy view
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
Labels: 6.1, Bug, UI, cla: yes

#11761 [CDAP-16137] Fixes the case of importing to work properly with upgrade step
  cdap-ui/app/hydrator/routes.js
Labels: 6.1, Bug, UI, cla: yes

#11763 (CDAP-16147) Handle exception during startup correctly
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-common/src/main/java/io/cdap/cdap/common/runtime/DaemonMain.java
  cdap-common/src/test/java/io/cdap/cdap/common/runtime/DaemonMainExceptionTest.java
Labels: 6.1, cla: yes
