Repository cdapio/cdap, pull requests merged in 2019-04, with the labels that each got.

#11251 Bugfix ui/cdap ui fixes round 4
  cdap-ui/app/cdap/components/ActionsPopover/ActionsPopover.scss
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/ConnectionPopover.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTable.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/PipelineTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTable.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsGraphHelpers.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.html
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.js
Labels: 6.0, Bug, UI

#11255 (CDAP-15191) Populate environment variables to the system app contain…
  cdap-kubernetes/src/main/java/co/cask/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/co/cask/cdap/master/environment/k8s/PodInfo.java
Labels: 6.0

#11256 (CDAP-15113) Disable app service discovery in remote runtime
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryService.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryServiceTest.java
  cdap-common/src/main/java/co/cask/cdap/common/guice/ZKDiscoveryModule.java
  cdap-proto/src/main/java/co/cask/cdap/proto/ProgramType.java
Labels: 6.0

#11257 (CDAP-15113) Fix MR and Spark runtime for on prem
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-spark-core-base/src/main/java/co/cask/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: 6.0

#11254 [CDAP-14571] Support macros in system HttpServiceContext
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/plugin/MacroParser.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-system-app-api/src/main/java/co/cask/cdap/api/service/http/SystemHttpServiceContext.java
Labels: 6.0

#11262 [CDAP-14697] Modify feature name for dataprep to wrangler
  cdap-ui/app/cdap/components/LoadingIndicator/index.js
  cdap-ui/app/cdap/services/GuidedTour/GuidedTour.scss
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.0, Bug, UI

#11260 (CDAP-15127) Make remote runtime startup asynchronous
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillControllerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
Labels: 6.0

#11258 Update pipeline resources to 2048m
  cdap-ui/app/cdap/services/global-constants.js
Labels: UI

#11263 [CDAP-15197] Increase showing backend down error message in UI.
  cdap-ui/app/cdap/services/StatusFactory.js
Labels: 6.0, Bug, UI

#11247 Remove hostname of cluster from logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
Labels: 6.0

#11268 Fixes lower bound value of the ydomain while rendering logs metrics g…
  cdap-ui/app/cdap/components/PipelineSummary/RunsGraphHelpers.js
Labels: 6.0, Bug, UI

#11267 Bugfix ui/cdap bugfix round 5
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/FieldLevelLineage.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/index.js
  cdap-ui/app/cdap/components/OpsDashboard/RunsGraph/graphRenderer.js
  cdap-ui/app/cdap/components/ResourceCenterEntity/ResourceCenterEntity.scss
  cdap-ui/app/tracker/controllers/lineage-ctrl.js
Labels: 6.0, Bug, UI

#11270 (CDAP-15212) Fix scp hanging issue
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
Labels: 6.0

#11264 [CDAP-15196] Tolerance to requesting a cursor and passing in an offset to a metadata search
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
  cdap-metadata-spi/src/test/java/io/cdap/cdap/spi/metadata/MetadataStorageTest.java
  cdap-ui/app/cdap/components/EntityListView/EntityListInfo/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/ActionCreator.js
Labels: 6.0, Bug

#11269 [CDAP-15210] Adds special case to remove projectId if empty while creating a profile
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/index.js
Labels: 6.0, Bug, UI

#11273 [CDAP-15217] Fix SecureKey to propagate right values during onChange event
  cdap-ui/app/cdap/components/AbstractWidget/SecureKey/index.js
Labels: 6.0, Bug, UI

#11272 Surfaces instance metadata id if present in footer
  cdap-ui/app/cdap/components/Footer/Footer.scss
  cdap-ui/app/cdap/components/Footer/index.js
  cdap-ui/server/express.js
Labels: 6.0, UI

#11276 Removes gcp and solutions categories from market.
  cdap-ui/app/cdap/components/Market/index.js
Labels: 6.0, Bug, UI

#11278 Fixes removing unnecessary categories from hub
  cdap-ui/app/cdap/components/Market/index.js
Labels: 6.0, Bug, UI

#11275 (CDAP-15224) Set program logging context in startup task
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
Labels: 6.0

#11282 (CDAP-15253) Fix a stop hanging issue for programs running in K8s
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/k8s/ServiceOptions.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/k8s/UserServiceProgramMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: 6.0

#11280 (CDAP-15249) Check for null firewall list
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.0

#11285 Fix all warnings from the mvn command
  cdap-app-fabric/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-tools/pom.xml
  cdap-cli/pom.xml
  cdap-explore-jdbc/pom.xml
  cdap-hbase-compat-0.96/pom.xml
  cdap-hbase-compat-0.98/pom.xml
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  cdap-runtime-ext-emr/pom.xml
  cdap-spark-core/pom.xml
  cdap-spark-core2_2.11/pom.xml
  pom.xml
Labels: 6.0

#11288 Revert "Use older dataproc image"
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: 6.0

#11284 [CDAP-15250] Fix the way extract plugin ids from endpoints (condition, alert/error, splitter)
  cdap-ui/app/cdap/components/EntityListView/Welcome/index.tsx
  cdap-ui/app/cdap/globals.ts
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/splitter-popover/splitter-popover.html
  cdap-ui/cypress/fixtures/null_splitter_pipeline-cdap-data-pipeline.json
  cdap-ui/cypress/fixtures/pipeline_old.json
  cdap-ui/cypress/fixtures/purchase_bad.csv
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
  cdap-ui/cypress/integration/navbar.spec.ts
  cdap-ui/cypress/integration/pipeline.plugin.multipleendpoints.spec.ts
  cdap-ui/cypress/pre-startup.js
  cdap-ui/package.json
  cdap-ui/pom.xml
Labels: 6.0, Bug, UI

#11287 (CDAP-14343) Use a ScheuledExecutorService to poll
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ClusterDeleteSubtask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ClusterPollSubtask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-common/src/main/java/io/cdap/cdap/common/async/KeyedExecutor.java
  cdap-common/src/main/java/io/cdap/cdap/common/async/RepeatedTask.java
  cdap-common/src/test/java/io/cdap/cdap/common/async/KeyedExecutorTest.java
Labels: 6.0

#11289 Revert "Update DataProc default worker nodes to be 9, instead of 2."
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.0

#11290 Update default workernodes to 2
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.0

#11293 (CDAP-15275) Remove dataset instance operation replication
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DatasetOperationMessageProcessor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetInstanceService.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/DatasetInstanceOperation.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/MessagingMetadataPublisher.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/MetadataMessage.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/MetadataPublisher.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/NoOpMetadataPublisher.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
Labels: 6.0

#11294 (CDAP-15279) Clear JUL handlers and redirect logs to SLF4j
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
Labels: 6.0

#11295 (CDAP-15280) Refactor DatasetService to remove unneeded thread
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetService.java
Labels: 6.0

#11297 [CDAP-14698] Changes 'directives' tab name to 'Transformation steps' …
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/DataPrepSidePanel.scss
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.0, UI

#11298 [CDAP-15286] Fixes the icon sizes in pipeline detail top panel so that it aligns horizontally
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsTopPanel.scss
Labels: 6.0, Bug, UI

#11308 Adjust width and position of auto-complete-container to not cover up CLI
  cdap-ui/app/cdap/components/DataPrep/DataPrepCLI/DataPrepCLI.scss
Labels: 6.0, Bug, UI

#11303 [CDAP-15231] Updates CDAP favicon for OSS
  cdap-ui/app/cdap/styles/img/favicon.png
  cdap-ui/app/styles/img/favicon.png
Labels: 6.0, UI

#11299 [CDAP-15262] Fixes add-properties in plugin function to accept plugin property to base its value from
  cdap-ui/app/directives/plugin-functions/functions/output-schema/output-schema.js
  cdap-ui/app/directives/plugin-functions/plugin-functions-factory.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-properties-template.html
Labels: 6.0, Bug, UI

#11306 [CDAP-15254] Renames label for dataprep service in admin view to be wrangler
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/AdminManagementTabContentVariables.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/ServicesTable.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/index.js
Labels: 6.0, Bug, UI

#11310 [CDAP-14575] Fixes opening multiple dropdown in dataprep while in pipeline studio
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
Labels: 6.0, Bug, UI

#11305 [CDAP-15148] Fix app drawer to close when hub is opened
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseOptions.js
  cdap-ui/app/cdap/services/global-events.js
  cdap-ui/cypress/integration/navbar.spec.ts
Labels: 6.0, UI
