Repository cdapio/cdap, pull requests merged in 2019-01, with the labels that each got.

#10909 [CDAP-14574] Adds sql editor to pipeline widgets
  cdap-ui/Gulpfile.js
  cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema-modal.html
  cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.js
  cdap-ui/app/directives/plugin-functions/functions/get-schema/get-schema.less
  cdap-ui/app/directives/widget-container/widget-factory.js
  cdap-ui/app/directives/widget-container/widget-js-editor/widget-js-editor.js
  cdap-ui/app/directives/widget-container/widget-js-editor/widget-js-editor.less
Labels: 6.0, UI

#10910 [CDAP-14241] Fix Provisioner default value not getting sent to backend
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.js
  cdap-ui/app/cdap/components/AbstractWidget/DefaultInput/index.js
  cdap-ui/app/cdap/components/AbstractWidget/MemoryTextbox/index.js
  cdap-ui/app/cdap/components/AbstractWidget/NumberTextbox/index.js
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
  cdap-ui/app/cdap/components/SelectWithOptions/index.js
Labels: 6.0, Bug, UI

#10912 [CDAP-14620] Removes code for old navbar
  cdap-ui/app/cdap/components/AppHeader/AboutPageModal/helper.js
  cdap-ui/app/cdap/components/AppHeader/AboutPageModal/index.tsx
  cdap-ui/app/cdap/components/Header/AnalyticsLink/AnalyticsLink.scss
  cdap-ui/app/cdap/components/Header/AnalyticsLink/index.tsx
  cdap-ui/app/cdap/components/Header/BrandSection/BrandSection.scss
  cdap-ui/app/cdap/components/Header/BrandSection/index.tsx
  cdap-ui/app/cdap/components/Header/CaskMarketButton/index.js
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/ControlCenterDropdown.scss
  cdap-ui/app/cdap/components/Header/ControlCenterDropdown/index.js
  cdap-ui/app/cdap/components/Header/DashboardLink/index.tsx
  cdap-ui/app/cdap/components/Header/DataPrepLink/DataPrepLink.scss
  cdap-ui/app/cdap/components/Header/DataPrepLink/index.tsx
  cdap-ui/app/cdap/components/Header/DropdownStyling.scss
  cdap-ui/app/cdap/components/Header/EntitiesLink/index.tsx
  cdap-ui/app/cdap/components/Header/Header.scss
  cdap-ui/app/cdap/components/Header/HubButton/HubButton.scss
  cdap-ui/app/cdap/components/Header/HubButton/index.tsx
  cdap-ui/app/cdap/components/Header/MetadataLink/MetadataLink.scss
  cdap-ui/app/cdap/components/Header/MetadataLink/index.tsx
  cdap-ui/app/cdap/components/Header/NamespaceLinkContext.js
  cdap-ui/app/cdap/components/Header/PipelinesLink/PipelinesLink.scss
  cdap-ui/app/cdap/components/Header/PipelinesLink/index.tsx
  cdap-ui/app/cdap/components/Header/ProductDropdown/AboutPageModal/AboutPageModal.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/AboutPageModal/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/AccessTokenModal/AccessTokenModal.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/AccessTokenModal/index.js
  cdap-ui/app/cdap/components/Header/ProductDropdown/ProductDropdown.scss
  cdap-ui/app/cdap/components/Header/ProductDropdown/index.js
  cdap-ui/app/cdap/components/Header/ReportsLink/index.tsx
  cdap-ui/app/cdap/components/Header/RulesEngineLink/RulesEngineLink.scss
  cdap-ui/app/cdap/components/Header/RulesEngineLink/index.tsx
  cdap-ui/app/cdap/components/Header/index.js
Labels: 6.0, UI

#10914 [CDAP-14620] Adds test for new navbar.
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ToolBarFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/cypress.json
  cdap-ui/cypress/.eslintrc.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/login.spec.ts
  cdap-ui/cypress/integration/navbar.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/plugins/index.js
  cdap-ui/cypress/tsconfig.json
  cdap-ui/package.json
  cdap-ui/server/express.js
  cdap-ui/test/integration/conf.js
  cdap-ui/test/integration/spec.js
  cdap-ui/test/unit/example-test.js
  cdap-ui/test/unit/services/hydratorplusplus/leftpanel-actions-test.js
  cdap-ui/test/unit/services/hydratorplusplus/leftpanel-store-test.js
  cdap-ui/test/unit/settings-test.js
  cdap-ui/yarn.lock
Labels: 6.0, UI

#10916 [CDAP-14657] add copy paste node action in pipeline
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.0, UI

#10920 [CDAP-14713] Fixes Gulp build after feature removal
  cdap-ui/Gulpfile.js
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/tracker/main.js
Labels: 6.0, Bug, UI

#10921 [CDAP-14718] Remove unused databasebrowser route
  cdap-ui/app/cdap/components/Home/index.js
Labels: 6.0, Bug, UI

#10918 [CDAP-11598] Fixes active connection in dataprep connections side panel
  cdap-ui/app/cdap/components/DataPrepConnections/AddConnection/AddConnection.scss
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/ConnectionPopover.scss
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
Labels: 6.0, Bug, UI

#10925 [CDAP-14634] Remove V1 Metadata APIs
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataHttpHandler.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/RemoteMetadataReader.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/co/cask/cdap/datapipeline/DataPipelineTest.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/GetMetadataCommand.java
  cdap-cli/src/main/java/co/cask/cdap/cli/command/metadata/SearchMetadataCommand.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/LineageHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/AbstractMetadataClient.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataCompat.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataRecord.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/MetadataRecordV2.java
  cdap-common/src/test/java/co/cask/cdap/common/metadata/MetadataCompatTest.java
  cdap-common/src/test/java/co/cask/cdap/common/metadata/MetadataRecordTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/audit/payload/builder/MetadataPayloadBuilder.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-examples/SparkPageRank/src/test/java/co/cask/cdap/examples/sparkpagerank/SparkPageRankAppTest.java
  cdap-examples/WikipediaPipeline/src/test/java/co/cask/cdap/examples/wikipedia/WikipediaPipelineAppTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResponse.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResponseV2.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResultRecord.java
  cdap-proto/src/main/java/co/cask/cdap/proto/metadata/MetadataSearchResultRecordV2.java
Labels: 6.0

#10888 CDAP-14617 Write tms messages for different topics to different LevelDB tables
  cdap-tms-tests/src/test/java/co/cask/cdap/messaging/store/hbase/HBaseMessageTableTestRun.java
  cdap-tms-tests/src/test/java/co/cask/cdap/messaging/store/hbase/HBaseMetadataTableTestRun.java
  cdap-tms-tests/src/test/java/co/cask/cdap/messaging/store/hbase/HBasePayloadTableTestRun.java
  cdap-tms-tests/src/test/java/co/cask/cdap/messaging/store/hbase/HBaseTableCoprocessorTestRun.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/service/CoreMessagingService.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/ForwardingTableFactory.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/TableFactory.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/cache/CachingTableFactory.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/hbase/HBaseTableFactory.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBPayloadTable.java
  cdap-tms/src/main/java/co/cask/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/DataCleanupTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/MessageTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/PayloadTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/cache/CachingMessageTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/leveldb/LevelDBMetadataTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/leveldb/LevelDBPayloadTableTest.java
  cdap-tms/src/test/java/co/cask/cdap/messaging/store/leveldb/LevelDBTTLCleanupTest.java
Labels: 6.0

#10924 Adds the ability to wrap react components with theme wrapper based on environment (angular vs react)
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/app/cdap/globals.ts
  cdap-ui/app/cdap/main.js
  cdap-ui/app/directives/my-global-navbar/my-global-navbar.html
  cdap-ui/app/tracker/tracker.html
Labels: 6.0, UI

#10922 [CDAP-14620] [CDAP-14631] Adds feature heading to navbar for appropriate pages
  cdap-ui/.storybook/Welcome.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbar.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/FeatureHeading.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/ToolBarFeatureLink.tsx
  cdap-ui/app/cdap/components/AppHeader/BrandImage.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/styles/img/company_logo-20-all.png
  cdap-ui/app/cdap/styles/img/company_logo.png
  cdap-ui/app/tracker/routes.js
  cdap-ui/server/config/themes/default.json
Labels: 6.0, UI

#10933 [CDAP-12535][CDAP-14714] Fix overflowing popover and allow decimal numbers in calculate directive
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Calculate/index.js
Labels: 6.0, Bug, UI

#10928 [CDAP-14722] Fix macro indicator in node config properties modal
  cdap-ui/app/directives/macro-widget-toggle/macro-widget-toggle.less
Labels: 6.0, Bug, UI

#10929 [CDAP-14625] Fix runtime arguments paddings
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/PipelineRuntimeArgsDropdownBtn.scss
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
Labels: 6.0, Bug, UI

#10931 [CDAP-14624] Fix tags modal header
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
Labels: 6.0, Bug, UI

#10932 [CDAP-13032] Hide metrics for actions, sparkprogram, and condition
  cdap-ui/app/directives/dag-plus/my-dag.html
Labels: 6.0, Bug, UI

#10930 [CDAP-14727] Reintroduce convenience metadata search methods removed in CDAP-14634
  cdap-client-tests/src/test/java/co/cask/cdap/client/MetadataTestBase.java
  cdap-common/src/main/java/co/cask/cdap/common/metadata/AbstractMetadataClient.java
Labels: 6.0

#10938 [CDAP-14641] Refactor Profile Metadata Processor
  cdap-app-fabric/src/main/java/co/cask/cdap/config/PreferencesDataset.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/audit/AuditPublishTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/SystemMetadataAuditPublishTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
Labels: 6.0

#10935 [CDAP-14729] Fixes HubButton component to have class function as fat arrow functions for context (this)
  cdap-ui/.gitignore
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/ResourceCenterEntity/ResourceCenterPipelineEntity.js
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/cypress.json
  cdap-ui/cypress/fixtures/pipeline1.json
  cdap-ui/cypress/fixtures/pipeline_old.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.upgrade.spec.ts
  cdap-ui/cypress/plugins/index.js
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/support/index.js
  cdap-ui/cypress/tsconfig.json
  cdap-ui/cypress/typings/index.d.ts
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.0, Bug, UI

#10923 [CDAP-12899] Add link to preview data to each node in preview mode
  cdap-ui/app/cdap/services/PipelineMetricsStore/index.js
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/create/actions/preview-action-creator.js
  cdap-ui/app/hydrator/services/create/stores/preview-store.js
Labels: 6.0, UI

#10940 [CDAP-12188] Trim trailing whitespace when adding or editing connecti…
  cdap-ui/app/cdap/components/DataPrepConnections/BigQueryConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/DatabaseConnection/DatabaseDetail.js
  cdap-ui/app/cdap/components/DataPrepConnections/GCSConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/S3Connection/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/SpannerConnection/index.tsx
Labels: 6.0, Bug, UI

#10898 CDAP-14665 Add secure store spis
  cdap-securestore-spi/pom.xml
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretManager.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretManagerContext.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretNotFoundException.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretStore.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/secret/Decoder.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/secret/Encoder.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/secret/Secret.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/secret/SecretMetadata.java
  pom.xml
Labels: 6.0

#10926 Storage spi update
  cdap-common/src/main/java/co/cask/cdap/common/AlreadyExistsException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/InvalidFieldException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTableInstantiationException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSchema.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSpecification.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/FieldType.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Fields.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Range.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/transaction/TransactionException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/transaction/TransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/transaction/TransactionRunners.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/transaction/TxCallable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/transaction/TxRunnable.java
Labels: 6.0

#10942 (CDAP-14592) Remove more Flow related references in metrics and cli.
  cdap-api/src/main/java/co/cask/cdap/api/metadata/MetadataEntity.java
  cdap-api/src/main/java/co/cask/cdap/internal/UserErrors.java
  cdap-api/src/test/java/co/cask/cdap/api/metadata/MetadataEntityTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-cli/src/main/java/co/cask/cdap/cli/ArgumentName.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/java/co/cask/cdap/common/queue/QueueName.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsHandlerTestRun.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-gateway/src/test/java/co/cask/cdap/gateway/router/RouterPathLookupTest.java
  cdap-proto/src/main/java/co/cask/cdap/proto/Containers.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricQueryParser.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricStoreRequestExecutor.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/query/MetricsQueryHelper.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/process/MetricsProcessorServiceTestBase.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/query/MetricQueryParserTest.java
Labels: 6.0

#10937 [CDAP-14556] Make arrows to and from sparkprogram plugin to be dotted…
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.0, Bug, UI

#10941 [CDAP-15584] Implement creation/replacement of system metadata in a single MetadataStore method
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-cli-tests/src/test/java/co/cask/cdap/cli/CLIMainTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataChange.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
Labels: 6.0

#10948 CDAP-14744 Fix tag search on update
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
Labels: 6.0

#10945 CDAP-13650 allow updates to stored keys on secure store
  cdap-api/src/main/java/co/cask/cdap/api/security/store/SecureStoreManager.java
  cdap-client-tests/src/test/java/co/cask/cdap/client/SecureStoreClientTest.java
  cdap-kms/src/main/java/co/cask/cdap/security/store/KMSSecureStore.java
  cdap-security/src/main/java/co/cask/cdap/security/store/DefaultSecureStoreService.java
  cdap-security/src/main/java/co/cask/cdap/security/store/FileSecureStore.java
  cdap-security/src/test/java/co/cask/cdap/security/store/FileSecureStoreTest.java
Labels: 6.0

#10950 (CDAP-14591) Re-add the set of RecordFormat classes
  cdap-api-common/src/main/java/co/cask/cdap/api/data/format/Formats.java
  cdap-formats/pom.xml
  cdap-formats/src/main/java/co/cask/cdap/format/AvroRecordFormat.java
  cdap-formats/src/main/java/co/cask/cdap/format/CombinedLogRecordFormat.java
  cdap-formats/src/main/java/co/cask/cdap/format/DelimitedStringsRecordFormat.java
  cdap-formats/src/main/java/co/cask/cdap/format/GrokRecordFormat.java
  cdap-formats/src/main/java/co/cask/cdap/format/RecordFormats.java
  cdap-formats/src/main/java/co/cask/cdap/format/TextRecordFormat.java
  cdap-formats/src/test/java/co/cask/cdap/format/AvroRecordFormatTest.java
  cdap-formats/src/test/java/co/cask/cdap/format/CombinedLogRecordFormatTest.java
  cdap-formats/src/test/java/co/cask/cdap/format/DelimitedStringsRecordFormatTest.java
  cdap-formats/src/test/java/co/cask/cdap/format/GrokRecordFormatTest.java
  pom.xml
Labels: 6.0

#10947 [CDAP-14584] Add an SPI for Metadata
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/Metadata.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataChange.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataDirective.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataKind.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataMutation.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataRecord.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/ScopedName.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/ScopedNameOfKind.java
Labels: 6.0

#10949 [CDAP-14620] Final navbar styling fixes
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/DrawerFeatureLink.tsx
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/cypress/integration/navbar.spec.ts
Labels: 6.0, UI

#10954 (CDAP-14765) Fix ExploreClient guice binding for program container
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/app/runtime/spark/distributed/SparkTwillRunnableModuleTest.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
Labels: 6.0

#10944 CDAP-14669 Google Cloud KMS Implementation
  cdap-app-fabric/src/main/java/co/cask/cdap/security/TokenSecureStoreRenewer.java
  cdap-master/pom.xml
  cdap-securestore-ext-cloudkms/pom.xml
  cdap-securestore-ext-cloudkms/src/main/java/co/cask/cdap/securestore/gcp/cloudkms/CloudKMSClient.java
  cdap-securestore-ext-cloudkms/src/main/java/co/cask/cdap/securestore/gcp/cloudkms/CloudSecretManager.java
  cdap-securestore-ext-cloudkms/src/main/java/co/cask/cdap/securestore/gcp/cloudkms/SecretInfo.java
  cdap-securestore-ext-cloudkms/src/main/java/co/cask/cdap/securestore/gcp/cloudkms/SecretInfoCodec.java
  cdap-securestore-ext-cloudkms/src/main/resources/META-INF/services/co.cask.cdap.securestore.spi.SecretManager
  cdap-securestore-ext-cloudkms/src/test/java/co/cask/cdap/securestore/spi/SecretInfoCodecTest.java
  cdap-securestore-spi/pom.xml
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretManager.java
  cdap-securestore-spi/src/main/java/co/cask/cdap/securestore/spi/SecretStore.java
  pom.xml
Labels: 6.0

#10952 Feature/cdap 14601 add preview for distributed mode in app fabric
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewHttpModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data/runtime/preview/PreviewDataModules.java
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 6.0

#10951 CDAP-14751 postgres sql implementation
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlStructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableId.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/nosql/NoSqlStructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/sql/SqlStructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
  pom.xml
Labels: 6.0

#10955 (CDAP-14591) Remove the notification modules
  cdap-notifications-api/pom.xml
  cdap-notifications/pom.xml
  pom.xml
Labels: 6.0

#10960 Feature/cdap 14665 secret manager service
  cdap-api/src/main/java/co/cask/cdap/api/security/store/SecureStore.java
  cdap-app-fabric-tests/src/test/java/co/cask/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/internal/guice/AppFabricTestModule.java
  cdap-app-fabric/src/test/java/co/cask/cdap/security/SecureStoreTest.java
  cdap-common/src/main/java/co/cask/cdap/common/SecureKeyNotFoundException.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-docs/admin-manual/build.sh
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-kms/src/main/java/co/cask/cdap/security/store/KMSSecureStoreService.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ExploreServiceTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/HBaseTableExporter.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-security/pom.xml
  cdap-security/src/main/java/co/cask/cdap/security/guice/SecureStoreModules.java
  cdap-security/src/main/java/co/cask/cdap/security/guice/SecureStoreServerModule.java
  cdap-security/src/main/java/co/cask/cdap/security/store/DefaultSecureStoreService.java
  cdap-security/src/main/java/co/cask/cdap/security/store/DummySecureStoreService.java
  cdap-security/src/main/java/co/cask/cdap/security/store/FileSecureStoreService.java
  cdap-security/src/main/java/co/cask/cdap/security/store/SecureStoreService.java
  cdap-security/src/main/java/co/cask/cdap/security/store/SecureStoreUtils.java
  cdap-security/src/main/java/co/cask/cdap/security/store/secretmanager/DefaultSecretManagerContext.java
  cdap-security/src/main/java/co/cask/cdap/security/store/secretmanager/SecretManagerExtensionLoader.java
  cdap-security/src/main/java/co/cask/cdap/security/store/secretmanager/SecretManagerSecureStoreService.java
  cdap-security/src/test/java/co/cask/cdap/security/authorization/NoOpAuthorizationContextFactory.java
  cdap-security/src/test/java/co/cask/cdap/security/store/FileSecureStoreServiceTest.java
  cdap-security/src/test/java/co/cask/cdap/security/store/secretmanager/MockSecretManager.java
  cdap-security/src/test/java/co/cask/cdap/security/store/secretmanager/MockSecretManagerContext.java
  cdap-security/src/test/java/co/cask/cdap/security/store/secretmanager/SecretManagerSecureStoreServiceTest.java
  cdap-standalone/pom.xml
  cdap-standalone/src/main/java/co/cask/cdap/StandaloneMain.java
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-unit-test/src/main/java/co/cask/cdap/test/TestBase.java
Labels: 6.0

#10963 (CDAP-14777) Enforce slf4j classes always coming from parent classloader
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/provision/ProvisionerExtensionLoader.java
  cdap-common/src/main/java/co/cask/cdap/extension/AbstractExtensionLoader.java
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/co/cask/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-emr/pom.xml
  cdap-runtime-ext-remote-hadoop/pom.xml
  cdap-security/src/main/java/co/cask/cdap/security/store/secretmanager/SecretManagerExtensionLoader.java
Labels: 6.0

#10913 CDAP-14630 make metrics minimum interval configurable
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/co/cask/cdap/data/tools/UpgradeTool.java
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MessagingMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
Labels: 6.0

#10962 CDAP-14665 Add remote secure store
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/co/cask/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-explore/src/main/java/co/cask/cdap/hive/context/ContextManager.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/co/cask/cdap/data/runtime/main/ExploreServiceTwillRunnable.java
  cdap-security/src/main/java/co/cask/cdap/security/guice/SecureStoreClientModule.java
  cdap-security/src/main/java/co/cask/cdap/security/store/SecureStoreHandler.java
  cdap-security/src/main/java/co/cask/cdap/security/store/client/RemoteSecureStore.java
  cdap-security/src/test/java/co/cask/cdap/security/store/SecureStoreTest.java
  cdap-security/src/test/java/co/cask/cdap/security/store/client/RemoteSecureStoreTest.java
Labels: 6.0

#10958 Minor styling modifications to app drawer
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/DrawerFeatureLink.tsx
  cdap-ui/app/cdap/components/NamespaceDropdown/NamespaceDropdown.scss
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
Labels: 6.0, UI

#10971 CDAP-14804 do not emit task level metrics by default
  cdap-app-fabric/src/main/java/co/cask/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
Labels: 6.0

#10977 [CDAP-14778] Fix logic to determine what namespaces to search metadata
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
Labels: 6.0, Bug

#10974 [CDAP-14613] add minimap display in pipeline
  cdap-ui/app/directives/dag-minimap/dag-minimap-ctrl.js
  cdap-ui/app/directives/dag-minimap/dag-minimap-utilities.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.html
  cdap-ui/app/directives/dag-minimap/dag-minimap.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.less
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js
Labels: 6.0, UI

#10979 [CDAP-14753] Add a dataset-based implementation for the Metadata SPI
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/co/cask/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/co/cask/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/dataset/MetadataDataset.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/MetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/metadata/store/NoOpMetadataStore.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/MetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorage.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/MetadataDatasetContext.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/metadata/dataset/SearchHelper.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/dataset/MetadataDatasetTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/data2/metadata/store/DefaultMetadataStoreTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/MetadataStorageTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/metadata/dataset/DatasetMetadataStorageTest.java
Labels: 6.0

#10982 CDAP-14787 Add byte[] type support to the storage SPI
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/SqlStructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredRow.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Field.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/FieldType.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/FieldValidator.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Fields.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/table/field/FieldTest.java
Labels: 6.0

#10988 (CDAP-14822) Fix race condition in AbstractMetricsCollectionService
  cdap-common/src/main/java/co/cask/cdap/common/conf/Constants.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/LocalMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/collect/MessagingMetricsCollectionService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/main/java/co/cask/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/co/cask/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
Labels: 6.0

#10983 [CDAP-14757] Add an Elasticsearch module that allows testing via 'mvn verify'
  cdap-elastic/pom.xml
  cdap-elastic/src/test/java/co/cask/cdap/metadata/elastic/ElasticClientTest.java
  pom.xml
Labels: 6.0

#10996 [CDAP-14757] Skip verify stage if -DskipTests is given
  cdap-elastic/pom.xml
Labels: 6.0, Bug

#10989 CDAP-14807 Add compare-and-swap and increment functions to the storage SPI
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/InvalidFieldException.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/StructuredTableSchema.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/FieldValidator.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/table/field/FieldValidatorTest.java
Labels: 6.0

#10998 CDAP-14808 Add deleteAll to the storage SPI
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/data2/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/StructuredTable.java
  cdap-data-fabric/src/main/java/co/cask/cdap/spi/data/table/field/Range.java
  cdap-data-fabric/src/test/java/co/cask/cdap/spi/data/StructuredTableTest.java
Labels: 6.0

#10986 [CDAP-14715] Add viewport box on minimap
  cdap-ui/app/directives/dag-minimap/dag-minimap-ctrl.js
  cdap-ui/app/directives/dag-minimap/dag-minimap-utilities.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.html
  cdap-ui/app/directives/dag-minimap/dag-minimap.js
  cdap-ui/app/directives/dag-minimap/dag-minimap.less
  cdap-ui/app/directives/dag-plus/my-dag.html
Labels: 6.0, UI
