Repository cdapio/cdap, pull requests merged in 2020-10, with the labels that each got.

#12788 Update preview to use Table components instead of Grid
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
Labels: 6.2, UI, cla: yes

#12785 [CDAP-17246] Fixes js error while importing from hub or adding pipeli…
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js
  cdap-ui/app/directives/node-metrics/node-metrics.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-service.js
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.complexschema.spec.ts
  cdap-ui/cypress/integration/pipeline.contextmenu.spec.ts
  cdap-ui/cypress/integration/pipeline.joiner.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/plugins.validation.spec.ts
Labels: 6.3, UI, cla: yes

#12784 [CDAP-17283] Fixes the name of record type to conform to Avro Schema spec
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaGenerator.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaParser.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
Labels: 6.1, UI, cla: yes

#12797 (CDAP-17323) Skip network checking logic for Existing Dataproc
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
Labels: 6.3, cla: yes

#12799 make DataprocProvisioner accept gcp-dataproc.serviceAccount property from cdap-site.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12798 (CDAP-17323) Skip network checking logic for Existing Dataproc
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
Labels: 6.2, cherry-pick, cla: yes

#12801 make DataprocProvisioner accept gcp-dataproc.serviceAccount property from cdap-site.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12800 make DataprocProvisioner accept gcp-dataproc.serviceAccount property from cdap-site.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12795 [CDAP-17299] Add metrics for pipeline and preview run time
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewDataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramRunners.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryHelper.java
Labels: 6.3, cla: yes

#12623 [CDAP-16937] Correctly fixes the merge conflict between full page modal resize + fixing footer for post run actions
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.3, UI, cherry-pick, cla: yes

#12805 Disable yarn app retries to avoid misleading error messages to the user.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.3, cla: yes

#12792 Use Table components instead of Grid in preview table
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12793 Use Table components instead of Grid in preview table
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
Labels: 6.1, UI, cherry-pick, cla: yes

#12803 (CDAP-17332) Enabling writing bytes read/written metrics in Spark
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BasicInputFormatProvider.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BasicOutputFormatProvider.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/DelegatingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/DelegatingOutputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatProvider.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/AbstractSparkCounter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/InputFormatProviderTypeAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingInputFormat.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingOutputCommitter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingOutputFormat.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingRecordReader.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingRecordWriter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingTaskAttemptContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBytesReadCounter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBytesWrittenCounter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBytesReadCounter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBytesWrittenCounter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
Labels: 6.3, cla: yes

#12811 Revert "Update preview to use Table components instead of Grid"
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
Labels: 6.2, UI, cla: yes

#12812 [CDAP-16850] Adds errors handling for input schema + Fixes input schema title
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/FieldsList/FieldRow.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-input-schema.html
Labels: 6.3, UI, cherry-pick, cla: yes

#12815 (CDAP-17333) Makes calls from the program context resilient against service outage
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/DefaultAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteMetadataReader.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
Labels: 6.3, cla: yes

#12817 Dynamic accelerator framework - Annotation for accelerator
  cdap-api/src/main/java/io/cdap/cdap/api/annotation/Requirements.java
  cdap-api/src/main/java/io/cdap/cdap/api/artifact/ApplicationClass.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/Requirements.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/app/inspection/InspectionApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PluginExclusionTest.java
  cdap-ui/pom.xml
  pom.xml
Labels: cla: yes

#12787 CDAP-17298 Upgrade Material-ui
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/FieldWrapper/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/index.tsx
  cdap-ui/app/cdap/components/AppHeader/HubButton.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/types.ts
  cdap-ui/app/cdap/components/Ingestion/PluginList/index.tsx
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/ProfileCustomizeContent.scss
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/index.js
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupPage/GroupPanel/WidgetCollection/WidgetAttributesPanel/WidgetAttributeInput/SingleAttributeInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/FilterPage/FilterPanel/FilterShowlistInput/ShowPropertyRow/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/FilterPage/FilterPanel/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/FilterPage/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/ImplicitSchemaDefiner/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/PluginInput/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/RefreshableSchemaEditor.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/Navigator.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/PluginInfo.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/ActionButton/index.tsx
  cdap-ui/app/cdap/components/SecureKeys/SecureKeyList/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/cypress/integration/pluginjsoncreator.spec.ts
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.3, UI, cla: yes, dependencies

#12821 Added cloud build for unit-tests
  cloudbuild.sh
  cloudbuild.yaml
Labels: cla: yes

#12818 (CDAP-17333) Makes calls from the program context resilient against service outage
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/DefaultAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteMetadataReader.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
Labels: 6.2, cla: yes

#12826 (CDAP-17367) Use different config name for tracking and limiting InputFormat
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/DelegatingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatProvider.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingInputFormat.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/io/TrackingInputFormatTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/pom.xml
Labels: 6.3, cla: yes

#12827 [CDAP-16263] Fix log messages with `null` object argument is getting dropped by the logging system
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogMessage.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/LoggingTester.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/file/TestFileLogging.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/tms/TestTMSLogging.java
Labels: cla: yes

#12455 [CDAP-16850] Adds unit tests to Schema Manager used by Schema Editor
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/SchemaManager.tests.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/data/large-schema.json
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/data/schema-10k.json
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/data/simple-schema.json
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/data/simpleSchema.json
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/__tests__/schemas.js
  cdap-ui/app/cdap/components/PluginJSONCreator/__tests__/plugin-json-creator-utilities.test.ts
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.3, UI, cla: yes

#12820 Fixes duplicate schema editor experiment entry
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
Labels: 6.2, UI, cla: yes

#12822 [CDAP-17288] Added Path rewrite for temporary Checkpoint file.
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeUtils.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkContainerClassLoader.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkRunnerClassLoader.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/classloader/SparkRunnerClassLoaderTest.java
Labels: cla: yes

#12825 CDAP-17339 Added Metrics api to accept additional tags in the metric context from program.
  cdap-api/src/main/java/io/cdap/cdap/api/metrics/Metrics.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/metrics/ProgramUserMetrics.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/metrics/WorkflowMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/NoopMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/MockMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockStageMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/NoopMetrics.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsHandlerTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkUserMetrics.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: 6.3, cla: yes

#12806 [CDAP-17335] Add Schema editor e2e tests
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/FieldWrapper/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/FieldsList/FieldRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/FieldsList/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/AddRowButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/Nullable.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/RemoveRowButton.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/DirectivesTab/DirectivesTabRow.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/index.js
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/cypress/fixtures/plugin-schema/error-schema.json
  cdap-ui/cypress/fixtures/plugin-schema/simple-schema.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.canvas.actions.spec.ts
  cdap-ui/cypress/integration/pipeline.complexschema.spec.ts
  cdap-ui/cypress/integration/pipeline.contextmenu.spec.ts
  cdap-ui/cypress/integration/pipeline.joiner.spec.ts
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/integration/pipeline.plugin.missing.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
  cdap-ui/cypress/integration/plugin.schemaeditor.spec.ts
  cdap-ui/cypress/integration/plugins.validation.spec.ts
  cdap-ui/cypress/integration/widgets.CSVWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueDropdownWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueWidget.spec.ts
  cdap-ui/cypress/snapshots/base/plugin.schemaeditor.spec.ts/error_highlighted_output_schema-base.png
Labels: 6.3, UI, cla: yes

#12832 (CDAP-17287) Fixed a bug in the event upload that it will hang for 30 seconds
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeUtils.java
Labels: 6.3, cla: yes

#12830 (CDAP-17276) Save accelerator annotation as system metadata
  cdap-api/src/main/java/io/cdap/cdap/api/artifact/ApplicationClass.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/Requirements.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/AppWithWorkflow.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/pipeline/ProgramGenerationStageTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/system/AppSystemMetadataWriter.java
Labels: cla: yes
