Repository cdapio/cdap, pull requests merged in 2020-11, with the labels that each got.

#12834 remove duplicate objectQuery imports
  cdap-ui/app/cdap/services/WindowManager/index.ts
Labels: 6.3, Bug, UI, cla: yes

#12833 (CDAP-17276) Remove fully qualified name from javadoc
  cdap-api/src/main/java/io/cdap/cdap/api/artifact/ApplicationClass.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
Labels: cla: yes

#12836 [CDAP-16810] Replication block proceeding from assessment if there's issue
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
Labels: 6.3, UI, cla: yes

#12824 [CDAP-17357] Replication add ability to drop table from assessment
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/server/config/themes/default.json
Labels: 6.3, UI, cla: yes

#12828 [CDAP-17368] Upgrade Jest and replace React Testing Library
  cdap-ui/app/cdap/components/If/__tests__/If.test.tsx
  cdap-ui/jest.config.js
  cdap-ui/jest/custom-queries.js
  cdap-ui/jest/jest.setup.js
  cdap-ui/jest/test-utils.ts
  cdap-ui/package.json
  cdap-ui/tsconfig.json
  cdap-ui/yarn.lock
Labels: 6.3, UI, cla: yes

#12835 [CDAP-17358] Replication use stricter typings for states
  cdap-ui/app/cdap/components/Replicator/ConfigDisplay/PluginConfigDisplay/index.tsx
  cdap-ui/app/cdap/components/Replicator/ConfigDisplay/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Documentation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/TableMultiRow/TableRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/TableList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/types.ts
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.3, UI, cla: yes

#12837 [CDAP-17366] Replication add ability to ignore warnings for partially supported column
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/types.ts
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.3, UI, cla: yes

#12796 Add pipeline count metric
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: 6.3, cla: yes

#12829 [CDAP-17295] Fixes selection and replacing text in code editor in UI
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
  cdap-ui/cypress/integration/widget.codeeditor.spec.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.3, UI, cla: yes

#12839 [CDAP-17388] Add asia-northeast3 region to Dataproc Provisioner
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
Labels: Bug, cla: yes

#12841 [CDAP-17279] Fixes multiple select to look similar to select in plugin properties
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
Labels: 6.2, UI, cla: yes

#12840 [CDAP-16539] Honor empty values set by user for plugin properties not to be overwritten by defaults set in widget json
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
Labels: 6.2, UI, cla: yes

#12857 CDAP-15652 Log additional information when launching the Dataproc cluster.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
Labels: cla: yes

#12856 (CDAP-17404) Disable spark event logs upload in preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
Labels: cla: yes

#12850 [CDAP-17399] Fix importing pipelines from 6.2.x to 6.1.x.
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
Labels: 6.1, UI, cla: yes

#12808 [CDAP-17336] Fixes schema editor to handle disabled schema in studio
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
Labels: 6.2, UI, cla: yes

#12813 [CDAP-17343] Added integration tests for pipeline config, scheduling, and properties
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/index.tsx
  cdap-ui/app/cdap/components/PipelineScheduler/AdvancedView.js
  cdap-ui/app/cdap/components/PipelineScheduler/ViewSwitch.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/cypress/integration/pipeline.studio.config.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.scheduling.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
Labels: 6.3, UI, cla: yes

#12843 [CDAP-16973] Add : before column name for drop directive
  cdap-ui/app/cdap/components/DataPrep/Directives/DropColumn/index.js
Labels: 6.3, UI, cla: yes

#12852 [CDAP-12925] Fixes running preview for realtime pipelines to max at 15 mins
  cdap-ui/app/directives/widget-container/widget-number/widget-number.html
Labels: 6.3, UI, cla: yes

#12851 [CDAP-17342] Fixes link in logs graph popover in pipeline summary to navigate to right log viewer page
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
Labels: 6.3, UI, cla: yes

#12845 [CDAP-17279] Fixes multiple select to look similar to select in plugi…
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
Labels: 6.3, UI, cla: yes

#12854 [CDAP-11010] Fixes saving name of the pipeline to save the pipeline as draft
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/services/create/actions/config-actions.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
Labels: 6.3, UI, cla: yes

#12859 [CDAP-17336] Fixes schema editor to handle disabled schema in studio
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
Labels: 6.3, UI, cherry-pick, cla: yes

#12860 [CDAP-17336] Fixes schema editor to handle disabled schema in studio
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
Labels: 6.1, UI, cherry-pick, cla: yes

#12846 [CDAP-16539] Honor empty values set by user for plugin properties not to be overwritten by defaults set in widget json
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
Labels: 6.3, UI, cla: yes

#12838 [CDAP-15190] Fix database table count when filtered
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
Labels: 6.3, UI, cla: yes

#12858 Fix NPE in adding accelerator tag
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ApplicationClassCodec.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ApplicationClassCodecTest.java
  cdap-app-fabric/src/test/resources/ApplicationClass_6_2.json
  cdap-app-fabric/src/test/resources/ApplicationClass_6_3.json
Labels: cla: yes

#12862 Rename accelerators to capabilities
  cdap-api/src/main/java/io/cdap/cdap/api/annotation/Requirements.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/Requirements.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppStep.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/AppWithWorkflow.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/pipeline/SystemMetadataWriterStageTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ApplicationClassCodecTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/app/inspection/InspectionApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PluginExclusionTest.java
  cdap-app-fabric/src/test/resources/ApplicationClass_6_3.json
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/system/AppSystemMetadataWriter.java
Labels: cla: yes

#12849 [CDAP-16566] Fix error collector in UI to show right input schema when connected to source
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/hydrator/controllers/create/canvas-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/controllers/detail/canvas-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.2, UI, cla: yes

#12865 (CDAP-17415) Speedup job launching by uploading files in parallel
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
Labels: 6.3, cla: yes

#12871 Revert "Use Table components instead of Grid in preview table"
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
Labels: 6.3, UI, cla: yes
