Repository cdapio/cdap, pull requests merged in 2020-03, with the labels that each got.

#11904 CDAP-15579 support fll for spark plugins
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/batch/SparkCompute.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/AbstractSparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/plugin/WrappedSparkCompute.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/plugin/WrappedSparkSink.java
Labels: 6.2, cla: yes

#11832 [CDAP-16208] Add generic widgets to storybook
  cdap-ui/.storybook/config.js
  cdap-ui/.storybook/preview-head.html
  cdap-ui/.storybook/stories.global.scss
  cdap-ui/app/cdap/components/AbstractWidget/CodeEditorWidgets.stories.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DateRangeWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/JoinWidgets.stories.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Widgets.stories.tsx
Labels: 6.2, UI, cla: yes

#11913 Code cleanup: rename xxxLogHandler to xxxLogHttpHandler to be consistent with other handler class
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/preview/PreviewHttpHandler.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/log/LogHandlerTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/AbstractLogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/guice/LogQueryServerModule.java
Labels: cla: yes

#11839 [CDAP-14284] Adds Condition & Splitter node types.
  cdap-ui/app/cdap/components/DAG/DAGProvider.tsx
  cdap-ui/app/cdap/components/DAG/DAGRenderer.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/AbstractNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/ConditionNode/conditionNode.scss
  cdap-ui/app/cdap/components/DAG/Nodes/ConditionNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/SplitterNode/PortPopover.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/SplitterNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/TransformNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/utilities.ts
  cdap-ui/app/cdap/components/DAG/index.tsx
Labels: 6.2, UI, cla: yes

#11906 [CDAP-16357] Fix upgrade to jexl library for Dynamic Plugin Filters in UI
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/__tests__/DynamicPluginFilters.test.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
Labels: 6.2, Bug, UI, cla: yes

#11907 [CDAP-16357] Fix hiding entire group with Dynamic Plugin Filter
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/__tests__/DynamicPluginFilters.test.ts
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
Labels: 6.1, Bug, UI, cla: yes

#11910 [CDAP-16338] Moves the polling logic to client 6.1
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/package.json
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/yarn.lock
Labels: 6.1, Bug, UI, cla: yes

#11912 [CDAP-16359] Integrate with nextruntime batch API from backend for pipelines
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/types.ts
  cdap-ui/graphql/helpers/BatchEndpoints/nextRuntime.js
  cdap-ui/graphql/helpers/createLoaders.js
  cdap-ui/graphql/schema/pipelineRecordSchema.graphql
  cdap-ui/graphql/types/PipelineRecord/nextRuntimeResolver.js
  cdap-ui/graphql/types/PipelineRecord/resolvers.js
Labels: 6.2, UI, cla: yes

#11918 (CDAP-16211) Updated AppRequest to add configuration field
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/AppRequest.java
Labels: cla: yes

#11920 CDAP-16356 improve the field lineage compute algorithms
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: 6.2, cla: yes

#11903 Add client to fetch Application/Schedule/Preferences details
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/PreferencesFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemotePreferencesFetcherInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteScheduleFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ScheduleFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/AppWithSchedule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/RemotePreferencesFetcherInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/RemoteScheduleFetcherTest.java
Labels: 6.2, cla: yes

#11921 CDAP-16356 improve the field lineage compute algorithms
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#11923 fix UI linting issue
  cdap-ui/app/cdap/components/Cloud/Profiles/Preview/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/Backpressure.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/EngineRadioInput.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/NumExecutors.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ClientResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/DriverResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsPairs.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/BasicView/Summary.js
  cdap-ui/app/cdap/components/PipelineScheduler/ViewContainer.js
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggerRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/ScheduleRuntimeArgsStore.js
  cdap-ui/app/cdap/components/PipelineTriggers/ScheduleRuntimeArgs/index.js
Labels: 6.2, Bug, UI, cla: yes

#11919 [CDAP-16368] Check for duplicate dataset names in operations modal
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
Labels: 6.2, Bug, UI, cla: yes

#11924 [CDAP-16335][CDAP-16273] Fix popovers in wrangler
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/WorkspaceTabs.scss
  cdap-ui/app/cdap/components/DataPrep/WorkspaceTabs/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/ConnectionPopover/index.js
  cdap-ui/app/cdap/components/UncontrolledComponents/Popover.js
Labels: 6.2, Bug, UI, cla: yes

#11914 Add local/remote program run record fetcher for LogHttpHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/preview/PreviewHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/LocalDatasetDeleterRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConstraintContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/LastRunConstraint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/trigger/TriggerInfoContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/WorkflowTable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/reporting/ProgramHeartbeatService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/reporting/ProgramHeartbeatTable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/security/impersonation/DefaultUGIProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/SleepingWorkflowApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/guice/AppFabricTestModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/reporting/ProgramHeartBeatTableTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/log/LogHttpHandlerTest.java
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MetricsTwillRunnable.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/AbstractLogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LocalProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/ProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/RemoteProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/AppMetadataStore.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/ProgramStore.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/guice/LogQueryRuntimeModule.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/guice/LogQueryServerModule.java
Labels: 6.2, cla: yes

#11915 [CDAP-16359] Integrate with nextruntime batch API from backend for pipelines
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/NextRun/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/types.ts
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/graphql/helpers/BatchEndpoints/nextRuntime.js
  cdap-ui/graphql/helpers/createLoaders.js
  cdap-ui/graphql/schema/pipelineRecordSchema.graphql
  cdap-ui/graphql/types/PipelineRecord/nextRuntimeResolver.js
  cdap-ui/graphql/types/PipelineRecord/resolvers.js
Labels: 6.1, UI, cla: yes

#11926 CDAP-15579 support fll for spark plugins
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/batch/SparkCompute.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/plugin/WrappedSparkCompute.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/plugin/WrappedSparkSink.java
Labels: 6.1, cla: yes

#11930 CDAP-16392 fix joiner fll
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/lineage/LineageOperationsProcessor.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/LineageOperationProcessorTest.java
Labels: 6.2, cla: yes

#11927 Adding RuntimeJobManager SPI to launch and manage runtime jobs.
  cdap-runtime-spi/pom.xml
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Provisioner.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJob.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobDetail.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobEnvironment.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobId.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobStatus.java
Labels: 6.2, cla: yes

#11928 CDAP-16390 fix fll cycle
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: 6.2, cla: yes

#11934 fix a fll compute bug due to algorithm change
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#11935 CDAP-16394 fix fll direction response
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/LineageHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetadataTestBase.java
  cdap-client/src/main/java/io/cdap/cdap/client/LineageClient.java
Labels: cla: yes

#11895 Added "Map to Target" directive stub to column actions dropdown.
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/index.js
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, UI, cla: yes

#11887 [CDAP-16249] Show/hide unrelated fields in cause/impact datasets
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllExpandableField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/cypress/fixtures/fll_wrangler-test-pipeline.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.2, UI, cla: yes

#11925 CDAP-16386 fix merged operations fll
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/lineage/LineageOperationsProcessor.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/LineageOperationProcessorTest.java
Labels: 6.2, cla: yes

#11937 (CDAP-16243) Added upgrade mechanism System Apps managed by SystemAppManagementService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/sysapp/SystemAppManagementServiceTest.java
Labels: 6.2, cla: yes

#11922 [CDAP-16382] add a way for cdap-site to overwrite UI theme files
  cdap-ui/server/uiThemeWrapper.js
Labels: 6.2, UI, cla: yes

#11841 Update release-notes.rst
  cdap-docs/reference-manual/source/release-notes.rst
Labels: cla: yes

#11938 Feature release/cdap cherry pick fll improvement
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/LineageOperationsProcessor.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/LineageOperationProcessorTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/LineageHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetadataTestBase.java
  cdap-client/src/main/java/io/cdap/cdap/client/LineageClient.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#11942 Revert "Merge pull request #11937 from cdapio/feature/CDAP-16243-syst…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/sysapp/SystemAppManagementServiceTest.java
Labels: cla: yes

#11931 [CDAP-16387] Add Icons and Docs viewer for replicator
  cdap-ui/app/cdap/api/replicator.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/Documentation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SourceConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/TargetList/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/PluginCard/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
Labels: 6.2, UI, cla: yes

#11933 [CDAP-16385] Add JDBC selector widget
  cdap-docs/developer-manual/source/pipelines/developing-plugins/presentation-plugins.rst
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.2, UI, cla: yes

#11932 [CDAP-16393] Replicator add config buttons and bugfixes
  cdap-ui/app/cdap/components/ActionsPopover/ActionsPopover.scss
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/FeatureHeading.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Actions/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/StatusIndicator/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Drafts/index.tsx
  cdap-ui/app/cdap/components/Replicator/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#11944 (CDAP-16243) Upgrade mechanism for System Apps managed by SystemAppManagementService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/bootstrap/BootstrapServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/sysapp/SystemAppManagementServiceTest.java
Labels: 6.2, cla: yes

#11939 [CDAP-15633] Add default implementation for RuntimeJob
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractListener.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: 6.2, cla: yes

#11945 [CDAP-15633] Add main class that will run on Dataproc driver
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
Labels: 6.2, cla: yes

#11825 [CDAP-16210] Support multiple hubs in UI
  cdap-ui/.storybook/preview-head.html
  cdap-ui/app/cdap/api/market.js
  cdap-ui/app/cdap/components/CaskWizards/LicenseStep/index.js
  cdap-ui/app/cdap/components/CaskWizards/MarketArtifactUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/MarketHydratorPluginUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
  cdap-ui/app/cdap/components/ConfigurableTab/index.js
  cdap-ui/app/cdap/components/Market/AllTab/index.js
  cdap-ui/app/cdap/components/Market/action/market-action.js
  cdap-ui/app/cdap/components/Market/index.js
  cdap-ui/app/cdap/components/Market/store/market-store.js
  cdap-ui/app/cdap/components/MarketEntityModal/index.js
  cdap-ui/app/cdap/components/MarketPlaceEntity/index.js
  cdap-ui/app/cdap/components/MarketPlaceUsecaseEntity/index.js
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
  cdap-ui/app/cdap/services/WizardStores/PublishPipeline/ActionCreator.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/express.js
  cdap-ui/server/url-helper.js
Labels: 6.2, UI, cla: yes

#11949 Set Delta Replicator to be hidden by default
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/server/config/themes/default.json
Labels: 6.2, UI, cla: yes

#11952 [CDAP-16417] Replicator add docs to target config page
  cdap-ui/app/cdap/components/Replicator/Create/Content/Documentation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SourceConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/index.tsx
  cdap-ui/app/cdap/components/SelectionBox/index.tsx
Labels: 6.2, UI, cla: yes

#11947 [CDAP-16404] Replicator add compute profile selector
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/server/express.js
Labels: 6.2, UI, cla: yes

#11953 [CDAP-16412] fixing leftover error and refactoring
  cdap-ui/app/cdap/services/NamespaceStore/index.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/services/helpers.js
  cdap-ui/app/tracker/routes.js
Labels: 6.2, Bug, UI, cla: yes

#11955 CDAP-16399 protect test against outside data
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetadataHttpHandlerTestRun.java
Labels: cla: yes

#11956 Shutdown SystemAppManagement when BootstrapService is shutting down
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
Labels: 6.2, cla: yes

#11954 [CDAP-16330] Added rawProperties field to PluginConfig and setting in…
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: cla: yes

#11957 CDAP-16431 write empty fll instead of NPE
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/lineage/FieldLineageProcessor.java
Labels: cla: yes

#11960 CDAP-16432 log level fix for programs other than mapreduce
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
Labels: cla: yes

#11959 [CDAP-16406] Fix creating System profile from UI
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/services/NamespaceStore/index.ts
Labels: 6.2, Bug, UI, cla: yes

#11965 (CDAP-16369) Use twill to launch job on remote Hadoop cluster
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ImpersonatedTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/MapReduceTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMainTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJobTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
  cdap-distributions/src/etc/cdap/conf.dist/logback.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJob.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
  cdap-standalone/src/main/resources/logback-container.xml
  cdap-standalone/src/main/resources/logback.xml
Labels: 6.2, cla: yes

#11860 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  cdap-app-templates/cdap-program-report/pom.xml
Labels: cla: yes

#11750 Removes duplicated ETL explanation
  cdap-docs/reference-manual/source/glossary.rst
Labels: cla: yes

#11967 [CDAP-15894] Navigate to cause/impact lineage from table header
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllTableHeader.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: Bug, UI, cla: yes

#11968 add missing default property to cdap-defaults.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
Labels: cla: yes

#11958 Fixing failing E2E UI tests
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
Labels: 6.2, Bug, UI, cla: yes

#11969 [CDAP-15894] Navigate to cause/impact lineage from table header
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllMenu/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllTableHeader.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cla: yes

#11971 [CDAP-16366] Fix universal-cookie usage and importing sessionToken
  cdap-ui/app/cdap/main.js
  cdap-ui/graphql/graphql.js
Labels: 6.2, Bug, UI, cla: yes

#11936 [CDAP-16278] Modifies selection to be default in pipeline studio
  cdap-ui/app/cdap/components/ContextMenu/index.tsx
  cdap-ui/app/cdap/components/PipelineContextMenu/index.tsx
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/support/commands.ts
Labels: 6.2, UI, cla: yes

#11970 [CDAP-16445] Refactor parent artifact and hide sensitive fields
  cdap-ui/app/cdap/api/replicator.js
  cdap-ui/app/cdap/components/Replicator/ConfigDisplay/PluginConfigDisplay/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/TargetList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.2, UI, cla: yes

#11961 [CDAP-15633] Adding dataproc runtime manager implementation
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocClusterInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/ProgramRunInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeLocalFile.java
Labels: 6.2, cla: yes

#11980 [CDAP-16448] Fix download logs in secure mode (for release/6.1)
  cdap-ui/server/express.js
Labels: 6.1, Bug, UI, cla: yes

#11979 [CDAP-16448] fix download logs in secure mode
  cdap-ui/server/express.js
Labels: 6.2, Bug, UI, cla: yes

#11973 Feature release/cdap cherry pick fll
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DatasetFieldLineageSummary.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FakeFieldLineageReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FieldLineageAdminTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: 6.1, cla: yes

#11974 Cherry-pick field level lineage changes for unrelated fields
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllHeader/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllExpandableField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/FllField.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/LineageSummary/index.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValuePair.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/cypress/fixtures/fll_wrangler-test-pipeline.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
Labels: 6.1, Bug, UI, cla: yes

#11978 (CDAP-16353) Refactoring: rename toArtifactId() to apiToProtoArtifactId
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/program/ProgramDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/Artifacts.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
Labels: cla: yes

#11976 [CDAP-16330] Added rawProperties field to PluginConfig and setting in ConfigFieldSetter
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: cla: yes

#11983 [CDAP-16384] Improve handling of 404 when last completed preview is missing
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
Labels: 6.1, Bug, UI, cla: yes

#11985 [CDAP-16384] Add missing argument to startClientPoll and improve error msg on 404 in Preview
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
Labels: 6.2, Bug, UI, cla: yes

#11986 CDAP-16454 add sleep time to waitForRuns method
  cdap-test/src/main/java/io/cdap/cdap/test/AbstractProgramManager.java
  cdap-test/src/main/java/io/cdap/cdap/test/ProgramManager.java
Labels: cla: yes

#11987 [CDAP-16451][CDAP-16457] Fix Configurable tab js error in UI
  cdap-ui/app/cdap/components/ConfigurableTab/index.js
  cdap-ui/server/url-helper.js
Labels: 6.2, Bug, UI, cla: yes

#11990 (CDAP-16211) Updated AppRequest class to work with configuration field
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/AppRequest.java
Labels: cla: yes

#11989 (CDAP-16353) Fix the incorrect comment on how preferences get resolved.
  cdap-app-fabric/src/main/java/io/cdap/cdap/config/PreferencesTable.java
Labels: cla: yes

#11981 Data Ingestion feature preview
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/Home/HomeActions/ActionCard.tsx
  cdap-ui/app/cdap/components/Home/HomeActions/ActionConfig.ts
  cdap-ui/app/cdap/components/Home/HomeActions/index.tsx
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Ingestion/PluginList/index.tsx
  cdap-ui/app/cdap/components/Ingestion/PluginWidgetRenderer/index.tsx
  cdap-ui/app/cdap/components/Ingestion/PluginsTableView/index.tsx
  cdap-ui/app/cdap/components/Ingestion/SinkList/index.tsx
  cdap-ui/app/cdap/components/Ingestion/SourceSinkConfigurator/index.tsx
  cdap-ui/app/cdap/components/Ingestion/helpers.ts
  cdap-ui/app/cdap/components/Ingestion/index.tsx
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, UI, cla: yes

#11950 [CDAP-16413] Fixes e2e tests after changing the polling logic for inactive tabs
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsPairsMaterial.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.contextmenu.spec.ts
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/server/config/parser.js
Labels: 6.2, Bug, UI, cla: yes

#11994 [CDAP-16467] Stop dataset overview pane from reloading every 10s
  cdap-ui/app/cdap/components/EntityListView/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
Labels: 6.1, Bug, UI, cla: yes

#11948 Add getInputStages API
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/MultiInputStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/io/cdap/cdap/etl/batch/BatchPhaseSpecTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/SchemaPropagator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/FieldLineageProcessorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/planner/PipelinePlannerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/v2/spec/StageSpecTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/action/MockActionContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockJoiner.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/transform/MockTransformContext.java
Labels: cla: yes

#11996 [CDAP-16467] Stop dataset overview pane reloading every 10s
  cdap-ui/app/cdap/components/EntityListView/index.js
Labels: 6.2, Bug, UI, cla: yes

#11998 [CDAP-16474] fix cursor issue with code editor widgets
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#11982 (CDAP-16353) Refactoring: move artifact http internal endpoints to a separate handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/program/ProgramDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/Artifacts.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PluginExclusionTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterPathLookup.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RouterPathLookupTest.java
Labels: cla: yes

#11999 Provide default implementation for getInputStages
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageContext.java
Labels: 6.2, cla: yes

#11988 (CDAP-16353) Replace ArtifactRepository param with PluginFinder for AbstractConfigurer…
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/InMemoryProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/AbstractConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/customaction/DefaultCustomActionConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/mapreduce/DefaultMapReduceConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultHttpServiceHandlerConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/DefaultSparkConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultWorkerConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowConditionConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowForkConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/WorkflowNodeCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/condition/DefaultConditionConfigurer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/deploy/spark/AbstractExtendedSparkConfigurer.scala
  cdap-spark-core/src/main/scala/io/cdap/cdap/app/deploy/spark/DefaultExtendedSparkConfigurer.scala
  cdap-spark-core2_2.11/src/main/scala/io/cdap/cdap/app/deploy/spark/DefaultExtendedSparkConfigurer.scala
Labels: cla: yes

#12000 (CDAP-16353) Adding an info log entry for twill program termination status
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
Labels: cla: yes

#11984 (CDAP-16353) Introduce ArtifactRepositoryReader interface and implement local and remote versions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/LocalArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/PluginFinderTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerInternalTest.java
  cdap-standalone/src/test/java/io/cdap/cdap/StandaloneTester.java
Labels: cla: yes

#12003 [CDAP-16453] Made LimitingInputFormat configurable so setConf for source plugins will be called even in Preview mode
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
Labels: cla: yes

#12002 [CDAP-16499] Fix macro and description showing up for get schema button
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/WidgetWrapper/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12005 [CDAP-16453] Made LimitingInputFormat configurable so setConf for sou…
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/alert/TMSAlertPublisher.java
Labels: cla: yes

#12004 (CDAP-16353) Move get artifact details for range into ArtifactRepositoryReader
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/LocalArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerTestBase.java
Labels: cla: yes

#12001 (CDAP-16353) Make ProperitesResolver use PreferencesFetcher to get properties
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/PreferencesHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalPreferencesFetcherInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerInternalTest.java
Labels: cla: yes

#12007 {CDAP-16353) Implement LocalScheduleFetcher to get schedule from local store
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleNotFoundException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalScheduleFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ScheduleFetcherTest.java
Labels: cla: yes

#12008 (CDAP-16353) parameterize preference fetcher test to ensure same behavior for local vs remote
  cdap-app-fabric/src/test/java/io/cdap/cdap/config/PreferencesServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/PreferencesFetcherInternalTest.java
Labels: cla: yes

#12010 {CDAP-16353) Implement LocalApplicationDetailFetcher to get ApplicationDetail
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ApplicationDetailFetcherTest.java
Labels: cla: yes

#12012 (CDAP-16353) Cleanup: remove MetadataServiceModule from AppFabricServiceRuntimeModule
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
Labels: cla: yes

#12013 (CDAP-16107) Added support for Spark 2.4
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
  cdap-spark-core/src/main/scala/io/cdap/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
  cdap-spark-core2_2.11/src/main/scala/io/cdap/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
Labels: 6.2, cla: yes

#12014 (CDAP-16509) Improve StructuredRecord memory footprint
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/LRUCache.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-api-common/src/test/java/io/cdap/cdap/api/data/format/LRUCacheTest.java
Labels: 6.2, cla: yes

#12017 (CDAP-16107, CDAP-16509) Cherry pick
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/LRUCache.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-api-common/src/test/java/io/cdap/cdap/api/data/format/LRUCacheTest.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
  cdap-spark-core/src/main/scala/io/cdap/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
  cdap-spark-core2_2.11/src/main/scala/io/cdap/cdap/app/runtime/spark/DefaultSparkExecutionContext.scala
Labels: 6.1, cla: yes

#12018 [CDAP-16493] Fix Joiner dropdown overflow issue
  cdap-ui/app/cdap/components/AbstractWidget/SqlConditionsWidget/Rule.tsx
  cdap-ui/app/cdap/components/OutlinedSelect/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#11995 [CDAP-16458] Fixing integration tests
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/RuntimeArgsModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/services/helpers.js
  cdap-ui/app/tracker/routes.js
  cdap-ui/app/tracker/tracker.html
  cdap-ui/cypress/integration/fieldlevellineage.v2.spec.ts
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/support/constants.ts
Labels: Bug, UI, cla: yes

#12015 [CDAP-16506] Pass correct arguments to renderGridBody
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/FllTable/index.tsx
  cdap-ui/cypress/fixtures/fll_wrangler-test-pipeline.json
  cdap-ui/cypress/helpers.ts
Labels: 6.1, Bug, UI, cla: yes
