Repository cdapio/cdap, pull requests merged in 2020-05, with the labels that each got.

#12136 (CDAP-16616) Make the View Raw Logs and Download All button enable al…
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.html
  cdap-ui/app/directives/log-viewer/log-viewer.html
Labels: 6.1, cla: yes

#12123 (CDAP-16676) Upgrade dataproc API v1->v1beta2 and add option to enable component gateway
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12140 Fix javadoc for MacroFunction
  cdap-api/src/main/java/io/cdap/cdap/api/macro/MacroFunction.java
Labels: 6.3, cla: yes

#12137 (CDAP-16730) Set correct -xmx for pods in k8s to run programs
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: cla: yes

#12118 [CDAP-16663] Properly surface macros in input schema
  cdap-ui/app/cdap/components/ConfirmationModal/index.js
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema-ctrl.js
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema.html
  cdap-ui/app/hydrator/services/hydrator-node-service.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/cypress/integration/pipeline.complexschema.spec.ts
  cdap-ui/cypress/support/commands.ts
Labels: 6.2, Bug, UI, cla: yes

#12119 [CDAP-16663] Properly surface macros in input schema
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema-ctrl.js
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema.html
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.1, Bug, UI, cla: yes

#12142 (CDAP-16730) Set correct -xmx for pods in k8s to run programs
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: cla: yes

#12141 (CDAP-16738) Fix secure macro function call for MR
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/AbstractLogPublisher.java
Labels: 6.2, cla: yes

#12138 (CDAP-16736) Includes record name in Schema comparison
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: 6.2, cla: yes

#12139 (CDAP-16736) Includes record name in Schema comparison
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: 6.1, cla: yes

#12143 Revert "(CDAP-16736) Includes record name in Schema comparison"
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: cla: yes

#12144 Revert "(CDAP-16736) Includes record name in Schema comparison"
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: cla: yes

#12145 (CDAP-16736) Includes record name in Schema comparison
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: 6.2, cla: yes

#12146 (CDAP-16736) Includes record name in Schema comparison
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: 6.1, cla: yes

#12147 (CDAP-16055) Fix logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkRuntimeSecurityManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/AbstractLogPublisher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppenderInitializer.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/kafka/KafkaLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/remote/RemoteLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/tms/TMSLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/framework/local/LocalLogAppender.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/LogAppenderInitializerTest.java
  cdap-watchdog/src/test/resources/test-appender.xml
Labels: 6.2, cla: yes

#12120 [CDAP-16656] Improve performance of schema editor
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/FieldRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/complex-schema/embedded-schema-selector/embedded-schema-selector.html
  cdap-ui/app/directives/complex-schema/embedded-schema-selector/embedded-schema-selector.js
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema.html
Labels: 6.2, Bug, UI, cla: yes

#12149 (CDAP-16055) Cherry-pick for 6.1 - fix spark logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/distributed/DistributedMapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkRuntimeSecurityManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/AbstractLogPublisher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppenderInitializer.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/kafka/KafkaLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/remote/RemoteLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/tms/TMSLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/framework/local/LocalLogAppender.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/LogAppenderInitializerTest.java
  cdap-watchdog/src/test/resources/test-appender.xml
Labels: 6.1, cla: yes

#12130 [CDAP-16696] Fixes Preview UI to handle INIT status of preview
  cdap-ui/app/cdap/services/PreviewStatus.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.2, Bug, UI, cla: yes

#12153 CDAP-16744 bump memory for unit test
  pom.xml
Labels: cla: yes

#12150 [CDAP-16749] Fix selecting connections in pipeline studio
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.2, Bug, UI, cla: yes

#12154 CDAP-16744 bump memory for unit test
  pom.xml
Labels: cla: yes

#12127 [CDAP-16634] Replicator assessment improvements
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/ConnectivityAssessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/FeaturesAssessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/NoIssuesTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/WithIssuesTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/tableStyles.ts
Labels: 6.2, UI, cla: yes

#12135 [CDAP-16660] Replicator select tables and columns improvements
  cdap-ui/app/cdap/components/Replicator/Create/Content/SearchBox/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.2, UI, cla: yes

#12155 CDAP-16725 Copied SparkApplication.scala to CDAP repository.
  cdap-spark-core2_2.11/src/main/scala/org/apache/spark/deploy/SparkApplication.scala
Labels: cla: yes

#12157 CDAP-16725 Copied SparkApplication.scala to CDAP repo so that spark c…
  cdap-spark-core2_2.11/src/main/scala/org/apache/spark/deploy/SparkApplication.scala
Labels: cla: yes

#12152 [CDAP-16751] Fix schema editor to properly check for logical type precision and scale values
  cdap-ui/app/cdap/services/cdapavscwrapper/DecimalLogicalType.ts
Labels: 6.2, Bug, UI, cla: yes

#12158 [CDAP-16453] Using setConf for delegateFormat in getSplits so delegateFormat.setConf will be called in all cases
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
Labels: cla: yes

#12133 [CDAP-16681] Fixes UI to remove any references to App detailed view page
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.js
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.scss
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/PropertiesTab.js
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/index.js
  cdap-ui/app/cdap/components/CaskWizards/ApplicationUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/LibraryUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/MarketHydratorPluginUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/DirectiveUploadWizard.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/PluginUploadWizard.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipelineUsecase/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Overview/AppOverview/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsDetailsActions.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/index.js
  cdap-ui/app/cdap/components/Wizard/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, Bug, UI, cla: yes

#12161 [CDAP-16453] Using setConf for delegateFormat in getSplits so delegateFormat.setConf will be called in all cases
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
Labels: 6.1, cla: yes

#12162 [CDAP-16453] Using setConf for delegateFormat in getSplits so delegateFormat.setConf will be called in all cases
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
Labels: 6.2, cla: yes

#12156 [CDAP-16642] Replicator assessment mapping restyle
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/Supported.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
Labels: 6.2, UI, cla: yes

#12163 [CDAP-16765] Fix wrangler switching connections throwing js error
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12160 [CDAP-16695] Replicator product rename
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/Home/HomeActions/ActionConfig.ts
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Actions/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Drafts/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/index.tsx
  cdap-ui/app/cdap/components/Replicator/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, UI, cla: yes

#12164 (CDAP-16673) Handle large TMS publish request
  cdap-common/src/main/java/io/cdap/cdap/common/http/CombineInputStream.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/SpillableBodyConsumer.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/FileSeekableInputStream.java
  cdap-common/src/test/java/io/cdap/cdap/common/http/CombineInputStreamTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/http/SpillableBodyConsumerTest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/StoreHandler.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: 6.3, cla: yes

#12166 [CDAP-16785] Update archetype pom
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
Labels: 6.3, cla: yes

#12151 Add X-Requested-With header to all xhr requests made from UI
  cdap-ui/app/cdap/components/AppHeader/AccessTokenModal/index.tsx
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/SessionTokenStore.ts
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/WindowManager/Heartbeat-web-worker.js
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/upload-file.js
  cdap-ui/app/cdap/styles/img/heartbeat.png
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/services/file-uploader.js
  cdap-ui/app/tracker/main.js
  cdap-ui/server/express.js
  cdap-ui/webpack.config.cdap.js
Labels: 6.2, UI, cla: yes

#12167 [CDAP-16786] Fix spotlight search modal to link to pipelines correctly
  cdap-ui/app/cdap/components/NavLinkWrapper/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
Labels: 6.2, Bug, UI, cla: yes

#12170 (CDAP-16673) TMS compression cherry-pick for release/6.1
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CombineInputStream.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/SpillableBodyConsumer.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/FileSeekableInputStream.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/io/cdap/cdap/common/http/CombineInputStreamTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/http/SpillableBodyConsumerTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMainTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/UserProgramServiceMainTest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/MessagingHttpService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/StoreHandler.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: 6.1, cla: yes

#12172 CDAP-16799 Fixed a bug where if no data to read preview fails with divided by zero ArithmeticException.
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
Labels: cla: yes

#12173 CDAP-16799 Fixed a bug where if no data to read preview fails with di…
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
Labels: cla: yes

#12177 CDAP-16816 fix schedule properties to override preferences
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunnerTest.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/service/hive/BaseHiveExploreService.java
Labels: 6.2, cla: yes

#12178 CDAP-16816 fix schedule properties to override preferences
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/service/hive/BaseHiveExploreService.java
Labels: cla: yes

#12175 [CDAP-16813] Fix including schema in table info when reopening draft
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/TableMultiRow/TableRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Metrics/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12179 [UI] Fixes the backend/Nodejs down message
  cdap-ui/app/cdap/components/LoadingIndicator/LoadingIndicator.scss
  cdap-ui/app/cdap/components/LoadingIndicator/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/tracker/main.js
Labels: 6.2, Bug, UI, cla: yes

#12180 [CDAP-16826] fix showing page level error when system services are down
  cdap-ui/app/cdap/components/AppHeader/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12176 Fix complex schema e2e test
  cdap-ui/cypress/integration/pipeline.complexschema.spec.ts
Labels: 6.3, Bug, UI, cla: yes

#12113 [CDAP-16621] Remove export modal when exporting pipeline JSON
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineExportModal/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftActions/index.tsx
  cdap-ui/app/cdap/services/download-file.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/cypress/integration/pipeline.canvas.actions.spec.ts
  cdap-ui/cypress/integration/pipeline.contextmenu.spec.ts
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
  cdap-ui/cypress/integration/widgets.CSVWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueDropdownWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueWidget.spec.ts
  cdap-ui/cypress/support/commands.ts
Labels: 6.3, UI, cla: yes

#12183 Change preview max out message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
Labels: 6.2, cla: yes

#12184 Change preview max out message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
Labels: 6.1, cla: yes

#11972 Completed "Map to Target" directive
  cdap-ui/app/cdap/api/dataprep.js
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/CurrentSelection/index.tsx
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/LoadingBar/index.tsx
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/OptionFilter/index.tsx
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/OptionList/index.tsx
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/MapToTarget/index.tsx
  cdap-ui/app/cdap/components/DataPrep/store/DataPrepActionCreator.js
  cdap-ui/app/cdap/components/DataPrep/store/DataPrepActions.js
  cdap-ui/app/cdap/components/DataPrep/store/index.ts
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.3, UI, cla: yes

#12169 (CDAP-16673) Added TMS payload compression supported
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMainTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/UserProgramServiceMainTest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/MessagingHttpService.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: 6.3, cla: yes

#12185 CDAP-16708 add API for autojoiner
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/batch/BatchAutoJoiner.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/batch/BatchJoiner.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/AutoJoiner.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/AutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/Field.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinConditionException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinKey.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinStage.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidationException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageConfigurer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: 6.1, cla: yes

#12188 merge Release/6.2 to develop
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunnerTest.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/service/hive/BaseHiveExploreService.java
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/LoadingIndicator/LoadingIndicator.scss
  cdap-ui/app/cdap/components/LoadingIndicator/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/TableMultiRow/TableRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Metrics/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/tracker/main.js
Labels: cla: yes

#12198 Minor text change - added space before paranthesis
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12194 [CDAP-16621] Remove export modal when exporting pipeline JSON
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineExportModal/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftActions/index.tsx
  cdap-ui/app/cdap/services/download-file.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/support/commands.ts
Labels: 6.1, UI, cla: yes

#12195 (CDAP-16784) Improve kryo serialization for Schema
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/SchemaSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: 6.3, cla: yes

#12203 CDAP-16708 rename Field to JoinField
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinField.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: cla: yes

#12201 CDAP-16709 batch spark auto-join implementation
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReducePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/AbstractSparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/PairRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: cla: yes

#12212 Release 6.2.0 License Dependencies and Release Notes
  cdap-docs/reference-manual/licenses-pdf/cdap-enterprise-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-level-1-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-sandbox-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-ui-dependencies.pdf
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/tools/licenses/cdap-level-1-dependencies.rst
  cdap-docs/tools/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
Labels: 6.2, cla: yes

#12187 (CDAP-16673) TMS compression
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CombineInputStream.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/SpillableBodyConsumer.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/FileSeekableInputStream.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/io/cdap/cdap/common/http/CombineInputStreamTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/http/SpillableBodyConsumerTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMainTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/UserProgramServiceMainTest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/MessagingHttpService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/StoreHandler.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: 6.2, On-hold, cla: yes

#12190 [CDAP-16656] Improve performance of schema editor
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/FieldRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/complex-schema/embedded-schema-selector/embedded-schema-selector.html
  cdap-ui/app/directives/complex-schema/embedded-schema-selector/embedded-schema-selector.js
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema.html
Labels: 6.1, UI, cherry-pick, cla: yes

#12192 [CDAP-16681][CDAP-16786] Remove reference to app detailed view + fix spotlight search
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.js
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/HistoryTab.scss
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/PropertiesTab.js
  cdap-ui/app/cdap/components/AppDetailedView/Tabs/index.js
  cdap-ui/app/cdap/components/AppDetailedView/index.js
  cdap-ui/app/cdap/components/CaskWizards/AddNamespace/index.js
  cdap-ui/app/cdap/components/CaskWizards/ApplicationUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/ArtifactUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/LibraryUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/MarketHydratorPluginUpload/index.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/DirectiveUploadWizard.js
  cdap-ui/app/cdap/components/CaskWizards/PluginArtifactUpload/PluginUploadWizard.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipelineUsecase/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/NavLinkWrapper/index.js
  cdap-ui/app/cdap/components/Overview/AppOverview/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsDetailsActions.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/index.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/Wizard/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, UI, cherry-pick, cla: yes

#12193 [UI][CDAP-16826] Fixes the backend/Nodejs down message + Fix showing error page when system services are down
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/LoadingIndicator/LoadingIndicator.scss
  cdap-ui/app/cdap/components/LoadingIndicator/index.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/tracker/main.js
Labels: 6.1, UI, cherry-pick, cla: yes

#12191 [CDAP-16617] Expand hub modal to entire page
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 6.1, UI, cherry-pick, cla: yes

#12210 CDAP-16709 implement auto join for mapreduce
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReducePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: cla: yes

#12215 CDAP-16711 implement null safe keys as an option
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12219 update MD5 hash
  cdap-docs/admin-manual/build.sh
  cdap-docs/developer-manual/source/pipelines/developing-plugins/presentation-plugins.rst
  cdap-docs/integrations/build.sh
Labels: 6.2, cla: yes

#12213 CDAP-16709 implement manual broadcasts
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinStage.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12223 fix md5 for docs
  cdap-docs/admin-manual/build.sh
Labels: 6.2, cla: yes

#12220 CDAP-16711 implemented null safe equality in mapreduce
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/Joiner.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
Labels: cla: yes

#12196 [CDAP-16829] Modify default 'No stages' message in joiner dropdown to…
  cdap-ui/app/cdap/components/AbstractWidget/JoinTypeWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlConditionsWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/index.tsx
  cdap-ui/app/directives/widget-container/widget-input-schema/widget-input-schema-ctrl.js
Labels: Bug, UI, cla: yes

#12221 (CDAP-16873) Remove guava dependencies from watchdog-api
  cdap-common/src/main/java/io/cdap/cdap/api/metrics/MetricsCollectionService.java
  cdap-watchdog-api/pom.xml
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricDataQuery.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricSearchQuery.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricTimeSeries.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricValue.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricValues.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/NoopMetricsContext.java
Labels: 6.3, cla: yes

#12227 CDAP-16856 mapreduce impl
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/ReducibleAggregatorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/AggregatorBridge.java
Labels: 6.1, cla: yes

#12228 CDAP-16709 implemented auto-join for spark streaming
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12230 CDAP-16855 aggregator spark streaming
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorAggregateFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorGroupByFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicAggregatorAggregate.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: 6.1, cla: yes

#12222 [CDAP-16835] Add new API in application interface for upgrading application config
  cdap-api/src/main/java/io/cdap/cdap/api/app/Application.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigUpdateAction.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateResult.java
Labels: cla: yes
