Repository cdapio/cdap, pull requests merged in 2020-06, with the labels that each got.

#12231 (CDAP-16841) Includes Dataproc API failure message in log message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
Labels: 6.3, cla: yes

#12235 (CDAP-16841) Includes Dataproc API failure message in log message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
Labels: 6.1, cla: yes

#12236 (CDAP-16841) Includes Dataproc API failure message in log message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
Labels: 6.2, cla: yes

#12238 Merge release 6.2 back to develop
  cdap-docs/admin-manual/build.sh
  cdap-docs/developer-manual/source/pipelines/developing-plugins/presentation-plugins.rst
  cdap-docs/integrations/build.sh
  cdap-docs/reference-manual/licenses-pdf/cdap-enterprise-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-level-1-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-sandbox-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-ui-dependencies.pdf
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/tools/licenses/cdap-level-1-dependencies.rst
  cdap-docs/tools/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
  cdap-ui/app/cdap/components/ConfigurationGroup/KitchenSync.tsx
  cdap-ui/cypress/fixtures/pipeline1.json
  cdap-ui/cypress/fixtures/pipeline_old.json
  cdap-ui/package.json
Labels: cla: yes

#12205 [CDAP-16860] Create Routing & Basic Plugin Information page (plugin JSON)
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/StepButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/WizardGuideline/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/steps.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/index.tsx
Labels: UI, cla: yes

#12242 CDAP-16875 include more detailed information in join exception
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/AutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinConditionException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/SelectedFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
Labels: cla: yes

#12246 CDAP-16875 export join error in hydrator test base
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: 6.3, cla: yes

#12245 CDAP-16875 include more detailed information in join exception
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/AutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinConditionException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/SelectedFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: cla: yes

#12200 [CDAP-16845] Fix preview starting when user clicks No with post-run actions
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.html
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/hydrator.html
  cdap-ui/app/hydrator/templates/create/popovers/run-preview-action-confirmation-modal.html
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.1, UI, cla: yes

#12232 CDAP-16852 handle dynamic schemas in auto join
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/OutputSchemaError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/test/java/io/cdap/cdap/etl/spark/SparkPipelineRunnerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12171 [CDAP-11661][CDAP-16797] Fix post run actions to remove success message + valid user feedback
  cdap-ui/app/cdap/components/PostRunActions/PostRunActions.scss
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-ctrl.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step-ctrl.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.js
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.3, Bug, UI, cla: yes

#12239 (CDAP-16884) Fix SparkDriverService to pause between failure retry
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkDriverService.java
Labels: 6.3, cla: yes

#12087 [CDAP-16607] Expands plugin configuration, plugin templates and post …
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/directives/plugin-templates/plugin-templates.less
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/leftpanel.less
  cdap-ui/app/hydrator/templates/detail/bottom-panel.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover-template.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/app/styles/themes/cdap/theme.less
Labels: 6.3, UI, cla: yes

#12240 [CDAP-16690] Add preview endpoint and factor out preview data fetching logic
  cdap-ui/app/cdap/api/preview.js
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.1, UI, cla: yes

#12255 (CDAP-16669) New Dataproc provisioner for existing cluster
  cdap-master/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/META-INF/services/io.cdap.cdap.runtime.spi.provisioner.Provisioner
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/common/DataprocUtilsTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
Labels: 6.3, cla: yes

#12257 Feature release/cdap 16852 autojoin dynamic schema
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/AutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinConditionException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/InvalidJoinException.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinKeyFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/OutputSchemaError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/SelectedFieldError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/io/cdap/cdap/etl/batch/BatchPhaseSpecTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultAutoJoinerContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/FieldLineageProcessorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/planner/PipelinePlannerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/v2/spec/StageSpecTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/test/java/io/cdap/cdap/etl/spark/SparkPipelineRunnerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: cla: yes

#12252 CDAP-16852 handle dynamic schemas in auto join
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/OutputSchemaError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/io/cdap/cdap/etl/batch/BatchPhaseSpecTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/JoinerBridge.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/FieldLineageProcessorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/planner/PipelinePlannerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/v2/spec/StageSpecTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/test/java/io/cdap/cdap/etl/spark/SparkPipelineRunnerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12259 (CDAP-16884) Fix SparkDriverService to pause between failure retry
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkDriverService.java
Labels: 6.1, cla: yes

#12260 (CDAP-16884) Fix SparkDriverService to pause between failure retry
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkDriverService.java
Labels: 6.2, cla: yes

#12247 [CDAP-16886] add pom profile to run UI unit tests
  cdap-ui/pom.xml
Labels: 6.3, UI, cla: yes

#12225 [CDAP-16876] Remove leftover 'provided' header in preview for 6.1.x
  cdap-ui/app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.html
  cdap-ui/app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.less
Labels: 6.1, UI, cla: yes

#12224 [CDAP-16801] removing filtering of runtime arguments
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
Labels: 6.1, UI, cla: yes

#12258 [CDAP-16607] Expands plugin configuration, plugin templates and post run actions
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/directives/plugin-templates/plugin-templates.less
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/leftpanel.less
  cdap-ui/app/hydrator/templates/detail/bottom-panel.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover-template.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/app/styles/themes/cdap/theme.less
Labels: 6.1, UI, cherry-pick, cla: yes

#12265 [CDAP-11438][CDAP-14190] Allow users to completely delete column name while editing in wrangler
  cdap-ui/app/cdap/components/DataPrep/DataPrepErrorAlert/DataPrepErrorAlert.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingPositions/CutDirective.js
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
Labels: 6.1, Bug, UI, cherry-pick, cla: yes

#12253 Adds X-Requested-With header to all the xhr requests made from UI + M…
  cdap-ui/app/cdap/components/AppHeader/AccessTokenModal/index.tsx
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployApp.js
  cdap-ui/app/cdap/components/CaskWizards/OneStepDeploy/OneStepDeployPlugin.js
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/SessionTokenStore.ts
  cdap-ui/app/cdap/services/StatusFactory.js
  cdap-ui/app/cdap/services/WindowManager/Heartbeat-web-worker.js
  cdap-ui/app/cdap/services/WindowManager/index.ts
  cdap-ui/app/cdap/services/upload-file.js
  cdap-ui/app/cdap/styles/img/heartbeat.png
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/logviewer/main.js
  cdap-ui/app/services/file-uploader.js
  cdap-ui/app/tracker/main.js
  cdap-ui/server/express.js
  cdap-ui/webpack.config.cdap.js
Labels: 6.1, UI, cherry-pick, cla: yes

#12266 [CDAP-16567] Improves the configuration group heading styles to be co…
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownHeading.tsx
Labels: 6.1, UI, cherry-pick, cla: yes

#12254 [CDAP-11661][CDAP-16797] Fix post run actions to remove success messa…
  cdap-ui/app/cdap/components/PostRunActions/PostRunActions.scss
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-ctrl.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.html
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step-ctrl.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.js
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.js
Labels: 6.1, UI, cherry-pick, cla: yes

#12264 (CDAP-16669) Cherry pick long running dataproc cluster support
  cdap-master/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/META-INF/services/io.cdap.cdap.runtime.spi.provisioner.Provisioner
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/common/DataprocUtilsTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
Labels: 6.2, cherry-pick, cla: yes

#12206 [CDAP-16861] Define configuration groups (plugin JSON Creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupInfoInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/PluginInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/StepButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/steps.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
Labels: UI, cla: yes

#12108 [CDAP-16649] Support authentication and TLS to Elastic metadata storage
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/Config.java
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticConfigurationTest.java
  cdap-elastic/src/test/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorageTest.java
Labels: cla: yes

#12270 CDAP-16902 run pipeline tests in serial since they are expensive
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
Labels: cla: yes

#12273 CDAP-16902 run pipeline tests in serial since they are expensive
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
Labels: 6.2, cla: yes

#12274 CDAP-16902 run pipeline tests in serial since they are expensive
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
Labels: 6.1, cla: yes

#12233 [CDAP-16835] REST API for upgrading Application and support for config upgrade for DataPipelineApp.
  cdap-api/src/main/java/io/cdap/cdap/api/app/Application.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateResult.java
  cdap-api/src/main/java/io/cdap/cdap/api/artifact/ArtifactVersionRange.java
  cdap-api/src/main/java/io/cdap/cdap/internal/io/AbstractSchemaGenerator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/DataPipelineApp.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/plugin/PluggableFilterTransform.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/HttpExceptionHandler.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/ExpectedNumberOfAuditPolicyPaths.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteApplicationManager.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationUpdateDetail.java
  cdap-test/src/main/java/io/cdap/cdap/test/ApplicationManager.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/internal/DefaultApplicationManager.java
Labels: 6.3, cla: yes

#12278 [CDAP-16493] Fix styling of select inside join rule
  cdap-ui/app/cdap/components/AbstractWidget/SqlConditionsWidget/Rule.tsx
  cdap-ui/app/cdap/components/OutlinedSelect/index.tsx
Labels: 6.1, Bug, UI, cherry-pick, cla: yes

#12186 [CDAP-16839] Base implementation for virtual scrolling
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/VirtualScroll/demo.tsx
  cdap-ui/app/cdap/components/VirtualScroll/index.tsx
  cdap-ui/app/cdap/components/VirtualScroll/useScroll.tsx
Labels: 6.3, UI, cla: yes

#12272 [CDAP-16894] Add MultiStageSelector widget for use in Joiner
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/MultiStageSelector/index.tsx
Labels: 6.1, UI, cla: yes

#12262 [CDAP-16690] Add preview data view
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/TableContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/preview-tab.html
Labels: 6.1, UI, cla: yes

#12256 [CDAP-16607]Fixes merge conflict for styling post run actions in deta…
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
Labels: 6.3, Bug, UI, cla: yes

#12289 [CDAP-16690] Add preview endpoint and factor out preview data fetching logic
  cdap-ui/app/cdap/api/preview.js
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12290 [CDAP-16690] Add preview endpoint and factor out preview data fetching logic
  cdap-ui/app/cdap/api/preview.js
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.2, UI, cherry-pick, cla: yes

#12296 [CDAP-16690] Add preview data view
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/TableContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/preview-tab.html
Labels: 6.3, UI, cherry-pick, cla: yes

#12297 [CDAP-16690] Add preview data view
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/TableContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/preview-tab.html
Labels: 6.2, UI, cherry-pick, cla: yes

#12294 (CDAP-16918) Added a REST endpoint to export all application details
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/InstanceOperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/InstanceOperationHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ProgramType.java
Labels: 6.3, cla: yes

#12293 [CDAP-16621] remove export modal when exporting pipelines
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PipelineExportModal/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/DeployedActions/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftActions/index.tsx
  cdap-ui/app/cdap/services/download-file.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/cypress/integration/pipeline.canvas.actions.spec.ts
  cdap-ui/cypress/integration/pipeline.contextmenu.spec.ts
  cdap-ui/cypress/integration/pipeline.multiselect.spec.ts
  cdap-ui/cypress/integration/pipeline.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
  cdap-ui/cypress/integration/widgets.CSVWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueDropdownWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueWidget.spec.ts
  cdap-ui/cypress/support/commands.ts
Labels: 6.2, UI, cherry-pick, cla: yes

#12288 [CDAP-16845] Fix data-cy attribute in e2e test
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.3, Bug, UI, cla: yes

#12287 [CDAP-16845] Fix preview starting when using clicks No in post-run actions confirmation modal
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/templates/create/popovers/run-preview-action-confirmation-modal.html
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.2, Bug, UI, cherry-pick, cla: yes

#12303 [CDAP-16211] Fixed JSON parsing error and added tests for deploying with configura…
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/AppRequest.java
Labels: 6.1, cherry-pick, cla: yes

#12295 CDAP-16928 add a no-op map to join results to emit records out
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12307 [CDAP-16461] Adding size limit for spark block fetches
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12305 CDAP-16928 add a no-op map to join results to emit records out
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12306 CDAP-16928 add a no-op map to join results to emit records out
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12281 [CDAP-16835] Adding support for artifact scope and snapshot artifact for upgrade
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricClient.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteApplicationManager.java
  cdap-test/src/main/java/io/cdap/cdap/test/ApplicationManager.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/internal/DefaultApplicationManager.java
Labels: 6.3, cla: yes

#12308 [Cherry-pick to 6.1] Adding support for artifact scope and snapshot artifact for upgrade
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricClient.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteApplicationManager.java
  cdap-test/src/main/java/io/cdap/cdap/test/ApplicationManager.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/internal/DefaultApplicationManager.java
Labels: cla: yes

#12309 [Cherry-pick to 6.2] Adding support for artifact scope and snapshot artifact for upgrade
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricClient.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteApplicationManager.java
  cdap-test/src/main/java/io/cdap/cdap/test/ApplicationManager.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/internal/DefaultApplicationManager.java
Labels: cla: yes

#12250 [CDAP-16873] Add metrics writer module
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MetricsProcessorTwillRunnable.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsWriter.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricStoreMetricsWriter.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoader.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterModule.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterProvider.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/MetricsTestBase.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MetricsProcessorServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MockMetricsWriterModule.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MockMetricsWriterProvider.java
Labels: cla: yes

#12312 [CDAP-16461] Adding size limit for spark block fetches
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.1, cherry-pick, cla: yes

#12313 [CDAP-16461] Adding size limit for spark block fetches
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.2, cherry-pick, cla: yes

#12304 [CDAP-16784] Add Kryo serializers for unmodifiable class types
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableCollectionSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableListSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSetSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedSetSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: 6.3, cla: yes

#12311 CDAP-16955 add metrics for records into an autojoin
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12320 CDAP-16955 add metrics for records into an autojoin
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12321 CDAP-16955 add metrics for records into an autojoin
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes

#12322 (CDAP-16953) Correctly suppress runtime monitor warning log
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/proxy/SimpleRelayChannelHandler.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
Labels: 6.1, cla: yes

#12325 CDAP-16943 use byte[] instead of ByteBuffer for record conversion
  cdap-api-spark-base/src/main/java/io/cdap/cdap/api/spark/sql/DataFrames.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/api/spark/sql/DataFramesTest.java
Labels: cla: yes

#12326 CDAP-16943 use byte[] instead of ByteBuffer for record conversion
  cdap-api-spark-base/src/main/java/io/cdap/cdap/api/spark/sql/DataFrames.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/api/spark/sql/DataFramesTest.java
Labels: cla: yes

#12327 CDAP-16943 use byte[] instead of ByteBuffer for record conversion
  cdap-api-spark-base/src/main/java/io/cdap/cdap/api/spark/sql/DataFrames.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/api/spark/sql/DataFramesTest.java
Labels: cla: yes

#12211 [CDAP-16862] Define properties under each configuration group (plugin JSON creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/PluginInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
Labels: UI, cla: yes

#12214 [CDAP-16863] Show the live JSON view (plugin JSON Creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/ClosedJsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/JsonLiveViewer/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
Labels: UI, cla: yes

#12286 [CDAP-16607] Removes unnecessary margin on smaller screens
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.3, Bug, UI, cla: yes

#12330 (CDAP-16950) Tag all ERROR logs from program execution as program log
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppender.java
Labels: 6.3, cla: yes

#11844 [CDAP-14284] Adds pan/zoom feature to pipeline canvas.
  cdap-ui/app/cdap/components/DAG/DAGProvider.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/ConditionNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/SplitterNode/PortPopover.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/utilities.ts
  cdap-ui/app/cdap/components/DAG/index.tsx
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.3, UI, cla: yes

#12318 [CDAP-16784] Added kryo serializers for unmodifiable types
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableCollectionSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableListSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSetSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedSetSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: cla: yes

#12319 [CDAP-16784] Added kryo serializers for unmodifiable types
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableCollectionSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableListSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSetSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedMapSerializer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/UnmodifiableSortedSetSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: cla: yes

#12331 (CDAP-16950) Tag all ERROR logs from program execution as program log
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppender.java
Labels: 6.1, cherry-pick, cla: yes

#12332 (CDAP-16950) Tag all ERROR logs from program execution as program log
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppender.java
Labels: 6.2, cherry-pick, cla: yes

#12285 [CDAP-16617] Expand hub modal to entire page
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 6.2, UI, cherry-pick, cla: yes

#12336 [CDAP-16607] Removes unnecessary margin on smaller screens
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.1, UI, cherry-pick, cla: yes

#12329 [CDAP-16835] Change Batch Upgrade REST API to take in list of ApplicationRecords
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLPlugin.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationUpdateDetail.java
Labels: 6.3, cla: yes

#12341 [Cherry-pick] Change Batch Upgrade REST API to take in list of ApplicationRecords.
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLPlugin.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationUpdateDetail.java
Labels: 6.2, cherry-pick, cla: yes

#12340 [Cherry-pick] Change Batch Upgrade REST API to take in list of ApplicationRecords.
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLPlugin.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationUpdateDetail.java
Labels: 6.1, cherry-pick, cla: yes

#12323 Support Dataproc custom Image
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12333 [CDAP-16871] Configure widget-attributes for each property (plugin JSON creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeKeyValueInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeMultipleValuesInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
Labels: UI, cla: yes

#12334 [CDAP-16869] Create a page for outputs configuration (plugin JSON creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Outputs/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/steps.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
Labels: UI, cla: yes

#12298 [CDAP-16617] Revert add entity modal to be smaller size + fix error m…
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 6.3, Bug, UI, cla: yes

#12302 [CDAP-16939] let Multiselect component accept an array of string for 'options'
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
Labels: 6.3, Bug, UI, cla: yes

#12317 [CDAP-16960] Preview error handling
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.3, Bug, UI, cla: yes

#12342 [CDAP-16975][CDAP-16976] Select latest version as default when choosing a plugin in UI + reset default plugins post upgrade
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/create/actions/available-plugins-action-creator.js
  cdap-ui/app/hydrator/services/create/stores/left-panel-store.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.1, UI, cla: yes

#12335 [CDAP-16240] Fix Master & Worker memory values in GCP profile
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/index.js
Labels: 6.1, Bug, UI, cherry-pick, cla: yes

#12229 [CDAP-16874] Importing existing plugin JSON file (plugin JSON Creator)
  cdap-ui/app/cdap/components/Alert/index.js
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/ClosedJsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/JsonLiveViewer/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/PluginJsonImporter/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Outputs/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeMultipleValuesInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
Labels: UI, cla: yes

#12351 Support Dataproc custom Image
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12350 Support Dataproc custom Image
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: cla: yes

#12337 [CDAP-16315] Disable showing system logs by default
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.js
  cdap-ui/app/directives/log-viewer/log-viewer.js
Labels: 6.1, UI, cherry-pick, cla: yes

#12344 [CDAP-16617] Revert add entity modal to be smaller size + fix error m…
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 6.1, UI, cherry-pick, cla: yes

#12345 [CDAP-16617] Revert add entity modal to be smaller size + fix error m…
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: 6.2, UI, cherry-pick, cla: yes

#12346 [CDAP-16960] Add error handling for when backend returns error while fetching preview
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.1, Bug, UI, cherry-pick, cla: yes

#12348 [CDAP-16975] Default to latest version while adding plugin from left …
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/create/actions/available-plugins-action-creator.js
  cdap-ui/app/hydrator/services/create/stores/left-panel-store.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.2, UI, cherry-pick, cla: yes

#12349 [CDAP-16975] Default to latest version while adding plugin from left …
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/create/actions/available-plugins-action-creator.js
  cdap-ui/app/hydrator/services/create/stores/left-panel-store.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12283 [CDAP-16607] Expands plugin configuration, plugin templates and post …
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard.js
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.html
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
  cdap-ui/app/directives/plugin-templates/plugin-templates.less
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/leftpanel.less
  cdap-ui/app/hydrator/templates/detail/bottom-panel.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover-template.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/app/styles/themes/cdap/theme.less
Labels: 6.2, UI, cherry-pick, cla: yes

#12355 [CDAP-16937][CDAP-16940] Fixes preview style + bump idle timeout to be 5 mins
  cdap-ui/app/cdap/components/PreviewData/TableContainer.tsx
  cdap-ui/app/cdap/services/WindowManager/index.ts
Labels: 6.1, Bug, UI, cla: yes

#12353 [CDAP-16993] Stringify fields that are byte and other object types
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
Labels: 6.1, Bug, UI, cla: yes

#12343 CDAP-16987 Keep single store for all preview runs owned by PreviewManager.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModuleFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/preview/PreviewHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewManagerTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/test/java/io/cdap/cdap/datastreams/preview/PreviewDataStreamsTest.java
Labels: cla: yes

#12360 CDAP-16994 fix schema equality check during pipeline deployment
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Schemas.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/record/StructuredRecordComparator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/SchemaPropagator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/SchemasTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: cla: yes

#12364 CDAP-16994 fix schema equality check during pipeline deployment
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Schemas.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/record/StructuredRecordComparator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/SchemaPropagator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/SchemasTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: cla: yes

#12365 CDAP-16994 fix schema equality check during pipeline deployment
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Schemas.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/record/StructuredRecordComparator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/SchemaPropagator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/SchemasTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: cla: yes

#12361 CDAP-16935 partition dataframes before join
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/scala/io/cdap/cdap/etl/spark/plugin/literalsBridge.scala
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12366 CDAP-16935 partition dataframes before join
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/scala/io/cdap/cdap/etl/spark/plugin/literalsBridge.scala
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12367 CDAP-16935 partition dataframes before join
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/scala/io/cdap/cdap/etl/spark/plugin/literalsBridge.scala
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: cla: yes

#12357 [CDAP-16891] Upgrading pipeline drafts
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.js
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/pipelineupgrade-modal-ctrl.js
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/services/hydrator-upgrade-service.js
  cdap-ui/app/hydrator/templates/create/pipeline-upgrade-modal.html
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/cypress/fixtures/draft_for_upgrade.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.upgrade.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.1, Bug, UI, cla: yes

#12363 CDAP-16367 handle direct read/write
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#12375 CDAP-16367 handle direct read/write
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#12374 CDAP-16367 handle direct read/write
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfoTest.java
Labels: cla: yes

#12354 [CDAP-16972] Fix to stop pipeline preview running properly
  cdap-ui/app/cdap/components/KeyValuePairs/KeyValueStoreActions.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineRunButton.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-service.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
Labels: 6.1, UI, cla: yes

#12373 [CDAP 16835] Use Primitive type wrapper instead of primitive types in Configs
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: 6.3, cla: yes

#12380 [Cherry-pick] Use Primtive class wrapper instead of primitive types in ETLBatchConf…
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: 6.1, cherry-pick, cla: yes

#12381 [Cherry-pick] Use Primtive class wrapper instead of primitive types in ETLBatchConf…
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: 6.2, cherry-pick, cla: yes

#12368 CDAP-16760 set resources for sparkprogram plugins
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/ExternalSparkProgram.java
Labels: cla: yes

#12369 CDAP-16760 set resources for sparkprogram plugins
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/ExternalSparkProgram.java
Labels: cla: yes

#12376 CDAP-17000 increase spark network timeout by default
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12377 CDAP-17000 increase spark network timeout by default
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12378 CDAP-17000 increase spark network timeout by default
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12384 (CDAP-17001) Reduce unit-test JVM memory to 5GB
  pom.xml
Labels: cla: yes

#12386 Cherrypick KubeTwillPrep changes allowing CPU & RAM scaling for SysApps
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: cla: yes

#12385 [CDAP-17005] Initialize default config if resolved config is invalid
  cdap-ui/app/directives/my-pipeline-runtime-args/my-pipeline-runtime-args.less
  cdap-ui/app/hydrator/controllers/create/create-studio-ctrl.js
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.1, Bug, UI, cla: yes

#12387 (CDAP-17001) Remove the unnecessary deleteNamespaces() when test completed
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/WorkflowStatsSLAHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/TimeSchedulerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/store/SqlProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
Labels: 6.3, cla: yes

#12390 [CDAP-16937] Fixes preview styling in source and sink nodes
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
  cdap-ui/app/hydrator/hydrator-modal.less
Labels: 6.1, UI, cla: yes

#12391 [CDAP-16602] Fix UI to access correct property to fetch total results
  cdap-ui/app/cdap/components/Pagination/PaginationDropdown.js
  cdap-ui/app/cdap/components/Pagination/PaginationDropdown.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModalHeader.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/Tags/Tag/Tag.scss
Labels: 6.1, UI, cherry-pick, cla: yes

#12392 [CDAP-16937] Correctly fixes the merge conflict between full page mod…
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-configure-confirm-step/wizard-configure-confirm-step.less
Labels: 6.1, Bug, UI, cla: yes

#12251 [CDAP-16893] Use immutable.js for updating states (plugin JSON Creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupInfoInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterConditionInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterShowlistInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/LiveViewer/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeKeyValueInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeMultipleValuesInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/CreateContextConnect/index.tsx
Labels: UI, cla: yes

#12347 [CDAP-16960] Add error handling when backend returns error while fetching preview
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, Bug, UI, cherry-pick, cla: yes

#12382 [CDAP-16993] Handle field names and values that are objects in data view
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
  cdap-ui/app/directives/my-post-run-action-wizard/my-post-run-action-wizard-modal.less
Labels: 6.2, Bug, UI, cherry-pick, cla: yes

#12383 [CDAP-16993] Handle field names and values that are objects in data view
  cdap-ui/app/cdap/components/PreviewData/Table.tsx
Labels: 6.3, Bug, UI, cherry-pick, cla: yes

#12388 (CDAP-16455) Output Dataproc job logs to console
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
  cdap-runtime-ext-dataproc/src/main/resources/logback-console.xml
Labels: 6.3, cla: yes

#12389 (CDAP-16455) Output Dataproc job logs to console
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
  cdap-runtime-ext-dataproc/src/main/resources/logback-console.xml
Labels: 6.2, cherry-pick, cla: yes

#12395 fix md5 for docs
  cdap-docs/admin-manual/build.sh
Labels: 6.1, cla: yes

#12397 [CDAP-17014] Bump the timeout for proxy calls to backend to be 30 mins to enable long running sync upgrades
  cdap-ui/server/express.js
Labels: 6.1, Bug, UI, cla: yes

#12182 [CDAP-14945] Remove table headers on empty pipeline list view
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
Labels: 6.3, Bug, UI, cla: yes

#12291 [CDAP-16920] Optimize performance for Plugin JSON Creator
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/index.tsx
  cdap-ui/app/cdap/components/KeyValuePairs/index.js
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/BasicPluginInfo/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupInfoInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/GroupPanel/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/ConfigurationGroupsCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterConditionInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterShowlistInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/ClosedJsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/JsonActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/LiveViewer/LiveConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/LiveViewer/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/PluginJsonImporter/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Outputs/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/StepButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetActionButtons/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/AttributeMultipleValuesInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/MultipleAttributesInput/KeyvalueRowsInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/MultipleAttributesInput/RowsInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/MultipleAttributesInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/SingleAttributeInput/AttributeKeyValueInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/SingleAttributeInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/WidgetAttributeInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetAttributesCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetInfoInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetPanel/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/WizardGuideline/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/steps.tsx
Labels: UI, cla: yes

#12301 [CDAP-16938] Support more configurations for the output page (plugin JSON Creator)
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Filters/FilterCollection/FilterConditionInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/JsonMenu/utilities.ts
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/ExplicitSchemaDefiner/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/ImplicitSchemaDefiner/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/Outputs/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/PluginInput/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/WidgetPanel/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/WidgetCollection/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/constants.tsx
Labels: UI, cla: yes

#12405 Revert "[CDAP-17014] Bump the timeout for proxy calls to backend to be 30 mins to enable long running sync upgrades"
  cdap-ui/server/express.js
Labels: 6.1, UI, cla: yes

#12402 (CDAP-17019) Upgrade netty-http to 1.5.0
  pom.xml
Labels: 6.3, cla: yes

#12403 (CDAP-17019) Upgrade netty-http to 1.5.0
  pom.xml
Labels: 6.2, cherry-pick, cla: yes

#12359 [CDAP-16690] Add record view when number of fields is large
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
  cdap-ui/app/cdap/components/PreviewData/DataView/TableContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/Navigator.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordContainer.tsx
  cdap-ui/app/cdap/components/PreviewData/RecordView/RecordTable.tsx
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.3, UI, cla: yes

#12406 [CDAP-17020] Use ChunkResponder to stream batch upgrade result to avoid timeout
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: cla: yes

#12408 [Cherry-pick] [CDAP-17020] Use ChunkResponder to stream batch upgrade result to avoid timeout
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: 6.1, cherry-pick, cla: yes

#12409 [Cherry-pick] [CDAP-17020] Use ChunkResponder to stream batch upgrade result to avoid timeout
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: 6.2, cla: yes

#12412 CDAP-17024 set spark sql case sensitivity
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12414 CDAP-17024 set spark sql case sensitivity
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12393 Add virtual scroll demo to experiment list
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
Labels: 6.3, Bug, UI, cla: yes

#12413 CDAP-17024 set spark sql case sensitivity
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: cla: yes

#12339 [CDAP-16981] LogViewer add Data Fetcher layer
  cdap-ui/app/cdap/api/program.js
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/LogViewer/DataFetcher/ProgramDataFetcher.ts
  cdap-ui/app/cdap/components/LogViewer/DataFetcher/index.ts
  cdap-ui/app/cdap/components/LogViewer/Playground.tsx
  cdap-ui/app/cdap/components/LogViewer/types.ts
Labels: 6.3, UI, cla: yes
