Repository cdapio/cdap, pull requests merged in 2020-04, with the labels that each got.

#12023 (CDAP-16353) cleanup/refactor: move bindings for preview runner into its module
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
Labels: cla: yes

#12024 (CDAP-16353) Small refactoring of test for k8s service test base
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
Labels: cla: yes

#12028 Handle backward compatibility for inputStages.
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/v2/spec/StageSpecTest.java
Labels: cla: yes

#12026 [CDAP-16515] Fix overflow in runtime arguments modeless on pipeline d…
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsKeyValuePairWrapper.scss
Labels: 6.1, Bug, UI, cla: yes

#12019 [CDAP-16505] fix error rendering issue
  cdap-ui/app/cdap/components/Alert/index.js
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.1, Bug, UI, cla: yes

#11977 Adding implementation for Twill Runner Service
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractRuntimeTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractRuntimeTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtime/RuntimeTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtime/TwillControllerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerExtensionLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ClusterCreateSubtask.java
  cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/ProgramRunInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobDetail.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobId.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeLocalFile.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.2, cla: yes

#12029 [CDAP-16500] Resumes polling for individual node metrics if user switches tab and circles back to pipeline detail view
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: 6.1, Bug, UI, cla: yes

#12031 [CDAP-16515] Fix overflow of runtime arguments dropdown in pipeline d…
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
Labels: 6.2, Bug, UI, cla: yes

#12030 [CDAP-16505] fix error rendering issue cherry-pick
  cdap-ui/app/cdap/components/Alert/index.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.2, Bug, UI, cla: yes

#12020 [CDAP-11438] Fix bug where user cannot delete a column name completel…
  cdap-ui/app/cdap/components/DataPrep/DataPrepErrorAlert/DataPrepErrorAlert.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ExtractFields/UsingPositions/CutDirective.js
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
Labels: 6.2, Bug, UI, cla: yes

#12027 Add a config to disallow creating new profile via REST endpoint
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/NoSqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/SqlProfileServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes

#12022 (CDAP-16353) Add binding providers to allow local vs remote bindings
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryReaderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/PluginFinderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ApplicationDetailFetcherProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/PreferencesFetcherProvider.java
Labels: cla: yes

#12021 [CDAP-16513] Fix complex schema editor focus
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/cypress/integration/pipeline.complexschema.spec.ts
Labels: 6.2, Bug, UI, cla: yes

#12032 (CDAP-16353) Support preview to run with non-sharing local level DB.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewManagerTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/app/PreviewTestAppWithPlugin.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMainTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#12034 (CDAP-16353) Refactor k8s deployment building in KubeTwillPreparer to a separate function
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: cla: yes

#12033 enable delta replicator by default for sandbox
  cdap-common/src/main/resources/system-apps/cdc.json
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: cla: yes

#12039 (CDAP-16369) Add missing app version to the ProgramRunInfo
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillController.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/ProgramRunInfo.java
Labels: 6.2, cla: yes

#12040 Release notes & licenses updates for 6.1.2
  cdap-docs/reference-manual/licenses-pdf/cdap-enterprise-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-level-1-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-sandbox-dependencies.pdf
  cdap-docs/reference-manual/licenses-pdf/cdap-ui-dependencies.pdf
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/tools/licenses/cdap-level-1-dependencies.rst
  cdap-docs/tools/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
Labels: cla: yes

#12041 [CDAP-16353] Add scaling factor to adjust resource size for KubeTwill program
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: 6.2, cla: yes

#12043 (CDAP-16353) fixing test breakage due to appfabric being stopped too soon
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#11991 CDAP-16239 include context in plugin config creation error
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/InvalidPluginConfigException.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/InvalidPluginProperty.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: cla: yes

#12044 (CDAP-16369) Introduce new runtime service
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/RuntimeServerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramOptions.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteRuntimeTable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/StoreProgramRunRecordFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/discovery/DefaultServiceDiscovered.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMainTest.java
Labels: 6.2, cla: yes

#12046 Fixed GSON parsing error when using configuration string
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/AppRequest.java
Labels: cla: yes

#12042 [CDAP-16490] fix get schema button to ignore macro value
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/cypress/integration/pipeline.joiner.spec.ts
Labels: 6.2, Bug, UI, cla: yes

#12011 [CDAP-16500] Resumes polling for individual node metrics if user switches tab and circles back to pipeline detail view
  cdap-ui/app/hydrator/controllers/detail-ctrl.js
Labels: 6.2, Bug, UI, cla: yes

#12045 [CDAP-12840] Add tooltip from angular-strap for tooltip fix
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/modified-tooltip/popover.html
  cdap-ui/app/directives/modified-tooltip/tooltip.html
  cdap-ui/app/directives/modified-tooltip/tooltip.js
  cdap-ui/app/hydrator/main.js
Labels: 6.2, Bug, UI, cla: yes

#12050 handle bucket name to include scheme 'gs://'
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: 6.2, cla: yes

#12052 Fix docs build for release 6.1.2
  cdap-docs/_common/common-build.sh
  cdap-docs/admin-manual/build.sh
  cdap-docs/integrations/build.sh
Labels: Docs, cla: yes

#12051 (CDAP-16369) Collections of provisioner improvement
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/RuntimeJobTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/NativeProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ClusterDeleteSubtask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/provision/MockProvisioner.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocClusterInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
  cdap-runtime-ext-emr/src/main/java/io/cdap/cdap/runtime/spi/provisioner/emr/ElasticMapReduceProvisioner.java
  cdap-runtime-ext-emr/src/test/java/io/cdap/cdap/runtime/spi/provisioner/emr/ElasticMapReduceProvisionerTest.java
  cdap-runtime-ext-remote-hadoop/src/main/java/io/cdap/cdap/runtime/spi/provisioner/remote/RemoteHadoopProvisioner.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/ProgramRunInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProgramRun.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Provisioner.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobDetail.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobInfo.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobStatus.java
Labels: cla: yes

#12049 [CDAP-16534] Update tooltip for batch pipeline engine config to remove Spark Str…
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config-ctrl.js
Labels: 6.2, Bug, UI, cla: yes

#12048 [CDAP-16434][CDAP-16551] Replicator Manual Table Selection and Parallelism Config
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/ColumnsMultiRow/ColumnRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/ColumnsMultiRow/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/TableMultiRow/TableRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/TableMultiRow/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/ManualSelectTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
Labels: 6.2, UI, cla: yes

#12053 [CDAP-16567] Properly fix styling for plugin configuration title
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12056 (CDAP-16538) Make sure the plugin properties are immutable
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginProperties.java
Labels: cla: yes

#12057 (CDAP-16521) Turn program start completely async
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/DelayedProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramControllerServiceAdapter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/DelayedProgramControllerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: 6.2, cla: yes

#12062 (CDAP-16369) Properly support SSH monitoring for jobs launched with RuntimeJobManager
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteExecutionService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ClusterCreateSubtask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMainTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: 6.2, cla: yes

#12060 CDAP-16239 include context in plugin config creation error
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/InvalidPluginConfigException.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/InvalidPluginProperty.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
Labels: 6.1, cla: yes

#12059 [CDAP -16581] Fix parse as JSON (and other directives) in Wrangler
  cdap-ui/app/cdap/components/DataPrep/Directives/ColumnActions/Bulkset/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ColumnActions/ReplaceColumns/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/ExcelModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/SingleFieldModal.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, Bug, UI, cla: yes

#12064 (CDAP-16590) Log all errors when a scheduled service failed
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
Labels: 6.2, cla: yes

#12054 [CDAP-16240] Fix Master & Worker memory values in GCP profile
  cdap-ui/app/cdap/components/Cloud/Profiles/DetailView/Content/DetailsInfo/index.js
Labels: 6.2, Bug, UI, cla: yes

#12061 [CDAP-16497] Add replicator to home page actions
  cdap-ui/app/cdap/components/Home/HomeActions/ActionConfig.ts
  cdap-ui/app/cdap/components/Home/HomeActions/index.tsx
  cdap-ui/app/cdap/styles/img/replicator.svg
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, UI, cla: yes

#12063 [CDAP-16571] Add empty indicator for plugin selector
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, Bug, UI, cla: yes

#12065 Added more options (16, 32, 64, 96) for master and worker vCPUs
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12068 [CDAP-16487] Using proper regex to detect empty columns in Wrangler UI
  cdap-ui/app/cdap/components/DataPrep/Directives/Filter/index.js
Labels: 6.2, UI, cla: yes

#12069 [CDAP-14190] Allows column name to be deleted completely
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
Labels: 6.2, Bug, UI, cla: yes

#12074 (CDAP-16408) Use the CDF bucket by default to allow adding caching later
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: 6.2, cla: yes

#12076 (CDAP-16408) Use the CDF bucket by default to allow adding caching later
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: cla: yes

#12072 [CDAP-16597] Fixes CodeEditor to correctly update
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12075 [CDAP-16602] Fix search by tags modal in UI to fetch results from correct property in response.
  cdap-ui/app/cdap/components/Pagination/PaginationDropdown.js
  cdap-ui/app/cdap/components/Pagination/PaginationDropdown.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModal.scss
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/SpotlightModalHeader.js
  cdap-ui/app/cdap/components/SpotlightSearch/SpotlightModal/index.js
  cdap-ui/app/cdap/components/Tags/Tag/Tag.scss
Labels: 6.2, Bug, UI, cla: yes

#12067 [CDAP-16588] Downgrades material-ui library to 4.0.1
  cdap-ui/app/cdap/components/Ingestion/PluginsTableView/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsRow.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/TargetList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/LeftPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.2, Bug, UI, cla: yes

#12083 (CDAP-16369) Remove unused method
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
Labels: 6.2, cla: yes

#12082 (CDAP-16369) Remove unused method
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
Labels: 6.3, cla: yes

#12079 (CDAP-16369) Collection of improvements for runtime
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramLaunchConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteExecutionService.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/ProgramRuntimeClassAcceptor.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.3, cla: yes

#12081 (CDAP-16369) Collection of improvements for runtime
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramLaunchConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteExecutionService.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/ProgramRuntimeClassAcceptor.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.2, cla: yes

#12084 (CDAP-16521) Turn program start completely async
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/DelayedProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramControllerServiceAdapter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/DelayedProgramControllerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: 6.1, cla: yes

#12073 [CDAP-16577][CDAP-16589] Replicator mapping table enhancements
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12078 [CDAP-16576] Replicator fix table selector when previously selected t…
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12088 (CDAP-16610) Fixing DataprocUtils.getBucketName null pointer exception
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: 6.3, cla: yes

#12092 (CDAP-16610) Fixing DataprocUtils.getBucketName null pointer exception
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: cla: yes

#12089 (CDAP-16614) Fix program runs limit
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: 6.3, cla: yes

#12091 (CDAP-16614) Fix program runs limit
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: cla: yes

#12090 (CDAP-16614) Fix program runs limit
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: cla: yes

#12085 (CDAP-16606) Limit total number of records in preview run
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputSplit.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
Labels: 6.3, cla: yes

#12093 Update pipeline versions for e2e tests
  cdap-ui/cypress/fixtures/fll_airport_pipeline2.json
  cdap-ui/cypress/fixtures/null_splitter_pipeline-cdap-data-pipeline.json
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
Labels: 6.3, UI, cla: yes

#12077 [CDAP-16603] Check for resource when setting timeout to poll during preview
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/directives/modified-tooltip/tooltip.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
Labels: Bug, UI, cla: yes

#12096 (CDAP-16616) Make the View Raw Logs and Download All button enable all the time
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.html
  cdap-ui/app/directives/log-viewer/log-viewer.html
Labels: 6.2, UI, cla: yes

#12097 (CDAP-16616) Make the View Raw Logs and Download All button enable all the time
  cdap-ui/app/directives/log-viewer-preview/log-viewer-preview.html
  cdap-ui/app/directives/log-viewer/log-viewer.html
Labels: 6.3, UI, cla: yes

#12094 (CDAP-16606) Limit total number of records in preview run
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputSplit.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
Labels: 6.2, cla: yes

#12095 (CDAP-16606) Limit total number of records in preview run
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormat.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputSplit.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingRecordReader.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatTest.java
Labels: 6.1, cla: yes

#12101 Fix javdoc for ProvisionerContext
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
Labels: 6.3, cla: yes

#12100 Fix javdoc for ProvisionerContext
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
Labels: 6.2, cla: yes

#12103 [CDAP-16612] Make sure correct classpath is used when using ssh for s…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.3, cla: yes

#12098 [CDAP-16612] Make sure correct classpath is used when using ssh for s…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.2, cla: yes

#12071 Dataproc Provisioner - Enhancements -NEW PR
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.2, cla: yes

#12107 (CDAP-16615) Various improvement for logs collection
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/AbstractLogPublisher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/loader/LogAppenderLoaderService.java
Labels: 6.2, cla: yes

#12109 (CDAP-16639) Move hive-exec to the bottom of the class path
  cdap-common/src/main/java/io/cdap/cdap/common/app/MainClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/HadoopClassExcluder.java
Labels: 6.2, cla: yes

#12110 (CDAP-16639) Move hive-exec to the bottom of the class path
  cdap-common/src/main/java/io/cdap/cdap/common/app/MainClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/HadoopClassExcluder.java
Labels: 6.3, cla: yes

#12112 (CDAP-16647) Only localize Spark when running from the target cluster
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: 6.2, cla: yes

#12116 (CDAP-16592) Don’t apply firewall rule when SSH is not used
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryServiceTest.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/RuntimeMonitorType.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
Labels: 6.2, cla: yes

#12102 Ingestion icon and font size changes
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
  cdap-ui/app/cdap/components/Home/HomeActions/ActionConfig.ts
  cdap-ui/app/cdap/components/Ingestion/PluginsTableView/index.tsx
  cdap-ui/app/cdap/components/Ingestion/SourceSinkConfigurator/index.tsx
  cdap-ui/app/cdap/components/Ingestion/index.tsx
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
  cdap-ui/app/cdap/styles/img/ingest-tile.svg
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.2, Bug, UI, cla: yes

#12099 [CDAP-16586] Use shift to select multiple plugins in Studio
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/cypress/integration/pipeline.canvas.actions.spec.ts
Labels: 6.2, UI, cla: yes

#12122 (CDAP-16672) Support GCP Dataproc cluster property override via cdap-site.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerSystemContext.java
Labels: cla: yes

#12126 (CDAP-16672) Support GCP Dataproc cluster property override via cdap-site.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerSystemContext.java
Labels: cla: yes

#12105 [CDAP-16645] Avoid unnecessarily re-rendering preferences in UI
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
Labels: 6.2, Bug, UI, cla: yes

#12086 [CDAP-16236] Reverts the change to remove check for macros before running preview
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.2, Bug, UI, cla: yes

#12104 [CDAP-16617] Expand hub modal to entire page
  cdap-ui/app/cdap/components/AppHeader/index.tsx
  cdap-ui/app/cdap/components/PlusButtonModal/PlusButtonModal.scss
Labels: UI, cla: yes

#12106 [CDAP-16645] Removes unnecessarily re-rendering preferences every 10 seconds
  cdap-ui/app/cdap/components/FastAction/SetPreferenceAction/SetPreferenceModal.js
Labels: 6.1, Bug, UI, cla: yes

#12128 (CDAP-16593) Restricts max network tags to 64.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/IPRange.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.2, cla: yes

#12117 Dataproc enhancements to support metadata, network tags and initactions
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.1, cla: yes

#12131 (CDAP-16593) Restricts max network tags to 64.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/IPRange.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.1, cla: yes

#12132 [CDAP-16704] Add isPreviewEnabled API in StreamingContext and Streami…
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingSourceContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingSourceContext.java
Labels: 6.3, cla: yes

#12111 [CDAP-16631] Replicator left panel stepper improvement
  cdap-ui/app/cdap/components/Replicator/Create/LeftPanel/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12114 [CDAP-16632] Replicator improve create view top panel
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/PluginInfo.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
Labels: 6.2, Bug, UI, cla: yes

#12134 CDAP-16659 enable container logs on ephemeral cluster
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.2, cla: yes

#12115 [CDAP-16641] Replicator restyle plugin tile
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/TargetList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/PluginCard/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/index.tsx
Labels: 6.2, Bug, UI, cla: yes
