Repository cdapio/cdap, pull requests merged in 2020-01, with the labels that each got.

#11804 (CDAP-16193) Correctly handle preview status after restart
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
Labels: 6.1, cla: yes

#11762 Fixes the case of showing all incoming data in preview in joiner plugin
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.2, Bug, UI, cla: yes

#11771 [CDAP-16153] Refactored Batch-Realtime Dichotomy and Added SQL Config UI
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/CustomConfig.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/EngineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/ServiceAccountPath.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/ExecutorResources.js
  cdap-ui/app/cdap/components/PipelineConfigurations/ConfigurationsContent/ResourcesTabContent/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/index.js
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineRunButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineScheduleButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineStopButton/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/index.js
  cdap-ui/app/cdap/services/PipelineErrorFactory.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/text/text-en.yaml
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-pipeline-configurations-factory.js
  cdap-ui/app/directives/my-pipeline-configurations/my-pipeline-configurations.less
  cdap-ui/app/directives/my-pipeline-configurations/my-realtime-pipeline-config/my-realtime-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-sql-pipeline-config/my-sql-pipeline-config-ctrl.js
  cdap-ui/app/directives/my-pipeline-configurations/my-sql-pipeline-config/my-sql-pipeline-config.html
  cdap-ui/app/directives/my-pipeline-configurations/my-sql-pipeline-config/my-sql-pipeline-config.js
  cdap-ui/app/hydrator/controllers/create/partials/settings-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/app/hydrator/templates/preconfigured-list.html
Labels: 6.2, UI, cla: yes

#11810 Merge release/6.1 to develop
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-common/bin/functions.sh
  cdap-ui/app/cdap/api/app.js
  cdap-ui/app/cdap/components/EntityCard/ApplicationMetrics/index.js
  cdap-ui/app/cdap/components/EntityCard/index.js
  cdap-ui/app/cdap/components/EntityListView/JustAddedSection/index.js
  cdap-ui/app/cdap/components/EntityListView/ListView/index.js
  cdap-ui/app/cdap/components/EntityListView/SearchStore/index.js
  cdap-ui/server/aggregator.js
Labels: 6.2, cla: yes

#11811 (CDAP-16128) Only get program ids for checking existence
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapterTest.java
Labels: 6.1, cla: yes

#11813 [UI][E2E-Tests] Adds pipeline E2E tests
  cdap-ui/app/cdap/components/AbstractWidget/CodeEditorWidget/JsonEditorWidget.tsx
  cdap-ui/app/cdap/components/AbstractWidget/CodeEditorWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/MultiSelect/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Number/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Password/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/TextBox/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/StateWrapper.js
  cdap-ui/app/cdap/components/AbstractWidget/ToggleSwitchWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/WranglerEditor/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/index.tsx
  cdap-ui/app/cdap/components/CodeEditor/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/WidgetWrapper/index.tsx
  cdap-ui/app/cdap/components/ToggleSwitch/index.js
  cdap-ui/app/directives/complex-schema/complex-schema.js
  cdap-ui/app/directives/my-pipeline-configurations/my-sql-pipeline-config/my-sql-pipeline-config-ctrl.js
  cdap-ui/app/directives/widget-container/widget-json-editor/widget-json-editor.html
  cdap-ui/app/directives/widget-container/widget-json-editor/widget-json-editor.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/app/services/pipeline-export-modal/pipeline-export-modal-template.html
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
Labels: 6.2, UI, cla: yes

#11812 Merge release/6.1 to develop
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapterTest.java
Labels: 6.2, cla: yes

#11814 [CDAP-16202] Add e2e tests for pipeline actions
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/FeatureHeading.tsx
  cdap-ui/app/cdap/components/Heading/index.tsx
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/cypress/integration/pipeline.canvas.actions.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
  cdap-ui/cypress/snapshots/base/pipeline.canvas.actions.spec.ts/pipeline_with_condition-base.png
  cdap-ui/cypress/snapshots/base/pipeline.plugin.multipleendpoints.spec.ts/Pipelines with plugins having more than one endpoints -- Should work with null splitter plugin (failed).png
  cdap-ui/cypress/snapshots/base/pipeline.plugin.multipleendpoints.spec.ts/Pipelines with plugins having more than one endpoints -- Should work with union splitter and condition plugins (failed) (1).png
  cdap-ui/cypress/snapshots/base/pipeline.plugin.multipleendpoints.spec.ts/Pipelines with plugins having more than one endpoints -- Should work with union splitter and condition plugins (failed) (2).png
  cdap-ui/cypress/snapshots/base/pipeline.plugin.multipleendpoints.spec.ts/Pipelines with plugins having more than one endpoints -- Should work with union splitter and condition plugins (failed) (3).png
  cdap-ui/cypress/snapshots/base/pipeline.plugin.multipleendpoints.spec.ts/Pipelines with plugins having more than one endpoints -- Should work with union splitter and condition plugins (failed).png
  cdap-ui/cypress/snapshots/base/pipeline.studio.spec.ts/pipeline_with_condition-base.png
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.2, UI, cla: yes

#11818 [CDAP-16206] Add email alert config check to pipeline e2e test
  cdap-ui/cypress/integration/pipeline.spec.ts
Labels: 6.2, UI, cla: yes

#11819 Refactoring and cleanup
  cdap-api/src/test/java/io/cdap/cdap/api/dataset/lib/CloseableIteratorTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredRow.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/Range.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: cla: yes

#11817 [CDAP-16199] Joiner pipeline integration test
  cdap-ui/app/cdap/components/AbstractWidget/GetSchemaWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/FieldRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/SchemaContainer.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SqlSelectorWidget/index.tsx
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-input-schema.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/cypress/integration/pipeline.joiner.spec.ts
  cdap-ui/cypress/integration/pipeline.studio.spec.ts
Labels: 6.2, UI, cla: yes

#11820 Update release notes + License dependencies for 6.1.0 & 6.1.1 releases
  cdap-docs/developer-manual/build-pipelines.sh
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-level-1-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.csv
  cdap-docs/reference-manual/source/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/licenses/index.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-enterprise-dependencies.rst
  cdap-docs/tools/licenses/cdap-level-1-dependencies.rst
  cdap-docs/tools/licenses/cdap-sandbox-dependencies.rst
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
Labels: 6.1, Docs, cla: yes

#11822 (CDAP-16212) Make querying of CDAP entities operation stats more efficient
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
Labels: 6.2, cla: yes

#11823 Updates MD5 checksum for cdap-default.xml for docs build
  cdap-docs/_common/common-build.sh
  cdap-docs/admin-manual/build.sh
Labels: 6.1, Docs, cla: yes

#11693 [CDAP-15941] Create DateTime widget
  cdap-docs/developer-manual/source/pipelines/developing-plugins/presentation-plugins.rst
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DateRangeWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/DateTimeWidget/index.tsx
  cdap-ui/app/cdap/components/TimeRangePicker/ExpandableTimeRange.js
  cdap-ui/app/cdap/components/TimeRangePicker/TimeRangePicker.scss
  cdap-ui/app/cdap/components/TimeRangePicker/index.js
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/widget-container/widget-factory.js
Labels: 6.2, UI, cla: yes

#11826 Fix minor typo in release notes
  cdap-docs/reference-manual/source/release-notes.rst
Labels: 6.1, Docs, cla: yes

#11829 Bump distributions version to 6.1.1
  cdap-distributions/src/emr/install.sh
  cdap-distributions/src/hdinsight/pkg/install.sh
  cdap-distributions/src/hdinsight/pkg/mainTemplate.json
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
  cdap-distributions/src/packer/files/cdap-sdk.json
Labels: cla: yes

#11815 [CDAP-16198] Add Multi Row Integration Tests
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/Container.tsx
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/CSVWidget/CSVRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueDropdownWidget/KeyValueDropdownRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueWidget/KeyValueRow.tsx
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/widgets.CSVWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueDropdownWidget.spec.ts
  cdap-ui/cypress/integration/widgets.KeyValueWidget.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/tsconfig.json
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.2, UI, cla: yes

#11805 [CDAP-14284] Adds base implementation to handle different types of nodes in React
  cdap-ui/app/cdap/components/DAG/DAGProvider.tsx
  cdap-ui/app/cdap/components/DAG/DAGRenderer.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/AbstractNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/AlertPublisherNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/Default/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/ErrorNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/SinkNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/SourceNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/TransformNode/index.tsx
  cdap-ui/app/cdap/components/DAG/Nodes/utilities.ts
  cdap-ui/app/cdap/components/DAG/index.tsx
Labels: 6.2, UI, cla: yes

#11831 [CDAP-16215] changing text color in error banner
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/styles/common.less
Labels: 6.2, Bug, UI, cla: yes

#11816 [CDAP-16201] Integration test for stage level validation
  cdap-ui/app/cdap/components/AbstractWidget/AbstractMultiRowWidget/AbstractRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/MultipleValuesWidget/MultipleValuesRow.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/PropertyRow/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/WidgetWrapper/index.tsx
  cdap-ui/app/directives/complex-schema/complex-schema.html
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/cypress/integration/plugins.validation.spec.ts
Labels: 6.2, UI, cla: yes

#11835 CDAP-16111 add field count to relation datasets
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DatasetFieldLineageSummary.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FakeFieldLineageReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FieldLineageAdminTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
Labels: cla: yes

#11837 (CDAP-15633) Part 1. Runtime monitor client and server
  cdap-api/src/main/java/io/cdap/cdap/api/messaging/Message.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/MonitorSchemas.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataService.java
  cdap-app-fabric/src/main/resources/schema/v1/MonitorResponse.avsc
  cdap-app-fabric/src/main/resources/schema/v2/MonitorRequest.avsc
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/monitor/RuntimeMonitorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/metrics/MetricsReporterHook.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetService.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/executor/DatasetOpExecutorService.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/executor/ExploreExecutorService.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ProgramType.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/context/MessageIterator.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/MessagingHttpService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogQueryService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogSaverStatusService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsProcessorStatusService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryService.java
Labels: 6.2, cla: yes
