Repository cdapio/cdap, pull requests merged in 2020-12, with the labels that each got.

#12874 CDAP-17425 expose max preview records to sources
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/batch/BatchSourceContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
Labels: cla: yes

#12875 adding all gcp regions dataproc is available in
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
Labels: cla: yes

#12876 CDAP-17428 default stage consolidation to true
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
Labels: cla: yes

#12877 CDAP-17408 fix to honor partitions set by aggregators
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/ReducibleAggregatorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/AbstractSparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/aggregator/DistinctReducibleAggregator.java
Labels: cla: yes

#12855 [CDAP-17329] Give all popovers in the pipeline toolbar the same appearance
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineScheduleButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/PipelineScheduler.scss
  cdap-ui/app/cdap/components/PipelineScheduler/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/directives/my-pipeline-scheduler/my-pipeline-scheduler.html
  cdap-ui/app/directives/my-pipeline-scheduler/my-pipeline-scheduler.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
  cdap-ui/app/hydrator/toppanel.less
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
Labels: 6.3, On-hold, UI, cla: yes

#12842 [CDAP-17393] Fix routing to compute profile in system namespace
  cdap-ui/app/cdap/services/NamespaceStore/index.ts
Labels: 6.3, Bug, UI, cla: yes

#12708 CDAP-17098 Add widget for Window Aggregation configuration
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/TextBox/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FunctionDropdownArgumentsWidget/FunctionDropdownArgumentsRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FunctionDropdownArgumentsWidget/__tests__/parser.tests.ts
  cdap-ui/app/cdap/components/AbstractWidget/FunctionDropdownArgumentsWidget/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/FunctionDropdownArgumentsWidget/parser.ts
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldDropdown/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Widgets.stories.tsx
  cdap-ui/app/cdap/components/AbstractWidget/index.tsx
Labels: 6.3, UI, cla: yes

#12868 [CDAP-17416] Fixes parsing resolution to show right label in x-axis of plugin metrics graph
  cdap-ui/app/cdap/components/PipelineNodeGraphs/PipelineNodeMetricsGraph.js
  cdap-ui/app/cdap/components/PipelineSummary/RunsGraphHelpers.js
  cdap-ui/app/cdap/components/PipelineSummary/__tests__/RunsGraphHelpers.test.ts
Labels: 6.3, UI, cla: yes

#12879 (CDAP-17439) Added runtime support for Hadoop + Spark 3
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/program/ManifestFields.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramClassLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginClassLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/HttpHandlerGenerator.java
  cdap-common/src/main/java/io/cdap/cdap/common/app/MainClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/ClassLoaders.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/GuavaClassRewriter.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/PackageFilterClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/internal/asm/Classes.java
  cdap-common/src/main/java/io/cdap/cdap/internal/asm/Methods.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/ClassLoaderTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterAuditLookUp.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeUtils.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkRuntimeEnv.scala
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppenderInitializer.java
  pom.xml
Labels: 6.3, cla: yes

#12880 CDAP-17389 improvements to dataproc provisioner
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12853 [CDAP-17321] Exclude system apps from pipeline count
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: 6.3, cla: yes

#12884 [CDAP-17321] Exclude system apps from pipeline count
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: cla: yes

#12882 [CDAP-17422] Updates the Namespace Admin link in App Drawer to naviga…
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
Labels: 6.3, UI, cla: yes

#12872 [CDAP-16637][CDAP-16638] Replication move source list to source config
  cdap-ui/app/cdap/components/EntityTopPanel/EntityTopPanel.scss
  cdap-ui/app/cdap/components/PlusButton/PlusButton.scss
  cdap-ui/app/cdap/components/PlusButton/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/PluginCard/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/PluginList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SourceConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/TargetConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/SourceList/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/index.tsx
  cdap-ui/app/cdap/components/Replicator/index.tsx
Labels: 6.3, UI, cla: yes

#12873 [CDAP-17409] Replication throughput graph
  cdap-ui/app/cdap/api/metric.js
  cdap-ui/app/cdap/api/replicator.js
  cdap-ui/app/cdap/components/ChartContainer/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Metrics/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.3, UI, cla: yes

#12867 [CDAP-17416] Show correct stage name in input schema
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
Labels: 6.3, UI, cla: yes

#12869 [CDAP-17417] Replace old schema editor with new schema editor in react side of app
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/AddRowButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/Nullable.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/RemoveRowButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DatasetDetailedView/Tabs/index.js
  cdap-ui/app/cdap/components/Experimental/index.js
  cdap-ui/app/cdap/components/Overview/DatasetOverview/DatasetOverviewTab.js
  cdap-ui/app/cdap/components/Overview/Tabs/SchemaTab/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/ExplicitSchemaDefiner/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/cdap/components/SchemaEditor/AbstractSchemaRow/AbstractSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/AbstractSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/ArraySchemaRow/ArraySchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/ArraySchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/EnumSchemaRow/EnumSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/EnumSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/MapSchemaRow/MapSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/MapSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/RecordSchemaRow/RecordSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/RecordSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/SchemaEditor.scss
  cdap-ui/app/cdap/components/SchemaEditor/SchemaHelpers.js
  cdap-ui/app/cdap/components/SchemaEditor/SchemaStore.js
  cdap-ui/app/cdap/components/SchemaEditor/UnionSchemaRow/UnionSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/UnionSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/index.js
Labels: 6.3, UI, cla: yes

#12878 [CDAP-17410] Replication add latency graph
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/latency.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/index.tsx
Labels: 6.3, UI, cla: yes

#12881 [CDAP-17430] Replication table scatter plot graph
  cdap-ui/app/cdap/components/ChartContainer/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/latency.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.3, UI, cla: yes

#12890 System program management service to ensure system programs are working as expected
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes

#12864 [CDAP-16233] Fixes operations modal to show errors instead of showing…
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsModal.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
Labels: 6.3, UI, cla: yes

#12897 (CDAP-17355) New Drafts API
  cdap-api/src/main/java/io/cdap/cdap/api/service/http/HttpServiceRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/DefaultHttpServiceRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/CodedException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/Draft.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftCollisionException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftId.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftNotFoundException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStoreRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/SortRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioUtil.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DraftServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-test/src/main/java/io/cdap/cdap/test/MetricsManager.java
Labels: 6.3, cherry-pick, cla: yes

#12885 (CDAP-17355) New Drafts API
  cdap-api/src/main/java/io/cdap/cdap/api/service/http/HttpServiceRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/DefaultHttpServiceRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/CodedException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/Draft.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftCollisionException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftId.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftNotFoundException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStoreRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/SortRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioUtil.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DraftServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-test/src/main/java/io/cdap/cdap/test/MetricsManager.java
Labels: cla: yes

#12863 [CDAP-16566] Fix error collector in UI to show right input schema when connected to source
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/hydrator/controllers/create/canvas-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/controllers/detail/canvas-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12866 [CDAP-17413] Fixes joiner in-memory input stages to show correct value when input stages change
  cdap-ui/app/cdap/components/AbstractWidget/MultiStageSelector/index.tsx
Labels: 6.3, UI, cla: yes

#12894 Fixes rendering boolean values in pipeline preview
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
Labels: 6.3, UI, cla: yes

#12895 [CDAP-16626] Fix post action to use latest artifact version
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-select-action-step/wizard-select-action-step-ctrl.js
Labels: 6.3, UI, cla: yes

#12911 (CDAP-17439) Turn on Adaptive Query Execution in Spark 3 by default
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.3, cla: yes

#12912 (CDAP-17439) Turn on Adaptive Query Execution in Spark 3 by default
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.3, cla: yes

#12902 [CDAP-17417] Replace old schema editor with new schema editor in react side of app
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/AddRowButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/Nullable.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/RowButtons/RemoveRowButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/SchemaModal.js
  cdap-ui/app/cdap/components/DataPrep/TopPanel/index.js
  cdap-ui/app/cdap/components/DatasetDetailedView/Tabs/index.js
  cdap-ui/app/cdap/components/Experimental/index.js
  cdap-ui/app/cdap/components/Overview/DatasetOverview/DatasetOverviewTab.js
  cdap-ui/app/cdap/components/Overview/Tabs/SchemaTab/index.tsx
  cdap-ui/app/cdap/components/PluginJSONCreator/Create/Content/OutputPage/ExplicitSchemaDefiner/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/cdap/components/SchemaEditor/AbstractSchemaRow/AbstractSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/AbstractSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/ArraySchemaRow/ArraySchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/ArraySchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/EnumSchemaRow/EnumSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/EnumSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/MapSchemaRow/MapSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/MapSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/RecordSchemaRow/RecordSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/RecordSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/SchemaEditor.scss
  cdap-ui/app/cdap/components/SchemaEditor/SchemaHelpers.js
  cdap-ui/app/cdap/components/SchemaEditor/SchemaStore.js
  cdap-ui/app/cdap/components/SchemaEditor/UnionSchemaRow/UnionSchemaRow.scss
  cdap-ui/app/cdap/components/SchemaEditor/UnionSchemaRow/index.js
  cdap-ui/app/cdap/components/SchemaEditor/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12903 [CDAP-16233] Fixes operations modal to show errors instead of showing loading icon
  cdap-ui/app/cdap/components/FieldLevelLineage/OperationsModal/OperationsModal.scss
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContext.tsx
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/Context/FllContextHelper.ts
  cdap-ui/app/cdap/components/FieldLevelLineage/v2/OperationsModal/ModalContent.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12904 [CDAP-16566] Fix error collector in UI to show right input schema when connected to source
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/hydrator/controllers/create/canvas-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/controllers/detail/canvas-ctrl.js
  cdap-ui/app/hydrator/services/hydrator-node-service.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12905 [CDAP-17413] Fixes joiner in-memory input stages to show correct value when input stages change
  cdap-ui/app/cdap/components/AbstractWidget/MultiStageSelector/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12906 Fixes rendering boolean values in pipeline preview
  cdap-ui/app/cdap/components/PreviewData/DataView/Table.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12907 [CDAP-16626] Fix post action to use latest artifact version
  cdap-ui/app/directives/my-post-run-action-wizard/wizard-select-action-step/wizard-select-action-step-ctrl.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12908 [CDAP-17422] Updates the Namespace Admin link in App Drawer to navigate to namespace detail instead of system admin
  cdap-ui/app/cdap/components/AppHeader/AppDrawer/AppDrawer.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12899 CDAP-17059 validate no actions in the middle of a pipeline
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: cla: yes

#12915 CDAP-17059 validate no actions in the middle of a pipeline
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: cla: yes

#12823 [CDAP-16889] replication unit tests
  cdap-ui/app/cdap/components/Replicator/utilities/__tests__/utilities.test.ts
Labels: 6.3, UI, cla: yes

#12889 [CDAP-17444] Replication add metrics table list view
  cdap-ui/app/cdap/components/Replicator/Detail/ChartTableSwitcher/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/LatencyTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.3, UI, cla: yes

#12898 CDAP-16527 include field name in casting errors for records
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordBuilderTest.java
Labels: cla: yes

#12893 [CDAP-17453][CDAP-17445][CDAP-17443] Replication graph tooltip, table selection, and time selections
  cdap-ui/app/cdap/components/ChartContainer/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/SelectedTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/LatencyTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/LatencyTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/LatencyGraph/latency.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/TimePeriodDropdown/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.3, UI, cla: yes

#12917 CDAP-16527 include field name is casting errors for records
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordBuilderTest.java
Labels: cla: yes

#12913 [CDAP-15593] Fix pipeline validation to show right error message if the studio service is down
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.4, UI, cla: yes

#12914 [CDAP-16242] Fixes description to be sent as part of config while updating the pipeline
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
Labels: 6.4, UI, cla: yes

#12916 [CDAP-17469] Remove artifact information from PluginListWidget and collapse options
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.4, UI, cla: yes

#12888 [CDAP-17282] Update UI to use new Drafts API + manages existing drafts in user store
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftCount/DraftCount.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/types.ts
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/services/hydrator/my-pipeline-api.js
  cdap-ui/cypress/fixtures/old_userstore_draft.json
  cdap-ui/cypress/integration/pipeline.draft.spec.ts
Labels: 6.4, UI, cla: yes

#12910 [CDAP-16962] Fix pipeline saving as draft to error in simillar way when deployed with space in pipeline name
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.4, UI, cla: yes

#12900 [CDAP-16909] Fixes showing error message while saving/running pipeline with invalid profile
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/RuntimeArgsModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
Labels: 6.4, UI, cla: yes

#12920 (CDAP-17474) Allow configuring ElasticSearch to trust all certs
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
Labels: 6.4, cla: yes

#12901 [CDAP-17461] Replication operations dashboard redesign
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/NamespacesPicker/NamespacesPopover.js
  cdap-ui/app/cdap/components/NamespacesPicker/index.js
  cdap-ui/app/cdap/components/Operations/JobsTable/index.tsx
  cdap-ui/app/cdap/components/Operations/TimePicker/index.tsx
  cdap-ui/app/cdap/components/Operations/index.tsx
  cdap-ui/app/cdap/components/Operations/parser.ts
  cdap-ui/app/cdap/components/Status/StatusIndicator.tsx
  cdap-ui/app/cdap/components/Status/index.tsx
  cdap-ui/app/cdap/components/Table/TableRow.tsx
  cdap-ui/app/cdap/services/ThemeHelper.ts
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.3, UI, cla: yes

#12922 Fix ClassNotFound error in DraftStore
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
Labels: cla: yes

#12923 Fix ClassNotFound error in DraftStore
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
Labels: 6.3, cherry-pick, cla: yes

#12921 [CDAP-17282] Update UI to use new Drafts API + manages existing drafts in user store
  cdap-ui/app/cdap/api/pipeline.js
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftCount/DraftCount.scss
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/DraftTableRow.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/DraftTable/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/types.ts
  cdap-ui/app/hydrator/routes.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/services/hydrator/my-pipeline-api.js
  cdap-ui/cypress/fixtures/old_userstore_draft.json
  cdap-ui/cypress/integration/pipeline.draft.spec.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#12909 Forceably disables latency notifications experiment in UI
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
  cdap-ui/app/cdap/components/Lab/index.tsx
Labels: 6.3, UI, cla: yes

#12870 [CDAP-17420] Fixes pipeline to correctly render splitter transform endpoints to be able to construct pipeline from scratch
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
  cdap-ui/app/directives/splitter-popover/splitter-popover.html
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.plugin.multipleendpoints.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.4, UI, cla: yes

#12930 [CDAP-17420] Fixes pipeline to correctly render splitter transform endpoints to be able to construct pipeline from scratch
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag-factory.js
  cdap-ui/app/directives/splitter-popover/splitter-popover.html
  cdap-ui/cypress/fixtures/union_condition_splitter_pipeline_v1-cdap-data-pipeline.json
  cdap-ui/cypress/helpers.ts
  cdap-ui/cypress/integration/pipeline.plugin.multipleendpoints.spec.ts
  cdap-ui/cypress/support/commands.ts
  cdap-ui/cypress/typings/index.d.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#12928 [CDAP-17469] Remove artifact information from PluginListWidget and co…
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12918 [CDAP-16242] Fix pipeline validation to show right error message if the studio service is down
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12919 [CDAP-16242] Fixes description to be sent as part of config while updating the pipeline
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12924 [CDAP-16962] Fix pipeline saving as draft to error in similar way when deployed with space in pipeline name
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12926 [CDAP-16909] Fixes showing error message while saving/running pipeline with invalid profile
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/RuntimeArgsModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/cypress/integration/pipeline.runtimeargs.spec.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#12929 Forceably disables latency notifications experiment in UI
  cdap-ui/app/cdap/components/Lab/experiment-list.tsx
  cdap-ui/app/cdap/components/Lab/index.tsx
Labels: 6.4, UI, cherry-pick, cla: yes

#12861 [CDAP-11761] Highlight current file in connector browser for file system, S3, GCS
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/S3Browser.scss
  cdap-ui/app/cdap/components/FileBrowser/FileBrowser.scss
  cdap-ui/app/cdap/components/FileBrowser/index.js
Labels: 6.4, UI, cla: yes

#12932 [CDAP-17479] Fixes js error while navigating to namespace detail page
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
Labels: 6.4, UI, cla: yes

#12925 [CDAP-15259] Populate schema on database source created by Wrangler
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
Labels: 6.4, UI, cla: yes

#12935 Fixed bug where draft creation failed due to null userId
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
Labels: cla: yes

#12936 Fixed bug where draft creation failed due to null userId
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
Labels: 6.3, cherry-pick, cla: yes

#12943 CDAP-17331 Reduce log level to trace for logging count of messages processed in TMS topic.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
Labels: cla: yes

#12944 CDAP-17331 Reduce log level to trace for logging count of messages processed in TMS topic.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
Labels: 6.3, cla: yes

#12941 CDAP-16812 update some dataproc info blurbs
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12940 CDAP-16812 update some dataproc info blurbs
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: cla: yes

#12934 [CDAP-16098] Fixes records out graph to show the right data in pipeline summary
  cdap-ui/app/cdap/components/PipelineSummary/Store/PipelineSummaryActions.js
Labels: 6.4, UI, cla: yes

#12945 System program management service to ensure system programs are running
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.3, cherry-pick, cla: yes

#12939 [CDAP-17479] Fixes js error while navigating to namespace detail page
  cdap-ui/app/cdap/components/NamespaceDropdown/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12931 [CDAP-17294] Fixes pipelines list to show the right count when searching for pipelines
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/PipelineCount.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
Labels: 6.4, UI, cla: yes

#12937 [CDAP-17381] Fix system services to not allow users to edit no.of instances requested for the service
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/ServicesTable.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/index.js
Labels: 6.4, UI, cla: yes

#12883 Added: InputKeyValueDropdown widget
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldKeyValueDropdown/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueDropdownWidget/KeyValueDropdownRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Widgets.stories.tsx
Labels: 6.4, UI, cla: yes

#12933 [CDAP-17442] Fix post-run notifications for deployed pipelines take 2
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/cdap/components/PostRunActions/index.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.html
  cdap-ui/cypress/integration/pipeline.postrunactions.spec.ts
Labels: 6.4, UI, cla: yes

#12946 [CDAP-16118] Set default properties when adding nodes to the canvas
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
Labels: 6.4, UI, cla: yes

#12952 [CDAP-15755] Check for valid pipeline before triggering preview run
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.4, UI, cla: yes

#12938 [CDAP-17470] Replication address UX review
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Password/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/MacroIndicator/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/WidgetWrapper/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/tableStyles.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/PluginList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/TableList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ContentHeading/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/Metrics/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/Metrics/parser.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/LatencyGraph/latency.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Drafts/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/app/cdap/services/PipelineErrorFactory.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.4, UI, cla: yes

#12949 [CDAP-16098] Fixes records out graph to show the right data in pipeline summary
  cdap-ui/app/cdap/components/PipelineSummary/Store/PipelineSummaryActions.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12950 [CDAP-17294] Fixes pipelines list to show the right count when searching for pipelines
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/PipelineCount.scss
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/PipelineCount/index.tsx
  cdap-ui/app/cdap/components/PipelineList/DeployedPipelineView/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12951 [CDAP-17381] Fix system services to not allow users to edit no.of instances requested for the service
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/ServicesTable.scss
  cdap-ui/app/cdap/components/Administration/AdminManagementTabContent/ServicesTable/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12961 [CDAP-17470] Replication address UX review
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Password/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/MacroIndicator/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/WidgetWrapper/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/DynamicPluginFilters.ts
  cdap-ui/app/cdap/components/Home/index.js
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/tableStyles.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/PluginList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/TableList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ContentHeading/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/Metrics/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/Metrics/parser.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/LatencyGraph/latency.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/ThroughputTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/ThroughputGraph/throughput.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Drafts/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/app/cdap/services/PipelineErrorFactory.js
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12960 Fixed bug in Drafts API that would result in all endpoints failing when running on CloudSQL
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/SortRequest.java
Labels: 6.3, cherry-pick, cla: yes

#12959 Fixed bug in Drafts API that would result in all endpoints failing when running on CloudSQL
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/draft/SortRequest.java
Labels: cla: yes

#12947 [CDAP-17480] Fixes surfacing the right error message when saving draft fails
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.4, UI, cla: yes

#12948 [CDAP-12429][CDAP-17463] Wrangler: Warn about problems with column names
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/index.js
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.4, UI, cla: yes

#12953 [CDAP-11761] Highlight current file in connector browser for file system, S3, GCS for 6.3
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/BrowserData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/TableContents.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/BucketData/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/S3Browser.scss
  cdap-ui/app/cdap/components/FileBrowser/FileBrowser.scss
  cdap-ui/app/cdap/components/FileBrowser/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12954 [CDAP-15259] Populate schema on database source created by Wrangler for 6.3
  cdap-ui/app/cdap/components/DataPrep/TopPanel/PipelineConfigHelper.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12955 [CDAP-17442] Fix post-run actions modal for deployed pipelines for 6.3
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PostRunActions/PostRunActionsWizard.js
  cdap-ui/app/cdap/components/PostRunActions/index.js
  cdap-ui/app/directives/my-pipeline-configurations/my-batch-pipeline-config/my-batch-pipeline-config.html
  cdap-ui/app/directives/my-post-run-actions/my-post-run-actions.html
  cdap-ui/cypress/integration/pipeline.postrunactions.spec.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#12956 [CDAP-16118] Set default properties when adding nodes to the canvas for 6.3
  cdap-ui/app/hydrator/controllers/create/leftpanel-ctrl.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12957 [CDAP-15755] Check for valid pipeline before triggering preview run 6.3
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12958 [CDAP-12429][CDAP-17463] Wrangler: Updated warning messages for duplicate column name and invalid characters in name for 6.3
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/index.js
  cdap-ui/app/cdap/components/TextboxOnValium/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.3, UI, cherry-pick, cla: yes

#12963 Added: InputKeyValueDropdown widget
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/InputFieldKeyValueDropdown/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/KeyValueDropdownWidget/KeyValueDropdownRow.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Widgets.stories.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#12968 [CDAP-17480] Fixes surfacing the right error message when saving draft fails
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12966 [CDAP-17483] Fix logical type for preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.2, cla: yes

#12967 [CDAP-17483] Fix logical type for preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.1, cla: yes

#12964 [CDAP-17483] Fix logical type for preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.3, cla: yes

#12962 (CDAP-16008) Added Kerberos support to Remote Hadoop provisioner
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/security/TokenSecureStoreRenewer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/security/impersonation/DefaultUGIProvider.java
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
  cdap-runtime-ext-remote-hadoop/src/main/java/io/cdap/cdap/runtime/spi/provisioner/remote/RemoteHadoopConf.java
  cdap-runtime-ext-remote-hadoop/src/main/java/io/cdap/cdap/runtime/spi/provisioner/remote/RemoteHadoopProvisioner.java
  cdap-runtime-ext-remote-hadoop/src/main/resources/remote-hadoop.json
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ClusterProperties.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/DefaultImpersonator.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/test/java/io/cdap/cdap/security/impersonation/SecurityUtilTest.java
Labels: 6.4, cla: yes

#12971 [CDAP-17371] Replication UI to query metrics using fully qualified ta…
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/SelectedTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.4, UI, cla: yes

#12972 [CDAP-17371] Replication UI to query metrics using fully qualified ta…
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/SelectedTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/scatterPlot.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#12973 (CDAP-16008) Added pre-job validation for kerberos information
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
Labels: 6.4, cla: yes

#12975 [PLUGIN-345] Remove parse-as-date from UI to begin deprecation
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
Labels: 6.4, UI, cla: yes

#12974 [CDAP-17485] Fix runtime args position when running pipeline
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
Labels: 6.4, UI, cla: yes

#12976 [CDAP-17487] Fix Runtime Args for completed Pipeline runs
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
Labels: 6.4, UI, cla: yes

#12978 [CDAP-17485] Fix runtime args position when running pipeline
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12980 [CDAP-17489] Fixes navigating to detailed pipeline while duplicating existing pipeline
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.3, UI, cla: yes

#12979 [CDAP-17487] Fix Runtime Args for completed Pipeline runs
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
Labels: 6.3, UI, cherry-pick, cla: yes

#12977 [PLUGIN-345] Remove parse-as-date from UI to begin deprecation
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#12984 Fixes UI build. Adds newline at the end of the file 'PipelineModelessOld.scss'
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
Labels: 6.3, UI, cla: yes

#12986 CDAP-17507 Enable Wrangler and studio by default for all distributions
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-common/src/main/resources/capability/dataprep.json
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-master/src/main/resources/capability/dataprep.json
  cdap-master/src/main/resources/capability/pipeline.json
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/capability/cdc.json
  cdap-standalone/src/main/resources/capability/dataprep.json
  cdap-standalone/src/main/resources/capability/pipeline.json
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: cla: yes

#12987 [Cherry-pick] CDAP-17507 Enable Wrangler and studio by default for all distributions
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-common/src/main/resources/capability/dataprep.json
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-master/src/main/resources/capability/dataprep.json
  cdap-master/src/main/resources/capability/pipeline.json
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/capability/cdc.json
  cdap-standalone/src/main/resources/capability/dataprep.json
  cdap-standalone/src/main/resources/capability/pipeline.json
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: 6.3, cherry-pick, cla: yes

#12990 Fixing Capability management flaky test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: cla: yes

#12991 [Cherry-pick] Fixing Capability management flaky test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: cla: yes

#12983 Fix flaky unit test
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.3, cla: yes

#12970 (CDAP-16008) Added Kerberos support to Remote Hadoop provisioner
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/security/TokenSecureStoreRenewer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/security/impersonation/DefaultUGIProvider.java
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
  cdap-runtime-ext-remote-hadoop/src/main/java/io/cdap/cdap/runtime/spi/provisioner/remote/RemoteHadoopConf.java
  cdap-runtime-ext-remote-hadoop/src/main/java/io/cdap/cdap/runtime/spi/provisioner/remote/RemoteHadoopProvisioner.java
  cdap-runtime-ext-remote-hadoop/src/main/resources/remote-hadoop.json
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ClusterProperties.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/DefaultImpersonator.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/test/java/io/cdap/cdap/security/impersonation/SecurityUtilTest.java
Labels: 6.3, cla: yes

#12993 fix build failure -- add new line to the end of file
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
Labels: cla: yes

#12994 (CDAP-17507) Default starting pipeline studio and dataprep system app
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/Retries.java
  cdap-common/src/main/resources/system-apps/cdc.json
  cdap-master/pom.xml
  cdap-master/src/main/resources/bootstrap/distributed.json
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/bootstrap/sandbox.json
Labels: 6.4, cla: yes

#12995 (CDAP-17507) Default starting pipeline studio and dataprep system app
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/Retries.java
  cdap-common/src/main/resources/system-apps/cdc.json
  cdap-master/pom.xml
  cdap-master/src/main/resources/bootstrap/distributed.json
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/bootstrap/sandbox.json
Labels: 6.3, cla: yes

#13001 [CDAP-17519] Log NPE in pipeline app
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: 6.4, cla: yes
