Repository cdapio/cdap, pull requests merged in 2021-05, with the labels that each got.

#13355 use a different store name to avoid conflict
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/ConnectionStore.java
Labels: build, cla: yes

#13358 [CDAP-17943] Add an option to run new aggregation without kryo
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/ReducibleAggregatorTestBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/ReducibleDatasetAggregatorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: build, cla: yes

#13359 🍒 [CDAP-17943] Add an option to run new aggregation without kryo
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/ReducibleAggregatorTestBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/src/test/java/io/cdap/cdap/datapipeline/ReducibleDatasetAggregatorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: 6.4, build, cla: yes

#13348 CDAP-17903 Allow reusing connection in pipeline
  cdap-api-common/src/main/java/io/cdap/cdap/internal/io/SchemaTypeAdapter.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfig.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginPropertyField.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginFieldNamingStrategy.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/plugin/nested/NestedConfigPlugin.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/OAuthMacroEvaluator.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSink.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: build, cla: yes

#13356 CDAP-17905 support emit metadata in plugin
  cdap-api/src/main/java/io/cdap/cdap/api/annotation/Metadata.java
  cdap-api/src/main/java/io/cdap/cdap/api/annotation/MetadataProperty.java
  cdap-api/src/main/java/io/cdap/cdap/api/metadata/MetadataEntity.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassesWithMetadata.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataValidator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/plugins/test/TestPlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/plugins/test/TestPlugin2.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/system/AbstractSystemMetadataWriter.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MetadataMutation.java
Labels: build, cla: yes

#13357 Added submitter lifecycle support for SQL engine.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BatchPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/submit/PipelinePhasePreparer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/engine/SQLEngineUtils.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLTransformationPushdown.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
Labels: build, cla: yes

#13360 Add a SonarCloud run to see code coverage
  .github/workflows/build-sonar.yml
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-data-fabric-tests/pom.xml
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-elastic/pom.xml
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  cdap-master/pom.xml
  cdap-standalone/pom.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingPollingService.java
  pom.xml
Labels: build, cla: yes

#13363 Log custom image uri instead of version if it's used
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build, cla: yes

#13361 [CDAP-17956] Don't exclude kafka scala.
  cdap-master/pom.xml
  pom.xml
Labels: build, cla: yes

#13365 CDAP-17942 fix macros in macro functions when skip invalid is set to …
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParser.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParserTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/TestMacroEvaluator.java
Labels: build, cla: yes

#13366 Add proper PR handling & fix jacoco support
  .github/workflows/build-sonar.yml
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-data-fabric-tests/pom.xml
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-elastic/pom.xml
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  cdap-master/pom.xml
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Action.java
  pom.xml
Labels: build, cla: yes

#13364 (CDAP-17853) Fix controller OOM
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramControllerCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/MapReduceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ServiceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkflowTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ScheduledRunRecordCorrectorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillProgramController.java
Labels: 6.5, build, cla: yes

#13368 [CDAP-17963] Fallback to copy if hardlinking failed (e.g. dirs on different FSes)
  cdap-common/src/main/java/io/cdap/cdap/common/lang/jar/BundleJarUtil.java
Labels: build, cla: yes

#13370 (CDAP-17888) Only rewrite methods defined in Authorizer interface
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizerClassLoader.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AuthorizerInstantiatorTest.java
Labels: 6.5, build, cla: yes

#13371 (CDAP-17853) Multiple fixes around runtime service
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementTestApp.java
Labels: 6.5, build, cla: yes

#13374 (CDAP-17853) Cherry-picking into release 6.3
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramControllerCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/MapReduceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ServiceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkflowTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementTestApp.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillProgramController.java
Labels: 6.3, build, cla: yes

#13372 (CDAP-17853) Cherry picking changes into release 6.4
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/RemoteExecutionProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramControllerCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/MapReduceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ServiceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkflowTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/SimpleRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ScheduledRunRecordCorrectorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementTestApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillProgramController.java
Labels: 6.4, build, cla: yes

#13375 CDAP-17941 add connection browse and sample
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/LimitingConnector.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/batch/BatchConnector.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseDetail.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseEntity.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/Connector.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/ConnectorSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/SampleRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/preview/LimitingInputFormatProvider.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/validation/SimpleFailureCollector.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/ConnectionBadRequestException.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/SampleResponse.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/SampleResponseCodec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/test/java/io/cdap/cdap/etl/proto/connection/SampleResponseCodecTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/connector/FileConnector.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: build, cla: yes

#13378 Migrate to the latest checkstyle to make it compatible with the Intellij plugin
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-common/src/main/java/io/cdap/cdap/common/options/OptionsParser.java
  cdap-common/src/main/java/io/cdap/cdap/common/service/Services.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/DirUtils.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/FileUtils.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/OSDetector.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data/runtime/DataFabricDistributedModule.java
  cdap-hbase-compat-base/src/test/java/io/cdap/cdap/data/hbase/HBaseTestBase.java
  cdap-master/src/main/java/io/cdap/cdap/common/MasterUtils.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationUpdateDetail.java
  cdap-test/src/main/java/io/cdap/cdap/test/ApplicationManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/plugins/LocationTriggeringPolicy.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerService.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MockMetricsWriterProvider.java
  checkstyle.xml
  pom.xml
Labels: build, cla: yes

#13381 CDAP-17983: disable task worker pods by default
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: 6.5, build, cla: yes

#13382 CDAP-17864 Tweaked plugin lifecycle for SQL engine.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/SerializableTransform.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/BatchSQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngineException.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockPullDataset.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockPushDataset.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngine.java
Labels: build, cla: yes

#13376 CDAP-17939 partition tms topics
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/AbstractMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/MessageTableKey.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RawMessageTableEntry.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RollbackRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/ScanRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/hbase/HBaseMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartition.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManager.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/PartitionedDBScanIterator.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/MessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/TestMessageEntry.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManagerTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTTLCleanupTest.java
Labels: 6.5, build, cla: yes

#13384 Fixed bug with Emitter emitting repeated values.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/TransformFromPairFunction.java
Labels: build, cla: yes

#13385 Updated SQL Engine Collection to prevent unnecessary pull operations.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLBackedCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/WrappedSQLEngineCollection.java
Labels: build, cla: yes

#13388 CDAP-17990 add a default flag to connection
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/ConnectionStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/connection/ConnectionStoreTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/Connection.java
Labels: build, cla: yes

#13386 CDAP-17939 upgrade old tms message tables
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/TableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManager.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
Labels: 6.5, build, cla: yes

#13387 CDAP-17989 add spec endpoint
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/LimitingConnector.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/Connector.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/ConnectorSpecRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/SpecGenerationRequest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/connector/FileConnector.java
Labels: build, cla: yes

#13391 Cdap 17939 partition tms 64
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/AbstractMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/MessageTableKey.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RawMessageTableEntry.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RollbackRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/ScanRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/TableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/hbase/HBaseMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartition.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManager.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/PartitionedDBScanIterator.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/MessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/TestMessageEntry.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManagerTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTTLCleanupTest.java
Labels: 6.4, build, cla: yes

#13397 add step to pull submodules for github actions
  .github/workflows/build-sonar.yml
  .github/workflows/build.yml
Labels: 6.5, build, cla: yes

#13395 Excluding all transitive dependencies from hive-exec
  pom.xml
Labels: 6.5, build, cla: yes

#13398 Commented out flacky assertion until after flackiness is fixed in CDA…
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: build, cla: yes

#13405 Fix javadoc links
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13402 Excluding the pentaho dependency from hive-exec
  pom.xml
Labels: build, cla: yes

#13403 Add logic to allow the SQL engine to validate if a join can be executed.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/request/SQLJoinDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/request/SQLJoinRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/test/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriverTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngine.java
Labels: build, cla: yes

#13407 Wrap UnauthorizedException into DatasetManagementException to preserve stable API for plugins (no "throws AccessException" added)
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/DatasetManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/NameMappedDatasetFramework.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingSourceContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/action/ActionContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/batch/BatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/customaction/BasicActionContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/AbstractBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ExternalDatasets.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingSourceContext.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/DefaultDatasetManager.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/DatasetFramework.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/ForwardingDatasetFramework.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/preview/PreviewDatasetFramework.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceAuthorizationTest.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/executor/ExploreExecutorHttpHandler.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAuthorizationContext.java
  cdap-unit-test/src/test/java/io/cdap/cdap/admin/AdminApp.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: build, cla: yes

#13401 Refactoring: introduce MasterEnvironmentRunnableContext to be passed to MasterEnvironmentRunnable
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/FileLocalizer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentRunnableContext.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/MockMasterEnvironment.java
Labels: 6.5, build, cla: yes

#13406 CDAP-17965 Made pod deletion call synchronous and ignore exception other than the ApiException till CDAP-18000 is fixed.
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
Labels: build, cla: yes

#13408 Fix tms upgrade
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
Labels: 6.4, build, cla: yes

#13412 Small optimization of EntityId.getHierarchy.
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/id/EntityIdTest.java
Labels: build, cla: yes

#13404 Introduce StandardPermission.LIST, add support for parent-only permissions and migrate profiles to new permission model
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AuthorizationModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesNoCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesTestBase.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/AuthorizationCLITest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Authorizable.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/StandardPermission.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/security/AuthorizableTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/AccessEnforcer.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/NoOpAccessController.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-security/src/main/java/io/cdap/cdap/proto/security/AuthorizationPrivilege.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessEnforcerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DelegatingPermissionManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemoteAccessEnforcer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/InMemoryAccessController.java
Labels: build, cla: yes

#13414 [CDAP-18012] Fix tms upgrade by making sure appropriate dirs are crea…
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
Labels: 6.4, build, cla: yes

#13417 Bugfix dev/cdap 18012 fix tms
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
Labels: 6.5, build, cla: yes

#13416 Make AccessException extend RuntimeException to ensure backwards compatibility
  cdap-api/src/main/java/io/cdap/cdap/api/security/AccessException.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/AbstractCachedUGIProvider.java
Labels: build, cla: yes

#13419 Corrected logic issue with wrapped SQL engine collections.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/WrappedSQLEngineCollection.java
Labels: build, cla: yes

#13422 Update MD5 for 6.4.0
  cdap-docs/admin-manual/build.sh
Labels: build, cla: yes

#13400 Move UnauthenticatedException to security spi near to other security exceptions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/UnsupportedExploreClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/CLIConfig.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/AbstractGetPreferencesCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetWorkflowLocalDatasetsCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetWorkflowStateCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetWorkflowTokenCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/app/BaseBatchCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/AppIdCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/DatasetModuleNameCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/DatasetNameCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/DatasetTypeNameCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/HttpEndpointPrefixCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/HttpMethodPrefixCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/ProgramIdCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/util/AbstractAuthCommand.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/AbstractClientTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetaClientAvailableTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetaClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/NamespaceClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/util/RESTClientTest.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ArtifactClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/AuthorizationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/DatasetClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/DatasetModuleClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/DatasetTypeClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/LineageClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/MetaClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/MetadataClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/MetricsClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/MonitorClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/NamespaceClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/PreferencesClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ScheduleClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/SecureStoreClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ServiceClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/WorkflowClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/util/RESTClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/AbstractMetadataClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/namespace/AbstractNamespaceQueryClient.java
  cdap-explore-client/src/main/java/io/cdap/cdap/explore/client/AbstractExploreClient.java
  cdap-explore-client/src/main/java/io/cdap/cdap/explore/client/ExploreClient.java
  cdap-explore-client/src/main/java/io/cdap/cdap/explore/client/ExploreHttpClient.java
  cdap-explore-client/src/main/java/io/cdap/cdap/explore/client/MockExploreClient.java
  cdap-explore-jdbc/src/main/java/io/cdap/cdap/explore/jdbc/ExploreDriver.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestBase.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/RemoteDatasetAdmin.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteSparkManager.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/remote/RemoteWorkflowManager.java
  cdap-integration-test/src/test/java/io/cdap/cdap/test/IntegrationTestBaseTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authentication/UnauthenticatedException.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/AppWithMetadataPrograms.java
Labels: build, cla: yes

#13425 CDAP-18010: Renaming ArtifactInspector to DefaultArtifactInspector
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspectorTest.java
Labels: 6.5, build, cla: yes

#13411 Fix bug in which task worker http handler shuts down before sending response
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
Labels: 6.5, build, cla: yes

#13431 CDAP-18010: Introduce ArtifactInspector interface
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
Labels: 6.5, build, cla: yes

#13435 CDAP-18030: Steps with multiple inputs within a condition branch are valid when condition is a source
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: build, cla: yes

#13413 CDAP-18010: Run artifact inspection in isolation.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/worker/RunnableTaskContext.java
Labels: 6.5, build, cla: yes
