Repository cdapio/cdap, pull requests merged in 2021-10, with the labels that each got.

#13608 [CDAP-18318] Adding Authorization Checks for MonitorHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/MonitorHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/MonitorHandlerAuthorizationTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/InstanceId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Authorizable.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
Labels: cla: yes, build, 6.5

#13680 CDAP-18504 use ip instead hostname for spark execution service
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkExecutionService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: cla: yes, build, 6.6

#13681 [CDAP-18318] Adding Authorization Checks and tests for MonitorHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/MonitorHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/MonitorHandlerAuthorizationTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/InstanceId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Authorizable.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
Labels: cla: yes, cherry-pick, build, 6.5

#13678 [CDAP-18504] Add config maps for spark localize resources with compression
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkLocalizeResource.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkSubmitContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerExecutorLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/LocalSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/SparkSubmitter.java
Labels: cla: yes, build, 6.6

#13682 Make sure no duplicate artifacts are localized
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
Labels: cla: yes, build, 6.6

#13676 [CDAP-18455] Pass artifact fetcher port to spark executors
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerExecutorLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core3_2.12/src/k8s/entrypoint.sh
Labels: cla: yes, build, 6.6

#13683 [CDAP-18529] Added macro evaluator support for Transformation Pushdown
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
Labels: cla: yes, build, bq-pushdown

#13719 [CDAP-18586] Deprecate getApplicationSpecification in ProgramStatusTriggerInfo
  cdap-api/src/main/java/io/cdap/cdap/api/schedule/ProgramStatusTriggerInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/trigger/DefaultProgramStatusTriggerInfo.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/TriggeringScheduleInfoAdapterTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
Labels: cla: yes, build, 6.6
