Repository cdapio/cdap, pull requests merged in 2021-03, with the labels that each got.

#13153 [CDAP-17717] Fixes alerts and errors with space in names to be connected properly
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.4, UI, build, cla: yes

#13152 CDAP-17719 exclude conflicting asm version
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
Labels: build, cla: yes

#13155 (CDAP-17618) Added support for file based key manager in distributed mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/CConfigurationUtil.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/AuthServerAnnounceTest.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMainTest.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AbstractKeyManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/DistributedKeyManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/FileBasedKeyManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/DistributedSecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/FileBasedSecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/InMemorySecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/SecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/SecurityModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/runtime/AuthenticationServerMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AuthenticationTool.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/FileBasedTokenManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractorTest.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: 6.4, build, cla: yes

#13144 [CDAP-17476] Added logic to return running records as of the start of the window for the dashboard.
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/reporting/ProgramHeartbeatService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/reporting/ProgramHeartbeatTable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/reporting/ProgramHeartBeatTableTest.java
Labels: cla: yes

#13161 Use 0.13.0 version of cdap-common
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
  cdap-app-templates/cdap-program-report/pom.xml
  pom.xml
Labels: build, cla: yes

#13159 [CDAP-17703] Fix using correct namesapce while saving draft
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
Labels: 6.3, UI, build, cla: yes

#13101 [CDAP-17651] Add support for auto install
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/HttpClients.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/autoinstall/HubPackage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/autoinstall/Spec.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-fabric/src/test/resources/cap1.json
  cdap-app-fabric/src/test/resources/cap2.json
  cdap-app-fabric/src/test/resources/packages.json
  cdap-app-fabric/src/test/resources/spec.json
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  pom.xml
Labels: 6.4, build, cla: yes

#13163 [CDAP-17724] Replication change pipeline to job
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TimePeriodSelection/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/index.tsx
Labels: 6.4, UI, cla: yes

#13164 [CDAP-17733] Do not Initialize TokenValidator when not in MANAGED mode.
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
Labels: 6.4, build, cla: yes, java

#13136 [CDAP-17241] Add Authorization Enforcement for Starting Preview Runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-common/src/main/java/io/cdap/cdap/common/security/AuthEnforceRewriter.java
  cdap-common/src/main/java/io/cdap/cdap/common/security/AuthEnforceUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/security/AuthEnforceUtilTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Action.java
Labels: 6.4, build, cla: yes, java

#13160 [CDAP-17028] Fixes UI to not show macro functions that doesn't need user input while running preview
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.4, UI, build, cla: yes

#13165 CDAP-17718 fix advanced join metrics
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: build, cla: yes

#13162 [CDAP-17683] Replication fix million indicator
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.4, UI, build, cla: yes

#13170 [CDAP-17683] Replication fix million indicator
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13172 [CDAP-17724] Replication change pipeline to job
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/DeleteConfirmation/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TimePeriodSelection/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/index.tsx
Labels: 6.4, UI, cherry-pick, cla: yes

#13169 CDAP-17718 fix advanced join metrics
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: 6.4, build, cla: yes

#13174 [CDAP-17733] 6.4 Cherrypick
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
Labels: 6.4, cherry-pick, cla: yes

#13175 [CDAP-17241] 6.4 Cherrypick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-common/src/main/java/io/cdap/cdap/common/security/AuthEnforceRewriter.java
  cdap-common/src/main/java/io/cdap/cdap/common/security/AuthEnforceUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/security/AuthEnforceUtilTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Action.java
Labels: 6.4, cherry-pick, cla: yes

#13173 [CDAP-17735] Fixed EntityId StackOverflow During GSON Serialization
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/codec/EntityIdTypeAdapterTest.java
Labels: 6.4, Bug, build, cla: yes, java

#13176 (CDAP-13281) Add UGI credentials in data pipeline app
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkFactory.java
Labels: build, cla: yes

#13179 [CDAP-17735] 6.4 Cherry-Pick
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/codec/EntityIdTypeAdapterTest.java
Labels: cla: yes

#13177 [CDAP-17598] Pipeline Summary - Adds visual treatment on metrics charts hover
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/index.js
  cdap-ui/app/cdap/components/PipelineSummary/GraphHint.scss
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/LogsMetricsGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesRecordsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/RunsHistoryGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/cdap/styles/colors.scss
Labels: 6.4, UI, build, cla: yes

#13178 (CDAP-13281) Add UGI credentials in data pipeline app
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkFactory.java
Labels: build, cla: yes

#13158 [CDAP-17598] Pipeline Summary - Adds visual treatment on metrics charts hover
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/index.js
  cdap-ui/app/cdap/components/PipelineSummary/GraphHint.scss
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/LogsMetricsGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/LogsMetricsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/NodesRecordsGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/PipelineSummary.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/RunsHistoryGraph.scss
  cdap-ui/app/cdap/components/PipelineSummary/RunsHistoryGraph/index.js
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/cdap/styles/colors.scss
Labels: 6.5, UI, build, cla: yes

#13103 [CDAP-17359] Add Hierarchy Widget for create record plugin
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTree.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/HierarchyTreeLeaf.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/InputFieldWrapper.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/PopoverButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/dataHandler.ts
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/index.tsx
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.4, UI, cla: yes

#13185 [CDAP-17717] Fixes alerts and errors with space in names to be connected properly
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.2, UI, build, cherry-pick, cla: yes

#13190 fix compilation typo
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
Labels: build, cla: yes

#13181 (CDAP-17721) Added Kerberos support in K8s environment
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: 6.5, build, cla: yes

#13183 [CDAP-17717] Fixes alerts and errors with space in names to be connected properly
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.3, UI, cherry-pick, cla: yes

#13191 Cherry-pick (CDAP-17721) Added Kerberos support in K8s environment
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: 6.4, build, cherry-pick, cla: yes

#13187 [CDAP-17028] Fixes UI to not show macro functions that doesn't need user input while running preview
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13180 [CDAP-17744] Fixes Schema editor to surface UI validation errors.
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaValidator/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/cypress/integration/plugin.schemaeditor.spec.ts
Labels: 6.5, UI, build, cla: yes

#13186 [CDAP-17028] Fix runtime arguments to check for logicalStartTime macro function to avoid user input
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.5, UI, build, cla: yes

#13168 [CDAP-17028] Fixes UI to not show macro functions that doesn't need user input while running preview
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: 6.3, UI, build, cla: yes

#13189 [CDAP-17359] Add hierarchy widget for create record plugin
  cdap-ui/app/cdap/components/AbstractWidget/AbstractWidgetFactory.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTree.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/HierarchyTreeLeaf.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/InputFieldWrapper.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/PopoverButton.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/HierarchyTreeNode/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/dataHandler.ts
  cdap-ui/app/cdap/components/AbstractWidget/HierarchyWidget/index.tsx
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13171 [CDAP-16180] Added logic to macros using preferences on the Plugin Validation stage.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13196 [CDAP-16180] Cherry Pick into 6.4
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13199 Revert "[CDAP-16180] Added logic to macros using preferences on the Plugin Validation stage."
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13200 Revert "[CDAP-16180] Cherry Pick into 6.4"
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13194 [CDAP-17744] Fixes Schema editor to surface UI validation errors.
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaValidator/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/cypress/integration/plugin.schemaeditor.spec.ts
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13195 [CDAP-17744] Fixes Schema editor to surface UI validation errors.
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaValidator/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/cdap/components/PluginSchemaEditor/index.tsx
  cdap-ui/app/hydrator/templates/partial/node-config-modal/node-config/plugin-edit-output-schema.html
  cdap-ui/cypress/integration/plugin.schemaeditor.spec.ts
Labels: 6.3, UI, build, cherry-pick, cla: yes

#13193 [CDAP-17400] Add logic to ensure plugin metadata back-fill only runs once
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
Labels: 6.5, build, cla: yes

#13197 [CDAP-17400] Add logic to ensure plugin metadata back-fill only runs once
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
Labels: 6.4, cherry-pick, cla: yes

#13192 Fix cypress version resolutions
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.5, Bug, UI, build, cla: yes

#13198 [CDAP-17564] Fix Dynamic Widget Race Condition
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
Labels: 6.5, Bug, UI, build, cla: yes

#13205 [CDAP-17564] Refactor Configuration Group
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13208 [CDAP-17737] Conditions do not work with spark3.
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/SparkStageStatisticsCollector.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/SparkStageStatisticsCollector.java
Labels: cla: yes

#13202 [CDAP-16180] Added logic to resolve preferences as macros on plugin validation
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FakePreferencesFetcher.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13210 [CDAP-16180] Cherry Pick into 6.4
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/FakePreferencesFetcher.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/validation/StageValidationRequest.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13213 [CDAP-17754] Workaround for Supporting Identity Propagation in Runtime Server
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
Labels: 6.4, Bug, cla: yes, java

#13206 [CDAP-16180] UI get schema to resolve macros from preferences
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.5, UI, build, cla: yes

#13207 [CDAP-16180] UI get schema to resolve macros from preferences
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.4, UI, cherry-pick, cla: yes

#13215 [CDAP-17754] Workaround Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
Labels: 6.4, cherry-pick, cla: yes, java

#13211 [CDAP-17761] Require formats with date and time for parse-as-datetime directive
  cdap-ui/app/cdap/components/DataPrep/Directives/Format/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/DateFormatModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
Labels: 6.5, UI, build, cla: yes

#13203 [CDAP-17709] Adds support for PROXY authentication mode in UI
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbarMenu.tsx
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/services/auth.js
  cdap-ui/app/services/data/my-cdap-datasource.js
  cdap-ui/app/services/file-uploader.js
  cdap-ui/app/services/settings.js
  cdap-ui/app/tracker/main.js
  cdap-ui/graphql/Query/pipelinesResolver.js
  cdap-ui/graphql/Query/statusResolver.js
  cdap-ui/graphql/graphql.js
  cdap-ui/graphql/helpers/BatchEndpoints/nextRuntime.js
  cdap-ui/graphql/helpers/BatchEndpoints/programRuns.js
  cdap-ui/graphql/helpers/BatchEndpoints/totalRuns.js
  cdap-ui/graphql/helpers/createLoaders.js
  cdap-ui/graphql/resolvers-common.js
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/config/router-check.js
  cdap-ui/server/express.js
  cdap-ui/server/token.mjs
Labels: 6.4, UI, build, cla: yes

#13204 Fix cypress version resolutions
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13217 [CDAP-17761] DateFormatModal: Pre-select sensible default when options are limited
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/DateFormatModal.js
Labels: 6.5, UI, build, cla: yes

#13219 [CDAP-17761] Require formats with date and time for parse-as-datetime for 6.4
  cdap-ui/app/cdap/components/DataPrep/Directives/Format/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/DateFormatModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13220 (CDAP-16180) Fix bindings for PreferencesFetcher
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/BasicHttpServiceContextFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemotePreferencesFetcherInternal.java
Labels: 6.5, build, cla: yes

#13221 (CDAP-16180) Fix bindings for PreferencesFetcher
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/BasicHttpServiceContextFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemotePreferencesFetcherInternal.java
Labels: cla: yes

#13209 Makes build action run on release branches in addition to develop
  .github/workflows/maven.yml
Labels: build, cla: yes

#13216 Makes build action run on release branches in addition to develop
  .github/workflows/maven.yml
Labels: build, cla: yes

#13222 [CDAP-17768] Set default concurrency settings for fixed dataproc.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: build, cla: yes

#13223 [CDAP-17768] Set default concurrency settings for fixed dataproc - Cherry-pick into 6.4
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.4, build, cla: yes

#13214 [CDAP-17757] [CDAP-17738] Fixes pipeline and plugin comments to close on clicking twice
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.5, UI, build, cla: yes

#13228 [CDAP-17757] [CDAP-17738] Fixes pipeline and plugin comments to close…
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.4, UI, cherry-pick, cla: yes

#13225 CDAP-17769 implement skip delete option in dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build, cla: yes

#13229 CDAP-17769 implement skip delete option in dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build, cla: yes

#13167 [CDAP-17709] Adds support for PROXY authentication mode in UI
  cdap-ui/app/cdap/components/AppHeader/AppToolBar/AppToolbarMenu.tsx
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/services/auth.js
  cdap-ui/app/services/data/my-cdap-datasource.js
  cdap-ui/app/services/file-uploader.js
  cdap-ui/app/services/settings.js
  cdap-ui/app/tracker/main.js
  cdap-ui/graphql/Query/pipelinesResolver.js
  cdap-ui/graphql/Query/statusResolver.js
  cdap-ui/graphql/graphql.js
  cdap-ui/graphql/helpers/BatchEndpoints/nextRuntime.js
  cdap-ui/graphql/helpers/BatchEndpoints/programRuns.js
  cdap-ui/graphql/helpers/BatchEndpoints/totalRuns.js
  cdap-ui/graphql/helpers/createLoaders.js
  cdap-ui/graphql/resolvers-common.js
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/config/router-check.js
  cdap-ui/server/express.js
  cdap-ui/server/token.mjs
Labels: 6.5, UI, build, cla: yes

#13226 (CDAP-17770) Properly propagate extra java options for remote processes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/TwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.5, build, cla: yes

#13227 (CDAP-17770) Properly propagate extra java options for remote processes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/TwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.4, build, cla: yes

#13231 [CDAP-17774]Fixes select dropdown in profile customization popover to not close the entire popover
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/index.js
Labels: 6.5, UI, build, cla: yes

#13233 Fixes select dropdown in profile customization popover to not close the entire popover
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/ProfileCustomizeContent/index.js
  cdap-ui/app/cdap/components/PipelineDetails/ProfilesListView/ProfileCustomizePopover/index.js
Labels: 6.4, UI, build, cla: yes

#13238 CDAP-17778] Fixes default canvas panning behavior in pipeline studio
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13239 [CDAP-17779] Fixes pipeline to show metrics if stage name has period in name
  cdap-ui/app/cdap/components/DAG/Nodes/SplitterNode/PortPopover.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PluginContextMenu/index.tsx
  cdap-ui/app/cdap/services/PipelineMetricsStore/ActionCreator.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js
  cdap-ui/app/hydrator/controllers/create/partials/pipelineupgrade-modal-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/hydrator/services/hydrator-service.js
  cdap-ui/app/hydrator/services/hydrator-upgrade-service.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13234 [CDAP-17778] Fixes default canvas panning behavior in pipeline studio
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
Labels: 6.5, UI, build, cla: yes

#13246 [CDAP-17796] Fix wrangler file browser to show up on initial wrangler connection
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13244 [CDAP-17784] radio group widget to not show value validation error when disabled
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13243 [CDAP-17784] radio group widget to not show value validation error when disabled
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
Labels: 6.5, Bug, UI, build, cla: yes

#13235 [CDAP-17779] Fixes pipeline to show metrics if stage name has period in name
  cdap-ui/app/cdap/components/DAG/Nodes/SplitterNode/PortPopover.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsDetailsActions/PipelineDetailsActionsButton/index.js
  cdap-ui/app/cdap/components/PluginContextMenu/index.tsx
  cdap-ui/app/cdap/services/PipelineMetricsStore/ActionCreator.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js
  cdap-ui/app/hydrator/controllers/create/partials/pipelineupgrade-modal-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/hydrator/services/hydrator-service.js
  cdap-ui/app/hydrator/services/hydrator-upgrade-service.js
Labels: 6.5, UI, build, cla: yes

#13236 [CDAP-17780] Fixes comments popover to close on clicking the comments icon again
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/index.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
Labels: 6.5, UI, build, cla: yes

#13247 [CDAP-17792] Bugfixes in Pipeline/Plugin comments
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentMenu.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/DynamicAnchoredComment.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/cdap/components/UniversalBackdrop/index.tsx
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13248 [CDAP-17792] Bugfixes in Pipeline/Plugin comments
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentMenu.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/DynamicAnchoredComment.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/cdap/components/UniversalBackdrop/index.tsx
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.5, UI, build, cla: yes

#13240 Fix flacky test
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13242 [CDAP-17791] Fix error message in runtime arguments modaless to wrap
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.tsx
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13241 [CDAP-17791] Fix error message in runtime arguments modaless to wrap
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.tsx
Labels: 6.5, Bug, UI, build, cla: yes

#13245 [CDAP-17796] Fix wrangler file browser to show up on initial wrangler connection
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
Labels: 6.5, Bug, UI, build, cla: yes

#13258 CDAP-17789 add auth for metadata
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: 6.4, cla: yes

#13252 [CDAP-17801] Handle long namespace names in Wrangler connections
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
Labels: 6.5, UI, build, cla: yes

#13254 CDAP-17789 add auth for metadata
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: build, cla: yes

#13212 Use more threads for maven run
  .github/workflows/maven.yml
Labels: build, cla: yes

#13256 [CDAP-17795] Fix authorization in datasource for polling
  cdap-ui/app/services/data/my-cdap-datasource.js
  cdap-ui/server/aggregator.js
Labels: 6.5, Bug, UI, build, cla: yes

#13257 [CDAP-17795] Fix authorization in datasource for polling
  cdap-ui/app/services/data/my-cdap-datasource.js
  cdap-ui/server/aggregator.js
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13249 Fixes close button behavior in pieline comments and in published pipeline view
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13250 Fixes close button behavior in pieline comments and in published pipeline view
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
Labels: 6.5, UI, build, cla: yes

#13255 [CDAP-17787] Add auth enforcement for preference service
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/PreferencesHttpHandler.java
Labels: 6.4, build, cla: yes

#13262 [CDAP-17786] Authorizer Error Support
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceAuthorizationTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/AuthorizationEnforcer.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationUtil.java
Labels: 6.4, Bug, build, cla: yes, java

#13260 Bugfix UI/cdap replication fixes
  cdap-ui/app/cdap/components/Replicator/Create/TopPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/SelectedTable/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTable.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/ScatterPlotTooltip.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/LogsButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.5, Bug, UI, build, cla: yes

#13266 [CDAP-17787] Add auth enforcement at preference http handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/PreferencesHttpHandler.java
Labels: cla: yes

#13264 [CDAP-17800] Add auth enforcement for profile http handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
Labels: 6.4, build, cla: yes

#13267 [CDAP-17800] Add auth enforcement for profile http handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
Labels: cla: yes

#13268 [CDAP-17786] 6.4 Cherrypick
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceAuthorizationTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/AuthorizationEnforcer.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationUtil.java
Labels: 6.4, cherry-pick, cla: yes

#13253 [CDAP-17801] Handle long namespace names in Wrangler connections
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13265 CDAP-17819 update leveldb library to pull in bug fixes
  cdap-data-fabric/pom.xml
  cdap-tms-tests/pom.xml
  cdap-tms/pom.xml
  pom.xml
Labels: build, cla: yes

#13270 [CDAP-17802] Handle 403 response when saving pipeline configuration
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
Labels: 6.5, UI, build, cla: yes

#13271 [CDAP-17802] Handle 403 response when saving pipeline configuration for 6.4
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13269 CDAP-17819 update leveldb library to pull in bug fixes
  cdap-data-fabric/pom.xml
  cdap-tms-tests/pom.xml
  cdap-tms/pom.xml
  pom.xml
Labels: 6.4, build, cla: yes

#13274 Revert "CDAP-17789 add auth for metadata"
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: cla: yes

#13279 [CDAP-17826] Replication fix configure popover behavior when only modifying the task memory
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
Labels: 6.5, Bug, UI, build, cla: yes

#13280 [CDAP-17826] Replication fix configure popover behavior when only mod…
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Configure/ConfigureModeless.tsx
Labels: 6.4, Bug, UI, cherry-pick, cla: yes

#13277 Metadata auth
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/DefaultMetadataReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/FieldLineageAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: build, cla: yes

#13278 put auth logic in metadata handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LineageHTTPHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
Labels: cla: yes

#13276 [CDAP-17824] Reduce initialPartitionNum for really tiny clusters.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: build, cla: yes

#13275 [CDAP-17824] Reduce initialPartitionNum for really tiny clusters.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: build, cla: yes

#13272 [CDAP-17823] Fixes preview to show default message when there is no preview run
  cdap-ui/app/cdap/components/PreviewData/index.tsx
Labels: 6.5, UI, build, cla: yes

#13273 [CDAP-17823] Fixes preview to show default message when there is no preview run
  cdap-ui/app/cdap/components/PreviewData/index.tsx
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13281 [CDAP-17822] Properly strip auth headers in response sent back to client in PROXY mode
  cdap-ui/server/aggregator.js
  cdap-ui/server/express.js
Labels: 6.4, 6.5, UI, build, cla: yes

#13283 [CDAP-17822] Properly strip auth headers in response sent back to client in PROXY mode
  cdap-ui/server/aggregator.js
  cdap-ui/server/express.js
Labels: 6.5, UI, build, cherry-pick, cla: yes

#13286 [CDAP-17833] Add auth enforcement for log http handler
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
Labels: build, cla: yes

#13287 [CDAP-17833] Add auth enforcement for log http handler
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
Labels: cla: yes

#13288 Fixes handling empty or undefined request origin to prevent sending auth headers to other domains
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/server/aggregator.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13285 [CDAP-17786 CDAP-17833] Properly propagate error messages throughout CDAP.
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesNoCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesTestBase.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-security/src/main/java/io/cdap/cdap/proto/security/AuthorizationPrivilege.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemoteAuthorizationEnforcer.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
Labels: 6.4, Bug, build, cla: yes

#13290 [CDAP-17786 CDAP-17833] 6.4 Cherrypick
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesNoCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePrivilegesTestBase.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-security/src/main/java/io/cdap/cdap/proto/security/AuthorizationPrivilege.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemoteAuthorizationEnforcer.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
Labels: cla: yes

#13291 [CDAP-17786] Reimplemented Single isVisible Call in DefaultAuthorizationEnforcer
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcerTest.java
Labels: 6.4, Bug, build, cla: yes

#13292 [CDAP-17786] 6.4 Cherry-Pick
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAuthorizationEnforcerTest.java
Labels: 6.4, Bug, cherry-pick, cla: yes

#13289 Fixes handling empty or undefined request origin to prevent sending auth headers to other domains
  cdap-ui/app/cdap/services/datasource/index.js
  cdap-ui/app/services/cask-angular-socket-datasource/datasource.js
  cdap-ui/server/aggregator.js
Labels: 6.5, UI, build, cla: yes

#13293 Fixes css class name added to connection to use node id instead of node name
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
Labels: 6.4, UI, build, cherry-pick, cla: yes

#13263 [CDAP-17818] Optimize jar unpacking in PluginInstantiator
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginClassLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/jar/BundleJarUtil.java
Labels: build, cla: yes

#13294 [CDAP-17835] display error when enabling or disabling pipeline triggers
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggerRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggersTab.scss
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/PayloadConfigModal.scss
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineListTab.scss
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineTriggersRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActions.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersStore.js
Labels: 6.5, Bug, UI, build, cla: yes

#13296 [CDAP-17837] Add auth enforcement for profile at system namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
Labels: 6.4, build, cla: yes

#13299 CDAP-17819 update leveldb library to pull in bug fixes
  cdap-data-fabric/pom.xml
  cdap-tms-tests/pom.xml
  cdap-tms/pom.xml
  pom.xml
Labels: 6.3, build, cla: yes

#13301 CDAP-17199 fix numberformatexception on dataproc provision
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.3, cla: yes

#13297 [CDAP-17837] Add auth enforcement for profile at system namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
Labels: 6.4, build, cla: yes

#13295 [CDAP-17835] display error when enabling or disabling pipeline triggers
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggerRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/EnabledTriggersTab.scss
  cdap-ui/app/cdap/components/PipelineTriggers/EnabledTriggersTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/PayloadConfigModal.scss
  cdap-ui/app/cdap/components/PipelineTriggers/PayloadConfigModal/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineListTab.scss
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/PipelineTriggersRow.js
  cdap-ui/app/cdap/components/PipelineTriggers/PipelineListTab/index.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActionCreator.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersActions.js
  cdap-ui/app/cdap/components/PipelineTriggers/store/PipelineTriggersStore.js
Labels: 6.4, Bug, UI, build, cherry-pick, cla: yes

#13298 [CDAP-17786] Modify Error Message to use prefix "Insufficient Permissions"
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceAuthorizationTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: 6.4, build, cla: yes, java

#13304 [CDAP-17786] Modify Wording of Error Messages for User Friendliness
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceAuthorizationTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: 6.4, cherry-pick, cla: yes, java

#13306 Refactor IntegrationTestManager to use APIs that dont require custom …
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
Labels: cla: yes

#13305 Update IntegrationTestManager for running against CDAP on Dataproc
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
Labels: 6.3, cherry-pick, cla: yes

#13307 [CDAP-17786] Update Error Message Format
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: 6.4, Bug, build, cla: yes, java

#13308 [CDAP-17786] Permissions to Privileges 6.4 Cherrypick
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/UnauthorizedException.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/UnauthorizedExceptionTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: 6.4, cherry-pick, cla: yes

#13315 Update MD5 for 6.4.0
  cdap-docs/admin-manual/build.sh
Labels: cla: yes

#13317 Switch to trigger/build schema.
  .github/workflows/build.yml
  .github/workflows/trigger.yml
Labels: build, cla: yes

#13318 Drop old single-phase build file in favor of a new two-phase one
  .github/workflows/maven.yml
Labels: 6.5, build, cla: yes

#13319 Further optimization of file handling.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/AbstractArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceClassLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/SystemArtifactsAuthorizationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-templates/cdap-program-report/src/test/java/io/cdap/cdap/report/ReportGenerationAppTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/Locations.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/jar/BundleJarUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/ClassLoaderTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/type/DatasetTypeManager.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/type/DirectoryClassLoaderProvider.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/GatewayFastTestsSuite.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizerInstantiator.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/UnitTestManager.java
Labels: build, cla: yes
