Repository cdapio/cdap, pull requests merged in 2021-12, with the labels that each got.

#13753 [CDAP-18627] Split preview leveldb store into 2 stores.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
Labels: cla: yes, build, 6.6

#13761 [CDAP-18627] Add put,get,getLatest,delete LevelDBTableCore APIs
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCore.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCoreTest.java
Labels: cla: yes, build, 6.7

#13771 [CDAP-18627] Remove confusing createEndKey(byte[] row) which just calls createStartKey(row)
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCore.java
Labels: cla: yes, build, 6.6

#13768 [CDAP-18627] Switch DefaultPreviewStore to use new LevelDBTableCore API
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
Labels: cla: yes, build, 6.6

#13772 Fixing macro-exception message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParser.java
Labels: cla: yes, build

#13774 CDAP-18437 Added logic to use the new capabilities when reading/writing records using the SQL engine.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/sql/engine/dataset/SparkRecordCollection.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/sql/engine/dataset/SparkRecordCollectionImpl.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/dataset/RecordCollection.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/dataset/SQLDatasetConsumer.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/dataset/SQLDatasetProducer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/pom.xml
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockPullProducer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockPushConsumer.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngineWithCapabilities.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
Labels: cla: yes, build

#13769 Add Tether permission to the Standard Permission
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/InstancePermission.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/PermissionType.java
Labels: cla: yes, build

#13778 Cherrypick removing getAppSpec API in programStatusTriggerInfo from dev to 6.6 release
  cdap-api/src/main/java/io/cdap/cdap/api/schedule/ProgramStatusTriggerInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/trigger/DefaultProgramStatusTriggerInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/trigger/ProgramStatusTrigger.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/TriggeringScheduleInfoAdapterTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/trigger/DefaultProgramStatusTriggerInfoTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
Labels: build, 6.6

#13779 Cherrypick levelDB reliability and performance fixes from dev to 6.6
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCore.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableService.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableCoreTest.java
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: build, 6.6

#13781 [CDAP-18626] Revive artifact-fetching-and-caching-WITHOUT-unpacking API
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
Labels: build, 6.6

#13786 optimize support bundle test cases
  cdap-app-fabric/src/main/java/io/cdap/cdap/support/services/SupportBundleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/support/services/SupportBundleServiceTest.java
Labels: build

#13788 CDAP-18656-store Adding scanApplications in Store with NamespaceId f…
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
Labels: cla: yes, build, 6.6

#13718 [CDAP-18613] Tethering control plane operations
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/NamespaceAllocation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerAlreadyExistsException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerBase.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerMetadata.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerNotFoundException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerState.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringActionRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringConnectionRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringConnectionStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlResponse.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringCreationRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringUtils.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/MockTetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/NamespaceMeta.java
Labels: cla: yes, build, 6.6

#13758 CDAP-18578 - Allow Metricswriter to subscribe to metrics at different intervals
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetadataHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetadataHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsMetaKeyProvider.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/TopicIdMetricsKeyProvider.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/TopicSubscriberMetaKey.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/TopicSubscriberMetricsKeyProvider.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/TopicIdMetricsKeyProviderTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/TopicSubscriberMetricsKeyProviderTest.java
Labels: cla: yes, build

#13793 [CDAP-18694] Refactor ArtifactRepository createArtifactClassLoader to take ArtifactDescriptor instead of just location
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DeployDatasetModulesStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/AuthorizationArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: build, 6.6

#13794 [CDAP-18694] Create artifact localizer sidecar for preview runner when enabled in cConf
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillApplication.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13791 [CDAP-18621] Add 30 minutes idle ttl value for ephemeral clusters
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#13799 [CDAP-18626] Revive artifact-fetching-and-caching-WITHOUT-unpacking API (address comment)
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
Labels: build, 6.6

#13798 [CDAP-18621] Add 30 minutes idle ttl value for ephemeral clusters
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#13802 [CDAP-18694] Refactor ArtifactRepository createArtifactClassLoader to take ArtifactDescriptor instead of just location
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DeployDatasetModulesStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/AuthorizationArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: build, 6.6

#13803 [CDAP-18694] Create artifact localizer sidecar for preview runner when enabled in cConf
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillApplication.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13804 [CDAP-18694] Allow preview runner to fetch metadata from AppFab and use sidecar for fetching and caching artifacts
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReaderWithLocalization.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryWithLocalization.java
Labels: build, 6.6

#13805 [CDAP-18694] Allow preview runner to fetch metadta from AppFab and use sidecar for fetching and caching aritfacts
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReaderWithLocalization.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryWithLocalization.java
Labels: build, 6.6
