Repository cdapio/cdap, pull requests merged in 2021-06, with the labels that each got.

#13434 Ensure proper logging if StandaloneMain can't be created
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: build, cla: yes

#13383 Pod isolation changes for system apps
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/pom.xml
  cdap-common/src/main/resources/cdap-default.xml
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RunnableTask.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RunnableTaskContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RunnableTaskRequest.java
Labels: 6.5, build, cla: yes

#13432 [CDAP-18023 CDAP-18024] Support Pod Privilege Reduction
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
Labels: 6.5, Bug, build, cla: yes

#13438 [CDAP-18039] Improve E2E Authorization Flow Debug Logging
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Principal.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/VisibilityRequest.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemoteAccessEnforcer.java
Labels: build, cla: yes

#13409 CDAP-17981: Add opnHttpURLConnection to master env runnable context interface
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentRunnableContext.java
Labels: 6.5, build, cla: yes

#13437 Refactor pipeline validation to extract reusable code
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/service/ValidationUtilsTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
Labels: build, cla: yes

#13440 (CDAP-18041) Add a flag to disable custom dataset module support
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DatasetModulesDeployer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DeployDatasetModulesStage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/AppWithCustomDatasetModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/TempFolder.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13444 Added additional logging for SQL Engine Pushdown execution.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build, cla: yes

#13313 Minor edit to Data Pipeline User Guide
  cdap-docs/user-guide/source/pipelines/index.rst
Labels: 6.5, build, cla: yes

#13424 Add labels to dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: 6.5, build, cla: yes

#13420 CDAP-17998: Allow dataproc provisioner to fetch Google Credentials from remote endpoint
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeEngineCredentials.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: 6.5, build, cla: yes

#13428 [CDAP-17862] Support for shielded vms in dataproc provisioner
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: 6.5, build, cla: yes

#13436 Allow system apps to do authorization checks and add checks to drafts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/DefaultAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/AbstractServiceHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/DelayedHttpServiceResponder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/AbstractDataPipelineHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DraftServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/CodedException.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Authorizable.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/AccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestConfiguration.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: build, cla: yes

#13447 Code cleanup and simplification around application deployment
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteExecutionException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ConfiguratorConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DeployDatasetModulesStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfigResponseResult.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/LocationBodyProducer.java
Labels: 6.5, build, cla: yes

#13418 Switch client/CLI to the new permission model
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AuthorizationHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/util/AbstractAppFabricHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/AuthorizationCLITest.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/ArgumentName.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/security/GrantPermissionCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/security/ListPrivilegesCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/security/RevokeEntityCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/security/RevokePermissionCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/security/RevokePermissionForPrincipalCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/commandset/SecurityCommands.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/util/AbstractAuthCommand.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/AuthorizationClient.java
  cdap-docs/reference-manual/source/http-restful-api/security.rst
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/AuthorizationRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/GrantRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/RevokeRequest.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/security/GrantRequestTest.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/security/RevokeRequestTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemotePermissionManager.java
Labels: build, cla: yes

#13457 Fix auto install hub path
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/autoinstall/HubPackage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
Labels: build, cla: yes

#13462 CDAP-18053: Fix hanging issue of testConcurrentRequests in TaskWorkerServiceTest
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
Labels: 6.5, build, cla: yes

#13460 Introduce a safety timeout for tests not to run infinitely
  pom.xml
Labels: build, cla: yes

#13456 CDAP-18045: Introduce Tink-based cipher class to be used later for encrypting credentials
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-security/pom.xml
  cdap-security/src/main/java/io/cdap/cdap/security/auth/CipherException.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/TinkCipher.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TinkCipherTest.java
  pom.xml
Labels: build, cla: yes

#13461 [CDAP-18052] populate EncryptionKeyName to dataproc default context properties
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.5, build, cla: yes

#13458 CDAP-18045: Encrypt user credential at router and decrypt before calling auth extension
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/TinkCipher.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AuthorizationTestBase.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcerTest.java
Labels: 6.5, build, cla: yes

#13467 disable flaky test case
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: build, cla: yes

#13469 CDAP-18046 add more browse property type
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/LimitingConnector.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseEntityProperty.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/Connector.java
Labels: build, cla: yes

#13450 Validate pipeline remotely on task worker
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/services/AbstractServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteValidationRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteValidationTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RemoteExecutionException.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RemoteTaskException.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RunnableTaskContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/SystemAppTaskContext.java
Labels: build, cla: yes

#13471 CDAP-18063 support creating a single classloader for all plugins created
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultServicePluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/DefaultConnectorConfigurer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/LimitingConnector.java
Labels: build, cla: yes

#13465 CDAP-17981: Introduce FileFetcherInternalHttpHandler in AppFabric
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/FileFetcherHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/FileFetcherHttpHandlerInternalTest.java
Labels: 6.5, build, cla: yes

#13468 Changes for BQ Pushdown behaviors
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BatchPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/io/cdap/cdap/etl/tool/config/Upgrader.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
Labels: build, cla: yes

#13473 change property so it is easier for UI to surface
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseDetail.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseEntity.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseEntityPropertyValue.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/ConnectorSpec.java
Labels: build, cla: yes

#13427 [CDAP-18004] Add support for CDAP SA separation
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillApplication.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecretDisk.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecureTwillPreparer.java
Labels: build, cla: yes

#13475 [CDAP-17892] Support python3 in Spark runtime
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core3_2.12/src/main/resources/pyspark/pyspark.zip
  cdap-spark-python/src/main/resources/cdap/pyspark/__init__.py
  cdap-spark-python/src/main/resources/cdap/pyspark/context.py
  cdap-spark-python/src/main/resources/cdap/pyspark/log.py
Labels: build, cla: yes

#13472 CDAP-17981: Make FileLocalizer to download files via AppFab instead of from HDFS
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/FileLocalizer.java
Labels: 6.5, build, cla: yes

#13479 CDAP-18073 let system app able to list namespaces
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
Labels: build, cla: yes

#13466 Add config allowing to enable/disable killing taskworker pod after an execution completes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13476 Fail early and show better message for failed runs
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/ReducibleAggregatorTestBase.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-system-app-unit-test/src/test/java/io/cdap/cdap/test/SystemAppTestBaseTest.java
  cdap-test/src/main/java/io/cdap/cdap/test/AbstractProgramManager.java
  cdap-test/src/main/java/io/cdap/cdap/test/ProgramManager.java
  cdap-unit-test-base/src/test/java/io/cdap/cdap/spark/Spark2Test.java
  cdap-unit-test/src/test/java/io/cdap/cdap/service/DynamicPluginServiceTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkTest.java
Labels: 6.5, build, cla: yes

#13478 Upgrade netty-http library to 1.6.0
  pom.xml
Labels: 6.5, build, cla: yes

#13463 This PR adds additional enforcement to drafts to ensure they need proper write permissions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DraftServiceTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authorization/ContextAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultContextAccessEnforcer.java
  cdap-system-app-api/pom.xml
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13459 Clean up security context to ensure next message in same thread won't pick up the wrong credentials
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authentication/SecurityRequestContext.java
Labels: build, cla: yes

#13481 Final migration of the App Fabric to new permission model.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AuthorizationModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePermissionsCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePermissionsNoCacheTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/remote/RemotePermissionsTestBase.java
Labels: build, cla: yes

#13470 Add TwillRunnable security context and readonly volumes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecureTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecurityContext.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/StatefulTwillPreparer.java
Labels: 6.5, build, cla: yes

#13454 Implement ArtifactLocalizerService which runs in sidecar container
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RemoteWorkerPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: 6.5, build, cla: yes

#13484 CDAP-18076: Unset certificate path in CConfiguration when launching TaskWorkerTwillApplication
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
Labels: 6.5, build, cla: yes

#13477 Refactor classLoader logic to accept already unpacked directory
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/jar/BundleJarUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/jar/BundleJarUtilTest.java
Labels: 6.5, build, cla: yes

#13486 CDAP-18081 add default impl for methods introduced in cdap-api to avo…
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfigurer.java
Labels: build, cla: yes

#13455 Permission model clean-up
  cdap-explore/src/test/java/io/cdap/cdap/explore/service/BaseHiveExploreServiceTest.java
  cdap-security-spi/src/test/java/io/cdap/cdap/security/spi/authorization/AuthorizerTest.java
  cdap-security/src/main/java/io/cdap/cdap/proto/security/AuthorizationPrivilege.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AbstractAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessEnforcerWrapper.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizerInstantiator.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DelegatingPrivilegeManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/RemoteAccessEnforcer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AccessControllerClassLoaderTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/InMemoryAuthorizer.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/InMemoryAuthorizerTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13487 CDAP-18084 support program life cycle for service
  cdap-api/src/main/java/io/cdap/cdap/api/service/AbstractService.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/Service.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/ServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/BasicServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/BasicSystemServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/AbstractServiceHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/AbstractSystemService.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/SystemNamespaceAdmin.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/SystemServiceContext.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/http/SystemHttpServiceContext.java
Labels: build, cla: yes

#13485 [CDAP-18004] Add Support for Setting Worker Security Secrets
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13489 [CDAP-17754] Identity propagation for Execution Clusters
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceBuilder.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMainTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
Labels: 6.5, build, cla: yes

#13496 Add dependencies to cdap-master to ensure they are built before cdap-master.
  cdap-master/pom.xml
Labels: build, cla: yes

#13497 [CDAP-17754] Identity propagation for Execution Clusters
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionJobMain.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceBuilder.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMainTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
Labels: 6.5, build, cla: yes

#13499 [CDAP-18004] Add support for setting worker security secrets 6.5 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cherry-pick, cla: yes

#13491 Add a new TaskWorker temp directory property
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cla: yes

#13501 Add a new TaskWorker temp directory property to resolve readonly file…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cla: yes

#13502 [CDAP-18095] Mount worker secrets by default for backwards compatibility
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: Bug, build, cla: yes

#13503 [CDAP-18095] Mount worker secrets by default for backwards compatibility
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cla: yes

#13492 CDAP-18010: Include namespace in ArtifactDescriptor
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
Labels: 6.5, build, cla: yes

#13494 CDAP-18010: Remove unused http REST endpoint TaskWorkerHttpHandlerInternal
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
Labels: 6.5, build, cla: yes

#13506 Integrate system app remote execution with artifact localizer
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedArtifactManagerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cla: yes

#13490 Integrate system app remote execution with artifact localizer
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedArtifactManagerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, cla: yes

#13507 [CDAP-18044] Don't detect spark version in production code.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/SparkCompatReader.java
  cdap-unit-test-base/src/test/java/io/cdap/cdap/spark/Spark2Test.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: 6.5, build, cla: yes

#13511 [Cherry-pick 6.5][CDAP-18044] Don't detect spark version in production code.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/SparkCompatReader.java
  cdap-unit-test-base/src/test/java/io/cdap/cdap/spark/Spark2Test.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, cla: yes

#13505 Reuse dataproc clusters
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerSystemContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerSystemContext.java
Labels: build, cla: yes

#13508 [6.5 Cherry-pick] Reuse dataproc clusters
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerContext.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/MockProvisionerSystemContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerContext.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/ProvisionerSystemContext.java
Labels: 6.5, build, cla: yes

#13510 Provide maven with dependencies to ensure system apps are built before standalone
  cdap-standalone/pom.xml
Labels: build, cla: yes

#13513 [Cherry-pick for 6.5] Skip spark3 PySpark test if runner do not have python3 installed
  cdap-unit-test-base/src/test/java/io/cdap/cdap/spark/Spark2Test.java
Labels: build, cla: yes

#13512 Skip spark3 PySpark test if runner do not have python3 installed
  cdap-unit-test-base/src/test/java/io/cdap/cdap/spark/Spark2Test.java
Labels: build, cla: yes

#13515 [Cherry-pick 6.5][CDAP-18117] We should not try to instantiate main classes if they are not Applications
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspector.java
Labels: build, cla: yes

#13514 [CDAP-18117] We should not try to instantiate main classes if they are not Applications
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspector.java
Labels: build, cla: yes

#13493 CDAP-18010: Code refactoring to move parentClassloader creation into DefaultArtifactInspector
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspectorTest.java
Labels: 6.5, build, cla: yes

#13518 (CDAP-18111) Includes protobuf-java 3.x into final packaging
  cdap-data-fabric-tests/pom.xml
  pom.xml
Labels: 6.6, build, cla: yes

#13521 (CDAP-18111) Includes protobuf-java 3.x into final packaging (cherry-pick)
  cdap-data-fabric-tests/pom.xml
  pom.xml
Labels: 6.5, build, cla: yes

#13520 [Cherry-pick for 6.5][CDAP-18124] Fix null label added without reuse enabled
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Cluster.java
Labels: build, cla: yes

#13522 Feature/refactor internal auth
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/TwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/guice/AppFabricTestModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/ZKClientModule.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterMain.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/GatewayTestBase.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/AuthServerAnnounceTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpsTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RouterResource.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RoutingToDataSetsTest.java
  cdap-kafka/src/main/java/io/cdap/cdap/kafka/run/KafkaServerMain.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/StorageMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMainTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/InMemoryKeyManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/CoreSecurityRuntimeModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/InMemoryCoreSecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/runtime/AuthenticationServerMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AuthenticationTool.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestInMemoryTokenManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalAuthenticationServerTestBase.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: 6.6, build, cla: yes

#13524 Refacotring related to internal auth and security related bindings (cherry-pick)
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunnerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/TwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/guice/AppFabricTestModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/ZKClientModule.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterMain.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/GatewayTestBase.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/AuthServerAnnounceTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpsTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RouterResource.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RoutingToDataSetsTest.java
  cdap-kafka/src/main/java/io/cdap/cdap/kafka/run/KafkaServerMain.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/JobQueueDebugger.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/UpgradeTool.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/StorageMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMainTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/InMemoryKeyManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/CoreSecurityRuntimeModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/InMemoryCoreSecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/runtime/AuthenticationServerMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AuthenticationTool.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestInMemoryTokenManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalAuthenticationServerTestBase.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: 6.5, build, cherry-pick, cla: yes

#13519 [CDAP-18124] Fix null label added without reuse enabled
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Cluster.java
Labels: build, cla: yes
