Repository cdapio/cdap, pull requests merged in 2021-02, with the labels that each got.

#13087 [CDAP-17627] Fix alignment of configuration Resources tab, esp. for real time
  cdap-ui/app/directives/my-pipeline-configurations/my-pipeline-configurations.less
Labels: 6.4, UI, cla: yes

#13094 [CDAP-16804] Plugin list adding placeholder option
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.4, UI, cla: yes

#13092 [CDAP-17613] Replication assessment red highlight schema issues table
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/NoIssuesTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/ViewMappingButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/WithIssuesTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/tableStyles.ts
  cdap-ui/app/cdap/components/Table/TableHeader.tsx
Labels: 6.4, UI, cla: yes

#13088 [CDAP-17642] Added tracking for namespaceCount metrics and namespaces table operations to AppMetadataStore
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/StorageProviderNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/DefaultNamespaceStore.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/NamespaceStore.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/NamespaceTable.java
Labels: 6.4, cla: yes

#13064 [CDAP-17575] Integrate gitpod with CDAP repo to help spin up CDAP UI directly from pull requests
  .gitpod.Dockerfile
  .gitpod.yml
  cdap-ui/gitpod/bamboo_plan_info.json
  cdap-ui/gitpod/package.json
  cdap-ui/gitpod/setup.js
  cdap-ui/gitpod/start.js
  cdap-ui/gitpod/unzip.js
  cdap-ui/gitpod/yarn.lock
  cdap-ui/pom.xml
  pom.xml
Labels: 6.4, UI, cla: yes

#13086 [CDAP-17544] Clean up PipelineModeless and use for other popovers
  cdap-ui/app/cdap/components/PipelineConfigurations/PipelineConfigurations.scss
  cdap-ui/app/cdap/components/PipelineConfigurations/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineConfigureButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineScheduleButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/PipelineDetailsButtons/PipelineSummaryButton.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/PipelineModeless.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModeless/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/index.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsModeless/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLevelInfo.scss
  cdap-ui/app/cdap/components/PipelineScheduler/PipelineScheduler.scss
  cdap-ui/app/cdap/components/PipelineSummary/index.js
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/templates/create/toppanel.html
Labels: 6.4, UI, cla: yes

#13091 [CDAP-17414] Replication improve table selection UX
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.4, UI, cla: yes

#13102 [CDAP-17597] Replication poll for metrics in detail view
  cdap-ui/app/cdap/api/metric.js
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/Metrics/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/ThroughputLatencyGraphs/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
Labels: 6.4, UI, cla: yes

#13098 [CDAP-17495] Replication disabling save button when no column is selected
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectColumns/index.tsx
Labels: 6.4, UI, cla: yes

#13100 CDAP-17622 add more dataproc provisioner options
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: 6.4, cla: yes

#13099 [CDAP-15552] Visual updates for new columns in ColumnsTab
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/ColumnsTab/ColumnsTab.scss
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/ColumnsTab/ColumnsTabRow.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/ColumnsTab/index.js
  cdap-ui/app/cdap/components/DataPrep/store/index.ts
Labels: 6.4, UI, cla: yes

#13106 (CDAP-17673) Fix the SparkCompiler to work in Spark 2.4+ environment
  cdap-api/src/main/java/io/cdap/cdap/internal/lang/CallerClassSecurityManager.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/dynamic/AbstractSparkCompiler.scala
Labels: 6.4, cla: yes

#13110 [CDAP-17670] Cache various transform objects in io.cdap.cdap.etl.spark.function
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorAggregateFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorFinalizeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorGroupByFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorInitializeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorMergePartitionFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorMergeValueFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/AggregatorReduceGroupByFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/BatchSinkFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/BatchSourceFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/ErrorTransformFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/FunctionCache.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinMergeFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/JoinOnFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/MultiOutputTransformFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/TransformFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicAggregatorAggregate.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicAggregatorGroupBy.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicJoinMerge.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicJoinOn.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/DynamicTransform.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/StreamingBatchSinkFunction.java
Labels: cla: yes

#13116 Added serializeNulls option to GSON configuration
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
Labels: cla: yes

#13117 [CDAP-17650] Add Dataproc Job labels to reflect what type of pipeline is being run
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: 6.4, cla: yes

#13109 [CDAP-17647] Update ETLStage to allow adding comments
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLStage.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/StageComments.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/StageInformation.java
Labels: 6.4, cla: yes

#13118 (CDAP-17691) Make it possible to store secret in the SYSTEM namespace
  cdap-app-templates/cdap-etl/hydrator-spark-core/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/pom.xml
  cdap-kms/src/main/java/io/cdap/cdap/security/store/KMSSecureStoreService.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/FileSecureStoreService.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/secretmanager/SecretManagerSecureStoreService.java
Labels: 6.4, cla: yes

#13115 [CDAP-17591] Don't round completion percentage for Wrangler DataQuality bar and ColumnsTabRow
  cdap-ui/app/cdap/components/DataPrep/DataPrepSidePanel/ColumnsTab/ColumnsTabRow.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepTable/DataQuality/index.js
Labels: 6.4, UI, cla: yes

#13120 CDAP-17556 add api for expression join conditions
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
Labels: cla: yes

#13114 [CDAP-17646] Implement basic support for CDAP proxy authentication mode
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterMain.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/AuditLogTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/AuthServerAnnounceTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/MockAccessTokenIdentityExtractor.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/MockAccessTokenTransfomer.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterHttpsTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/NettyRouterPipelineAuthTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RouterResource.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/RoutingToDataSetsTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Principal.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authentication/SecurityRequestContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessToken.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessTokenCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessTokenIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessTokenTransformer.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AuthenticationMode.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/TokenManager.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentity.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityExtractionException.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityExtractionResponse.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityExtractionState.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentityPair.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/MasterAuthenticationContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/SecurityModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/runtime/AuthenticationServerMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/server/GrantAccessToken.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractorTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestFileBasedTokenManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestTokenManager.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: 6.4, cla: yes, java

#13107 [CDAP-17623] Add logical type in UI for DateTime (ISO 8601)
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaGenerator.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaManagerUtilities.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/Context/SchemaParser.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaConstants.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaHelpers.ts
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaTypes.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/DateTimeLogicalType.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/LogicalTypes.ts
  cdap-ui/app/cdap/services/cdapavscwrapper/index.ts
Labels: 6.4, UI, cla: yes

#12809 [CDAP-17338] Add integration tests for LogViewer
  cdap-ui/app/cdap/components/IconSVG/index.js
  cdap-ui/app/cdap/components/LoadingSVG/index.js
  cdap-ui/app/cdap/components/LogViewer/LogLevel.tsx
  cdap-ui/app/cdap/components/LogViewer/LogRow.tsx
  cdap-ui/app/cdap/components/LogViewer/TopPanel.tsx
  cdap-ui/app/cdap/components/LogViewer/index.tsx
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunLogs.js
  cdap-ui/cypress/fixtures/logs_generator-cdap-data-pipeline.json
  cdap-ui/cypress/integration/logviewer.spec.ts
Labels: 6.4, UI, cla: yes

#13108 Wrangler Decimal Improvement and Cross Column Arithmetic
  cdap-ui/app/cdap/components/DataPrep/ColumnActionsDropdown/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Calculate/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/ChangeDataType/index.js
  cdap-ui/app/cdap/services/global-constants.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.4, cla: yes

#13123 Introduce GitHub actions for unit test build
  .github/workflows/maven.yml
Labels: build, cla: yes

#13126 (CDAP-17630) Capture environment variables setup by spark-env.sh
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkPackageUtils.java
Labels: 6.4, build, cla: yes

#13122 [CDAP-17189] Add loading indicator to log viewer while fetching logs
  cdap-ui/app/cdap/components/LogViewer/TopPanel.tsx
  cdap-ui/app/cdap/components/LogViewer/index.tsx
Labels: 6.4, UI, cla: yes

#13124 [CDAP-17617] Replication display table status on hover in overview detail page
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/styles/fonts/symbol-defs-full.svg
  cdap-ui/app/cdap/styles/fonts/symbol-defs.svg
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
Labels: 6.4, UI, cla: yes

#13128 CDAP-17605 implement join expressions for batch pipelines
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/ExpressionConditionError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/JoinError.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinExpressionRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/join/JoinRequest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/joiner/MockAutoJoiner.java
Labels: build, cla: yes

#13130 [CDAP-17702] Filter out empty hub URLs
  cdap-ui/server/url-helper.js
Labels: 6.4, cla: yes

#13093 Add new system APIs to support OAuth in pipelines
  cdap-app-templates/cdap-etl/cdap-data-pipeline/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/CredentialIsValidResponse.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/GetAccessTokenResponse.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthClientCredentials.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthProvider.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthRefreshToken.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStoreException.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/PutOAuthCredentialRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/PutOAuthProviderRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/oauth/RefreshTokenResponse.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/OAuthServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
Labels: 6.4, build, cla: yes

#13132 Remove SureFire report as it does not work with PRs from forks
  .github/workflows/maven.yml
Labels: build, cla: yes

#13131 Remove Travis & Cloud Build.
  .travis.yml
  cloudbuild.sh
  cloudbuild.yaml
Labels: build, cla: yes

#13134 CDAP-17606 basic validation for join condition expressions
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/error/ExpressionConditionError.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/join/JoinDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: build, cla: yes

#13137 [CDAP-17706] Allow to disable function cache
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/PairRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/FunctionCache.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/PairDStreamCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/function/FunctionCacheTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: build, cla: yes

#13096 (CDAP-17610) Adding a new macro function for OAuth integration
  cdap-api/src/main/java/io/cdap/cdap/api/ServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/services/AbstractServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactInspector.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceLifecycleContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/plugins/test/TestPlugin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/ExternalSparkProgram.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/JavaSparkMainWrapper.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/main/scala/io/cdap/cdap/datapipeline/ScalaSparkMainWrapper.scala
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/condition/PipelineCondition.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/customaction/PipelineAction.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/ETLMapReduce.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceTransformExecutorFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractStageContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/OAuthMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/SecureStoreMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/macro/LogicalStartTimeMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/OAuthMacroEvaluatorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/macro/LogicalStartTimeMacroEvaluatorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/macro/LogicalStartTimeMacroTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/MultiSinkFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/StreamingAlertPublishFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/StreamingBatchSinkFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/StreamingMultiSinkFunction.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/function/StreamingSparkSinkFunction.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/action/MockActionContext.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/transform/MockTransformContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/BasicSparkClientContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkServiceDiscoverer.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: 6.4, build, cla: yes

#13081 Resolve "java.lang.NumberFormatException: multiple points"
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: 6.4, build, cla: yes

#13121 [CDAP-17400] Emit plugin metadata for applications
  cdap-api/src/main/java/io/cdap/cdap/api/metadata/MetadataEntity.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/element/EntityType.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/PluginId.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: 6.4, build, cla: yes

#12207 Renames all occurence of github org 'caskdata' to 'cdapio' in cdap docs
  cdap-docs/_common/common-build.sh
  cdap-docs/_common/common_conf.py
  cdap-docs/admin-manual/source/operations/logging.rst
  cdap-docs/admin-manual/source/security/authorization.rst
  cdap-docs/developer-manual/build-pipelines.sh
  cdap-docs/developer-manual/build.sh
  cdap-docs/developer-manual/source/ingesting-tools/cdap-flume.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-java.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-python.rst
  cdap-docs/developer-manual/source/ingesting-tools/cdap-stream-clients-ruby.rst
  cdap-docs/developer-manual/source/metadata/audit-logging.rst
  cdap-docs/developer-manual/source/security/custom-authentication.rst
  cdap-docs/examples-manual/build.sh
  cdap-docs/examples-manual/source/_includes/apps-packs.txt
  cdap-docs/examples-manual/source/_includes/tutorials-index.txt
  cdap-docs/examples-manual/source/tutorials/wise.rst
  cdap-docs/integrations/build.sh
  cdap-docs/reference-manual/licenses-pdf/cdap-ui-dependencies.pdf
  cdap-docs/reference-manual/source/java-client-api.rst
  cdap-docs/reference-manual/source/licenses/cdap-ui-dependencies.rst
  cdap-docs/reference-manual/source/release-notes.rst
  cdap-docs/tools/cdap-default/cdap-xml-sdl-files.txt
  cdap-docs/tools/licenses/cdap-dependencies-master.csv
  cdap-docs/tools/licenses/cdap-ui-dependencies.rst
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-docs/vars
Labels: cla: yes

#13135 [CDAP-17703] Fix using correct namespace while saving draft
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
Labels: 6.4, UI, build, cla: yes

#13143 CDAP-17715 Added retry logic to fetch data from dataset.
  cdap-common/src/main/java/io/cdap/cdap/common/utils/Tasks.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
Labels: 6.4, build, cla: yes

#13140 CDAP-17331 suppress debezium verbose info logs
  cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
  cdap-distributions/src/etc/cdap/conf.dist/logback.xml
  cdap-standalone/src/main/resources/logback-container.xml
  cdap-standalone/src/main/resources/logback.xml
Labels: cla: yes

#13139 [CDAP-17471] Replication add ability to export/import/duplicate
  cdap-ui/app/cdap/api/__mocks__/pipeline.js
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/TopPanel/ActionButtons/Actions/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Drafts/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/ReplicationPlusButton/index.tsx
  cdap-ui/app/cdap/components/Replicator/types.ts
  cdap-ui/app/cdap/components/Replicator/utilities/__tests__/utilities.test.ts
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
  cdap-ui/jest/jest.setup.js
  cdap-ui/package.json
  cdap-ui/yarn.lock
Labels: 6.4, UI, build, cla: yes

#13147 add logging to debug BUT failures
  cdap-common/src/main/java/io/cdap/cdap/internal/asm/Classes.java
Labels: build, cla: yes

#13149 Update IntegrationTestManager for running against CDAP on Dataproc
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
Labels: cla: yes

#13127 [CDAP-17684] Add Datetime parse and format directives to Wrangler UI
  cdap-ui/app/cdap/components/DataPrep/Directives/Format/index.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/Modals/DateFormatModal.js
  cdap-ui/app/cdap/components/DataPrep/Directives/Parse/index.js
  cdap-ui/app/cdap/text/text-en.yaml
Labels: 6.4, UI, build, cla: yes

#13146 [CDAP-17464] Add integration test to create compute profile in system…
  cdap-ui/app/cdap/components/AbstractWidget/SecureKey/index.js
  cdap-ui/app/cdap/components/BtnWithLoading/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateProfileBtn/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/CreateProfileMetadata/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/CreateView/ProvisionerSelection/index.js
  cdap-ui/app/cdap/components/Cloud/Profiles/ListView/index.js
  cdap-ui/cypress/integration/computeprofile.spec.ts
Labels: 6.4, UI, build, cla: yes

#13145 [CDAP-17450] Replication fixes
  cdap-ui/app/cdap/components/Replicator/ConfigDisplay/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/TableList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/ContentHeading/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
  cdap-ui/app/cdap/components/Replicator/utilities/index.ts
Labels: 6.4, Bug, UI, build, cla: yes

#13125 [CDAP-17603] Replication add ability to jump to any completed step during creation
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/LeftPanel/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
Labels: 6.4, UI, build, cla: yes

#13142 [CDAP-17400] Backfill plugin metadata on startup
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/PluginId.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingPollingService.java
Labels: 6.4, build, cla: yes

#13151 [CDAP-16726] Replication add message in schema assessment when there are tables that cannot be accesssed
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/index.tsx
Labels: 6.4, UI, build, cla: yes

#13104 [CDAP-17549] Revamping Pipeline comments
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentBox.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentConstants.ts
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentIcon.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/CommentMenu.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/DynamicAnchoredComment.tsx
  cdap-ui/app/cdap/components/AbstractWidget/Comment/index.tsx
  cdap-ui/app/cdap/components/Markdown/MarkdownImplExample.tsx
  cdap-ui/app/cdap/components/Markdown/index.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineComments.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsActionBtn.tsx
  cdap-ui/app/cdap/components/PipelineCanvasActions/PipelineCommentsConstants.ts
  cdap-ui/app/cdap/components/PluginContextMenu/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Documentation/index.tsx
  cdap-ui/app/cdap/components/ThemeWrapper/colors.ts
  cdap-ui/app/cdap/components/ThemeWrapper/index.tsx
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/cdap/styles/bootstrap_4_patch.scss
  cdap-ui/app/cdap/styles/colors.scss
  cdap-ui/app/common/cask-shared-components.js
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/directives/dag-plus/my-dag.html
  cdap-ui/app/directives/dag-plus/my-dag.less
  cdap-ui/app/directives/dag-plus/services/actions/nodes-actions.js
  cdap-ui/app/directives/dag-plus/services/stores/nodes-store.js
  cdap-ui/app/directives/react-components/index.js
  cdap-ui/app/hydrator/adapters.less
  cdap-ui/app/hydrator/controllers/create/canvas-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/hydrator-modal.less
  cdap-ui/app/hydrator/services/create/stores/config-store.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
  cdap-ui/app/styles/themes/cdap/theme.less
Labels: 6.4, UI, build, cla: yes

#13150 [CDAP-17713] Fixes sending empty string for plugin properties during plugin validation
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.4, UI, build, cla: yes

#13154 [CDAP-17114] Hide Record/Table switch in preview for joiner and aggregator plugins
  cdap-ui/app/cdap/components/PreviewData/index.tsx
  cdap-ui/app/cdap/components/PreviewData/utilities.ts
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.4, UI, build, cla: yes

#13148 Capability management fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/CapabilitySleepingWorkflowPluginApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: 6.4, build, cla: yes
