Repository cdapio/cdap, pull requests merged in 2021-07, with the labels that each got.

#13526 (CDAP-18000) Upgrade k8s client to latest
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/ApiCallbackAdapter.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillControllerFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodKillerTask.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: 6.6, build, cla: yes

#13516 CDAP-18110: Disable verifyssl in ArtifactLocalizer and ComputeEngineCredentials
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeEngineCredentials.java
Labels: build, cla: yes

#13523 [6.5 cherry-pick] CDAP-18110: Disable verifyssl in artifact localizer and ComputeEngineCredentials
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeEngineCredentials.java
Labels: build, cla: yes

#13527 CDAP-18136 CDAP-18143 some connector fixes
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
Labels: build, cla: yes

#13528 CDAP-18136 CDAP-18143 some connector fixes
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
Labels: build, cla: yes

#13504 [CDAP-17772] Introduce Internal Identity Enforcement
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/OAuthMacroEvaluatorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceBuilder.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/DefaultInternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/InternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/NoOpInternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/DefaultInternalAuthenticatorTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/MockAccessTokenIdentityExtractor.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/HBaseTableExporter.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessToken.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/KeyIdentifier.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/KeyIdentifierCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentity.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/SystemAuthenticationContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/InternalAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/CoreSecurityRuntimeModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/server/GrantAccessToken.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/FileBasedTokenManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestKeyIdentifierCodec.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestTokenManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/context/RemoteClientInternalAuthenticatorTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/InternalAccessEnforcerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/impersonation/UGIProviderTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/client/RemoteSecureStoreTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/logbuffer/handler/LogBufferHandlerTest.java
Labels: 6.5, build, cla: yes

#13534 CDAP-18162 let preview discover external services
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/preview/PreviewDiscoveryService.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/preview/PreviewDiscoveryRuntimeModule.java
Labels: build, cla: yes

#13535 CDAP-18162 let preview discover external services
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/preview/PreviewDiscoveryService.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/preview/PreviewDiscoveryRuntimeModule.java
Labels: build, cla: yes

#13532 [CDAP-17772] Enforcement 6.5 Cherry-Pick
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppModuleTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/OAuthMacroEvaluatorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceBuilder.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/DefaultInternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/InternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/NoOpInternalAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/DefaultInternalAuthenticatorTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/NettyRouter.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/router/MockAccessTokenIdentityExtractor.java
  cdap-master/src/main/java/io/cdap/cdap/data/tools/HBaseTableExporter.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessToken.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/KeyIdentifier.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/KeyIdentifierCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/ProxyUserIdentityExtractor.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/UserIdentity.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/SystemAuthenticationContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/InternalAccessEnforcer.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/CoreSecurityRuntimeModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
  cdap-security/src/main/java/io/cdap/cdap/security/server/GrantAccessToken.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/DistributedKeyManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/FileBasedTokenManagerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestKeyIdentifierCodec.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestTokenManager.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/context/RemoteClientInternalAuthenticatorTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/InternalAccessEnforcerTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/impersonation/UGIProviderTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/client/RemoteSecureStoreTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/logbuffer/handler/LogBufferHandlerTest.java
Labels: 6.5, build, cherry-pick, cla: yes

#13538 Added interface method to count long values for Metrics
  cdap-api/src/main/java/io/cdap/cdap/api/metrics/Metrics.java
Labels: build, cla: yes

#13540 Added interface method to count long values for Metrics
  cdap-api/src/main/java/io/cdap/cdap/api/metrics/Metrics.java
Labels: build, cla: yes

#13536 Fixed integer overflow issue with records count from SQL Engine operations
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/metrics/ProgramUserMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/NoopMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/MockMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/TransformExecutorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapterTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockStageMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/NoopMetrics.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkUserMetrics.java
Labels: build, cla: yes

#13498 Implementing PR review comments: Clarify authentication module used
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
Labels: build, cla: yes

#13541 [CDAP-18203] Handle dataproc cluster creation error
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: build, cla: yes

#13531 Enable bypass_cmek_check by default to allow all gcp plugins for all distributions
  cdap-master/src/main/resources/capability/bypass_cmek_check.json
  cdap-standalone/src/main/resources/capability/bypass_cmek_check.json
Labels: 6.5, build, cla: yes

#13544 [Cherrypick] [release/6.5] Enable bypass_cmek_check by default
  cdap-master/src/main/resources/capability/bypass_cmek_check.json
  cdap-standalone/src/main/resources/capability/bypass_cmek_check.json
Labels: 6.5, build, cla: yes

#13546 Fixing protobuf dependency by shading into the cdap-security jar
  cdap-security/pom.xml
  pom.xml
Labels: 6.6, build, cla: yes

#13547 Fixing protobuf dependency by shading into the cdap-security jar
  cdap-security/pom.xml
  pom.xml
Labels: 6.5, build, cla: yes

#13556 Fixed issue with default implementation for Stage Metrics
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageMetrics.java
Labels: build, cla: yes

#13552 Upgrade to natty-http 1.7.0 to fix buffer leakage issue
  pom.xml
Labels: 6.6, build, cla: yes

#13557 Feature/fix flaky task worker test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.6, build, cla: yes

#13558 Feature release 65/fix flaky task worker test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13555 [CDAP-18222] Add Binding for InternalAuthenticator to ON_PREM Clusters
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
Labels: 6.5, build, cla: yes

#13542 [CDAP-18208] Disable Runtime Token Generation if Internal Auth is Disabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
Labels: 6.5, Bug, build, cla: yes

#13559 [CDAP-18222] Add Binding for InternalAuthenticator for ON_PREM Clusters
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
Labels: 6.5, build, cherry-pick, cla: yes

#13551 [CDAP-18146] Inherit ImagePullPolicy From Parent Pod
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
Labels: 6.5, build, cla: yes

#13561 [CDAP-18146] Inherit ImagePullPolicy From Parent Pod 6.5 Cherry-Pick
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
Labels: 6.5, build, cherry-pick, cla: yes

#13549 CDAP-18176: Fix high latency issue when deploying pipelines in rbac enabled instances
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
Labels: 6.5, build, cla: yes

#13550 [Cherry-pick 6.5] CDAP-18176: Fix high latency issue when deploying pipelines in rbac enabled instances
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
Labels: 6.5, build, cla: yes

#13560 [CDAP-18208] 6.5 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
Labels: 6.5, build, cherry-pick, cla: yes

#13553 Upgrade to natty-http 1.7.0 to fix buffer leakage issue
  pom.xml
Labels: 6.5, build, cla: yes

#13533 [CDAP-17772] Fix styling
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
Labels: build, cla: yes

#13562 [CDAP-17772] Fix styling 6.5 Cherry-Pick
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationTestContext.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
Labels: 6.5, build, cherry-pick, cla: yes

#13543 [Cherry-Pick] [6.5] Fixed integer overflow issue with records count from SQL Engine operations
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/metrics/ProgramUserMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/StageMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultStageMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/NoopMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/MockMetrics.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/TransformExecutorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapterTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/MockStageMetrics.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/common/NoopMetrics.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkUserMetrics.java
Labels: build, cla: yes

#13563 Skip schema deserialization and hash computation if it's already in cache
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/LRUCache.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaCache.java
  cdap-api-common/src/test/java/io/cdap/cdap/api/data/schema/LRUCacheTest.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/StructuredRecordSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: build, cla: yes

#13564 CDAP-18132 add support to add default connections
  cdap-api/src/main/java/io/cdap/cdap/api/service/AbstractService.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/ServiceConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/ServiceSpecification.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ServiceSpecificationCodec.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/DataPipelineApp.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/PreconfiguredConnectionCreationRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ConnectionConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
Labels: build, cla: yes

#13566 [🍒 into 6.5] Skip schema deserialization and hash computation if it's already in cache
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/LRUCache.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaCache.java
  cdap-api-common/src/test/java/io/cdap/cdap/api/data/schema/LRUCacheTest.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/serializer/StructuredRecordSerializer.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/serializer/KryoSerializerTest.java
Labels: 6.5, build, cla: yes

#13567 CDAP-18132 add support to add default connections
  cdap-api/src/main/java/io/cdap/cdap/api/service/AbstractService.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/ServiceConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/ServiceSpecification.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ServiceSpecificationCodec.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/DataPipelineApp.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/PreconfiguredConnectionCreationRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ConnectionConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
Labels: build, cla: yes

#13573 Connection changes
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/ConnectionCreationRequest.java
Labels: build, cla: yes

#13572 CDAP-18010: Remove unused http REST endpoint TaskWorkerHttpHandlerInt…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
Labels: 6.5, build, cla: yes

#13574 Cherry pick tx
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/ConnectionCreationRequest.java
Labels: build, cla: yes

#13570 CDAP-18251: Fix the bug in which task worker pod does not accept new requests under high contention
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
Labels: 6.5, build, cla: yes

#13571 [cherry-pick] CDAP-18251: Fix the bug in which task worker pod does not accept new requests under high contention
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
Labels: 6.5, build, cla: yes

#13568 [CDAP-18242] Check for CREATE Permission on Compute Profile Creation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
Labels: 6.5, build, cla: yes

#13575 [CDAP-18242] Check for CREATE Permission on Compute Profile Creation 6.5 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProfileHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
Labels: 6.5, build, cherry-pick, cla: yes

#13576 [CDAP-18242] Styling fixes
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
Labels: 6.5, build, cla: yes

#13577 [CDAP-18242] Styling fixes 6.5 Cherry-Pick
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
Labels: 6.5, build, cherry-pick, cla: yes

#13578 CDAP-18272: Fix missing binding for InternalAuthenticator
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: 6.5, build, cla: yes

#13582 [CDAP-18172] Use Proper Authentication Context for System Apps
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
Labels: 6.5, Bug, build, cla: yes

#13583 [CDAP-18172] Use Proper Authentication Context for System Apps 6.5 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
Labels: 6.5, build, cherry-pick, cla: yes

#13581 CDAP-18272: Fix missing binding for InternalAuthenticator
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: 6.5, build, cla: yes

#13585 Make task worker container's disk configurable as readonly or read/write
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13586 Make task worker container's disk configurable as readonly or read/write
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: 6.5, build, cla: yes

#13589 (CDAP-17640) Add YARN client to dependency when running in Hadoop
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.5, build, cla: yes

#13588 (CDAP-17640) Add YARN client to dependency when running in Hadoop
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: 6.6, build, cla: yes

#13590 CDAP-18265 - Remove unnecessary log message to prevent flooding the logs.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: build, cla: yes

#13591 Remove unnecessary log message to prevent flooding the logs.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: build, cla: yes

#13592 [CDAP-18270] - Fix scala 2.11/2.12 compatibility issue
  cdap-spark-core-base/src/main/scala/org/apache/spark/deploy/SparkApplication.scala
Labels: build, cla: yes

#13594 [Cherry-pick for 6.5][CDAP-18270] - Fix scala 2.11/2.12 compatibility issue
  cdap-spark-core-base/src/main/scala/org/apache/spark/deploy/SparkApplication.scala
Labels: 6.5, build, cla: yes

#13597 CDAP-18293 - Retry for 503 error while creating dataproc client
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build, cla: yes

#13596 CDAP-18293 - Retry for 503 error while creating dataproc client
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build, cla: yes

#13598 [CDAP-18288] remove unnecessary artifact upgrades
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
Labels: build, cla: yes
