Repository cdapio/cdap, pull requests merged in 2021-09, with the labels that each got.

#13662 [CDAP-18290] Catch ArrayIndexOutOfBounds in PipelineSpecGenerator
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: cla: yes, build

#13657 [CDAP-18315] Adding k8s spark submitter changes
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: cla: yes, build, 6.6

#13670 [CDAP-18315] Add ArtifactFetcher service for fetching artifacts bundle from spark driver
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/ArtifactFetcherHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/ArtifactFetcherService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build

#13669 [CDAP-17705] Add validation check if source is in middle of pipeline
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
Labels: cla: yes, build

#13674 Cherry-pick lineage improvements into release 6.5
  cdap-api/src/main/java/io/cdap/cdap/api/messaging/Message.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewDataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-program-report/src/main/java/io/cdap/cdap/report/main/MessageUtil.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndpointFieldDeserializer.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsAdminSubscriberService.java
Labels: cla: yes, build, 6.5

#13667 CDAP-18249 Uploading a directive does not close an upload window
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
Labels: cla: yes, build

#13672 [CDAP-18455] Add Spark driver and executor launchers for spark on k8s
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerExecutorLauncher.java
  cdap-spark-core3_2.12/src/k8s/entrypoint.sh
Labels: cla: yes, build, 6.6

#13671 CDAP-18451 setup guice bindings for spark on k8s
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
Labels: cla: yes, build, 6.6

#13679 Remove port binding in unit test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
Labels: cla: yes, build
