Repository cdapio/cdap, pull requests merged in 2021-08, with the labels that each got.

#13600 [Cherry-pick into 6.5][CDAP-18288] remove unnecessary artifact upgrades
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
Labels: build, cla: yes

#13602 [CDAP-18303] Fix Compute Credentials Bug
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.5, Bug, build, cla: yes

#13603 [CDAP-18303] Fix Compute Credentials Bug
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: 6.5, build, cherry-pick, cla: yes

#13599 [CDAP-17858] Fix Upgrade and Post Upgrade Jobs to Work with Proxy Auth Mode
  cdap-client/src/main/java/io/cdap/cdap/client/config/ClientConfig.java
  cdap-client/src/main/java/io/cdap/cdap/client/util/RESTClient.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/PostUpgradeJobMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeUserIDProvider.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: 6.5, Bug, build, cla: yes

#13605 [CDAP-17858] 6.5 Cherry-Pick
  cdap-client/src/main/java/io/cdap/cdap/client/config/ClientConfig.java
  cdap-client/src/main/java/io/cdap/cdap/client/util/RESTClient.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/PostUpgradeJobMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeUserIDProvider.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: 6.5, build, cherry-pick, cla: yes

#13606 Added a method to create nameless record type in Schema
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/test/java/io/cdap/cdap/api/data/schema/SchemaTest.java
Labels: build, cla: yes

#13587 CDAP-18285 : Implementing coalesce for only outer joins case
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
Labels: cla: yes, build

#13593 [CDAP-18125] Allow running workers on k8s
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/TwillConstants.java
Labels: cla: yes, build, 6.6

#13609 Added support for instance Id logic in k8s environment
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/TwillConstants.java
Labels: cla: yes, build, 6.6

#13613 (CDAP-18292) Delete pod with grace-period = 1 to speed up shutdown of task runner
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
Labels: cla: yes, cherry-pick, build, 6.5

#13612 (CDAP-18292) Delete pod with grace-period = 0 to speed up shutdown of task runner
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
Labels: cla: yes, build, 6.6

#13614 CDAP-18337 fix connection macro encode
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
Labels: cla: yes, build

#13580 [CDAP-18273] Runtime Identity Compatibility 6.5 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build

#13616 [CDAP-18330] Dynamic spark plugin does not work with Spark 3.
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/dynamic/DefaultSparkCompiler.scala
Labels: cla: yes, build

#13617 [Cherry-pick into 6.5][CDAP-18330] Dynamic spark plugin does not work with Spark 3.
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/dynamic/DefaultSparkCompiler.scala
Labels: cla: yes, build

#13610 Annotate Worker and Workflow TwillRunnables to allow submitting them as k8s jobs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramLaunchConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkflowTwillRunnable.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/Completable.java
Labels: cla: yes, build, 6.6

#13615 CDAP-18337 fix connection macro escaping
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
Labels: cla: yes, build, 6.5

#13620 [Cherry-pick into 6.5] Exception / log messages cleanup
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/PermissionAdapterFactory.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerInstantiator.java
Labels: cla: yes, build, 6.5

#13621 CDAP-18345: clean up messages in logs and exceptions
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/FileFetcherHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/namespace/RemoteNamespaceQueryClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes, build

#13624 CDAP-18340 let service able to create plugin with macro evaluator
  cdap-api/src/main/java/io/cdap/cdap/api/plugin/PluginConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/http/HttpServiceContext.java
  cdap-api/src/main/java/io/cdap/cdap/api/service/http/ServicePluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultPluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultServicePluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/DefaultPluginContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/service/http/HttpHandlerGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/DefaultConnectorConfigurer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/LimitingConnector.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/service/DefaultSparkHttpServicePluginContext.java
  cdap-unit-test/src/test/java/io/cdap/cdap/service/DynamicPluginServiceApp.java
  cdap-unit-test/src/test/java/io/cdap/cdap/service/DynamicPluginServiceTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/service/function/MacroFunction.java
Labels: cla: yes, build

#13474 [CDAP-18051] Added cache cleanup logic to ArtifactLocalizerService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerCleaner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/FileUtils.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build, 6.5

#13623 [CDAP-18051] Added cache cleanup logic to ArtifactLocalizerService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerCleaner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/FileUtils.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build, 6.5

#13390 Cdap 17939 partition tms 63
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/AbstractMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/MessageTableKey.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RawMessageTableEntry.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/RollbackRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/ScanRequest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/TableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/hbase/HBaseMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartition.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManager.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/PartitionedDBScanIterator.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/MessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/TestMessageEntry.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBMessageTableTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBPartitionManagerTest.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTTLCleanupTest.java
Labels: cla: yes, 6.3, build

#13625 CDAP-18345: clean up messages in logs and exceptions
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/FileFetcherHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/namespace/RemoteNamespaceQueryClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes, build, 6.5

#13627 CDAP-18362-CDAP-18357-multiple-fixes-in-url
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
Labels: cla: yes, build

#13629 CDAP-18362-CDAP-18357-multiple-fixes-in-url
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
Labels: cla: yes, build

#13632 CDAP-18372 disallow disabled connections get created
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
Labels: cla: yes, build, 6.6

#13619 Exception / log messages cleanup
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/PermissionAdapterFactory.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerInstantiator.java
Labels: cla: yes, build

#13618 Add dockerfile to create custom spark image for CDAP execution
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-spark-core3_2.12/pom.xml
  cdap-spark-core3_2.12/src/k8s/Dockerfile
  cdap-spark-core3_2.12/src/k8s/entrypoint.sh
Labels: cla: yes, build, 6.6

#13630 CDAP-18351 change connection metadata to system scope
  cdap-api/src/main/java/io/cdap/cdap/api/app/AbstractApplication.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/metadata/Metadata.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppSpecInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/MetadataWriterStage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/MetadataEmitApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/MockAppConfigurer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/system/AppSystemMetadataWriter.java
Labels: cla: yes, build

#13634 CDAP-18361 fix json value in nested macro evaluation
  cdap-api/src/main/java/io/cdap/cdap/api/macro/MacroEvaluator.java
  cdap-api/src/main/java/io/cdap/cdap/api/macro/MacroObjectType.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParser.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParserTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/TestMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteValidationTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/OAuthMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/OAuthMacroEvaluatorTest.java
Labels: cla: yes, build

#13636 Multiple cherry pick
  cdap-api/src/main/java/io/cdap/cdap/api/app/AbstractApplication.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/macro/MacroEvaluator.java
  cdap-api/src/main/java/io/cdap/cdap/api/macro/MacroObjectType.java
  cdap-api/src/main/java/io/cdap/cdap/api/metadata/Metadata.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppSpecInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/MetadataWriterStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParser.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/MetadataEmitApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/MockAppConfigurer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/MacroParserTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/TestMacroEvaluator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteValidationTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/StudioService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/DefaultMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/OAuthMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/common/OAuthMacroEvaluatorTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/system/AppSystemMetadataWriter.java
Labels: cla: yes, build

#13637 fix connection immutable
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/ConnectionStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/connection/ConnectionStoreTest.java
Labels: cla: yes, build

#13638 fix connection immutable
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/ConnectionStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/connection/ConnectionStoreTest.java
Labels: cla: yes, build

#13635 [🍒 into 6.5] CDAP-18370: Use lz4 version compatible with Spark 3
  cdap-master/pom.xml
Labels: cla: yes, build

#13633 CDAP-18370: Use lz4 version compatible with Spark 3
  cdap-master/pom.xml
Labels: cla: yes, build

#13639 [CDAP-18323] Add exception propagation for artifact localizer
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerHttpHandlerInternal.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RemoteExecutionException.java
Labels: cla: yes, build, 6.5

#13642 [CDAP-18323] Add exception propagation for artifact localizer
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerHttpHandlerInternal.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RemoteExecutionException.java
Labels: cla: yes, cherry-pick, build, 6.5

#13628 CDAP-18374: Add worker pod periodic restart and kill after certain number of user code executions
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build, 6.6

#13641 [cherry-pick] CDAP-18374: Add worker pod periodic restart and kill after certain number of user code executions
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes, build, 6.5

#13645 [cherry-pick] Fix bugs and address comments in PR #13628
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
Labels: cla: yes, build, 6.5

#13644 Fix bugs and address comments in PR #13628
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
Labels: cla: yes, build, 6.5

#13646 Do proper cross-module coverage & add copied sources
  .github/workflows/build-sonar.yml
  cdap-api-spark2_2.11/pom.xml
  cdap-api-spark3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams3_2.12/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core3_2.12/pom.xml
  cdap-coverage/pom.xml
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core3_2.12/pom.xml
  cdap-unit-test-spark2_2.11/pom.xml
  cdap-unit-test-spark3_2.12/pom.xml
  pom.xml
Labels: cla: yes, build

#13648 Reduce unnecessary memory overhead when only the RunId is needed
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
Labels: cla: yes, build, 6.6

#13649 (CDAP-18400) Improve deserialization of FieldLineageInfo
  cdap-api/src/main/java/io/cdap/cdap/api/messaging/Message.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewDataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
  cdap-app-templates/cdap-program-report/src/main/java/io/cdap/cdap/report/main/MessageUtil.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndpointFieldDeserializer.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/FieldLineageInfo.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsAdminSubscriberService.java
Labels: cla: yes, build, 6.6

#13655 Replace retired ha.pool.sks-keyservers.net keyserver with pgp.mit.edu
  cdap-distributions/src/Dockerfile
Labels: cla: yes, build

#13654 Replace retired ha.pool.sks-keyservers.net keyserver with pgp.mit.edu
  cdap-distributions/src/Dockerfile
Labels: cla: yes, build

#13640 [CDAP-18315] Interface changes to pass env related spark configs to…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
Labels: cla: yes, build, 6.6
