Repository cdapio/cdap, pull requests merged in 2021-01, with the labels that each got.

#12965 [CDAP-17483] Fix logical type for preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.4, cla: yes

#12996 [CDAP-17500] Fixes scope in pipelines from hub to be stored correctly before publishing
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
Labels: 6.3, UI, cla: yes

#12998 [CDAP-17508] Fixes preview to show invalid name before starting preview
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.4, UI, cherry-pick, cla: yes

#13000 [CDAP-17512] Resets error between multiple stage level validation calls
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaValidator/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.4, UI, cherry-pick, cla: yes

#12981 [CDAP-17489] Fixes navigating to detailed pipeline while duplicating existing pipeline
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.4, UI, cherry-pick, cla: yes

#13007 (CDAP-16008) Checks if kerberos settings are empty
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
Labels: 6.4, cla: yes

#13009 CDAP-17538 fix cdap broken on kerberos cluster
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: cla: yes

#13004 [CDAP-17519] Log NPE in pipeline app
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: 6.1, cla: yes

#13003 [CDAP-17519] Log NPE in pipeline app
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: 6.2, cla: yes

#12989 [CDAP-17506] Pipeline details: Stop overwriting next run's runtime args with historical values
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
Labels: 6.4, UI, cla: yes

#13011 Cherry pick kerberos
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-security/src/main/java/io/cdap/cdap/security/impersonation/SecurityUtil.java
Labels: cla: yes

#13010 Fix flaky unit test
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.2, cla: yes

#12992 Fix flaky unit test
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: 6.1, cla: yes

#13002 [CDAP-17519] Log NPE in pipeline app
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: 6.3, cla: yes

#12999 [CDAP-17500] Fixes scope in pipelines from hub to be stored correctly before publishing
  cdap-ui/app/cdap/components/CaskWizards/PublishPipeline/index.js
Labels: 6.4, UI, cherry-pick, cla: yes

#12997 [CDAP-17512] Resets error between multiple stage level validation calls
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/SchemaValidator/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/SchemaEditor/index.tsx
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
Labels: 6.3, UI, cla: yes

#13006 [CDAP-17492] Removes schema property while calling validation API (Validate & Get Schema buttons) for individual plugins
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.3, UI, cla: yes

#13017 [CDAP-17541] Ignore exception logs if program is already running for starting program in SystemProgramManagementService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
Labels: cla: yes

#13014 [CDAP-17513] Add loading indicator to plugin list widget while fetching extensions
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.4, UI, cla: yes

#13018 [CDAP-17541] [Cherry-pick] Ignore exception logs if program is already running for starting program in SystemProgramManagementService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
Labels: cla: yes

#13016 [CDAP-17506] Stop overwriting next run's runtime args with historical values for 6.3
  cdap-ui/app/cdap/components/PipelineDetails/RunLevelInfo/RunConfigs.js
Labels: 6.3, UI, cherry-pick, cla: yes

#13013 [CDAP-17526][CDAP-17524][CDAP-17497][CDAP-17514] Replication Fixes
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
Labels: 6.4, Bug, UI, cla: yes

#12988 [CDAP-17508] Fixes preview to show invalid name before starting preview
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
  cdap-ui/app/hydrator/services/create/stores/config-store.js
Labels: 6.3, UI, cla: yes

#13015 [CDAP-17492] Removes schema property while calling validation API (Get Schema button) for individual plugins
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/services/plugin-config-factory.js
Labels: 6.4, UI, cherry-pick, cla: yes

#13020 [CDAP-17513] Add loading indicator to plugin list widget while fetchi…
  cdap-ui/app/cdap/components/AbstractWidget/FormInputs/Select/index.tsx
  cdap-ui/app/cdap/components/AbstractWidget/PluginListWidget/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#13019 (CDAP-17439) Add the missing Preconditions.checkNotNull methods for H…
  cdap-common/src/main/java/io/cdap/cdap/common/lang/GuavaClassRewriter.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/ClassLoaderTest.java
Labels: 6.4, cla: yes

#13021 Replication Fixes cherry-pick
  cdap-ui/app/cdap/components/Replicator/Create/Content/Advanced/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/Content/Summary/ActionButtons/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#13024 [CDAP-17492] Fixes opening plugins in deployed pipeline to properly open plugin properties
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 6.3, UI, cla: yes

#13025 (CDAP-17439) Add the missing Preconditions.checkNotNull methods for H…
  cdap-common/src/main/java/io/cdap/cdap/common/lang/GuavaClassRewriter.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/ClassLoaderTest.java
Labels: cla: yes

#13023 [CDAP-17503] replication fix view mapping error
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
Labels: 6.4, Bug, UI, cla: yes

#13028 [CDAP-17492] Fixes opening plugins in deployed pipeline to properly open plugin properties
  cdap-ui/app/directives/dag-plus/my-dag-ctrl.js
  cdap-ui/app/hydrator/controllers/create/partials/nodeconfig-ctrl.js
  cdap-ui/app/hydrator/templates/partial/node-config-modal/popover.html
Labels: 6.4, UI, cherry-pick, cla: yes

#13027 [CDAP-17545] Fixes js-error while configuring profiles worker nodes for a pipeline
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
Labels: 6.3, UI, cla: yes

#13030 [CDAP-17545] Fixes js-error while configuring profiles worker nodes for a pipeline
  cdap-ui/app/cdap/components/AbstractWidget/RadioGroupWidget/index.tsx
Labels: 6.4, UI, cherry-pick, cla: yes

#13012 CDAP-17504 Introduce new state for preview failing because of OOM so …
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-ui/app/cdap/services/PreviewStatus.ts
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: cla: yes

#13032 CDAP-17540-Add codec for Requirements class to avoid null capabilities
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RequirementsCodec.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/RequirementsCodecTest.java
  cdap-app-fabric/src/test/resources/PluginClass_Pre_6_3.json
  cdap-app-fabric/src/test/resources/Requirements_6_3.json
  cdap-app-fabric/src/test/resources/Requirements_Pre_6_3.json
Labels: cla: yes

#13033 CDAP-17540-Add codec for Requirements class to avoid null capabilities
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RequirementsCodec.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/RequirementsCodecTest.java
  cdap-app-fabric/src/test/resources/PluginClass_Pre_6_3.json
  cdap-app-fabric/src/test/resources/Requirements_6_3.json
  cdap-app-fabric/src/test/resources/Requirements_Pre_6_3.json
Labels: 6.3, cherry-pick, cla: yes

#13031 CDAP-17504 Introduce new state for preview failing because of OOM
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-ui/app/cdap/services/PreviewStatus.ts
  cdap-ui/app/hydrator/controllers/create/toppanel-ctrl.js
Labels: cla: yes

#13029 Bugfix release UI/cdap 17503 replication view mapping 63
  cdap-ui/app/cdap/components/Replicator/Create/Content/Assessment/TablesAssessment/Mappings/index.tsx
Labels: 6.3, Bug, UI, cherry-pick, cla: yes

#13022 [CDAP-17487] Fix overflow issue in RunConfigs popover
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
Labels: 6.4, UI, cla: yes

#13034 [CDAP-17487] Fix overflow issue in RunConfigs popover for 6.3
  cdap-ui/app/cdap/components/PipelineDetails/PipelineModelessOld/PipelineModelessOld.scss
Labels: 6.3, UI, cherry-pick, cla: yes

#13035 [CDAP-17536] Reduce unnecessary logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: cla: yes

#13036 [Cherry-pick] Remove self explanatory logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: 6.3, cherry-pick, cla: yes

#13037 [CDAP-17548] Added json codec for application artifacts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapter.java
Labels: cla: yes

#13038 [Cherry-pick] Added json codec for application artifacts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/ApplicationSpecificationAdapter.java
Labels: 6.3, cherry-pick, cla: yes

#13040 [CDAP-17516] Replication remove total columns information from select tables step
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.4, UI, cla: yes

#13042 [CDAP-17516] Replication remove total columns information from select tables step
  cdap-ui/app/cdap/components/Replicator/Create/Content/SelectTables/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#13044 [CDAP-17550] replication label changes
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
Labels: 6.4, UI, cla: yes

#13045 [CDAP-17550] replication label changes
  cdap-ui/app/cdap/components/Replicator/Create/Content/NameDescription/index.tsx
  cdap-ui/app/cdap/components/Replicator/Create/steps.tsx
  cdap-ui/app/cdap/components/Replicator/List/Deployed/index.tsx
Labels: 6.3, UI, cherry-pick, cla: yes

#13046 Fix first load of CDAP UI in k8s environment
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/cdap-config.js
  cdap-ui/server/config/config-reader.js
  cdap-ui/server/config/parser.js
Labels: 6.4, UI, cla: yes

#13047 CDAP-17559 remove Spark adaptive excecution default in app
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.4, cla: yes

#13048 CDAP-17559 remove Spark adaptive excecution default in app
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: 6.3, cla: yes

#13054 Fix the Spark detection via SSH
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/resources/setupSpark.py
  cdap-app-fabric/src/main/resources/setupSpark.sh
Labels: 6.3, cherry-pick, cla: yes

#13053 Fix the Spark detection via SSH
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/resources/setupSpark.py
  cdap-app-fabric/src/main/resources/setupSpark.sh
Labels: 6.4, cla: yes

#13049 One capability failure should not affect the next
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-unit-test/src/main/resources/pipeline.json
Labels: cla: yes

#13050 One capability failure shoud not affect the next
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-unit-test/src/main/resources/pipeline.json
Labels: cla: yes

#13055 [CDAP-17552] Fixes js error when no time based schedule exists for a pipeline
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/index.js
Labels: 6.4, UI, cla: yes

#13058 [CDAP-17567] Fixes UI to show drafts from user store even if pipeline studio service is down
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
Labels: 6.4, UI, cla: yes

#13061 [Cherry-pick] Redeploy capability with newer artifacts if available.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: 6.3, cherry-pick, cla: yes

#13059 [CDAP-17552] Fixes js error when no time based schedule exists for a pipeline
  cdap-ui/app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/index.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/ActionCreator.js
  cdap-ui/app/cdap/components/PipelineScheduler/Store/index.js
Labels: 6.3, UI, cherry-pick, cla: yes

#13043 Fix first load of CDAP UI in k8s environment
  cdap-ui/server.js
  cdap-ui/server/aggregator.js
  cdap-ui/server/cdap-config.js
  cdap-ui/server/config/config-reader.js
  cdap-ui/server/config/parser.js
Labels: 6.3, UI, cherry-pick, cla: yes

#13057 Provide method to enable capability in unit test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: 6.3, cherry-pick, cla: yes

#13060 [CDAP-17563] Redeploy capability with newer artifacts if available.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityApplierTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: cla: yes

#13062 [CDAP-17567] Fixes UI to show drafts from user store even if pipeline studio service is down
  cdap-ui/app/cdap/components/PipelineList/DraftPipelineView/store/ActionCreator.ts
Labels: 6.3, UI, cherry-pick, cla: yes

#13056 Provide method to enable capability in unit test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cla: yes

#13063 [CDAP-16566] Replication metrics error
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.4, Bug, UI, cla: yes

#13065 [CDAP-16566] Replication metrics error
  cdap-ui/app/cdap/components/ConfigurationGroup/index.tsx
  cdap-ui/app/cdap/components/ConfigurationGroup/utilities/index.ts
  cdap-ui/app/cdap/components/Replicator/Create/Content/PluginConfig/index.tsx
  cdap-ui/app/cdap/components/Replicator/Detail/Monitoring/TableScatterPlotGraph/parser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/Overview/TablesList/metricsParser.ts
  cdap-ui/app/cdap/components/Replicator/Detail/index.tsx
Labels: 6.3, Bug, UI, cherry-pick, cla: yes

#13066 Start CapabilityManagementService after bootstrap steps are complete
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/bootstrap/BootstrapServiceTest.java
Labels: cla: yes

#13067 Start CapabilityManagementService after bootstrap steps are complete
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/bootstrap/BootstrapServiceTest.java
Labels: 6.3, cherry-pick, cla: yes

#13068 Fix flakyness of the CapabilityManagementServiceTest due to artifact store setup
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: cla: yes

#13071 [Cherry-pick] Fix CapabilityManagementServiceTest flakyness
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: 6.3, cherry-pick, cla: yes

#13073 Do not run CapabilityManagementService scheduled runs for CapabilityManagementServiceTest
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/bootstrap/BootstrapServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: cla: yes

#13070 Loop and set the SparkConf instead of calling setAll
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkRuntimeEnv.scala
Labels: 6.3, cherry-pick, cla: yes

#13069 Loop and set the SparkConf instead of calling setAll
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkRuntimeEnv.scala
Labels: 6.4, cla: yes

#13074 Do not run service for CapabilityManagementServiceTest
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/BootstrapService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/bootstrap/BootstrapServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
Labels: 6.3, cherry-pick, cla: yes

#13076 Fix the Spark detection via SSH
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/resources/setupSpark.py
  cdap-app-fabric/src/main/resources/setupSpark.sh
Labels: 6.1, cherry-pick, cla: yes

#13072 Fix the Spark detection via SSH
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/resources/setupSpark.py
  cdap-app-fabric/src/main/resources/setupSpark.sh
Labels: 6.2, cherry-pick, cla: yes

#13078 [CDAP-17599] Fixes setting up UI experiments globally
  cdap-ui/app/cdap/components/Lab/index.tsx
  cdap-ui/app/cdap/components/Lab/types.ts
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/tracker/main.js
Labels: 6.3, UI, cherry-pick, cla: yes

#13077 [CDAP-17599] Fixes setting up UI experiments globally
  cdap-ui/app/cdap/components/Lab/index.tsx
  cdap-ui/app/cdap/components/Lab/types.ts
  cdap-ui/app/cdap/main.js
  cdap-ui/app/cdap/services/helpers.js
  cdap-ui/app/hydrator/main.js
  cdap-ui/app/tracker/main.js
Labels: 6.4, UI, cla: yes

#13079 Fixes component alias from within services helpers module
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.3, UI, cla: yes

#13080 Fixes component alias from within services helpers module.
  cdap-ui/app/cdap/services/helpers.js
Labels: 6.4, UI, cherry-pick, cla: yes

#13085 [CDAP-17290] Change default value for Checkpoint Temp File Rewrite config value
  cdap-common/src/main/resources/cdap-default.xml
Labels: cla: yes

#13095 (CDAP-17645) Applies SSH config from the system and default a timeout
  cdap-common/src/main/java/io/cdap/cdap/common/ssh/DefaultSSHSession.java
Labels: 6.4, cla: yes

#13089 Support DateTime datatype in CDAP Schema
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/format/StructuredRecord.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/SchemaHash.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaHashTest.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/JsonStructuredRecordDatumWriter.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordBuilderTest.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordStringConverterTest.java
Labels: 6.4, cla: yes

#13084 [CDAP-16623] Simplify Connections side panel expand/hide controls
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/ADLSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/BigQueryBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DataPrepBrowserTopPanel/index.tsx
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/DatabaseBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/GCSBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/KafkaBrowser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/S3Browser/index.js
  cdap-ui/app/cdap/components/DataPrep/DataPrepBrowser/SpannerBrowser/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/DataPrepConnections.scss
  cdap-ui/app/cdap/components/DataPrepConnections/NoDefaultConnection/index.tsx
  cdap-ui/app/cdap/components/DataPrepConnections/UploadFile/index.js
  cdap-ui/app/cdap/components/DataPrepConnections/index.js
  cdap-ui/app/cdap/components/FileBrowser/index.js
Labels: 6.4, UI, cla: yes

#13090 [CDAP-17553] Change ActionPopover icon to three dots
  cdap-ui/app/cdap/components/ActionsPopover/ActionsPopover.scss
  cdap-ui/app/cdap/components/ActionsPopover/index.tsx
  cdap-ui/app/cdap/styles/fonts/symbol-defs_new.svg
Labels: 6.4, UI, cla: yes
