Repository cdapio/cdap, pull requests merged in 2022-06, with the labels that each got.

#14359 [CDAP-19341] Validate URI while adding a tethering connection
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
Labels: build

#14358 [CDAP-19342] Tethering: Polling should return a batch of messages
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14361 Fixes to build for Kubernetes E2E test
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/actions/NamespaceCreationActions.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/actions/package-info.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/locators/NamespaceCreationLocators.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/locators/package-info.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/runners/package-info.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/stepsdesign/KubernetesNamespaceCreation.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/stepsdesign/package-info.java
Labels: build

#14362 Revert ClusterRole Validation Upon KubeMasterEnvironment Initialization
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14364 [CDAP-19344] Use the correct artifact repository for local program runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
Labels: build

#14351 [CDAP-19324] Start TokenManager in all AbstractServiceMains
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/AbstractServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MessagingServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SupportBundleServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/server/GrantAccessToken.java
Labels: Bug, build, 6.7

#14365 Cherrypick tethering fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14369 [CDAP-19292] Create only watcher for jobs in non-default namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#14375 [Cherry-pick] [CDAP-19289] [CDAP-19292] Validate tethering connection and watcher threads
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: cherry-pick, build, 6.7

#14356 Update cdap-sdk-ubuntu16-with-uri.json
  cdap-distributions/src/packer/cdap-sdk-ubuntu16-with-uri.json
Labels: build

#14380 CDAP-19078 extend detect schema API
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/DelegatingSeekableInputStream.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InputFile.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InputFiles.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/SeekableInputStream.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidatingInputFormat.java
Labels: build, 6.8

#14381 CDAP-19078 extend detect schema API
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/DelegatingSeekableInputStream.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InputFile.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/InputFiles.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/SeekableInputStream.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidatingInputFormat.java
Labels: build, 6.7

#14383 [cherry-pick] [CDAP-19353] Return STARTING state if program controller is not set
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/DelayedProgramController.java
Labels: build, 6.7

#14384 CDAP-19351 fix s3 sink on odf
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#14385 CDAP-19351 fix s3 sink on odf
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build
