Repository cdapio/cdap, pull requests merged in 2022-02, with the labels that each got.

#13913 Added default values to implementation for backwards compatibility
  cdap-api/src/main/java/io/cdap/cdap/api/feature/FeatureFlagsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/service/ValidationUtilsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRuntime.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/PluginFunctionContext.java
Labels: build

#13916 [CDAP-18322] Fix 2 issues with internal auth: start tokenmanager sooner and auth context for program
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
Labels: build, 6.6

#13903 [CDAP-18785] Add metrics to flow-control
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.6

#13924 [cherry-pick] [CDAP-18785] Add metrics to flow-control
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.6

#13921 [CDAP-18322] Fix 2 issues with internal auth: start tokenmanager sooner er and auth context for program
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/AuthenticationContextModules.java
Labels: build, 6.6

#13692 (CDAP-18796) Added GCP Cloud Spanner StorageProvider implementation
  cdap-master/pom.xml
  cdap-storage-ext-spanner/pom.xml
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStorageProvider.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredRow.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerTransactionRunner.java
  cdap-storage-ext-spanner/src/main/resources/META-INF/services/io.cdap.cdap.spi.data.StorageProvider
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableTest.java
  cdap-storage-ext-spanner/src/test/resources/logback-test.xml
  cdap-storage-spi/pom.xml
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
  pom.xml
Labels: cla: yes, build, 6.7

#13922 CDAP-18791 - Fix LevelDB memory usage
  cdap-common/pom.xml
  cdap-common/src/main/java/io/cdap/cdap/common/app/MainClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/leveldb/FileMetaDataUtil.java
  cdap-common/src/main/java/io/cdap/cdap/common/leveldb/LevelDBClassRewriter.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableServiceTest.java
Labels: build

#13929 [🍒 for 6.6][CDAP-18791] - Fix LevelDB memory usage
  cdap-common/pom.xml
  cdap-common/src/main/java/io/cdap/cdap/common/app/MainClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/leveldb/FileMetaDataUtil.java
  cdap-common/src/main/java/io/cdap/cdap/common/leveldb/LevelDBClassRewriter.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableServiceTest.java
Labels: build

#13935 make cdap use cdap twill instead of apache twill
  cdap-api/pom.xml
  cdap-app-fabric/pom.xml
  cdap-app-templates/cdap-etl/pom.xml
  cdap-client/pom.xml
  cdap-common/pom.xml
  cdap-data-fabric/pom.xml
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-explore-client/pom.xml
  cdap-explore/pom.xml
  cdap-kafka/pom.xml
  cdap-kubernetes/pom.xml
  cdap-master-spi/pom.xml
  cdap-master/pom.xml
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-spi/pom.xml
  cdap-security/pom.xml
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core3_2.12/pom.xml
  cdap-standalone/pom.xml
  cdap-unit-test/pom.xml
  cdap-watchdog/pom.xml
  pom.xml
Labels: build

#13891 CDAP-18653 : Backend changes to support UI : Passing filters section from widget : adding toggle button : new grouping
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProvisionerHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/provisioner/ProvisionerDetail.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#13925 [CDAP-18653]:[cherrypick] : Backend changes to support UI : Passing filters…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerConfig.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProvisionerHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/provision/ProvisioningServiceTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/provisioner/ProvisionerDetail.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#13931 [CDAP-18653][cherrypick] : warn message when unrequired fields are present for auto…
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: build

#13923 [CDAP-18322] Fix connection manager "test connection" for remote execution.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionBrowseTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSampleTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSpecTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTaskBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTestTask.java
Labels: build, 6.6

#13934 [CDAP-18322] Fix connection manager "test connection" for remote execution.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionBrowseTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSampleTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSpecTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTaskBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTestTask.java
Labels: build, 6.6

#13936 make cdap use cdap twill instead of apache twill
  cdap-api/pom.xml
  cdap-app-fabric/pom.xml
  cdap-app-templates/cdap-etl/pom.xml
  cdap-client/pom.xml
  cdap-common/pom.xml
  cdap-data-fabric/pom.xml
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-explore-client/pom.xml
  cdap-explore/pom.xml
  cdap-kafka/pom.xml
  cdap-kubernetes/pom.xml
  cdap-master-spi/pom.xml
  cdap-master/pom.xml
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-spi/pom.xml
  cdap-security/pom.xml
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core3_2.12/pom.xml
  cdap-standalone/pom.xml
  cdap-unit-test/pom.xml
  cdap-watchdog/pom.xml
  pom.xml
Labels: build, 6.6

#13933 [cherrypick] CDAP-18656-JsonListResponders - Adding JsonListResponders for Streaming APIs
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/JsonListResponder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/JsonPaginatedListResponder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/JsonWholeListResponder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/JsonListResponderTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
Labels: build, 6.6

#13932 Bumping surefire version to 3.0.0-M5
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  pom.xml
Labels: build

#13857 fix delete support bundle test
  cdap-app-fabric/src/main/java/io/cdap/cdap/support/services/SupportBundleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/support/services/SupportBundleServiceTest.java
Labels: build

#13937 [Cherry-pick for 6.6] CDAP-18603 Add limits to application scan request, implement pagination in a streaming way with limit & filtering.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/PaginatedApplicationRecords.java
Labels: build

#13860 Dist metric store
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricValue.java
  cdap-watchdog-api/src/test/java/io/cdap/cdap/api/metrics/MetricValueTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsCollectionService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsEmitter.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/Distribution.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/collect/DistributionTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MetricsProcessorServiceTestBase.java
Labels: build, 6.6

#13938 Release/6.6 distribution
  cdap-common/pom.xml
  cdap-common/src/main/java/io/cdap/cdap/common/http/HttpHeaderNames.java
  cdap-common/src/main/java/io/cdap/cdap/common/metrics/MetricsReporterHook.java
  cdap-common/src/main/java/io/cdap/cdap/common/metrics/NoOpMetricsCollectionService.java
  cdap-common/src/test/java/io/cdap/cdap/common/metrics/MetricsReporterHookTest.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricType.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricValue.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsContext.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/NoopMetricsContext.java
  cdap-watchdog-api/src/test/java/io/cdap/cdap/api/metrics/MetricValueTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/pipeline/LogProcessorPipelineContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsCollectionService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsEmitter.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/Distribution.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/collect/AggregatedMetricsCollectionServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/collect/DistributionTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MetricsProcessorServiceTestBase.java
Labels: build, 6.6

#13928 CDAP-18653 : warn message when unrequired fields are present for auto…
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: build

#13940 Cherry Pick 6.6 - add replication transformation feature flag
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#13930 Update the embedded postrgreSQL dependency
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/test/java/io/cdap/cdap/config/SqlUserConfigStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/SqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/queue/SqlJobQueueTableTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/store/SqlProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/SqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/reporting/SqlProgramHeartBeatTableTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/security/SqlDefaultSecretStoreTest.java
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/SqlLineageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/SqlFieldLineageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/registry/SqlUsageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/SqlCachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/PostgresInstantiator.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableConcurrencyTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/store/SqlOwnerStoreTest.java
  pom.xml
Labels: build, 6.7

#13845 Add core API classes to support BQ Pushdown for aggregations
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/Field.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/AggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/AggregationField.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/GroupByAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/GroupByField.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/join/JoinField.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/Relation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/StringExpressionFactoryType.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/GroupByAggregationDefinitionTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockPullProducer.java
Labels: build, bq-pushdown

#13904 [CDAP-18603] Add limits to application scan request, implement pagination in a streaming way with limit & filtering.
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/PaginatedApplicationRecords.java
Labels: build

#13944 [CDAP-18763] added use permission to control access to use operation on entities
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/StandardPermission.java
Labels: build

#13950 [CDAP-18653][cherry-pick] : correcting name to as per UI pr
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: build, 6.6

#13946 Only use higher embedded Postgres version by default in MacOS
  pom.xml
Labels: build, 6.7

#13949 [CDAP-18805] Fix Deploy Failure Error Message
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: cherry-pick, build, 6.6

#13942 Revert ProvisionerExtensionLoader changes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerExtensionLoader.java
Labels: build, 6.7

#13947 [CDAP-18805] Fix Deploy Failure Error Message
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: build, 6.6

#13948 bug : correcting name to as per UI pr
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
Labels: build

#13957 [CDAP-18322] Fixing SystemAuthenticationContext userID and credential setting and pipeline deploy http handler auth check
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/SystemAuthenticationContext.java
Labels: build, 6.6

#13962 Drop unused getApps methods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
Labels: build

#13965 [CDAP-18826] Fix artifact handler permission check
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
Labels: build, 6.6

#13966 [CDAP-18826] Fix artifact handler permission check Cherry-pick 6.6
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandler.java
Labels: build, 6.6

#13970 Small refactoring: short circuit namespace validation when scope is system
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
Labels: build, 6.6

#13971 short circuit namespace validation if it is system scope (i.e. system namespace)
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
Labels: build, 6.6

#13961 [CDAP-18798] Add starting time metric
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.7

#13951 [CDAP-18802] Fixed incorrect log warning during pipeline run
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
Labels: build, 6.6

#13964 [CDAP-18819][cherrypick] : fixing the condition for warn log
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScaling.java
Labels: build

#13963 CDAP-18819 : fixing the condition for warn log
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScaling.java
Labels: build

#13973 [CDAP-18798] Add starting time metric
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: cherry-pick, build, 6.6

#13887 [CDAP-18701] Fix program state transition from STARTING -> RUNNING up…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#13886 [CDAP-18701] Fix program state where it intermittently transitions to…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/ResourceChangeListener.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeJobCleaner.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#13978 CDAP-18810 correct underlying program runs if the workflow status is …
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
Labels: build

#13979 CDAP-18810 correct underlying program runs if the workflow status is …
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
Labels: build, 6.6

#13853 Read stopping event details from TMS and write to persistence
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/NoOpProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/RunRecord.java
Labels: build

#13977 [CDAP-18701] Fix program state transition from STARTING -> RUNNING up…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#13983 [CDAP-18701] Fix program state where it intermittently transitions to…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/ResourceChangeListener.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeJobCleaner.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#13960 CDAP-18820 : moving log warn to a place where it will be called singl…
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build

#13975 [CDAP-18820][cherrypick] : moving log warn to a place where it will be called singl…
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build, 6.6

#13974 [CDAP-18802] Fixed incorrect log warning during pipeline run
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
Labels: cherry-pick, build, 6.6

#13981 Allow edit connections
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/connection/ConnectionStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/ConnectionCreationRequest.java
Labels: build

#13900 [CDAP-18715] Add main service for launching JMX metrics collection service
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentContext.java
  cdap-master/src/main/java/io/cdap/cdap/app/guice/SystemMetricsExporterModule.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/metrics/jmx/JMXMetricsCollector.java
  cdap-master/src/main/java/io/cdap/cdap/metrics/jmx/JMXMetricsCollectorFactory.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/MockMasterEnvironment.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMainTest.java
  cdap-master/src/test/java/io/cdap/cdap/metrics/jmx/JMXMetricsCollectorTest.java
Labels: build

#13958 CDAP-18822 : change condition to handle Blank value for toggle field
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#13976 [CDAP-18822][cherrypick] : change condition to handle Blank value for toggle field
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build, 6.6

#13955 Provide CDAP version for metricwriter extension
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsWriterContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
Labels: build

#13986 [CDAP-18836] Add basic namespace enforcement for connections
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
Labels: build, 6.6

#13972 Adding sampling default property type to BrowseEntity
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/BrowseEntityPropertyValue.java
Labels: build

#13988 Fix race condition in Auth ChannelHandler
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
Labels: build, 6.7

#13984 Enhanced Provisioner Extension loader
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerConfigProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerConfigProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerExtensionLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/resources/META-INF/services/io.cdap.cdap.runtime.spi.provisioner.Provisioner
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/provision/MockProvisionerConfigProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisionerTest.java
  cdap-common/src/main/java/io/cdap/cdap/extension/AbstractExtensionLoader.java
  cdap-master/pom.xml
  cdap-standalone/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoader.java
Labels: build, 6.7

#13980 CDAP-18332: Introduce retries to all non-mutation RemoteDatasetFramework methods.
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkRetryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
Labels: build

#13989 [Cherry-pick into 6.6] CDAP-18332: Introduce retries to all non-mutation RemoteDatasetFramework methods.
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFramework.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkRetryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
Labels: build

#13990 Fix race condition in Auth ChannelHandler
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
Labels: build, 6.6

#13992 [CDAP-18322] Set emtpy runtime token in http header instead of enforcing the presence
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
Labels: build, 6.6

#13991 [CDAP-18322] Set empty runtime token in http header instead of enforcing the presence
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeIdentityHandler.java
Labels: build, 6.6

#13926 Remove the word provisioner from tethering provisioner label
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
Labels: build

#13945 Make TrackingTaskAttemptContext class public to fix plugin issues
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/io/TrackingTaskAttemptContext.java
Labels: build

#13993 [CDAP-18823] - Replace getApps with scanApps
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
Labels: build, 6.6

#13999 [Cherry-pick][CDAP-18823] - Replace getApps with scanApps
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
Labels: build, 6.6

#14000 (CDAP-18594) Set YARN max attempts to 1
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: build, 6.7

#13795 Dataproc timeout increase and making endpoint configurable
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScaling.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14002 Updated Aggregation Definition classes to have a key-value pair for Select expressions.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/AggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/GroupByAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/GroupByAggregationDefinitionTest.java
Labels: build

#13994 [CDAP-18842] Include stream and replication jobs when calculating total number of running programs for flow control
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.6

#14001 [cherry-pick] [CDAP-18842] Include stream and replication jobs when calculating total number of running programs for flow control
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.6

#14006 Adding an invalid relation api
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/InvalidRelation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/Relation.java
Labels: build

#14007 (CDAP-18594) Set YARN max attempts to 1
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: build, 6.6

#14003 (CDAP-18594) Fix workflow inner program state update logic
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/WorkflowProgramInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/BufferingTable.java
Labels: build, 6.7

#13982 Add request time and description field in tethering request.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerBase.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerMetadata.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/PeerState.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringConnectionRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringCreationRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
Labels: build, 6.7

#14008 [CDAP-18845] Fix double counting issue when program is in starting state
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
Labels: build, 6.6

#14009 [cherry-pick] [CDAP-18845] Fix double counting issue when program is in starting state
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
Labels: build, 6.6

#14010 Cherry pick cdap 18594 fix workflow state
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/WorkflowProgramInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/BufferingTable.java
Labels: cherry-pick, build, 6.6

#14012 [Cherry-pick into 6.6][CDAP-18848] Limit of 20K MetricValues can make metric service go OOM
  cdap-common/src/main/resources/cdap-default.xml
Labels: cherry-pick, build, 6.6

#14011 [CDAP-18848] Limit of 20K MetricValues can make metric service go OOM
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14014 Add branch name for sonar analysis
  .github/workflows/build-sonar.yml
Labels: build

#14015 Stop the TokenManager in k8s MasterEnvironmentMain on process shutdown
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
Labels: build, 6.7

#14018 Always shutdown the token manager
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
Labels: build, 6.7

#14021 Stop the TokenManager in k8s MasterEnvironmentMain on process shutdown
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
Labels: build, 6.6

#14020 Added new exception classes to denote errors when operating on relations within an ExpressionFactory
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/ExpressionFactory.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/ExtractableExpression.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/InvalidExtractableExpression.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/InvalidExtractableExpressionException.java
Labels: build

#14025 Add input and output schemas to RelationalTransformContext.
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/RelationalTranformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BasicRelationalTransformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build

#13911 [CDAP-18789] Add artifact cache service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/AbstractArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerCleaner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCache.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/NoOpDiscoveryServiceClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/ArtifactCacheServiceMain.java
Labels: build, 6.7

#14022 CDAP-18700: Expose Plugin template to all users in the same namespace…
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ConsoleSettingsHttpHandler.java
Labels: build, 6.7

#14019 [PLUGIN-975] filter connection specification response on basis of plugin name and type
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSpecTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/SpecGenerationRequest.java
Labels: build

#14033 update twill to 1.0.0
  pom.xml
Labels: build

#14034 update twill to 1.0.0
  pom.xml
Labels: build, 6.6

#14035 [PLUGIN-975] minor refactor to avoid NPE in connection spec
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
Labels: build

#14036 CDAP-18653 : changing labels and values
  cdap-proto/src/main/java/io/cdap/cdap/proto/provisioner/ProvisionerInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#14037 [cherrypick][CDAP-18653] : changing labels and values
  cdap-proto/src/main/java/io/cdap/cdap/proto/provisioner/ProvisionerInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build, 6.6

#13755 Adding debugging logs at File level with size
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: cla: yes, build

#14026 [cherrypick][CDAP-18607]Adding extra detailed debugging logs
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.6

#13820 Add in App Fabric start and end of Event Manager
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/DefaultEventWriterContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterExtensionProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEvent.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/dummy/DummyEventWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/dummy/DummyEventWriterExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisherTest.java
  cdap-app-fabric/src/test/resources/mocked_pipeline_notification.json
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/Event.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/EventWriter.java
  cdap-standalone/src/main/resources/cdap-site.xml
Labels: build

#13840 [CDAP-18740] Process control messages from tethered instances
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: build, 6.7

#14032 [CDAP-18857] Limit artifact repository upload parallelism
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14031 [Cherry-pick][CDAP-18857] Limit artifact repository upload parallelism
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14040 [Cherry-pick] Use fetch size for all statements where executeQuery is called
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
Labels: build

#13967 add health check generic service, handler and implemntation
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/InstancePermission.java
  cdap-support-bundle/pom.xml
  cdap-support-bundle/src/main/java/io/cdap/cdap/app/guice/HealthCheckModule.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/app/guice/SupportBundleServiceModule.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/handlers/HealthCheckHttpHandler.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/implementation/HealthCheckImplementation.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/internal/app/services/HealthCheckService.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/metadata/HealthCheckFetcher.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/metadata/RemoteHealthCheckFetcher.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/healthcheck/HealthCheckImplementationTest.java
Labels: build

#14041 Added previous signature to constructor
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/SpecGenerationRequest.java
Labels: build

#13895 [CDAP-18774] Create tethering message payload to launch pipelines
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
Labels: build, 6.7

#14058 CDAP-18389 fail if bad macro is provided
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTaskBase.java
Labels: build

#14057 CDAP-18745 increase retry timeout for conn macro
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#14054 Updated SQLEngineCollection to run pull operations for Store tasks within the async runnable
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
Labels: build

#14059 CDAP-18733 add metrics for connection
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
Labels: build

#14051 Existing Dataproc Root URL fix
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScaling.java
Labels: build

#14064 Fix tagNameToHuman conversion in MetricsQueryHelper
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryHelper.java
Labels: build

#14045 Feature/cdap 18575 cdap event publish program status
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/DefaultEventWriterContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterExtensionProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEvent.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/dummy/DummyEventWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/dummy/DummyEventWriterExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisherTest.java
  cdap-app-fabric/src/test/resources/mocked_pipeline_notification.json
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-event-writer-spi/pom.xml
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/Event.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/EventType.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/EventWriter.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/EventWriterContext.java
  cdap-standalone/src/main/resources/cdap-site.xml
  pom.xml
Labels: build

#14062 Fixed issue with aggregations not generating metrics in the SQL engine
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build

#14046 Metrics provider
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ExecutionMetrics.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/MetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/http/SparkApplicationsResponse.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/http/SparkApplicationsStagesResponse.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-app-fabric/src/test/resources/mocked_spark_applications_response.json
  cdap-app-fabric/src/test/resources/mocked_spark_stages_response.json
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build
