Repository cdapio/cdap, pull requests merged in 2022-03, with the labels that each got.

#13736 [CDAP-18574] check user visibility for support bundle
  cdap-app-fabric/src/main/java/io/cdap/cdap/support/handlers/SupportBundleHttpHandler.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/element/EntityType.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/SupportBundleEntityId.java
Labels: cla: yes, build, 6.7

#13985 CDAP-18837: Bringing up system pods for execution
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillApplication.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: build, 6.7

#14029 [CDAP-18841] Add tether peer name to run record
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/RunRecord.java
Labels: build, 6.7

#14053 Update GCS bucket field description in compute profile to be more accurate
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build, 6.7

#14065 CDAP-18880 - Adding changes for system pods client url
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
Labels: build, 6.7

#14067 Improved logging when a SQL Engine write task fails
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
Labels: build

#14069 retry - enabling replication transformation for 6.7+
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14070 Added runtime argument that can be used to disable ELT Transformation pushdown, if enabled.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/AutoJoinerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
Labels: build

#14075 CDAP-18905 make MockExternalSink more resilient
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockExternalSink.java
Labels: build, 6.7

#14080 Added 2 additional filter functions for Dedup aggregation definition
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinition.java
Labels: build

#14078 [CDAP-18879] Only bind RemoteAuthenticator for TetheringAgentService to external usages
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-common/src/main/java/io/cdap/cdap/common/guice/RemoteAuthenticatorModules.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
Labels: build, 6.7

#14044 CDAP-18864: Adding logic for system pods to accept tasks
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnableTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14073 Moved classes to Event Writer SPI from App Fabric
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/MetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-event-writer-spi/pom.xml
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ExecutionMetrics.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ProgramStatusEvent.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ProgramStatusEventDetails.java
Labels: build

#14039 Use fetch size for all statements where executeQuery is called
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
Labels: build

#14050 [CDAP-18788] Update TetheringAgentService to start/stop programs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: build, 6.7

#14028 [CDAP-18648] Add a service in app fabric to scan for programs in stopping status
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14068 [CDAP-18891] Use peer's artifacts for tethered pipeline runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheServiceTest.java
Labels: build, 6.7

#14091 Fix guice dependencies for ArtifactCacheService, TetheringAgentService
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ProgramRunnerRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCache.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/ArtifactCacheServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
Labels: build, 6.7

#14092 Add metricswriter extension to CDAP image - part 2
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoader.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoaderTest.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/loader/MockMetricsWriter.java
Labels: build

#14093 Updating check style rules
  cdap-api-common/src/main/java/io/cdap/cdap/api/common/Bytes.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/AppWithWorker.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinitionTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/GroupByAggregationDefinitionTest.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/HttpEndpointPrefixCompleter.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/completer/element/HttpMethodPrefixCompleter.java
  cdap-common/src/main/java/io/cdap/cdap/common/db/DBConnectionPoolManager.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/guava/ClassPath.java
  cdap-common/src/test/java/io/cdap/cdap/common/conf/CConfigurationUtilTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/api/dataset/lib/KeyValueTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/TestObject.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/partitioned/PartitionConsumerTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetArgumentsTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/partitioned/PartitionedFileSetTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/partitioned/TimePartitionedFileSetTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/MDSKeyTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/ObjectStoreDatasetTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsHandlerTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/zookeeper/SharedResourceCache.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/TestTokenManager.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkContainerLauncher.java
  cdap-unit-test/src/test/java/io/cdap/cdap/partitioned/PartitionRollbackTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/AppWithWorker.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/TopicProcessMeta.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/collect/DistributionTest.java
  checkstyle.xml
Labels: build, 6.7

#14094 Fix build failure in ProgramRunStatusMonitorServiceTest
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
Labels: build

#14097 CDAP-18890 update program killer to kill and skip tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
Labels: build, 6.7

#14083 [CDAP-18927] Send program state updates to local TMS when running in …
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/LocalClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/guice/MessagingClientModule.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/guice/MessagingServerRuntimeModule.java
Labels: build, 6.7

#14082 [CDAP-18121] Disable launching kubernetes jobs on certain environments
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-common/src/main/java/io/cdap/cdap/common/ProgramRunForbiddenException.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: build, 6.7

#14098 Use remote tethering authenticator in artifact cache
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheService.java
Labels: build

#13737 [CDAP-18564] ensure support bundle executor finish
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/SupportBundleServiceMainTest.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/handlers/SupportBundleHttpHandler.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/services/SupportBundleGenerator.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/handlers/SupportBundleHttpHandlerTest.java
Labels: cla: yes, build, 6.7

#14106 [CDAP-18907] additional tags in starting and runtime metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
Labels: build, 6.7

#14104 [CDAP-18937] Code cleanup: rename Count -> Counter
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
Labels: build, 6.7

#14107 Fix/make tests universal
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/LocalizationUtilsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryServiceTest.java
Labels: build

#14108 [CDAP-18933] Send program state updates between tethered instances
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlChannelRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/MockTetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
Labels: build, 6.7

#14103 [CDAP-18648] Change default stop programs behavior
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#13808 [CDAP-18526] Map programs to k8s namespaces
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTxTimeoutTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeJobCleaner.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: build, 6.7

#14110 Added explicit classloader to the BigQuery SQL Engine Adapter child threads
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build

#14079 [CDAP-18955] Launch Pipeline Refactoring
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/deploy/ProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ConfiguratorFactoryProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactoryProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ProgramRunDispatcherInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.7

#14111 [CDAP-18224] Replace use of getApps in SupportBundlePipelineInfoTask with scan
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ApplicationDetailFetcherTest.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/task/SupportBundlePipelineInfoTask.java
Labels: build, 6.7

#14109 CDAP-18945 add more logging to program stopper
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramStopSubscriberService.java
Labels: build, 6.7

#14112 Added method to execute ad-hoc jobs using the SQL Engine Adapter.
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
Labels: build

#14114 CDAP-18945 add more logging to help debug flaky tests
  cdap-common/src/test/resources/logback-test.xml
Labels: build

#14113 Rename metric writer folder
  cdap-master/pom.xml
Labels: build

#14090 [CDAP-18955] Remote program run dispatcher integration
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactoryProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ProgramRunDispatcherTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.7

#14027 Moved DefaultFeatureFlags to cdap common and Moved MetricsHook to NettyHttpService
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/AuthorizationHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerMetricsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/feature/DefaultFeatureFlagsProvider.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceBuilder.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/CommonNettyHttpServiceFactory.java
  cdap-common/src/main/java/io/cdap/cdap/common/metrics/MetricsReporterHook.java
  cdap-common/src/test/java/io/cdap/cdap/common/metrics/MetricsReporterHookTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetService.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/service/executor/DatasetOpExecutorService.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/service/DatasetServiceTestBase.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/executor/ExploreExecutorService.java
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/transaction/TransactionHttpService.java
  cdap-security/src/test/java/io/cdap/cdap/security/auth/context/RemoteClientAuthenticatorTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/SecureStoreTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/service/ArtifactFetcherService.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/services/SupportBundleInternalService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/server/MessagingHttpService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/logbuffer/LogBufferService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogQueryService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogSaverStatusService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsProcessorStatusService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryService.java
Labels: build

#14101 [CDAP-18955] Add support for remote program run dispatch tasks
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ImpersonatedTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/RemoteTwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillApplication.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnableTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/SConfiguration.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14115 [CDAP-18526] Skip checking for configs for bootstrapped namespaces
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: build, 6.7

#14119 Tethering agent: fix peer URI construction
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
Labels: build

#14121 Revert "[CDAP-18927] Send program state updates to local TMS when run…
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/LocalClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/guice/MessagingClientModule.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/guice/MessagingServerRuntimeModule.java
Labels: build

#14124 Artifact cache fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/NoOpDiscoveryServiceClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/URIScheme.java
Labels: build, 6.7

#14118 [CDAP-18967] Add cdap-authenticator-ext-gcp module dependency
  cdap-master/pom.xml
Labels: build, 6.7

#14126 [CDAP-18967] Add cdap-authenticator-ext-gcp module dependency to cdap-master Cherry-Pick 6.7
  cdap-master/pom.xml
Labels: build, 6.7

#14128 Make terminate time grace period configurable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14129 [Cherry-pick][CDAP-18988] Make metric processing fair under load
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
Labels: build

#14131 [CDAP-18993] Improve metrics cleanup speed by doing removal per-row instead of per-column
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/MetricsTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/MetricsTableTest.java
Labels: build

#14125 Support using tethered peer namespace for artifact caching
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
Labels: build, 6.7

#14132 [Cherry-pick][CDAP-18993] Improve metrics cleanup speed by doing removal per-row instead of per-column
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/MetricsTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBMetricsTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/table/MetricsTableTest.java
Labels: build, 6.7

#14089 Add feature flag support_and_triggers
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build
