Repository cdapio/cdap, pull requests merged in 2022-12, with the labels that each got.

#14783 [CDAP-20168] fix NPE while running preview when runtime args are null
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
Labels: build

#14784 fix(CDAP-19783&CDAP-20018): use stream fashion for getApplications
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ApplicationFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/store/ScanApplicationsRequestTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
Labels: build

#14785 [CDAP-20172] Fix security vulnerabilities due to hadoop-common dependency
  cdap-kms/pom.xml
  cdap-standalone/pom.xml
  pom.xml
Labels: build

#14795 [CDAP-20184] Bump up tethering client read timeout
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14796 [CDAP-20171] fix pushdown config with lcm
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultPluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: build

#14786 Bumped commons-compress dependency to 1.22 version
  pom.xml
Labels: build

#14791 [vuln-fix] exclude xalan:xalan in esapi dependency to resolve vulnerability
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  pom.xml
Labels: build

#14798 [Cherry pick] 6.8.1-CDAP-20171
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultPluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: build

#14799 CDAP-19500: add retries for connection macro evaluator
  cdap-api-common/src/main/java/io/cdap/cdap/api/common/Constants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
Labels: build

#14789 Fix security vulnerabilities due to netty dependency
  pom.xml
Labels: build

#14800 Fix security vulnerability in org.apache.ivy:ivy dependency
  pom.xml
Labels: build

#14803 Cherrypick cdap 20043 to 6.8.0 branch
  cdap-api/src/main/java/io/cdap/cdap/api/metadata/MetadataEntity.java
  cdap-api/src/test/java/io/cdap/cdap/api/metadata/MetadataEntityTest.java
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ScheduledRunTimeTest.java
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ProgramSchedule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ProgramScheduleRecord.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/queue/JobQueueTable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteScheduleFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/SleepingWorkflowApp.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppScheduleUpdateTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ScheduleFetcherTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ScheduleClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/MetadataUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/metadata/MetadataEntityCodecTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/OwnerTable.java
  cdap-master/src/main/java/io/cdap/cdap/master/upgrade/UpgradeJobMain.java
  cdap-metadata-spi/src/test/java/io/cdap/cdap/spi/metadata/MetadataStorageTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ScheduleDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/codec/NamespacedEntityIdCodec.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ScheduleId.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/ProtoTriggerCodecTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: build

#14806 [CDAP-20205] Overwrite org.apache.ivy to use 2.5.1
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core3_2.12/pom.xml
  pom.xml
Labels: Bug, build

#14807 [CDAP-20206] Fix flaky CDAPLogAppenderTest
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/system/CDAPLogAppenderTest.java
Labels: Bug, build

#14792 [CDAP-20182] Update security policy
  CONTRIBUTING.rst
  SECURITY.md
Labels: Docs, build

#14805 [Cherry pick] Change search log to trace level instead of debug
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
Labels: build, 6.8

#14808 Fix tethering e2e tests
  cdap-e2e-tests/pom.xml
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRegistration.feature
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRuntime.feature
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringServer.java
Labels: build

#14790 fix(CDAP-20174): fix performance issue caused by scanning runs ignoring version
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/StoreProgramRunRecordFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/task/SupportBundlePipelineInfoTask.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/context/LoggingContextHelper.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LocalProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/ProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/RemoteProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/AppMetadataStore.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/ProgramStore.java
Labels: build

#14804 Change search log to trace level instead of debug
  cdap-elastic/src/main/java/io/cdap/cdap/metadata/elastic/ElasticsearchMetadataStorage.java
Labels: build

#14809 Cherry pick/cdap-20174
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/StoreProgramRunRecordFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/support/task/SupportBundlePipelineInfoTask.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/context/LoggingContextHelper.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LocalProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/LogHttpHandler.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/ProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/RemoteProgramRunRecordFetcher.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/AppMetadataStore.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/ProgramStore.java
Labels: build

#14811 [CDAP-20212] Properly filter out multi-release jar dependencies from dependency tracing logic
  cdap-common/src/main/java/io/cdap/cdap/common/lang/ClassPathResources.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/ClassPathResourcesTest.java
Labels: build

#14771 [CDAP-19636] Upgraded k8s java client version to 16.0.2
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/WorkloadIdentityUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
Labels: build

#14815 Revert "Fix security vulnerabilities due to netty dependency"
  pom.xml
Labels: build

#14817 [CDAP-20222] Overwrite org.apache.ivy version to 2.5.1 to remediate CVE-2022-37866
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core3_2.12/pom.xml
  pom.xml
Labels: build, 6.8

#14818 [CDAP-20222] Overwrite org.apache.ivy version to 2.5.1 to remediate CVE-2022-37866
  pom.xml
Labels: cherry-pick, build, 6.8
