Repository cdapio/cdap, pull requests merged in 2022-09, with the labels that each got.

#14478 chore(CDAP-19495): Add feature flag for LCM edit
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14498 [CDAP-19462] Enforce at least once correct initialization for SystemMetricsExporter
  cdap-master/src/main/java/io/cdap/cdap/metrics/publisher/MetricsWritersMetricsPublisher.java
  cdap-master/src/test/java/io/cdap/cdap/metrics/publisher/MetricsWritersMetricsPublisherTest.java
Labels: build

#14512 CDAP-19565 fix backwards incompatible change to storage SPI
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdmin.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTableAdmin.java
Labels: build, 6.8

#14510 feature/CDAP-19521-remove-registry
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/CachedStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStorageProvider.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/CachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/NoSqlCachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/SqlCachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistryTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableAdminTest.java
Labels: build

#14519 [CDAP 19575] Cherry pick fixes in LocalizationUtilsTest to release/6.6
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/LocalizationUtilsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionDiscoveryServiceTest.java
Labels: build

#14516 CDAP-19573 increase default resources for test pipelines
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: build

#14513 [CDAP-19476] Add logs in TetheringAgentService, TetheringServerHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
Labels: build

#14505 CDAP-19540: add unit test for overwriting old tags and properties
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/DefaultMetadataServiceClientTest.java
Labels: build

#14511 Add additional stage metrics for Pushdown execution
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/engine/SQLEngineJobTypeMetric.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build

#14518 feat(CDAP-19426): add parentversion in draft store
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/draft/Draft.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/draft/DraftStoreRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DraftServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
Labels: build

#14517 CDAP-19577 - Auto detect atleast once processing mode for streaming pipelines
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpec.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsStateSpec.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/MockStateHandlerSource.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingStateHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build, 6.8

#14521 Cache artfacts and artifact_archive.jar files in GCS
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobTwillPreparer.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/CacheableLocalFile.java
Labels: build, 6.8

#14531 CDAP-19614 - Don't pass ApplicationDescription through the runtime service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
Labels: build

#14533 [Cherry pick info 6.7] CDAP-19618 Deduplicate strings in MetricValues deserialization
  cdap-common/src/main/java/io/cdap/cdap/common/io/StringCachingDecoder.java
  cdap-common/src/test/java/io/cdap/cdap/common/io/StringCachingDecoderTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
Labels: build

#14534 [Cherry-pick into 6.7] CDAP-19614 - Don't pass ApplicationDescription through the runtime service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
Labels: build

#14532 CDAP-19618 Deduplicate strings in MetricValues deserialization
  cdap-common/src/main/java/io/cdap/cdap/common/io/StringCachingDecoder.java
  cdap-common/src/test/java/io/cdap/cdap/common/io/StringCachingDecoderTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
Labels: build

#14535 Refactor AppDeploymentInfo class
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
Labels: build, 6.8

#14507 CDAP-19536: hide version in MatadataEntity json response
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataHttpHandler.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/AbstractMetadataClient.java
  cdap-common/src/main/java/io/cdap/cdap/common/metadata/MetadataEntityCodec.java
  cdap-common/src/test/java/io/cdap/cdap/common/metadata/MetadataEntityCodecTest.java
Labels: build

#14523 CDAP-19556 | State store changes in platform
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppStateHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/state/AppStateKey.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/state/AppStateKeyValue.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/state/AppStateTable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/state/AppStateHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/state/AppStateTableTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
Labels: build

#14522 Adds pipeline runtime argument to prevent cleanup of k8s resources
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/SystemArgumentsTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillControllerTest.java
Labels: build, 6.8

#14530 Streaming pipeline runner changes for state handling
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsStateSpec.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingEventHandler.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/EmittedRecords.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: build

#14537 [CDAP-19551] Add Dataproc config to explicitly disable GCS caching in a profile
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
Labels: build, 6.8

#14543 CDAP-19601 : changing default drop down option for machine type to E2
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#14544 [cherrypick][6.7.2][CDAP-19601] Bug-cherry pick cdap 19601 default machinetype
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#14527 [CDAP-19569] cache twill and launcher jar to prevent building for every run
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJarUtil.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14547 Update the deprecated spark configuration key
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: build, 6.8

#14524 [CDAP-19581] Start deployment watcher thread for non-system namespaces
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeAPIException.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: Bug, build, 6.8

#14529 [CDAP-19609] Create an access token generator tool
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AccessTokenGeneratorService.java
  cdap-security/src/test/java/io/cdap/cdap/security/tools/AccessTokenGeneratorServiceTest.java
Labels: build

#14557 Possible fix for flaky HangingWorkerTest ITN. Increasing stop wait ti…
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
Labels: build

#14558 Log ProgramId of App timing out during Stop
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
Labels: build

#14548 Extend scanByIndex in StructuredTable - sql/spanner implementation
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14553 Enable state handling in StreamingContext
  cdap-api-spark-base/src/main/scala/io/cdap/cdap/api/spark/SparkExecutionContextBase.scala
  cdap-api/src/main/java/io/cdap/cdap/api/app/AppStateStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppStateModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/InMemoryProgramRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppStateHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AppStateStoreProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/BasicMapReduceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/BasicMapReduceTaskContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/batch/MapReduceTaskContextProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/customaction/BasicCustomActionContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/BasicServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/BasicSystemServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/ServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/worker/BasicWorkerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/worker/WorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/BasicWorkflowContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/WorkflowDriver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/workflow/WorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ServiceHttpServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/state/AppStateHandlerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SerializableSparkExecutionContext.scala
Labels: build

#14536 [CDAP-19529] Setup Classloading for SparkTwillRunnable for running in MasterEnvironment
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramRuntimeProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/DummyProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentRunnableContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilters.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkResourceFiltersTest.java
Labels: Bug, build, 6.7, 6.8

#14563 [CDAP-19632] Check if delete lifecycle is enabled on bucket before caching artifacts
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14562 CDAP-18510 only skip k8s job cleanup if the job failed
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillControllerTest.java
Labels: build, 6.8

#14567 CDAP-19463 make k8s client connect and read timeouts configurable
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/ApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultKubeMasterPathProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodKillerTask.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/PodKillerTaskTest.java
Labels: build, 6.8

#14568 Fixed a bug in AccessTokenGeneratorService
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AccessTokenGeneratorService.java
  cdap-security/src/test/java/io/cdap/cdap/security/tools/AccessTokenGeneratorServiceTest.java
Labels: build

#14566 [CDAP-19605] Collect logs from the twill AM container as part of program execution logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/common/twill/TwillAppLifecycleEventHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: build, 6.8

#14572 CDAP-19560 - Add state store enabled info in streaming context
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/streaming/StreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build

#14569 [CDAP-19459] Refactor ArtifactClassLoaderFactory to use ProgramRunnerClassLoaderFactory
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ProgramRunnerClassLoaderModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryWithLocalization.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheServiceTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
Labels: build, 6.8

#14561 [CDAP-18966] Run kubeJobCleaner only in appfabric pod
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeJobCleaner.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentTask.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MasterTaskExecutorService.java
Labels: build, 6.8

#14554 NoSql scan by filter and range
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14577 CDAP-19560 - Add stage name prefix to the state key for uniqueness in the app
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
Labels: build

#14575 CDAP-19563 | Add warning message as untested usage for more than one source to discourage users
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
Labels: build

#14559 CDAP-19562 | Capture metrics for multiple sources, types for atleast once processing used by pipelines
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14580 update locators for tethering e2e tests
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/locators/TetheringLocators.java
Labels: build
