Repository cdapio/cdap, pull requests merged in 2022-01, with the labels that each got.

#13757 build new module for support bundle
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/RouterPathLookup.java
  cdap-master/pom.xml
  cdap-master/src/main/java/io/cdap/cdap/common/MasterUtils.java
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SupportBundleServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/MasterServiceMainTestBase.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/SupportBundleServiceMainTest.java
  cdap-standalone/pom.xml
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
  cdap-support-bundle/pom.xml
  cdap-support-bundle/src/main/java/io/cdap/cdap/app/guice/SupportBundleServiceModule.java
  cdap-support-bundle/src/main/java/io/cdap/cdap/internal/app/services/SupportBundleInternalService.java
  cdap-unit-test/pom.xml
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  pom.xml
Labels: cla: yes, build

#13809 [CDAP-18621] Allow overriding of idle ttl minutes value for dataproc clusters
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#13811 change the snapshot version to 6.7
  cdap-support-bundle/pom.xml
Labels: build

#13813 Allow overriding of idle ttl minutes value for dataproc clusters
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#13822 [CDAP-18738]: Enable cluster reuse when skip delete is enabled.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#13792 make starting pipeline idempotent for dataproc and k8s
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.6

#13823 fix the support bundle test null pointer
  cdap-app-fabric/src/test/java/io/cdap/cdap/support/services/SupportBundleServiceTest.java
Labels: build

#13777 Log System.exit in tests to track "The forked VM terminated" test flackiness
  cdap-unit-test/src/main/java/io/cdap/cdap/test/LogSystemExitRule.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build

#13824 [6.6 Cherry-pick][CDAP-18738]: Enable cluster reuse when skip delete is enabled.
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build, 6.6

#13825 make starting pipeline idempotent for dataproc
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#13819 [CDAP-18737] Initialize GSON with ApplicationSpecificationAdapter
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
Labels: build, 6.6

#13827 [cherry-pick] [CDAP-18737] Initialize GSON with ApplicationSpecificationAdapter
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
Labels: build, 6.6

#13826 make starting pipeline idempotent for dataproc and k8s
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.7

#13821 [CDAP-18603] Adding basic support for Pagination in the getAllApps API
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/PaginatedApplicationRecords.java
Labels: build, 6.6

#13796 [CDAP-18680] Fix issue with pipelines failing when app-fabric restarts
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
Labels: build, 6.6

#13807 [CDAP-18696] Add flow control to launch requests
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCounter.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/TooManyRequestsException.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13831 [cherry-pick] [CDAP-18680] Fix issue with pipelines failing when app-fabric restarts
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
Labels: build

#13830 [cherry-pick] [CDAP-18680] Fix issue with pipelines failing when app-fabric restarts
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
Labels: build, 6.6

#13780 Get stopping timeout from Runtime Handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/ProgramRunInfo.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ProgramRunStatus.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/RunRecord.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
Labels: build

#13759 CDAP-18643 regenerate app spec for on premise program run
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/RuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppRuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SystemProgramManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/executor/AppCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/ExternalSparkProgram.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteValidationTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/service/ValidationUtilsTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsApp.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-batch/src/main/java/io/cdap/cdap/etl/batch/mapreduce/ETLMapReduce.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/BatchPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/ConnectionRegistryMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/PipelinePhase.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/spec/PipelineSpecGeneratorTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/test/HydratorTestBase.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/transform/PluginValidationTransform.java
Labels: cla: yes, build, 6.7

#13814 [CDAP-18725] Adding additional tags in existing program metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build, 6.6

#13818 [CDAP-18713] Add Workload Identity Setup Support for K8s Environment
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/DefaultLocalFileProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/LocalFileProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/identity/GCPWorkloadIdentityCredential.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultKubeMasterPathProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterPathProvider.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/DefaultLocalFileProviderTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/TemporaryLocalFileProvider.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/TemporaryLocalFileProviderTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build, 6.7

#13833 [CDAP-18656] Adding BatchingConsumer and using Consumer in getApps
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/BatchingConsumer.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-common/src/test/java/io/cdap/cdap/common/utils/BatchingConsumerTest.java
Labels: build, 6.6

#13835 [CDAP-18725] Adding additional tags in existing program metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetail.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/RunRecordDetailWithExistingStatus.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build, 6.6

#13812 [CDAP-18720] Kubernetes namespace creation for bootstrap namespaces
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/NamespaceHttpHandler.java
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/NamespaceId.java
Labels: build, 6.7

#13838 [CDAP-18322] Save user principal of preview request to set up SecurityRequestContext when running preview
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/preview/PreviewStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRequestQueue.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/RemotePreviewRequestFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRequestQueueTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStoreTest.java
Labels: build, 6.6

#13842 Revert "Log System.exit in tests to track "The forked VM terminated" test flackiness"
  cdap-unit-test/src/main/java/io/cdap/cdap/test/LogSystemExitRule.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build

#13834 [CDAP-18748] Set pending/starting runs in run record counter upon app-fabric restart
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCounter.java
Labels: build, 6.6

#13847 [cherry-pick] [CDAP-18748] Set pending/starting runs in run record counter upon app-fabric restart
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordCounter.java
Labels: build, 6.6

#13841 [CDAP-18322] Set empty user credential in SecurityRequestContext instead of enforcing they are present in the request.
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
Labels: build, 6.6

#13850 add existing app spec to runtime configurer
  cdap-api/src/main/java/io/cdap/cdap/api/app/RuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppRuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
Labels: build

#13784 [CDAP-18601] Create provisioner for tethered instances
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringConf.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/main/resources/META-INF/services/io.cdap.cdap.runtime.spi.provisioner.Provisioner
  cdap-app-fabric/src/main/resources/tethering.json
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisionerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-master/pom.xml
  cdap-standalone/pom.xml
Labels: build, 6.7

#13849 [CDAP-18322] Make WorkerAuthenticationContext get principal from SecurityRequestContext
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/WorkerAuthenticationContext.java
Labels: build, 6.6

#13851 [CDAP-18322] Set auth headers when ArtifactLocalizerClient requests localizing artifacts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
Labels: build, 6.6

#13848 [CDAP-18322] Mount secret in sidecar ArtifactLocalizer but not in preview runner and task worker
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.6

#13854 Cherrypick Internal Auth Fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/preview/PreviewStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRequestQueue.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/RemotePreviewRequestFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRequestQueueTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/preview/DefaultPreviewStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/context/WorkerAuthenticationContext.java
Labels: build, 6.6

#13856 fix streaming pipeline by using the old pipeline id
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpec.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/aggregator/FieldCountAggregator.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/aggregator/FieldCountReducibleAggregator.java
Labels: build

#13782 [CDAP-18672] - Moving fetch size to a config
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStorageProvider.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/SqlCachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistryTest.java
Labels: build, 6.6

#13859 [CDAP-18763] add system app entity id
  cdap-proto/src/main/java/io/cdap/cdap/proto/element/EntityType.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/SystemAppEntityId.java
Labels: build, 6.7

#13839 Enhance state transition diagram to include stopping state
  cdap-api/src/main/java/io/cdap/cdap/api/ProgramStatus.java
  cdap-api/src/main/java/io/cdap/cdap/api/workflow/NodeStatus.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ProgramRunStatus.java
Labels: build

#13862 [CDAP-18322] Fix two issues for preview when internal auth is enabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessTokenValidator.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/TokenManager.java
Labels: build, 6.6

#13865 [CDAP-18322] Fix two issues for preview when internal auth is enabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewManager.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/AccessTokenValidator.java
  cdap-security/src/main/java/io/cdap/cdap/security/auth/TokenManager.java
Labels: build, 6.6

#13866 Set to use a test temp directory to avoid generating a “data” directo…
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiatorTest.java
Labels: build, 6.7

#13869 [CDAP-18322] Leave SecurityRequestContxt unset for http chunk request instead of using placeholder values
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
Labels: build, 6.6

#13870 [CDAP-18322] Leave SecurityRequestContxt unset for http chunk request instead of using placeholder values
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
Labels: build, 6.6

#13828 CDAP-17986 : Moving the existing retry code to accomodate the refreshAccessTokenLocally
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeEngineCredentials.java
Labels: build

#13864 [CDAP-18651] Disable access enforcement in preview runners
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
Labels: build, 6.6

#13876 [CDAP-18651] Disable access enforcement in preview runners
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
Labels: build, 6.6

#13875 Added stage name to SQL engine output
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngineOutput.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSinkWithWriteCapability.java
Labels: build

#13868 Fixes recursion to have a group per a unescaped block, not per each char
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/program/ManifestFields.java
Labels: build

#13816 support app spec regeneration in isolated
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ArtifactHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/AbstractConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultPluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemotePluginConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/customaction/DefaultCustomActionConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/mapreduce/DefaultMapReduceConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultHttpServiceHandlerConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/DefaultServiceConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/DefaultSparkConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultWorkerConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowConditionConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/DefaultWorkflowForkConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/WorkflowNodeCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/workflow/condition/DefaultConditionConfigurer.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/deploy/spark/AbstractExtendedSparkConfigurer.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/deploy/spark/DefaultExtendedSparkConfigurer.scala
Labels: build, 6.7

#13879 [cherry-pick] CDAP-18656-store Adding scanApplications in Store with NamespaceId f…
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
Labels: build, 6.6

#13877 [CDAP-18713] Read SA Email from Namespace Creation Request
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build

#13837 Add API for distribution/histogram/event metric
  cdap-common/src/main/java/io/cdap/cdap/common/metrics/NoOpMetricsCollectionService.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricType.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricValue.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsContext.java
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/NoopMetricsContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/pipeline/LogProcessorPipelineContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsCollectionService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/collect/AggregatedMetricsEmitter.java
Labels: build, 6.6

#13884 Cherry picking commit for CDAP-18672
  cdap-app-fabric/src/test/java/io/cdap/cdap/config/SqlUserConfigStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/SqlArtifactStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/store/SqlProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/SqlProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/reporting/SqlProgramHeartBeatTableTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/security/SqlDefaultSecretStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data/runtime/StorageModule.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableContext.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistry.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/SqlLineageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/metadata/lineage/field/SqlFieldLineageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/registry/SqlUsageTableTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/common/SqlCachedStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRegistryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/store/SqlOwnerStoreTest.java
Labels: build, 6.6

#13892 [cherryPick][CDAP-18603] Add basic support for Pagination for getAllApps
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/PaginatedApplicationRecords.java
Labels: build, 6.6

#13881 Fix preview runner breakage.
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13855 [CDAP-18603] Filtering & Pagination in the application metadata store
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ApplicationFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/SortOrder.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: build

#13852 [CDAP-18766] Add retention time to run record counter entries
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13888 [cherry-pick] [CDAP-18766] Add retention time to run record counter entries
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13883 Fix preview runner breakage.
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.6

#13871 [CDAP-18322] Refactoring: Move artifact sidecar cache prewarming from TaskWorkerService to ArtifactLocalizerService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
Labels: build, 6.6

#13766 [CDAP-18715] Add service that polls JMX server on localhost to collect and publish CPU load, thread count and heap used/max metrics.
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-master/src/main/java/io/cdap/cdap/api/metrics/MetricsPublisher.java
  cdap-master/src/main/java/io/cdap/cdap/metrics/jmx/JMXMetricsCollector.java
  cdap-master/src/main/java/io/cdap/cdap/metrics/publisher/AbstractMetricsPublisher.java
  cdap-master/src/main/java/io/cdap/cdap/metrics/publisher/MetricsWritersMetricsPublisher.java
  cdap-master/src/test/java/io/cdap/cdap/metrics/jmx/JMXMetricsCollectorTest.java
  cdap-master/src/test/java/io/cdap/cdap/metrics/publisher/MetricsWritersMetricsPublisherTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
Labels: cla: yes, build

#13890 [CDAP-18322] Refactoring: Move artifact sidecar cache prewarming from TaskWorkerService to ArtifactLocalizerService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
Labels: build, 6.6

#13889 [CDAP-18763] enforce system app entity permissions on connection
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ConnectionEntityId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/SystemAppEntityId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Authorizable.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/security/AuthorizableTest.java
Labels: build

#13829 CDAP-18559 : throwing RetryableProvisionException for read time out while fetching networks
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
Labels: build

#13898 [CDAP-18322] Fix missing internal auth binding in SystemAppTask.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: build, 6.6

#13899 [CDAP-18322] Fix missing internal auth binding in SystemAppTask.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
Labels: build, 6.6

#13894 Fixes recursion to have a group per a unescaped block, not per each c…
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/program/ManifestFields.java
Labels: build, 6.7

#13902 [6.6 Cherry-pick][CDAP-18603] Filtering & Pagination in the application metadata store
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ApplicationFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgresSqlStructuredTable.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/SortOrder.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: build

#13905 [CDAP-18322] Support executing connection requests remotely in worker pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionBrowseTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSampleTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSpecTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTaskBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTestTask.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/SystemAppTaskContext.java
Labels: build

#13909 [CDAP-18322] Support executing connection requests remotely in worker pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/DefaultSystemAppTaskContext.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionBrowseTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionRequest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSampleTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionSpecTask.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTaskBase.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/RemoteConnectionTestTask.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/SystemAppTaskContext.java
Labels: build

#13906 [CDAP-18713] Minor Change to Workload Identity SA Email Property
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#13901 [CDAP-18559][Cherrypick] : throwing RetryableProvisionException for read…
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
Labels: build

#13897 [CDAP-17986][ cherry pick ]Moving the existing retry code to accommodate the refreshAccessTokenLocally
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeEngineCredentials.java
Labels: build

#13896 [CDAP-18647] Set max limit on number of preview records.
  cdap-api/src/main/java/io/cdap/cdap/api/preview/DataTracer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/NoopDataTracer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/preview/SparkDataTracer.java
Labels: build, 6.6

#13885 [CDAP-18712] Limit lineage publishing to messages of a configurable maximum size
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageLimitingTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/MessagingLineageWriter.java
Labels: build

#13914 [Cherry-pick][CDAP-18712] Limit lineage publishing to messages of a configurable maximum size
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageLimitingTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/writer/MessagingLineageWriter.java
Labels: build

#13915 [CDAP-18647] Set max limit on number of preview records
  cdap-api/src/main/java/io/cdap/cdap/api/preview/DataTracer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultDataTracerFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/NoopDataTracer.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/preview/SparkDataTracer.java
Labels: build, 6.6

#13917 Use ConnectionBadRequestException for sample response.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
Labels: build

#13919 Use ConnectionBadRequestException for sample response.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
Labels: build

#13878 Fix TetheringProvisioner loading bug
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerExtensionLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
Labels: build, 6.7
