Repository cdapio/cdap, pull requests merged in 2022-10, with the labels that each got.

#14509 Capture error message in pipeline logs when getClusterStatus detects cluster creation failure
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Provisioner.java
Labels: build

#14579 [CDAP-18966] Use tasks list for MasterEnvironmentTask in KubeMasterEnvironment
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.8

#14540 CDAP-19465 Refactoring the Kill() method in RemoteExecutionTwillController.complete()
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobStatus.java
Labels: build, 6.8

#14581 [CDAP-19459] Remove ProgramRunnerClassLoaderFactory
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DefaultProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ProgramRunnerClassLoaderModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepository.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryWithLocalization.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/DummyProgramRunnerClassLoaderFactory.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/DefaultArtifactInspectorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
Labels: build, 6.8

#14583 [CDAP-19640] Read before setting custom time to avoid being throttled by GCS
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14578 Window aggregation Bigquery Pushdown CDAP
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/DeduplicateAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/WindowAggregationDefinition.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/InvalidRelation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/Relation.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/aggregation/WindowAggregationDefinitionTest.java
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build, bq-pushdown

#14473 [CDAP-19437] Exclude recent log folders during cleanup in LogCleaner service and fix flaky test
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/clean/LogCleaner.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/clean/LogCleanerTest.java
Labels: build

#14493 Deployment logic for edit flow
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/executor/AppCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/AppFabricTestHelper.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/ConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/AppRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/ChangeDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/ChangeSummary.java
Labels: build

#14576 Adjust tethering agent connection interval
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14593 changing creationTimeMillis datatype
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationDetail.java
Labels: build

#14596 [CDAP-19444] Enabling Artifact Localizer service in system pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.8

#14555 [CDAP-19567] Garbage Collection of Cached Program Artifacts
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/ArtifactCacheManager.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14571 [CDAP-19455] Classify dataproc cluster creation and job submission user errors, add links to dataproc troubleshooting docs
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeException.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
Labels: build

#14600 Added optional properties for Window aggregate definition
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/aggregation/WindowAggregationDefinition.java
Labels: build, bq-pushdown

#14604 CDAP-19468 configure Spark to return after submitting the job
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.8

#14598 Add program.jar to GCS caching
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
Labels: build, 6.8

#14606 [CDAP-19567] Reusing existing blob info while updating temporary hold on GCS object
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/ArtifactCacheManager.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14587 [CDAP-19659] Refactor SparkResourceFilter to be Non-Static Instance and Instantiate it using Spark classloader
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilters.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/NoSparkClassLoaderTestRunner.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilterTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/UnitTestManager.java
Labels: Bug, build, 6.8

#14520 [CDAP-19579] Fix Security Vulnerability in Logback
  cdap-common/src/test/java/io/cdap/cdap/common/service/RetryOnStartFailureServiceTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/LogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/framework/LogPipelineLoader.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/pipeline/LogPipelineConfigurator.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/plugins/LocationManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/plugins/RollingLocationLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/serialize/DelegatingLoggingEvent.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/plugins/RollingLocationLogAppenderTest.java
  pom.xml
Labels: build

#14609 CDAP-19579: upgrade cdap-twil to 1.2.0-SNAPSHOT
  pom.xml
Labels: build

#14551 Add Metadata consumer subscriber service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/DefaultMetadataConsumerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerExtensionLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/dummy/DummyMetadataConsumer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/dummy/DummyMetadataConsumerExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/metadata/MetadataConsumerExtensionProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
Labels: build, 6.8

#14612 [cherry-pick] Add Metadata consumer subscriber service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/DefaultMetadataConsumerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerExtensionLoader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/dummy/DummyMetadataConsumer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/dummy/DummyMetadataConsumerExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/metadata/MetadataConsumerExtensionProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/pom.xml
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/DatasetOpExecutorServerTwillRunnable.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
Labels: build, 6.8

#14613 Add latest field to ChangeDetail in the response
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/ChangeDetail.java
Labels: build

#14611 CDAP-19579: upgrade cdap-twil and slf4j
  pom.xml
Labels: build

#14614 Adding change-detail to GET /apps response
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ApplicationClientTestRun.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
Labels: build

#14617 [CDAP-19684] Remove using BooleanUtils
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
Labels: build, 6.8

#14618 [cherry-pick] [CDAP-19684] Fix BooleanUtils exception
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
Labels: build, 6.8

#14619 [Cherry-pick] CDAP-19676 Fix returning proper next token for NoSQL StructuredTablestore (e.g. Sandbox)
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
Labels: build

#14597 [CDAP-19668] add 'latestOnly' and 'nameFilterType' queryparams to GET apps
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ApplicationFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/NameFilterType.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableTest.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14592 CDAP-19543 make schedule versionless and schedules carryover
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ScheduleDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ScheduleId.java
Labels: build

#14469 [CDAP-19453] Save pipeline configs to preference table
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineArguments.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: build

#14591 feat(CDAP-19600): use latest version as default in programlifecyclehandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/PreferencesHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/WorkflowHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramLiveInfoCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramRunsCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramStatusCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/schedule/DeleteScheduleCommand.java
  cdap-common/src/main/java/io/cdap/cdap/common/id/Id.java
Labels: build

#14605 feat(CDAP-19664): relaxing range restriction on existing scan methods & update in logHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/table/field/FieldValidatorTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/AppMetadataStore.java
Labels: build

#14629 Cherrypick/CDAP-19543
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/ScheduleTaskRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDataset.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ScheduleDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ScheduleId.java
Labels: build

#14628 Cherrypick/CDAP-19600
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/PreferencesHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/WorkflowHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramLiveInfoCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramRunsCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/GetProgramStatusCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/schedule/DeleteScheduleCommand.java
  cdap-common/src/main/java/io/cdap/cdap/common/id/Id.java
Labels: build

#14636 cherry-pick(CDAP-19664): relaxing range restriction on existing scan methods & update in logHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/table/field/FieldValidatorTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/gateway/handlers/store/AppMetadataStore.java
Labels: build

#14560 [CDAP-19218] Distinguish between user and system programs in master environment extensions
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/MasterOptionConstants.java
Labels: build, 6.8

#14631 Add latest field to ChangeDetail in the response
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/artifact/ChangeDetail.java
Labels: build

#14630 Cherry pick lcm add change detail to application record
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ApplicationClientTestRun.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
Labels: build

#14574 CDAP-19463 make k8s client connect and read timeouts configurable
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/ApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultKubeMasterPathProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodKillerTask.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/PodKillerTaskTest.java
Labels: build, 6.7

#14632 [Cherry pick] CDAP-19668-6.8
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ApplicationFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/NameFilterType.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableTest.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14639 CDAP-19660 - Encode key for app state to avoid malforming the remote URL.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
Labels: build

#14642 [Cherry Pick] CDAP-19453-6.8
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineArguments.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: build

#14640 Encode key for app state to avoid malforming the remote URL.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
Labels: build

#14637 CDAP-19468 configure Spark to return after submitting the job
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.7

#14634 Add project ID to Asset
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/Asset.java
Labels: build, 6.8

#14635 [Cherry-pick] Add project to asset
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/Asset.java
Labels: build, 6.8

#14641 fix(CDAP-19688): fix the edge case in nosql table that longest prefix range should be default as INCLUSIVE if the range has omitted fields
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTableTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14552 [CDAP-19581] Cherry-pick 6.7
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeAPIException.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: Bug, build, 6.7, 6.8

#14538 [CDAP-19529] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramRuntimeProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentRunnableContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilters.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/NoSparkClassLoaderTestRunner.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilterTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/UnitTestManager.java
Labels: cherry-pick, build, 6.7

#14625 [cherry-pick][6.7]CDAP-19465 Refactoring the Kill() method in RemoteExecutionTwillController.complete()
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobStatus.java
Labels: build, 6.7

#14638 [CDAP-19687] Replaces ref-counting algorithm for cacheable artifacts with time-bucket hash
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcherTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14646 [cherry-pick] [CDAP-19687] Replaces ref-counting algorithm for cacheable artifacts with time-bucket hash
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcherTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.8

#14573 CDAP-19630: Inconsistency between bucket property keys used for overriding gcsBucket
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
Labels: build, 6.8

#14645 [CDAP-19218] Cherry-pick 6.8
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/MasterOptionConstants.java
Labels: build, 6.8

#14647 feat(CDAP-19781): Support scan on non-primary-key fields in StructuredTable
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/table/field/FieldValidatorTest.java
Labels: build

#14654 Cherrypick/CDAP-19781
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/table/field/FieldValidatorTest.java
Labels: build

#14656 Fix properties filtering for consumer extension
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14657 [cherry-pick] Fix properties filtering for consumer extension
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14650 [CDAP-19673] cache common artifacts per CDAP version in GCS
  cdap-common/src/main/java/io/cdap/cdap/common/utils/ProjectInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocImageVersion.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/VersionInfo.java
Labels: build, 6.8

#14661 [cherry-pick][CDAP-19673] cache common artifacts per CDAP version in GCS
  cdap-common/src/main/java/io/cdap/cdap/common/utils/ProjectInfo.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocImageVersion.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/VersionInfo.java
Labels: build

#14658 [CDAP-19683] Null check when decrementing cache usage counter for cached artifacts
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/ArtifactCacheManager.java
Labels: build

#14652 [CDAP-19790] Fix creation of Assets map in case of multiple fields in schema
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build

#14653 [Cherry pick] Fix creation of Assets map in case of multiple fields in schema
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build

#14663 (CDAP-19827) Fix a race condition in AbstractProgramController
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractProgramController.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/ProgramControllerTest.java
Labels: build

#14666 CDAP-19833: upgrade github actions due to node16 and set-output depre…
  .github/workflows/build-sonar.yml
  .github/workflows/build.yml
Labels: build

#14667 (CDAP-19827) Fix a race condition in AbstractProgramController
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractProgramController.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/ProgramControllerTest.java
Labels: build, 6.8

#14655 [CDAP-19791] Version history sort DESC on creationTime
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanApplicationsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
Labels: build

#14670 fix(CDAP-19802): form primary key by correct order
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdminTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableAdminTest.java
Labels: build

#14674 fix(CDAP-19802): form primary key by correct order
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdminTest.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableAdminTest.java
Labels: build

#14677 fix(CDAP-19954): return the correct runRecord of versionless programRunId
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: build

#14564 [CDAP-18623] 500 instead of 401 is returned as a result of malformed identifier
  cdap-common/src/main/java/io/cdap/cdap/common/http/AuthenticationChannelHandler.java
  cdap-common/src/test/java/io/cdap/cdap/common/http/AuthenticationChannelHandlerTest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/authentication/UnauthenticatedException.java
Labels: build

#14671 CDAP-19916: Batch retrieve latest programs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/element/EntityType.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ApplicationId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ApplicationReference.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramReference.java
Labels: build

#14678 Add feature flag for LCM deploy apis
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ScheduledRunTimeTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/store/ProgramScheduleStoreDatasetTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppScheduleUpdateTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ScheduleFetcherTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-program-report/src/test/java/io/cdap/cdap/report/ReportGenerationAppTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLIMainLinkTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ApplicationClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/LineageHttpHandlerTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/MetricsClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/PreferencesClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ProgramClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/QueryClientTest.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ScheduleClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ServiceClientTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/UsageHandlerTestRun.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/WorkflowClientTestRun.java
  cdap-integration-test/src/test/java/io/cdap/cdap/test/IntegrationTestBaseTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/job/SupportBundleJobTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/services/SupportBundleGeneratorTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/tasks/SupportBundleSystemLogTaskTest.java
  cdap-system-app-unit-test/src/test/java/io/cdap/cdap/test/SystemAppTestBaseTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/mapreduce/service/MapReduceServiceIntegrationTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/partitioned/PartitionConsumingTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/partitioned/PartitionCorrectorTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/partitioned/PartitionRollbackTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/service/FileUploadServiceTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkStreamingTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/service/SparkServiceIntegrationTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/DynamicPartitioningTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestAppWithCube.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/app/TestFrameworkTestRun.java
  cdap-unit-test/src/test/java/net/fake/test/app/TestBundleJarApp.java
Labels: build

#14681 [CDAP-19949] Add retries for sql tx connection failures
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionException.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRetryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableTest.java
Labels: build, 6.8
