Repository cdapio/cdap, pull requests merged in 2022-07, with the labels that each got.

#14389 CDAP-19347 - Enforce correct configurations for monitoring
  cdap-common/merge-config-transform.xsl
  cdap-common/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
Labels: build

#14391 [Cherry-Pick][6.7] Added logic to output and handle decimal values using delimited and json formats
  cdap-formats/src/main/java/io/cdap/cdap/common/io/Encoder.java
  cdap-formats/src/main/java/io/cdap/cdap/format/StructuredRecordStringConverter.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/JsonEncoder.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/JsonStructuredRecordDatumReader.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/JsonStructuredRecordDatumWriter.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/StructuredRecordDatumReader.java
  cdap-formats/src/main/java/io/cdap/cdap/format/io/StructuredRecordDatumWriter.java
  cdap-formats/src/main/java/io/cdap/cdap/format/utils/FormatUtils.java
  cdap-formats/src/test/java/io/cdap/cdap/format/StructuredRecordStringConverterTest.java
  cdap-formats/src/test/java/io/cdap/cdap/format/utils/FormatUtilsTest.java
Labels: build

#14382 [CDAP-19330] Add internal identity remote runtime token to tethered pipeline runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerResourceCopyTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
Labels: Bug, build, 6.7

#14388 [CDAP-19330] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerResourceCopyTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
Labels: cherry-pick, build, 6.7

#14395 (Cherry-pick) (CDAP-19355) (CDAP-19356) (CDAP-19361) Implements timeout based graceful stop
  cdap-api-spark-base/src/main/java/io/cdap/cdap/api/spark/JavaSparkExecutionContextBase.java
  cdap-api-spark-base/src/main/scala/io/cdap/cdap/api/spark/SparkExecutionContextBase.scala
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/DelayedProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/AbstractInMemoryProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/AbstractProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramControllerServiceAdapter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ServiceTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/WorkerTwillProgramController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams3_2.12/pom.xml
  cdap-common/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/ProgramRunInfo.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramController.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeUtils.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/classloader/SparkClassRewriter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkCommand.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkDriverService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkExecutionService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkJobFuture.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/LocalSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/SparkJobFuture.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/SparkSubmitter.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/AbstractSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/DefaultJavaSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SerializableSparkExecutionContext.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkMainWrapper.scala
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkRuntimeEnv.scala
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/SparkExecutionServiceTest.java
  pom.xml
Labels: build, 6.7

#14394 Enable adding to default configurations.
  cdap-common/merge-config-transform.xsl
  cdap-common/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorManagerServiceTest.java
Labels: build

#14208 [CDAP-19071] Fix Preview Runners when ArtifactLocalizer is Disabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryReaderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/PluginFinderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/PreferencesFetcherProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnableTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMainTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: Bug, build, 6.7

#14399 (CDAP-19361) Always check and log for unprocessed blocks
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
Labels: build, 6.8

#14404 (CDAP-19361) Always check and log for unprocessed blocks
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
Labels: build, 6.7

#14407 [CDAP-19397] Mount Secrets for Internal Identity in Spark Driver and Executors
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: Bug, build, 6.7

#14409 [CDAP-19397] Cherry-pick 6.7
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: Bug, build, 6.7

#14400 [CDAP-19071] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryReaderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/PluginFinderProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/PreferencesFetcherProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnableTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMainTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: cherry-pick, build, 6.7

#14397 [CDAP-19302] Fix Preview Running in Different Namespaces with k8s Namespace Creation Enabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/StorageProviderNamespaceAdminTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: Bug, build, 6.7

#14374 [CDAP-19031] Handle IOException as a retryable exception for idempotent operations.
  cdap-api/src/main/java/io/cdap/cdap/api/retry/Idempotency.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/DatasetServiceClient.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/datafabric/dataset/RemoteDatasetFrameworkRetryTest.java
Labels: build, 6.7

#14402 Add overrides for hashcode and equals in CacheKey
  cdap-common/src/main/java/io/cdap/cdap/common/io/DefaultCachingPathProvider.java
  cdap-common/src/test/java/io/cdap/cdap/common/io/CachingLocationTest.java
  pom.xml
Labels: Bug, build

#14414 [Cherrypick] [CDAP-19381] Prevent duplicate keys in cache map
  cdap-common/src/main/java/io/cdap/cdap/common/io/DefaultCachingPathProvider.java
  cdap-common/src/test/java/io/cdap/cdap/common/io/CachingLocationTest.java
  pom.xml
Labels: cherry-pick, build

#14408 (CDAP-19134) Tracks and emits all changes in k8s watcher
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/ResourceChangeListener.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/ResourceCleanupRule.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: build, 6.8

#14413 Shutdown the SparkExecutionService when the spark job completed
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkExecutionService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.8

#14417 Shutdown the SparkExecutionService when the spark job completed
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkExecutionService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.7

#14415 (Cherry-pick) (CDAP-19134) Tracks and emits all changes in k8s watcher
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/ResourceChangeListener.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/ResourceCleanupRule.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: build, 6.7

#14410 [CDAP-19302] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewConfigModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/AbstractStorageProviderNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/StorageProviderNamespaceAdminTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: cherry-pick, build, 6.7

#14390 CDAP-19366 : Wait approach : solving spark jar race condition
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkPackageUtils.java
Labels: build

#14412 [Cherrypick][CDAP-19366] : Wait approach : solving spark jar race condition
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkPackageUtils.java
Labels: build

#14422 Fix flaky AuthenticationServiceMainTest
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMainTest.java
Labels: build, 6.7

#14401 CDAP-19050 refactor dataproc client to remove unneeded calls
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DefaultDataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/GoogleComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/RuntimeMonitorDataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/SSHDataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScalingTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Node.java
Labels: build, 6.8

#14420 CDAP-19050 refactor dataproc client to remove unneeded calls
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DefaultDataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/GoogleComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/RuntimeMonitorDataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/SSHDataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScalingTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Node.java
Labels: build, 6.7

#14416 [CDAP-19376] Explicitly Check for Existing Service In KubeDiscoveryService
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
Labels: build, 6.7

#14393 [CDAP-19329] Allow system pods to launch pipelines when cluster mode is on_premise
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/RemoteTwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14421 [cherry-pick] [CDAP-19329] Allow system pods to launch pipelines when cluster mode is on_premise
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/RemoteTwillModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14424 [CDAP-19376] Explicitly Check for Existing Service In KubeDiscoveryService
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
Labels: build, 6.7

#14368 [CDAP-19337] Add tethering e2e tests
  cdap-e2e-tests/pom.xml
  cdap-e2e-tests/src/e2e-test/features/tethering/ManageRequestsServer.feature
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRegistration.feature
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/actions/TetheringActions.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/actions/TetheringRegistrationActions.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/actions/package-info.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/locators/TetheringLocators.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/locators/TetheringRegistrationLocators.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/locators/package-info.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/runners/TestRunner.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/runners/package-info.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringClient.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringRegistration.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringServer.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/package-info.java
  cdap-e2e-tests/src/e2e-test/resources/pluginParameters.properties
  pom.xml
Labels: build

#14405 [CDAP-19337] Add tethering compute profile e2e test
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRegistration.feature
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRuntime.feature
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/runners/TestRunner.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringClient.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringServer.java
Labels: build

#14425 (CDAP-19415) Fix the rewatch with observing all resource version
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: build, 6.8

#14427 (CDAP-19415) Fix the rewatch with observing all resource version
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: cherry-pick, build, 6.7

#14429 [CDAP-19211] Reduced verbosity of BigQuery Hadoop connector
  cdap-distributions/src/etc/cdap/conf.dist/logback-container.xml
  cdap-distributions/src/etc/cdap/conf.dist/logback.xml
  cdap-standalone/src/main/resources/logback-container.xml
  cdap-standalone/src/main/resources/logback.xml
Labels: build

#14437 [cherry-pick] [CDAP-19329] Recreate TwillController in AppFabric post program launch
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillApplication.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/ExtendedTwillApplication.java
Labels: build, 6.7

#14436 Fix a race condition in AbstractWatcherThread
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: build, 6.8

#14433 Combine log.buffer.service with log.saver server
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/LogsServiceMainTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/remote/RemoteLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/framework/distributed/DistributedLogFramework.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/guice/DistributedLogFrameworkModule.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/logbuffer/LogBufferService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/meta/CheckpointManagerFactory.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/read/DistributedLogReader.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogSaverStatusService.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/logbuffer/handler/LogBufferHandlerTest.java
Labels: build, 6.8

#14439 (cherry-pick) Fix a race condition in AbstractWatcherThread
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
Labels: cherry-pick, build, 6.7

#14440 (cherry-pick) Combine log.buffer.service with log.saver server
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/LogsServiceMainTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/remote/RemoteLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/framework/distributed/DistributedLogFramework.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/guice/DistributedLogFrameworkModule.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/logbuffer/LogBufferService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/meta/CheckpointManagerFactory.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/read/DistributedLogReader.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/service/LogSaverStatusService.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/logbuffer/handler/LogBufferHandlerTest.java
Labels: cherry-pick, build, 6.7

#14441 [CDAP-19311] Do not unpack artifacts beforehand when running in preview runners
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
Labels: Bug, build, 6.7

#14431 [CDAP-19409] Only initialize TokenManager when running on-premise to prevent Guice injection errors
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: Bug, build, 6.7

#14432 [CDAP-19409] Cherry-Pick 6.7
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
Labels: cherry-pick, build, 6.7

#14443 [CDAP-19311] 6.7 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
Labels: cherry-pick, build, 6.7

#14444 [CDAP-19438] Don't swallow uncaught exceptions
  cdap-common/src/main/java/io/cdap/cdap/common/logging/common/UncaughtExceptionHandler.java
Labels: Bug, build, 6.7

#14445 [CDAP-19408] Add job watchers in non-system k8s namespaces
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/namespace/NamespaceDetail.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/namespace/NamespaceListener.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/NamespaceInitializerService.java
Labels: build

#14403 [CDAP-19379] Log service leaves empty folders behind
  cdap-common/src/test/java/io/cdap/cdap/common/io/LocationsTest.java
  cdap-watchdog/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/LogFileManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/LogPathIdentifier.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/clean/LogCleaner.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/clean/LogCleanerTest.java
  pom.xml
Labels: build

#14447 [cherry-pick][CDAP-19379] Log service leaves empty folders behind
  cdap-common/src/test/java/io/cdap/cdap/common/io/LocationsTest.java
  cdap-watchdog/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/LogFileManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/LogPathIdentifier.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/clean/LogCleaner.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/clean/LogCleanerTest.java
  pom.xml
Labels: cherry-pick, build, 6.7

#14442 [CDAP-19340] Allow Running Pipelines In Namespaces Without Workload Identity
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/WorkloadIdentityUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: Bug, build, 6.7

#14448 [CDAP-19340] Cherry-Pick 6.7
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/WorkloadIdentityUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: cherry-pick, build, 6.7

#14451 CDAP-19451 update spark dockerfile to include licenses and source
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build, 6.8

#14452 CDAP-19451 update spark dockerfile to include licenses and source
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build, 6.7

#14450 changing default machine type to n2 while PROFILE CREATION
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build

#14453 [cherrypick][CDAP-18336]changing default machine type to n2 while PROFILE CREATION
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
Labels: build
