Repository cdapio/cdap, pull requests merged in 2022-05, with the labels that each got.

#14229 Added metrics support for the SQL Engine context.
  cdap-api/src/main/java/io/cdap/cdap/api/SQLEngineContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/BatchSQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/engine/SQLEngineJobTypeMetric.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineMetrics.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngine.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngineWithCapabilities.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngineWithStageSettings.java
Labels: build

#14246 feat-CDAP-18746: add icon for tethering provisioner
  cdap-app-fabric/src/main/resources/tethering.json
Labels: build

#14254 [CDAP-13926] ResourceCoordinator should not log resource requirements at INFO level
  cdap-common/src/main/java/io/cdap/cdap/common/zookeeper/coordination/ResourceCoordinator.java
Labels: build

#14258 feat-CDAP-18746: add icon for tethering provisioner
  cdap-app-fabric/src/main/resources/tethering.json
Labels: build

#14256 Add method for getting platform version
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsWriterContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
Labels: build

#14261 CDAP-19123 set batch interval for flaky test
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
Labels: build, 6.8

#14262 CDAP-19123 set batch interval for flaky test
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
Labels: build, 6.7

#14251 CDAP-19167 update spark build to include gcp auth extension
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build, 6.7

#14260 CDAP-19153 strip artifact scheme and host for tethering
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
Labels: build, 6.8

#14265 [CDAP-19142] Fix program status for non-default namespace runs
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#14248 [CDAP-19164] Check if program is authorized to run on the tethered namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisionerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
Labels: build, 6.7

#14259 [CDAP-19168] Set pipeline status to failed when k8s job fails to start
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#14250 CDAP-19167 update spark build to include gcp auth extension
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#14230 [CDAP-19141,CDAP-18721,CDAP-19144,CDAP-19151] Create roles for namespaced role bindings
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/KubeUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/util/KubeUtilTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: Bug, build, 6.7

#14264 [CDAP-19141,CDAP-18721,CDAP-19144,CDAP-19151] 6.7 Cherry-Pick
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/KubeUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/util/KubeUtilTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: cherry-pick, build, 6.7

#14268 Cherrypick tethering fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlDefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisionerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build, 6.7

#14266 [Cherrypick] [CDAP-19142] Fix program status for non-default namespace runs
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: cherry-pick, build, 6.7

#14263 CDAP-19153 strip artifact scheme and host for tethering
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactDescriptor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
Labels: build, 6.7

#14255 [6.7]Added metrics support for the SQL Engine context.
  cdap-api/src/main/java/io/cdap/cdap/api/SQLEngineContext.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/BatchSQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/SQLEngine.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/engine/SQLEngineJobTypeMetric.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineMetrics.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngine.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngineWithCapabilities.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSQLEngineWithStageSettings.java
Labels: build

#14232 CDAP-19133 fix spark launch namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/service/hive/BaseHiveExploreService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkSubmitContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.8

#14276 CDAP-19133 fix spark launch namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/scheduler/SchedulerQueueResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/PropertiesResolver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-explore/src/main/java/io/cdap/cdap/explore/service/hive/BaseHiveExploreService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodInfo.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkSubmitContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.7

#14235 Added small fix to prevent Spark caching for SQL engine collections
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: build

#14267 [CDAP-19171] Add http request config for system worker pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteProgramRunDispatcher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14200 Scheduled pipeline metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/DefaultSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/TimeScheduler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/ConstraintCheckerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/ScheduleNotificationSubscriberService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/query/MetricsQueryHelper.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build

#14285 CDAP-19133 fix namespaceId creation in tethering agent
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
Labels: build, 6.7

#14278 Remove guava dependency from event writer SPI
  cdap-event-writer-spi/pom.xml
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ExecutionMetrics.java
Labels: build

#14277 add try/catch if the event writer extension fails. add event publishe…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
Labels: build

#14219 CDAP-18616 : Enforcing successful start of provisioningService before…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#14288 add try/catch if the event writer extension fails.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
Labels: build

#14292 CDAP-18616 : adding a comment for count down latch
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#14287 [cherrypick][6.7]CDAP-18616 : handling initialization before provision/ deprovision
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#14294 CDAP-19207 do not expose macro impl detail
  cdap-api-common/src/main/java/io/cdap/cdap/api/macro/InvalidMacroException.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#14295 CDAP-19207 do not expose macro impl detail
  cdap-api-common/src/main/java/io/cdap/cdap/api/macro/InvalidMacroException.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build, 6.7

#14299 Added Feature Flags for Pushdown transformations
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/RelationalTranformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BasicRelationalTransformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14296 [CDAP-19215] Fix remote program run dispatcher breaking standalone
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
Labels: build, 6.7

#14297 [cherry-pick] [CDAP-19215] Fix remote program run dispatcher breaking standalone
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
Labels: build, 6.7

#14300 [6.7]Added Feature Flags for Pushdown transformations
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/RelationalTranformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BasicRelationalTransformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14279 [CDAP-19068] Add pod requests and limits while launching pipelines on…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkSubmitContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.7

#14281 [CDAP-19068] Add pod requests and limits while launching pipelines on…
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkSubmitContext.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.8

#14298 [CDAP-18325]: expose draft to all users withine the same namespace with RABC enabled
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
Labels: build

#14275 [CDAP-18846] Fix issue about wrong schema catching from stage
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
Labels: build

#14293 [CDAP-19184] Fix stuck program status for failed workflow pods
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
Labels: build, 6.7

#14303 [Cherrypick] [CDAP-19184] Fix stuck program status for failed workflow pods
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillController.java
Labels: cherry-pick, build, 6.7

#14306 [CDAP-18319] Cherry-Pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ConfigHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/ConfigHandlerAuthorizationTest.java
Labels: cherry-pick, build, 6.7

#14301 Use feature flag framework for event publish
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14307 Use feature flag framework for event publish
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventPublishManager.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14313 cherry-pick: CDAP-18325 expose draft to all admins within the same namespace
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/DraftHandler.java
Labels: build

#14311 [CDAP-19264] Start TokenManager for TetheringServiceMain on startup
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
Labels: Bug, build, 6.7

#14302 [6.7][CDAP-19063]Added checks to ensure dataproc cluster version is greater than 1.5 before running
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocImageVersion.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#14317 [CDAP-19268] Start TokenManager in SystemMetricsExporterServiceMain if internal auth is enabled
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMain.java
Labels: Bug, build, 6.7

#14318 [CDAP-19268] Cherry-Pick 6.7
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMain.java
Labels: cherry-pick, build, 6.7

#14310 added additional stage metrics
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/engine/SQLEngineJobTypeMetric.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
Labels: build

#14280 CDAP-19078 extend format interface for schema detection
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidatingInputFormat.java
Labels: build, 6.8

#14282 CDAP-19078 extend format interface for schema detection
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/validation/ValidatingInputFormat.java
Labels: build, 6.7

#14304 [CDAP-19165] Add ValidationException catch
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/AbstractDataPipelineHandler.java
Labels: build

#14319 [CDAP-19192] Enable write-ahead logs by default in spark config
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
Labels: build

#14316 [CDAP-18511] Watch for driver pod status
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkDriverWatcher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.7

#14322 [CDAP-19273] Cherry-Pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ConfigHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/ConfigHandlerAuthorizationTest.java
Labels: cherry-pick, build, 6.7

#14291 [CDAP-18511] Watch for driver pod status
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkDriverWatcher.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build, 6.8

#14324 [CDAP-19194] Regenerate appspec for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: build, 6.7

#14253 [Cherry-pick] [CDAP-18648] Emit metrics for force terminated programs runs and expected and actual stop times for a program
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14305 [CDAP-19192] Enable write-ahead logs by default in spark config
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/test/java/io/cdap/cdap/datastreams/DataStreamsTest.java
Labels: build

#14321 [CDAP-19273] Switch ConfigHandler authorization checks to use StandardPermission.GET
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ConfigHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/ConfigHandlerAuthorizationTest.java
Labels: Bug, build, 6.7

#14327 Add metrics for program status event publish
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisherMetricsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ProgramStatusEventDetails.java
Labels: build

#14328 [CDAP-19194] Regenerate appspec for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
Labels: build

#14326 Add metrics for program status event publish
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisherMetricsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ProgramStatusEventDetails.java
Labels: build

#14332 CDAP-19290 updated pushdown feature flags to enable in 6.7.0
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14331 CDAP-19290 updated pushdown feature flags to enable in 6.7.0
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14334 CDAP-19291: Allow to set default reuse threshold from system context
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build

#14335 [Cherry-pick into 6.7] CDAP-19291: Allow to set default reuse threshold from system context
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build

#14337 [CDAP-18926]: Add log entries for all pipeline events
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
Labels: build

#14330 [CDAP-19286] 6.7 Cherry-Pick
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: cherry-pick, build, 6.7

#14329 [CDAP-19286] Fail master environment initialization if cluster role does not exist
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: Bug, build, 6.7

#14341 Revert "[CDAP-19286] 6.7 Cherry-Pick"
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build

#14314 CDAP-19050 remove GCE calls when they are not needed
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocTool.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DefaultDataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/GoogleComputeFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/RuntimeMonitorDataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/SSHDataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/PredefinedAutoScalingTest.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/provisioner/Node.java
Labels: build, 6.8

#14346 (6.7. Cherry-pick) Always stores timestamp in seconds in RunRecord
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
Labels: cherry-pick, build, 6.7

#14345 Always stores timestamp in seconds in RunRecord
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeProgramStatusSubscriberService.java
Labels: build, 6.8

#14323 [CDAP-18013] Deploy error message for pipeline with conditional in preview mode
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineDriver.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/batch/mapreduce/MapReduceBatchContext.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/PhaseSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/PipelineSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSourceContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DefaultStreamingSourceContext.java
Labels: build

#14348 [CDAP-19316] Fix security vulnerability in commons-fileupload dependency
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
Labels: build
