Repository cdapio/cdap, pull requests merged in 2022-04, with the labels that each got.

#14136 [CDAP-18996] Fix Guice bindings for ArtifactLocalizerTwillRunnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnableTest.java
Labels: build, 6.7

#14134 Temporary files cleanup fix for Program Run operation
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
Labels: build

#14133 [CDAP-18985] Remove artifact localizer sidecar container from system worker
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillApplication.java
Labels: build, 6.7

#14130 Add a log statement to let the user know the timeout value for the program stop request
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
Labels: build

#14137 [cherry-pick] [CDAP-18985] Remove artifact localizer sidecar container from system worker
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillApplication.java
Labels: build, 6.7

#14135 [cherry-pick] Make terminate time grace period configurable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14074 [CDAP-18900] Fix Case Insensitivity for FileSecureStoreService and Switch to using PKCS12 for Key Storage
  cdap-api/src/test/java/io/cdap/cdap/api/common/BytesTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/SecureStoreServerModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/FileSecureStoreImporter.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/FileSecureStoreService.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/FileSecureStoreCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/KeyInfo.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/SecureStoreDataCodecV1.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/SecureStoreDataCodecV2.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/FileSecureStoreImporterTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/FileSecureStoreServiceTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/client/RemoteSecureStoreTest.java
  cdap-security/src/test/resources/file-secure-store-65.jks
Labels: build, 6.7

#14138 [CDAP-18996] Fix Guice bindings for ArtifactLocalizerTwillRunnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnableTest.java
Labels: build, 6.7

#14139 [cherry-pick] [CDAP-18986] Temporary files cleanup fix for Program Run operation
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
Labels: build, 6.7

#14142 (CDAP-18927) Write program states to local TMS in tethered mode
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnableModuleTest.java
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeatTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
Labels: build, 6.7

#14140 [cherry pick] Add a log statement to let the user know the timeout value for the pipeline stop request
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
Labels: build, 6.7

#14143 Use HDFS when storing resources for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: build, 6.7

#14145 [CDAP-19016] Optimize deserialization
  cdap-common/src/main/java/io/cdap/cdap/common/lang/FieldCollector.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/InstantiatorFactory.java
  cdap-common/src/main/java/io/cdap/cdap/internal/io/ReflectionDatumReader.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/FieldCollectorTest.java
Labels: build

#14149 [Cherry-pick][CDAP-19016] Optimize deserialization
  cdap-common/src/main/java/io/cdap/cdap/common/lang/FieldCollector.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/InstantiatorFactory.java
  cdap-common/src/main/java/io/cdap/cdap/internal/io/ReflectionDatumReader.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/FieldCollectorTest.java
Labels: build

#14152 Cp tethering
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnableModuleTest.java
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillRunnableModuleTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/ArtifactCacheHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/NoOpDiscoveryServiceClient.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeatTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/URIScheme.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
Labels: build

#14147 [CDAP-19011] Cleanup fix for remote dispatcher
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build

#14151 [cherry-pick] [CDAP-19011] Cleanup fix for remote dispatcher
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.7

#14150 [Cherry pick] Support using tethered peer namespace and Use HDFS when storing resources
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedMapReduceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedServiceProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkerProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedWorkflowProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
Labels: build, 6.7

#14153 [CDAP-19001] Add unit test for guice bindings in system worker twill runnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnableTest.java
Labels: build, 6.7

#14155 [Cherry-pick][CDAP-19016] Parallel computation / writes to metric tables
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build

#14157 [Cherry-pick] [CDAP-19001] Add unit test for guice bindings in system worker twill runnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnableTest.java
Labels: build, 6.7

#14148 [CDAP-19016] Parallel computation / writes to metric tables
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MessagingMetricsProcessorService.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build

#14154 [CDAP-19001] Fix guice modules for system worker twill runnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.7

#14158 [cherry-pick] [CDAP-19001] Fix guice modules for system worker twill runnable
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.7

#14161 [CDAP-19021] Fix guice bindings for SparkContainerDriverLauncher
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncherTest.java
Labels: build, 6.7

#14162 [CDAP-19021] Fix guice bindings for SparkContainerDriverLauncher
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncherTest.java
Labels: cherry-pick, build, 6.7

#14164 CDAP-12977 fix app deletion when trigger not found
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/AbstractTimeSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/TimeScheduler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/TimeSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/TimeSchedulerTest.java
Labels: build, 6.7

#14146 Include event writer extension in CDAP packaging
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/EventWriterExtensionProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-master/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoader.java
Labels: build

#14163 Tethering fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
Labels: build

#14166 Include event writer extension in CDAP packaging
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/EventWriterExtensionProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/EventWriterExtensionProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-master/pom.xml
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/loader/MetricsWriterExtensionLoader.java
Labels: build

#14167 CDAP-12977 fix app deletion when trigger not found
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/AbstractTimeSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/TimeScheduler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/TimeSchedulerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/scheduler/CoreSchedulerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/TimeSchedulerTest.java
Labels: build, 6.7

#14169 CDAP-18994 avro schema compatibility fixes
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/io/cdap/cdap/internal/io/SchemaTypeAdapter.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: build

#14168 CDAP-19019 parallelize program force killing
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14156 [CDAP-19016] Disable emitting spark metrics by default
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestConfiguration.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/metrics/SparkMetricsIntegrationTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/base/TestFrameworkExploreTestSuite.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/base/TestFrameworkTestSuite.java
Labels: build

#14173 [Cherry-pick][CDAP-19016] Disable emitting spark metrics by default
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestConfiguration.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/metrics/SparkMetricsIntegrationTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/base/TestFrameworkExploreTestSuite.java
  cdap-unit-test/src/test/java/io/cdap/cdap/test/base/TestFrameworkTestSuite.java
Labels: build

#14172 [CDAP-18962] Add support for read program types that can be launched in system pods from config
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14174 [cherry-pick] [CDAP-18962] Add support for read program types that can be launched in system pods from config
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/ProgramRunDispatcherFactory.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14175 Tethering agent: fix bug in sending peer notifications
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
Labels: build, 6.8

#14171 CDAP-18994 avro schema compatibility fixes
  cdap-api-common/src/main/java/io/cdap/cdap/api/data/schema/Schema.java
  cdap-api-common/src/main/java/io/cdap/cdap/internal/io/SchemaTypeAdapter.java
  cdap-common/src/test/java/io/cdap/cdap/io/SchemaTest.java
Labels: build, 6.7

#14181 [Cherry-pick][CDAP-19016] Add coarse metrics fact processing
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDataset.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDatasetDefinition.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodec.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/AbstractCubeTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDatasetTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCubeTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodecTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTableTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/MetricsTestBase.java
Labels: build

#14177 [CDAP-19016] Add coarse metrics fact processing
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDataset.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDatasetDefinition.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodec.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/AbstractCubeTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/CubeDatasetTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCubeTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodecTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTableTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricDatasetFactory.java
  cdap-watchdog/src/test/java/io/cdap/cdap/metrics/MetricsTestBase.java
Labels: build

#14178 Added BigQuery capability for SQL Expressions
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/StandardSQLCapabilities.java
Labels: build

#14183 CDAP-19042 fix flaky program kill test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
Labels: build

#14185 CDAP-19042 fix flaky program kill test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
Labels: build, 6.7

#14179 [CDAP-19032] Refactor PreviewRunnerTwillRunnable and DefaultPreviewRunnerManager to remove unused Guice modules
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnableTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: build, 6.7

#14189 [CDAP-19032] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/DefaultPreviewRunnerManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewRunnerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnableTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/preview/PreviewDataPipelineTest.java
Labels: cherry-pick, build, 6.7

#14184 [6.7]Added BigQuery capability for SQL Expressions
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/StandardSQLCapabilities.java
Labels: build

#14180 Fixes for stopping tethered program runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ClusterMode.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramStopSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
Labels: build

#14190 [CDAP-19016] Allow configuring LevelDB max open files to prevent OOMs.
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
Labels: build

#14141 [CDAP-18900] Cherry-pick 6.7
  cdap-api/src/test/java/io/cdap/cdap/api/common/BytesTest.java
  cdap-security/src/main/java/io/cdap/cdap/security/guice/SecureStoreServerModule.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/FileSecureStoreImporter.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/FileSecureStoreService.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/FileSecureStoreCodec.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/KeyInfo.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/SecureStoreDataCodecV1.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/file/SecureStoreDataCodecV2.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/FileSecureStoreImporterTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/FileSecureStoreServiceTest.java
  cdap-security/src/test/java/io/cdap/cdap/security/store/client/RemoteSecureStoreTest.java
  cdap-security/src/test/resources/file-secure-store-65.jks
Labels: cherry-pick, build, 6.7

#14192 Use RemoteLogAppender for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
Labels: build, 6.8

#14193 [Chery-pick][CDAP-19016] Allow configuring LevelDB max open files to prevent OOMs.
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/table/leveldb/LevelDBTableService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/store/leveldb/LevelDBTableFactory.java
Labels: build

#14191 [CDAP-19016] Optimize metrics aggregation
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/EntityTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodec.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
Labels: build

#14194 Cherrypick Tethering fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ClusterMode.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramStopSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringControlMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
Labels: build

#14195 [Cherry-pick][CDAP-19016] Optimize metrics aggregation
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/cube/DefaultCube.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/EntityTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactCodec.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/dataset2/lib/timeseries/FactTable.java
Labels: build

#14165 CDAP-18984 ensure app class is in manifest for integration tests
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
  pom.xml
Labels: build

#14196 CDAP-18984 ensure app class is in manifest for integration tests
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
  pom.xml
Labels: build, 6.7

#14198 Fix error logging when dispatching fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
Labels: build, 6.7

#14199 [cherry-pick] Fix error logging when dispatching fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
Labels: build, 6.7

#14197 [CDAP-19048] Add new twill runner service for launching programs inside system pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/FireAndForgetTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.7

#14205 [cherry-pick] [CDAP-19048] Add new twill runner service for launching programs inside system pods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/FireAndForgetTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
Labels: build, 6.7

#14204 [CDAP-19022] Don't show tethering provisioner in provisioner list if …
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build, 6.8

#14100 [CDAP-18648] Emit metrics for force terminated programs runs and expected and actual stop times for a program
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14201 [CDAP-19058] Do not inherit Java Opts from Parent Launching Pod
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/LauncherUtils.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/LauncherUtilsTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
Labels: build, 6.7

#14209 [CDAP-19058] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/LauncherUtils.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/LauncherUtilsTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
Labels: cherry-pick, build, 6.7

#14176 CDAP-19023: add support for configuring composite trigger
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/PipelineTriggers.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/service/PipelineTriggersTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ArgumentMapping.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/PluginPropertyMapping.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/TriggeringPipelineId.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#14212 [CDAP-19129] 6.7 Cherry-Pick
  cdap-authenticator-ext-gcp/src/main/resources/resources/META-INF/services/io.cdap.cdap.security.spi.authenticator.RemoteAuthenticator
Labels: cherry-pick, build, 6.7

#14211 [CDAP-19129] Add ServiceLoader configuration for GCPRemoteAuthenticator
  cdap-authenticator-ext-gcp/src/main/resources/resources/META-INF/services/io.cdap.cdap.security.spi.authenticator.RemoteAuthenticator
Labels: build, 6.7

#14215 [CDAP-19058] Add default JVM opts for system workers 6.7 Cherry-Pick
  cdap-common/src/main/resources/cdap-default.xml
Labels: cherry-pick, build, 6.7

#14214 [CDAP-19058] Add default JVM opts for system workers
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.7

#14217 [CDAP-19129] Move service loader config to correct directory
  cdap-authenticator-ext-gcp/src/main/resources/META-INF/services/io.cdap.cdap.security.spi.authenticator.RemoteAuthenticator
Labels: Bug, build, 6.7

#14218 [CDAP-19129] Move service loader config to correct directory Cherry-Pick 6.7
  cdap-authenticator-ext-gcp/src/main/resources/META-INF/services/io.cdap.cdap.security.spi.authenticator.RemoteAuthenticator
Labels: cherry-pick, build, 6.7

#14203 [CDAP-19064] Add validation on Kubernetes namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build, 6.7

#14223 [Cherrypick] [CDAP-19064] Add validation on Kubernetes namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build, 6.7

#14213 [CDAP-19065] Revert namespace if kube creation fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
Labels: build, 6.7

#14227 [Cherrypick] [CDAP-19065] Revert namespace if kube creation fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
Labels: build, 6.7

#14207 [CDAP-18741] Check if there are profiles using tethered connection be…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/profile/ProfileStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
Labels: build

#14222 CDAP-18567 fix s3 on k8s
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#14225 Tethering fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringConf.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: build, 6.7

#14228 CDAP-18567 fix s3 on k8s
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build, 6.7

#14231 Tethering cherrypicks
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/profile/ProfileStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/profile/ProfileService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringConf.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: build

#14233 Fix macro fields when there is secure macro when regenerate app spec
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
Labels: build

#14216 [CDAP-18607] added ifGenerationMatch idempotency and default retry strategy for al…
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.7

#14226 [CDAP-19135] Copy spark service account to new Kube namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14182 Fix/events spark metrics provider
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/MetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/http/SparkApplicationsStagesResponse.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-app-fabric/src/test/resources/mocked_spark_stages_response_several_stages.json
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ExecutionMetrics.java
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ProgramStatusEventDetails.java
Labels: build

#14234 Fix macro fields when there is secure macro when regenerate app spec
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactRepositoryTest.java
Labels: build, 6.7

#14236 [CDAP-18607] added ifGenerationMatch idempotency and default retry strategy for al…
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: cherry-pick, build, 6.7

#14237 [Cherrypick] [CDAP-19135] Copy spark service account to new Kube namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14220 [CDAP-19062] Changes to run tethered programs on different namespaces
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.7

#14239 [Cherrypick] [CDAP-19062] Changes to run tethered programs on different namespaces
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramOptionConstants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/proto/v1/TetheringLaunchMessage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: cherry-pick, build, 6.7

#14238 Add method for getting platform version in MetricsWriterContext
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsWriterContext.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/DefaultMetricsWriterContext.java
Labels: build

#14240 [CDAP-19129] Add guava dependency for GCPRemoteAuthenticator
  cdap-authenticator-ext-gcp/pom.xml
Labels: Bug, build, 6.7

#14241 [CDAP-19129] Cherry-Pick 6.7
  cdap-authenticator-ext-gcp/pom.xml
Labels: cherry-pick, build, 6.7

#14243 Add back the constant temporarily for not breaking dependent repos
  cdap-watchdog-api/src/main/java/io/cdap/cdap/api/metrics/MetricsWriterContext.java
Labels: build

#14245 CDAP-18319 - Add authorization check in ConfigHandler to only allow the users with…
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ConfigHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/ConfigHandlerAuthorizationTest.java
Labels: build, 6.7

#14244 [CDAP-19148] Change logging level from debug to trace in caching location code
  cdap-common/src/main/java/io/cdap/cdap/common/io/CachingLocation.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/DefaultCachingPathProvider.java
Labels: build, 6.7

#14247 [CDAP-19148] Change logging level from debug to trace in caching location code
  cdap-common/src/main/java/io/cdap/cdap/common/io/CachingLocation.java
  cdap-common/src/main/java/io/cdap/cdap/common/io/DefaultCachingPathProvider.java
Labels: build

#14249 Remove guava dependency from event writer SPI
  cdap-event-writer-spi/pom.xml
  cdap-event-writer-spi/src/main/java/io/cdap/cdap/spi/events/ExecutionMetrics.java
Labels: build
