Repository cdapio/cdap, pull requests merged in 2022-08, with the labels that each got.

#14455 handling error during lock file creation
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkPackageUtils.java
Labels: build

#14459 [cherrypick][CDAP-19366]handling error during lock file creation
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkPackageUtils.java
Labels: build

#14460 [CDAP-19456] Set namespaces.creation.hook.enabled to false by default
  cdap-common/src/main/resources/cdap-default.xml
Labels: Bug, build, 6.7

#14462 Revert graceful parameter from stop APIs
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
Labels: build, 6.7

#14456 [CDAP-19448] Fix ScalaSparkCompute Errors in TaskWorkers
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/MockMasterEnvironment.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncherTest.java
Labels: Bug, build, 6.7

#14463 [CDAP-19448] Cherry-pick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/MockMasterEnvironment.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncherTest.java
Labels: cherry-pick, build, 6.7

#14461 [CDAP-19456] Set namespaces.creation.hook.enabled to false by default
  cdap-common/src/main/resources/cdap-default.xml
Labels: cherry-pick, build, 6.7

#14464 [CDAP-19448] Switch SystemAppTaskModule to use DISTRIBUTED ProgramRuntimeProvider.Mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
Labels: Bug, build, 6.7

#14465 [CDAP-19448] 6.7 Cherry-pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
Labels: cherry-pick, build, 6.7

#14458 [CDAP-19448] Don't unpack artifacts in task workers due to spark compilation failure
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RemoteWorkerPluginFinder.java
Labels: Bug, build, 6.7

#14467 [CDAP-19448] Cherrypick 6.7
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RemoteWorkerPluginFinder.java
Labels: cherry-pick, build, 6.7

#14449 [CDAP-19446] Start ArtifactLocalizerService in CDAP Standalone
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: Bug, build, 6.7

#14457 [CDAP-19446] Cherry-pick 6.7
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: cherry-pick, build, 6.7

#14398 [CDAP-19396] Fix security vulnerability - remove unused hive-jdbc dependency
  cdap-explore/pom.xml
  pom.xml
Labels: build

#14468 replace installation of curl | bash by chef debian
  cdap-distributions/src/Dockerfile
Labels: build

#14470 [CDAP-19328] Implement prepareRun, onRunFinish in WrappedSplitterTransform
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/plugin/WrappedSplitterTransform.java
Labels: build

#14479 try to fetch gpg key from multiple servers
  cdap-distributions/src/Dockerfile
Labels: build

#14480 [CDAP-19283] Throw exception from SparkProgramStatusMetricsProvider when metrics cannot be retrieved successfully
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/MetricsProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/ProgramStatusEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/MetricRetrievalException.java
Labels: build

#14475 Enhance EndPoint class to also include location value
  cdap-api/src/main/java/io/cdap/cdap/api/lineage/field/EndPoint.java
Labels: build, 6.8

#14476 Ensure cleanup is executed for ProgramRunDispatcher and also code cleanup
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/deploy/ProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/deploy/ProgramRunDispatcherContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/InMemoryProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ProgramRunDispatcherTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/app/runtime/AbstractProgramRuntimeServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/RunRecordCorrectorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/RunnableTaskLauncherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerMetricsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RunnableTaskContext.java
Labels: build, 6.8

#14488 [CDAP-19316] Fix security vulnerabilities in commons-collections
  pom.xml
Labels: build

#14491 [CDAP-19512] Fix security vulnerability in log4j
  cdap-data-fabric-tests/pom.xml
  cdap-security/pom.xml
  pom.xml
Labels: build

#14490 [CDAP-19271] Add spark metrics retry policy and host check
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProvider.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/SparkProgramStatusMetricsProviderTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14487 Add SPI definition for consuming metadata
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/Asset.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/LineageInfo.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MetadataConsumer.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/ProgramRun.java
  cdap-metadata-spi/src/test/java/io/cdap/cdap/spi/metadata/ProgramRunTest.java
Labels: build, 6.8

#14499 [CDAP-19512] Fix security vulnerability in log4j
  cdap-common/pom.xml
  cdap-data-fabric/pom.xml
  cdap-watchdog/pom.xml
  pom.xml
Labels: build

#14477 chore(CDAP-19493): turn on the feature flag for Composite Trigger
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14497 Make OAuth API more generic.
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/OAuthServiceTest.java
Labels: build

#14495 Add Sampling Options for Wrangler
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ConnectionUtils.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/ConnectorSpec.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/SampleRequest.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/connector/SampleType.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/test/java/io/cdap/cdap/etl/api/connector/SampleRequestTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/connection/ConnectorDetail.java
Labels: build
