Repository cdapio/cdap, pull requests merged in 2023-05, with the labels that each got.

#15114 [CDAP-18394] 6.9 Cherry-Pick
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: cherry-pick, build, 6.9.1

#15130 [CDAP-20608] Set program version in stop message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringAgentServiceTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramRunId.java
Labels: build

#15133 [CDAP-20608] Set program version in stop message
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringAgentServiceTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramRunId.java
Labels: build

#15131 Update cdap-e2e-framework snapshot.
  cdap-e2e-tests/pom.xml
  cdap-kubernetes/pom.xml
Labels: build

#15129 [CDAP-20604] Java11 fix for stream pipelines
  cdap-common/src/main/java/io/cdap/cdap/common/lang/ClassLoaders.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
Labels: build

#15137 [CP][CDAP-20604] Java11 fix for stream pipelines #15129
  cdap-common/src/main/java/io/cdap/cdap/common/lang/ClassLoaders.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
Labels: build

#15138 [CDAP-20622]: Apply software updates to cdap-spark-core docker image
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#15135 Set the context class loader for all calls to RuntimeJobManager
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build, 6.10

#15140 [cherry-pick][CDAP-20622]: Apply software updates to cdap-spark-core docker image
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build, 6.9.1

#15142 CDAP-20623: Add 3 seconds of retries to the reuse
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15147 CDAP-20624 make entity id hash code deterministic
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
Labels: build, 6.9.1, 6.10

#15148 CDAP-20624 make entity id hash code deterministic
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/EntityId.java
Labels: build, 6.9.1

#15145 Cherrypick 6.8.3 fixes
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/AbstractRuntimeTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramStopSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringConf.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringAgentServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/util/WorkloadIdentityUtil.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ProgramRunId.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
Labels: build

#15132 [CDAP-20611] Bump twill version to 1.3.1
  pom.xml
Labels: build, 6.9.1

#15149 [Cherry-pick] [CDAP-20506] Fix unexpected transition of program run from state COMPLETED to FAILED
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
Labels: build, 6.8.3

#15150 [CDAP-20628] Auto install: fix pipeline JSON parsing
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/autoinstall/Spec.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-app-fabric/src/test/resources/spec2.json
Labels: build

#15153 CDAP-20623: Update reuse logic
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DefaultDataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/SshDataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15156 CDAP-20638: Log plan from writeCombinedRDD
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkFactory.java
Labels: build

#15157 [Cherry-pick] CDAP-20638: Log plan from writeCombinedRDD
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkBatchSinkFactory.java
Labels: build

#15154 Fix permission error for spark dockerfile
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#15143 [Cherry-pick] CDAP-20623: Add 3 seconds of retries to the reuse
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocConf.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DefaultDataprocClientFactory.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/SshDataprocClient.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClientTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15159 Fix spark build 683
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#15155 [CDAP-20597] skip normal macro evaluation during app spec regeneration
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: build

#15160 [cherry-pick][CDAP-20597]: skip normal macro evaluation during app spec regeneration
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: build, 6.9.1

#15158 CDAP-20631 fix logback localization in client mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramRunners.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/ProgramRunnersTest.java
Labels: build, 6.10

#15162 [cherry-pick] CDAP-20597: unit test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
Labels: build, 6.9.1

#15163 [cherry-pick] [CDAP-20597] skip normal macro evaluation during app spec regeneration
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
Labels: build, 6.8.3

#15164 CDAP-20631 fix logback localization in client mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramRunners.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/ProgramRunnersTest.java
Labels: build, 6.9.1

#15167 [CDAP-20640] Fixed incorrect merge conflict resolution
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
Labels: build

#15165 Make dataproc 2.0 image version to be default
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15169 Cherry picking for b/280664429
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#15168 fix(CDAP-20642): fix the export/apps API and apply latestOnly filter on ScanApplicationsRequest#builder() usages
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
Labels: build, 6.9.1

#15173 Cherrypick/cdap-20642
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/ApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/MetadataSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/profile/ProfileMetadataMessageProcessor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-operational-stats-core/src/main/java/io/cdap/cdap/operations/cdap/CDAPEntities.java
Labels: build, 6.9.1

#15171 [CDAP-20632] Add new aggregation for app entities
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build, 6.9.1

#15176 fix(CDAP-20646): convert UncheckedIOException back to IOException in SCM metrics calc
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9.1

#15177 cherrypick(CDAP-20646): convert UncheckedIOException back to IOException in scm metrics calc
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9.1

#15175 [CDAP-20632] Cherrypick
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/store/DefaultMetricStore.java
Labels: build, 6.9.1

#15179 PLUGIN-1613 : adding ignoreEmptySplits = false as spark 3.2 onwards t…
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: build

#15180 [Cherry-pick] Update spark version and fix pyspark
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/SparkRuntimeEnv.scala
  cdap-spark-core3_2.12/src/main/resources/pyspark/pyspark33.zip
  cdap-unit-test/pom.xml
  pom.xml
Labels: build

#15181 [cherrypick][CDAP-20651]Cherry fix emptysplits
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: build, 6.9.1

#15184 [CDAP-20654] Add watcher on correct namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build

#15187 [CDAP-20661] Reverting default version of dataproc to 2.0
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15185 [CDAP-20654] Add watcher on correct namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build

#15186 [CDAP-20654] Add watcher on correct namespace
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
Labels: build

#15189 CDAP-20649 fix dynamic plugin registration with client launch mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramRunners.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: build, 6.10

#15190 CDAP-20649 fix dynamic plugin registration with client launch mode
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/ProgramRunners.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
Labels: build, 6.9.1

#15191 [CDAP-20663] Fix spark-version access during program start
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
Labels: build

#15192 [Cherry-pick][CDAP-20663] Fix spark-version access during program start
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
Labels: build, 6.9.1

#15178 CDAP-20657: Make Dataset / Dataframe first class citizens and reduce conversions to RDD
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/SparkStreamingPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/DelegatingSparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkPipelineRunner.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BaseRDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/OpaqueDatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLBackedCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/WrappedSQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/CountingFunction.java
Labels: build

#15195 CDAP-20667 Deprecate table based datasets and custom datasets
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/DatasetDefinition.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/CounterTimeseriesTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/IndexedObjectStore.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/IndexedTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/KeyValueTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/ObjectMappedTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/ObjectStore.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/PartitionedFileSet.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/TimePartitionedFileSet.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/TimeseriesTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/cube/Cube.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/table/Table.java
Labels: build, 6.10

#15196 CDAP-20667 Deprecate table based datasets and custom datasets
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/DatasetDefinition.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/CounterTimeseriesTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/IndexedObjectStore.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/IndexedTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/KeyValueTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/ObjectMappedTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/ObjectStore.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/PartitionedFileSet.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/TimePartitionedFileSet.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/TimeseriesTable.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/lib/cube/Cube.java
  cdap-api/src/main/java/io/cdap/cdap/api/dataset/table/Table.java
Labels: build, 6.9

#15197 Fix merge merge conflict resolution issue
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
Labels: build
