Repository cdapio/cdap, pull requests merged in 2023-11, with the labels that each got.

#15394 [Cherry-pick] [CDAP-20869] Fix closing message tables
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
Labels: build, 6.10

#15399 CDAP-20867 switch to cheaper secure store call in oauth handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStore.java
Labels: build, 6.10

#15398 cdap e2e framework snapshot version fix
  cdap-e2e-tests/pom.xml
Labels: build

#15401 CDAP-20867 switch to cheaper secure store call in oauth handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStore.java
Labels: build, 6.10

#15400 CDAP-20858 add tag for launch mode in Dataproc job submission metric
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocMetric.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.10

#15403 [CDAP-20795] remove identity from namespace wi request body
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandlerInternal.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceWorkloadIdentity.java
Labels: build, namespaced_service_accounts

#15402 Cdap 20858 add launch mode metric 6 10
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocMetric.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.10

#15404 [🍒][CDAP-20795] remove identity from namespace wi request body
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandlerInternal.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceWorkloadIdentity.java
Labels: build, 6.10

#15405 [CDAP-20657] fixes & additional support
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/DelegatingSparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
Labels: build

#15406 [🍒 6.10] [CDAP-20657] fixes & additional support for Datasets
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/DelegatingSparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/streaming/DStreamCollection.java
Labels: build

#15391 [CDAP-20868] Allow task workers to run concurrent requests when configured
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15407 [Cherrypick][CDAP-20868] Allow task workers to run concurrent requests when configured
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15409 [CDAP-20879] Use default k8s namespace in hybrid mode for workload identity token exchanges
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
Labels: build, 6.10, namespaced_service_accounts

#15413 [CDAP-20785] do not set WI env vars when NSA is enabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecureTwillPreparer.java
Labels: build, namespaced_service_accounts

#15414 [CDAP-20879] Cherry-pick 6.10
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
Labels: cherry-pick, build, 6.10, namespaced_service_accounts

#15319 CDAP-20809: Operation Runner
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/AbstractOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/LongRunningOperationContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/MessagingOperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationDriver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, 6.10

#15385 Multi push operation
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationException.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationTest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/MultiPushAppOperationRequest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
Labels: build, 6.10

#15415 [CDAP-20785] Use GCP remote authenticator to fetch token
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternalTest.java
  cdap-authenticator-ext-gcp/src/main/java/io/cdap/cdap/authenticator/gcp/GCPRemoteAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Credential.java
Labels: build, namespaced_service_accounts

#15416 [🍒][CDAP-20785] Do not set WI env and use client library to fetch auth token.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternalTest.java
  cdap-authenticator-ext-gcp/src/main/java/io/cdap/cdap/authenticator/gcp/GCPRemoteAuthenticator.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/SecureTwillPreparer.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/Credential.java
Labels: build, 6.10

#15411 Operation state publisher
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/MessagingOperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotification.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationStatePublisher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/Notification.java
Labels: build, 6.10

#15410 Fix the null pointer exception caused by unsafe unboxing of Boolean
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
Labels: build, 6.10

#15418 🍒 CDAP 20862 application manager (from #15379)
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/RemoteApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/AppVersion.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ApplicationId.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/ApplicationManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlException.java
Labels: build, 6.10

#15419 [🍒][CDAP-20877] Fix the null pointer exception (from #15410)
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/gateway/handlers/OperationsDashboardHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlAppMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/ProfileServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
Labels: build, 6.10

#15417 🍒 CDAP 20884 multi push operation (#15385)
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationException.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationTest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/MultiPushAppOperationRequest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
Labels: build, 6.10

#15420 Fix the operation runner test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
Labels: build, 6.10

#15424 Add scan operation runs by status method
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRunStatus.java
Labels: build, 6.10

#15421 Add Operation notification consumer
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRuntime.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/MessagingOperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotification.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRuntime.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/ScanOperationRunsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/SqlOperationRunsStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/OperationRunId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRunStatus.java
Labels: build, 6.10

#15427 [CDAP-20874] Added API handler functions (scan and get) for LRO
  cdap-app-fabric/.gitignore
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build, 6.10

#15426 [CDAP-20897] Properly throw error with response content upon error HTTP response in GcpWorkloadIdentityCredentialProvider
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
Labels: Bug, build, 6.10, credential_provider, namespaced_service_accounts

#15430 [CDAP-20897] Cherry-pick 6.10
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
Labels: cherry-pick, build, 6.10

#15431 [CDAP-20860] cache provisioned credential in memory in appfabric
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/ProvisionedCredentialCacheKey.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
Labels: build, namespaced_service_accounts

#15432 [🍒] [CDAP-20860] cache provisioned credential in memory in appfabric
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/ProvisionedCredentialCacheKey.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
Labels: build, 6.10

#15434 [CDAP-20900] Handle URL encoded data in Internal Router Service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/AbstractServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/MockServiceHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/URIScheme.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/AbstractMasterServiceManager.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/log/LogHttpHandlerTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/LogsServiceMainTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/SupportBundleTestBase.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/handlers/SupportBundleHttpHandlerTest.java
Labels: build, 6.10

#15438 [🍒] [CDAP-20809] Operation runner implementation from #15319
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/AbstractOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/LongRunningOperationContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/MessagingOperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationDriver.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
Labels: build, 6.10

#15444 [🍒 ] Add pending run scan method from #15424
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRunStatus.java
Labels: build, 6.10

#15437 [Cherrypick][CDAP-20900] Handle url encoded params in Internal router
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/WorkflowHttpHandlerTest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/TransactionServiceManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/AbstractServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/MockServiceHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/PreferencesHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProfileHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/profile/ProfileMetadataTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ApplicationDetailFetcherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/LineageLimitingTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/MetadataSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/PreferencesFetcherInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ScheduleFetcherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/discovery/URIScheme.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/AbstractMasterServiceManager.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/DatasetExecutorServiceManager.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/datafabric/dataset/MetadataServiceManager.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/log/LogHttpHandlerTest.java
  cdap-gateway/src/test/java/io/cdap/cdap/gateway/handlers/metrics/MetricsSuiteTestBase.java
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/LogsServiceMainTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/SupportBundleTestBase.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/handlers/SupportBundleHttpHandlerTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/job/SupportBundleJobTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/services/SupportBundleGeneratorTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/tasks/SupportBundlePipelineInfoTaskTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/tasks/SupportBundleSystemLogTaskTest.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/distributed/MessagingServiceManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/run/LogSaverServiceManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/runtime/MetricsProcessorStatusServiceManager.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/runtime/MetricsServiceManager.java
Labels: build, 6.10

#15423 [CDAP-20815] Fix pipeline description on pipeline upgrade
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: build

#15446 [🍒 ] Operation notification consumer from # 15421
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRuntime.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/MessagingOperationStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotification.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRuntime.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/ScanOperationRunsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/InMemoryOperationRunnerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/SqlOperationRunsStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/OperationRunId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRunStatus.java
Labels: build, 6.10

#15448 [Cherrypick][CDAP-20815] Fix pipeline description on pipeline upgrade
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLBatchConfig.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/ETLConfig.java
Labels: build

#15443 Add small fixes for operation launch
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/AbstractOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-master/src/main/java/io/cdap/cdap/master/startup/ConfigurationCheck.java
Labels: build, 6.10

#15442 CDAP-20841: Add stop operation api
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberServiceTest.java
Labels: build, 6.10

#15396 Multiple applications push and pull API
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PullMultipleAppsRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PushMultipleAppsRequest.java
Labels: build, 6.10

#15454 [🍒 ] [CDAP-20874] Added API handler functions (scan and get) for LRO from #15427
  cdap-app-fabric/.gitignore
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build, 6.10

#15451 [🍒 ] Add small fixes for operation launch from 15443
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/AbstractOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/InMemoryOperationRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/guice/OperationModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-master/src/main/java/io/cdap/cdap/master/startup/ConfigurationCheck.java
Labels: build, 6.10

#15450 Skip pulling a pipeline if the current hash is same
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
Labels: build, 6.10

#15452 [🍒 ] CDAP-20841: Add stop operation api from #15442
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberServiceTest.java
Labels: build, 6.10

#15455 [🍒] Add APIs to do multi pull/push from #15396
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationLifecycleManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationTestBase.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PullMultipleAppsRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PushMultipleAppsRequest.java
Labels: build, 6.10

#15457 [🍒 ] Skip pulling if current hash is the same from #15450
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
Labels: build, 6.10

#15462 [CDAP-20781] fix issue where service ip is cached forever
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
Labels: build, 6.8

#15463 [CDAP-20781] fix issue where service ip is cached forever
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/AbstractProgramTwillRunnable.java
Labels: build, 6.9

#15453 [CDAP-20893] Move created workload identities to system namespace
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/RemoteCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/handler/CredentialProviderHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/handler/CredentialProviderHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/DefaultNamespaceCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/GcpWorkloadIdentityUtil.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/RemoteNamespaceCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderServiceTest.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/ProvisionedCredentialCacheKey.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/CredentialProvider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/CredentialProvisionContext.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/IdentityValidationException.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceCredentialProvider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/ValidateIdentityRequest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/credential/CredentialProvider.java
Labels: build, 6.10, credential_provider, namespaced_service_accounts

#15465 [CDAP-20893] Cherry-pick 6.10
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/RemoteCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/handler/CredentialProviderHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/handler/CredentialProviderHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/DefaultNamespaceCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/GcpWorkloadIdentityUtil.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/RemoteNamespaceCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderServiceTest.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/ProvisionedCredentialCacheKey.java
  cdap-credential-ext-gcp-wi/src/test/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProviderTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/CredentialProvider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/CredentialProvisionContext.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/IdentityValidationException.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceCredentialProvider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/ValidateIdentityRequest.java
  cdap-security-spi/src/main/java/io/cdap/cdap/security/spi/credential/CredentialProvider.java
Labels: cherry-pick, build, 6.10, namespaced_service_accounts

#15461 CDAP-20906 Add end time for all terminal states in operation
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationNotificationSingleTopicSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
Labels: build, 6.10

#15449 [CDAP-20893] Add metrics for credential provider resource and namespaced workload identity counts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialIdentityManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialIdentityStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialProfileManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialProfileStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/GcpWorkloadIdentityUtil.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/credential/CredentialProviderTestBase.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.10, credential_provider, namespaced_service_accounts

#15466 [CDAP-20893] Cherry-pick 6.10
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialIdentityManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialIdentityStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialProfileManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/CredentialProfileStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/GcpWorkloadIdentityUtil.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/credential/CredentialProviderTestBase.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: cherry-pick, build, 6.10, namespaced_service_accounts

#15467 [CDAP-20909] Cherry-pick 6.10
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  cdap-hbase-compat-base/pom.xml
Labels: cherry-pick, build, 6.10, credential_provider, namespaced_service_accounts

#15468 [CDAP-20909] Move protobuf to cdap-hbase-compat child modules instead of cdap-hbase-compat-base
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  cdap-hbase-compat-1.2-cdh5.7.0/pom.xml
  cdap-hbase-compat-base/pom.xml
Labels: Bug, build, 6.10, credential_provider, namespaced_service_accounts

#15469 [CDAP-20872] Remove validation check for default project in GcpEnvelopeTinkCipherCryptor since CloudKmsClient is capable of detecting the local project automatically
  cdap-encryption-ext-tink/src/main/java/io/cdap/cdap/encryption/tink/GcpEnvelopeTinkCipherCryptor.java
Labels: Bug, build, 6.10, credential_provider

#15470 [CDAP-20872] Cherry-pick 6.10
  cdap-encryption-ext-tink/src/main/java/io/cdap/cdap/encryption/tink/GcpEnvelopeTinkCipherCryptor.java
Labels: cherry-pick, build, 6.10, credential_provider

#15478 [CDAP-20911] Fix ClassCastException by adding a workaround for SPARK-46176
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DatasetDataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/OpaqueDatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/TransformFunction.java
Labels: build
