Repository cdapio/cdap, pull requests merged in 2023-03, with the labels that each got.

#14956 Adding cdap lcm backend metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/preview/PreviewApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#14959 feat(CDAP-20248): Handler and service code for pulling and deploying application
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/executor/AppCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/NoChangesToPullException.java
Labels: build, 6.9

#14964 Add checkstyle report plugin to the workflow
  .github/workflows/build.yml
Labels: build

#14967 fix(CDAP-20412): get the fileHash after commit but before push, avoid empty filHash in db
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppResponse.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
Labels: build, 6.9

#14969 fix(CDAP-20417): enforce commit message in push flow
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PushAppRequest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9

#14962 feature/CDAP-20322: implement push app task and RemoteSourceControlOperationRunner
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-source-control/pom.xml
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationConfigException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/NoChangesToPushException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/guice/SourceControlModule.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/guice/SourceControlOperationRunnerProvider.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppContext.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushFailureException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PushAppTask.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/SourceControlTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/LocalGitServer.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.9

#14970 fix(CDAP-20418): fix the issue that the cause of RemoteTaskException is not the actual cause exception
  cdap-system-app-api/src/main/java/io/cdap/cdap/api/service/worker/RemoteExecutionException.java
Labels: build

#14946 CDAP-20326 Add SCM list apps handler and implementation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RepositoryApp.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RepositoryAppsResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PushAppTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.9

#14957 [CDAP-19611] Kill tethered pipeline runs stuck in STOPPING state
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramStopSubscriberService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramRunStatusMonitorServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14974 CDAP-20357: Add base test class for source control tests
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/SourceControlTestBase.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.9

#14975 delete app with deleteAll
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLIMainTest.java
Labels: build

#14948 [CDAP-20387] Separate subscriber transaction size from subscriber fetch size
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AbstractNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/TimeBoundIterator.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingPollingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberServiceTest.java
Labels: build, 6.9

#14971 [CDAP-20381] Add ability to configure java options for program run
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/SystemArguments.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/AbstractRuntimeTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocRuntimeJobManagerTest.java
Labels: build

#14978 Add method to compile an expression taking a Relation into account
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/ExpressionFactory.java
Labels: build, bq-pushdown

#14981 Enhance GitHub Actions reporting
  .github/workflows/build.yml
  cdap-hbase-compat-1.0-cdh/pom.xml
  cdap-hbase-compat-1.0-cdh5.5.0/pom.xml
  cdap-hbase-compat-1.0/pom.xml
  cdap-hbase-compat-1.1/pom.xml
  pom.xml
Labels: build

#14982 Fix build yaml (missing name tag)
  .github/workflows/build.yml
Labels: build

#14966 CDAP-20357: Add remote task worker for listing applications from SCM
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/NamespaceRepository.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteExceptionProvider.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/ListAppsTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/LocalGitServer.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/SourceControlTestBase.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.9

#14980 CDAP-20430 return unevaluated properties in validation call
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/ValidationUtils.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/service/ValidationUtilsTest.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/spec/StageSpec.java
Labels: build

#14985 Add default language capability to relational transform context
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/engine/sql/StandardSQLCapabilities.java
  cdap-app-templates/cdap-etl/cdap-etl-api/src/main/java/io/cdap/cdap/etl/api/relational/RelationalTranformContext.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BasicRelationalTransformContext.java
Labels: build, bq-pushdown

#14989 Fixing log statements for delete app
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: build

#14947 [CDAP-20386] Reset to remote branch on repeated git clone
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/SourceControlTestBase.java
Labels: build, 6.9

#14991 Apply checkstyle to cdap-default.xml
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#14992 [CDAP-20273] Mark idempotency for remote secure store
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-security/src/main/java/io/cdap/cdap/security/store/client/RemoteSecureStore.java
Labels: build

#14977 Fix field-level lineage for multi-plugins
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/lineage/LineageOperationsProcessor.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/lineage/Origin.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/test/java/io/cdap/cdap/etl/lineage/LineageOperationProcessorTest.java
Labels: build

#14995 [CDAP-20457] KubeTwillPreparer: dont' overwrite global JVM opts
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
Labels: build

#14998 [cherry-pick][CDAP-20431]Cache application_jar in GCS using hash appended name
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/AbstractRuntimeTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobTwillPreparer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJobInfo.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/HashUtils.java
  cdap-common/src/test/java/io/cdap/cdap/common/utils/HashUtilsTest.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobInfo.java
Labels: build, 6.8.2

#14940 Turning LCM flag on
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/DeletedProgramHandlerStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-app-templates/cdap-etl/cdap-etl-tools/src/main/java/io/cdap/cdap/etl/tool/UpgradeTool.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLIMainTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/app/DeleteAppCommand.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/app/ListAppsCommand.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ApplicationClientTestRun.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14987 Emit metrics in metadata consumer subscriber service
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/DefaultMetadataConsumerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/DefaultMetadataConsumerMetrics.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MetadataConsumerContext.java
  cdap-metadata-spi/src/main/java/io/cdap/cdap/spi/metadata/MetadataConsumerMetrics.java
Labels: build

#15002 Deprecating APIs
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
Labels: build

#15003 CDAP-20114 avoid setting owner refs for user jobs
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
Labels: build

#15000 [CDAP-20458] Improve run record monitor
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#15001 CDAP-20375: Start event publish manager after task worker.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-standalone/src/main/java/io/cdap/cdap/StandaloneMain.java
Labels: build, 6.9

#14990 [CDAP-20428] Set program.status.event.topic.num.partitions to 10 by default
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramRunLimitTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#14979 CDAP-20342 : Spark SQL engine implementation as a fallback engine
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/sql/engine/relation/SparkSQLExpression.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/SparkCollectionRelationalEngine.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineRelationalEngine.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkSQLEngine.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLDataset.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLExpressionFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLPullProducer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLPushConsumer.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLRelation.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/batch/SparkSQLEngineTest.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/test/java/io/cdap/cdap/etl/spark/batch/relation/SparkSQLRelationTest.java
Labels: build

#14994 CDAP-20216: Stop DefaultRuntimeJob in case of failure in any core services + Don't retry in case of 400/404 error during RuntimeClientService shutdown
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
Labels: build

#15009 Runtime fix sonar test
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
Labels: build

#14867 CDAP Observability scripts basic draft
  cdap-support-bundle/bin/collect_support_bundle.py
Labels: build

#15005 [CDAP-20482] Disable hooks in RepositoryManager
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SecureSystemReader.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/ListAppsTask.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PullAppTask.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PushAppTask.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/SourceControlTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.9

#15011 Fix build failure due to missing license
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/src/main/java/io/cdap/cdap/etl/api/sql/engine/relation/SparkSQLExpression.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#15006 fixing metrics bug
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build

#15010 Revert "CDAP-20216: Stop DefaultRuntimeJob in case of failure in any core services + Don't retry in case of 400/404 error during RuntimeClientService shutdown "
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
Labels: build

#15015 fix(CDAP-20491): Add necessary access enforcement deploy permission checks in SCM pull
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
Labels: build, 6.9

#15016 CDAP-20493 remove avro usage in data-pipeline app
  cdap-app-templates/cdap-etl/cdap-data-pipeline3_2.12/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SparkSQLEngine.java
Labels: build, 6.9

#15019 [CDAP-20501] Separate netty configs for task worker and system worker
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#15018 Enforcing access permissions on listAppVersions
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
Labels: build

#15007 Add new RunRecordTimeToLiveService
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordTimeToLiveService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15024 [CDAP-20461] GCS read, connection and total timeout increased and making them configurable
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build, 6.9

#15025 fix(CDAP-20515): throw SourceControlException if the repository exists but is not initialized
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9

#15027 Cherrypick/CDAP-20515
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9
