Repository cdapio/cdap, pull requests merged in 2023-01, with the labels that each got.

#14828 [CDAP-20220] re-initialise job controller client in case of app-fabric restarts
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14831 [cherry-pick] [CDAP-20220] initialise job controller client in case of app-fabric restart
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14832 Fix merge function while creating asset map
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build, 6.8

#14837 [Cherry-pick] Fix merge function while creating asset map
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build, 6.8

#14840 [6.8 Cherry-pick] [CDAP-20275] Do more rare reloads
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.8

#14839 [CDAP-20275] Do more rare reloads
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14825 Cdap 20041 spark k8s extra jvm opts 6 8
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeService.java
  cdap-spark-core3_2.12/src/k8s/entrypoint.sh
Labels: build, 6.8

#14836 [CDAP-20268] ArtifactCache: ignore temporary files
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/AbstractArtifactLocalizer.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheTest.java
Labels: build

#14842 CDAP-20271 fix secure macro json
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
Labels: build

#14843 [CDAP-20201] Set Spark k8s connect/read timeouts based on the CDAP k8…
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/stepsdesign/KubernetesNamespaceCreation.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build

#14844 [CDAP-20281] Fix copy directory failures in Intellij
  cdap-unit-test-base/src/main/.gitignore
Labels: Bug, build

#14851 CDAP-20271 fix secure macro json
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
Labels: build, 6.8

#14850 CDAP-20271 fix secure macro json
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineConnectionTest.java
  cdap-app-templates/cdap-etl/hydrator-test/src/main/java/io/cdap/cdap/etl/mock/batch/MockSource.java
Labels: build, 6.7

#14846 CDAP-19622 : adding app spec info to Application Configurator
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/RuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppRuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
Labels: build

#14849 [CDAP-20283] upgrade dataproc client to v1
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14797 [CDAP-20238] Remove Spark2 dependencies
  cdap-api-spark2_2.11/pom.xml
  cdap-api-spark3_2.12/pom.xml
  cdap-app-fabric-tests/pom.xml
  cdap-app-fabric-tests/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRunnerTxTimeoutTest.java
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/spark/SparkCompatReader.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/CapabilityManagementServiceTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-pipeline3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams2_2.11/pom.xml
  cdap-app-templates/cdap-etl/cdap-data-streams3_2.12/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-api-spark/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-archetypes/cdap-data-pipeline-plugins-archetype/src/main/resources/archetype-resources/pom.xml
  cdap-app-templates/cdap-etl/cdap-etl-batch/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/pom.xml
  cdap-app-templates/cdap-etl/hydrator-spark-core2_2.11/src/main/java/io/cdap/cdap/etl/spark/Compat.java
  cdap-app-templates/cdap-etl/hydrator-test/pom.xml
  cdap-app-templates/cdap-etl/pom.xml
  cdap-app-templates/cdap-program-report/pom.xml
  cdap-app-templates/cdap-program-report/src/main/scala/io/cdap/cdap/report/ReportGenerationHelper.scala
  cdap-app-templates/cdap-program-report/src/main/scala/io/cdap/cdap/report/SparkCompat.scala
  cdap-app-templates/cdap-program-report/src/test/java/io/cdap/cdap/report/ReportGenerationAppTest.java
  cdap-cli-tests/pom.xml
  cdap-client-tests/pom.xml
  cdap-common/pom.xml
  cdap-coverage/pom.xml
  cdap-data-fabric/pom.xml
  cdap-data-fabric/src/test/java/io/cdap/cdap/kafka/KafkaTester.java
  cdap-docs/user-guide/source/pipelines/plugins/pom.xml
  cdap-integration-test/pom.xml
  cdap-kafka/pom.xml
  cdap-master/pom.xml
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
  cdap-spark-core2_2.11/pom.xml
  cdap-spark-core2_2.11/src/main/java/io/cdap/cdap/app/runtime/spark/Spark2ProgramRuntimeProvider.java
  cdap-spark-core2_2.11/src/main/resources/META-INF/services/io.cdap.cdap.app.runtime.ProgramRuntimeProvider
  cdap-spark-core2_2.11/src/main/resources/pyspark/py4j-src.zip
  cdap-spark-core2_2.11/src/main/resources/pyspark/pyspark.zip
  cdap-spark-core2_2.11/src/test/scala/io/cdap/cdap/app/runtime/spark/dynamic/SparkCompilerTest.scala
  cdap-standalone/pom.xml
  cdap-standalone/src/main/resources/cdap-site.xml
  cdap-unit-test-spark2_2.11/pom.xml
  cdap-unit-test-spark3_2.12/pom.xml
  cdap-unit-test/pom.xml
  cdap-unit-test/src/main/java/io/cdap/cdap/test/TestBase.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkStreamingTestRun.java
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkTest.java
  cdap-unit-test/src/test/scala/io/cdap/cdap/spark/app/KafkaSparkStreaming.scala
  cdap-watchdog/pom.xml
  pom.xml
Labels: build

#14852 rate limit warning log for StructuredTable
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
Labels: build, 6.9

#14853 [CDAP-20110] Spark program types should be run as k8s job
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
Labels: build

#14830 [CDAP-20202] Add retries in FileLocalizer
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/FileLocalizer.java
Labels: build

#14826 [CDAP-20211] Fix remote client retry behavior
  cdap-api-common/src/main/java/io/cdap/cdap/api/common/Constants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/HttpCodes.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/HttpCodes.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: build

#14859 cherrypick(CDAP-20031): use scan run in WorkflowHttpHandler and ProgramLifecycleHttpHandler where version is not available
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/ProgramLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/WorkflowHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
Labels: build

#14854 [CDAP-20285] Filter out $repl_$init.class from compiled JARs
  cdap-common/src/main/java/io/cdap/cdap/common/lang/jar/BundleJarUtil.java
  cdap-common/src/test/java/io/cdap/cdap/common/lang/jar/BundleJarUtilTest.java
  cdap-spark-core-base/src/main/scala/io/cdap/cdap/app/runtime/spark/dynamic/AbstractSparkCompiler.scala
  cdap-unit-test/src/test/java/io/cdap/cdap/spark/SparkTest.java
Labels: Bug, build

#14860 [CDAP-20206] Fix flaky CDAPLogAppenderTest
  cdap-watchdog/src/main/java/io/cdap/cdap/logging/appender/system/CDAPLogAppender.java
  cdap-watchdog/src/test/java/io/cdap/cdap/logging/appender/system/CDAPLogAppenderTest.java
Labels: cherry-pick, build, 6.8

#14857 Cherrypick fixes to release/6.8
  cdap-api-common/src/main/java/io/cdap/cdap/api/common/Constants.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/AbstractArtifactLocalizer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringProvisioner.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/HttpCodes.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/http/HttpCodes.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-e2e-tests/pom.xml
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRegistration.feature
  cdap-e2e-tests/src/e2e-test/features/tethering/TetheringRuntime.feature
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/tethering/stepsdesign/TetheringServer.java
  cdap-kubernetes/src/e2e-test/java/io/cdap/cdap/master/environment/k8s/stepsdesign/KubernetesNamespaceCreation.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/FileLocalizer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/SparkTwillRunnable.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/server/MessagingHttpServiceTest.java
Labels: build

#14861 [CDAP-20290] Remove remaining hive dependencies and fix unit tests to depend only on Gson
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/SystemApplication.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ProgramLifecycleHttpHandlerTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline3_2.12/pom.xml
  cdap-app-templates/cdap-program-report/pom.xml
  cdap-support-bundle/src/test/java/io/cdap/cdap/SupportBundleTestBase.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/job/SupportBundleJobTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/services/SupportBundleGeneratorTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/tasks/SupportBundlePipelineInfoTaskTest.java
  cdap-support-bundle/src/test/java/io/cdap/cdap/support/tasks/SupportBundleSystemLogTaskTest.java
  cdap-system-app-unit-test/pom.xml
  cdap-unit-test/pom.xml
  pom.xml
Labels: Bug, build

#14864 CDAP-20294 fix temp directory used in artifact cache test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheTest.java
Labels: build

#14865 CDAP-20294 fix temp directory used in artifact cache test
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/ArtifactCacheTest.java
Labels: build, 6.8

#14835 CDAP-20179 Appfabric and Preview pods to watch only the resources they create
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
Labels: build, 6.9

#14847 [Cherry pick] CDAP-19622 : adding app spec info to Application Configurator
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/RuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppRuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
Labels: build

#14848 [Cherry-pick] [CDAP-19622] : adding app spec info to Application Configurator
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationConfigurer.java
  cdap-api/src/main/java/io/cdap/cdap/api/app/RuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/DefaultAppRuntimeConfigurer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentRuntimeInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
Labels: build

#14819 [CDAP-20277] Allow processing program status events in parallel for different run by sharding into N partitions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ProgramRunnerRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerNotifier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/MessagingProgramStatePublisherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMainTest.java
Labels: build

#14856 [CDAP-20288] Add support for dataproc driver pools
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14820 [Cherry-pick][CDAP-20277] Allow processing program status events in parallel for different runs by sharding into N partitions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/ProgramRunnerRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStatePublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/MessagingProgramStateWriter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/program/ProgramStateWriterWithHeartBeat.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisionerNotifier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/program/MessagingProgramStatePublisherTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/scheduler/CoreSchedulerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/test/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMainTest.java
Labels: build

#14869 [CDAP-20265] Add polling strategy for existing dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
Labels: build, 6.8

#14870 [Cherry-Pick] [CDAP-20265] Add polling strategy for existing dataproc provisioner
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/ExistingDataprocProvisioner.java
Labels: build, 6.8

#14874 Revert "CDAP-20179 Appfabric and Preview pods to watch only the resources they create"
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
Labels: build

#14878 [CDAP-20303] Fix missing messages due to transaction retry
  cdap-tms/pom.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingPollingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberServiceTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsAdminSubscriberService.java
Labels: build

#14879 [Cherry-pick][CDAP-20303] Fix missing messages due to transaction retry
  cdap-tms/pom.xml
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingPollingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberService.java
  cdap-tms/src/test/java/io/cdap/cdap/messaging/subscriber/AbstractMessagingSubscriberServiceTest.java
  cdap-watchdog/src/main/java/io/cdap/cdap/metrics/process/MetricsAdminSubscriberService.java
Labels: build, 6.8

#14876 Guard against any exceptions so that metadata service does not terminate
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build

#14875 [Cherry-pick] Guard against any exceptions so that metadata service does not terminate
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
Labels: build, 6.8

#14880 [CDAP-20298] Ensure proper topic order is retained in the runtime client and even if a message is sent into a completed run it does not get into 1h retry loop
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/GoneException.java
Labels: build

#14882 [CDAP-19500] add retries for macro evaluation and correctly close the client
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14883 [CDAP-19500][cherry-pick] add retries for macro evaluation
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#14872 [Cherry-pick][CDAP-20298] Sometimes runtime client don't shutdown nicely because it tries to publish messages after run is completed
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeMonitors.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeRequestValidator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/DirectRuntimeRequestValidatorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/GoneException.java
Labels: build

#14884 [CDAP-20316] Remove broker.id properties when creating Kafka servers to allow auto-generation of broker IDs
  cdap-common/src/test/java/io/cdap/cdap/common/guice/KafkaClientModuleTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/kafka/KafkaTester.java
  cdap-kafka/src/main/java/io/cdap/cdap/kafka/run/KafkaServerMain.java
Labels: Bug, build
