Repository cdapio/cdap, pull requests merged in 2023-02, with the labels that each got.

#14885 fix(CDAP-20318): return in the catch block of setRepository, otherwise it still sets the repo wrongly
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/AuthConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfigRequest.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfigTest.java
Labels: build

#14890 [CDAP-20288][cherry-pick] Add driver pools support in CDAP
  cdap-runtime-ext-dataproc/pom.xml
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
Labels: build

#14894 Fix EndPointFieldDeserializer in the case where a field is dropped in a pipeline
  cdap-api/src/main/java/io/cdap/cdap/api/lineage/field/EndPoint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndpointFieldDeserializer.java
Labels: build

#14896 [Cherry pick] Fix EndPointFieldDeserializer in the case where a field is dropped in a pipeline
  cdap-api/src/main/java/io/cdap/cdap/api/lineage/field/EndPoint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/metadata/MetadataConsumerSubscriberService.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndPointField.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/data2/metadata/lineage/field/EndpointFieldDeserializer.java
Labels: build, 6.8

#14893 Adding updateAll method to SPI
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/field/FieldValidator.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14891 chore(CDAP-20329): Add SCM feature flag check in handler
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-proto/src/test/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfigTest.java
Labels: build

#14895 [CDAP-20000] Logging ProgramRunId in case of ProgramDispatch failure
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ProgramRunDispatcherTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
Labels: build

#14902 [CDAP-20000] Logging ProgramRunId in case of ProgramDispatch failure
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ProgramRunDispatcherTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
Labels: build, 6.8

#14898 CDAP-19729 : Enable upgrade for Datastream apps using state store.
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/DefaultApplicationUpdateContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsApp.java
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsPipelineSpecGenerator.java
  cdap-app-templates/cdap-etl/cdap-etl-proto/src/main/java/io/cdap/cdap/etl/proto/v2/DataStreamsConfig.java
Labels: build

#14899 Revert tethering mode changes from 6.7.3
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/runtime/ProgramRuntimeProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RuntimeJobRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/SSHRemoteProcessController.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/master/environment/DefaultMasterEnvironmentRunnableContextTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/handlers/AuthenticationHandler.java
  cdap-integration-test/src/main/java/io/cdap/cdap/test/IntegrationTestManager.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/common/AbstractWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/AppResourceWatcherThread.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeAPIException.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillContext.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillLauncher.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/ApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultApiClientFactory.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/DefaultKubeMasterPathProvider.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/PodKillerTask.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/common/AbstractWatcherThreadTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/PodKillerTaskTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironmentRunnableContext.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocRuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobManager.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/RuntimeJobStatus.java
  cdap-security/src/main/java/io/cdap/cdap/security/tools/AccessTokenGeneratorService.java
  cdap-security/src/test/java/io/cdap/cdap/security/tools/AccessTokenGeneratorServiceTest.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilters.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkRuntimeContextProvider.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/DistributedSparkProgramRunner.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/NoSparkClassLoaderTestRunner.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProviderTest.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/SparkResourceFilterTest.java
  cdap-unit-test/src/main/java/io/cdap/cdap/test/UnitTestManager.java
Labels: build

#14906 CDAP-19729 add default implementation of new method
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
Labels: build, 6.9

#14907 CDAP-19729 add default implementation of new method
  cdap-api/src/main/java/io/cdap/cdap/api/app/ApplicationUpdateContext.java
Labels: build, 6.8

#14913 Add http connection and read timeout properties for task worker pods.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.8

#14910 CDAP-20308 - Add http connection and read timeout properties for task worker pods.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9

#14908 fix macro in nested fields
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiatorTest.java
Labels: build, 6.9

#14909 fix macro in nested fields
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiatorTest.java
Labels: build, 6.8

#14886 [CDAP-20313] SourceControlManager implementation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfigValidationException.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SetRepositoryResponse.java
  cdap-proto/src/test/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfigTest.java
  cdap-source-control/pom.xml
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationConfigException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationStrategy.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationStrategyNotFoundException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/CommitMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/GitPATAuthenticationStrategy.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlConfig.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/LocalGitServer.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  pom.xml
Labels: build

#14921 [CDAP-20355] Ensure DefaultProvisionerContext property updates logging context
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#14905 Feature/cdap-20252 validate remote repository config
  cdap-app-fabric/pom.xml
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryValidationFailure.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SetRepositoryResponse.java
  cdap-standalone/pom.xml
Labels: build, 6.9

#14922 [CDAP-20355] Ensure DefaultProvisionerContext property updates logging context
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultProvisionerContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/ProvisioningService.java
Labels: build

#14924 Add http connection and read timeout properties for task worker pods.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#14918 [CDAP-20146] Force system workers to reset security context upon verifying permissions to launch a task
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
Labels: Bug, build

#14919 [CDAP-20146] Cherry-Pick 6.8 Force system workers to reset security context upon verifying permissions to launch a task
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
Labels: cherry-pick, build, 6.8

#14920 [CDAP-20146] Cherry-Pick 6.7 Force system workers to reset security context upon verifying permissions to launch a task
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
Labels: cherry-pick, build, 6.7

#14927 [CDAP-20341] Implement autocloseable for RepositoryManager instead of extending Service
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build

#14923 [CDAP-20353] RemoteClient: Decompress error responses from remote tas…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/ServiceException.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  pom.xml
Labels: build

#14929 fix(CDAP-20240): Strings.isNullOrEmpty(defaultBranchName) for repo config validation
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
Labels: build, 6.9

#14926 fix(CDAP-20361): the GET /appdetail api should return the requested versions
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
Labels: build, 6.9

#14930 [CDAP-20368] Only bind InternalAccessEnforcer when internal auth is enabled
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
Labels: Bug, build, 6.7, 6.8

#14931 [CDAP-20368] Cherry-pick 6.8
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
Labels: cherry-pick, build, 6.8

#14932 [CDAP-20368] Cherry-pick 6.7
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AuthorizationEnforcementModule.java
Labels: cherry-pick, build, 6.7

#14933 [CDAP-20353] RemoteClient: Decompress error responses from remote tas…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/RemoteTaskExecutor.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/RemoteTaskExecutorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/RemoteAppStateStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/ServiceException.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClient.java
  pom.xml
Labels: build

#14892 Initial GCP Secret Manager Secure Store implementation
  cdap-master/pom.xml
  cdap-securestore-ext-gcp-secretstore/pom.xml
  cdap-securestore-ext-gcp-secretstore/src/main/java/io/cdap/cdap/securestore/gcp/cloudsecretmanager/CloudSecretManagerClient.java
  cdap-securestore-ext-gcp-secretstore/src/main/java/io/cdap/cdap/securestore/gcp/cloudsecretmanager/GcpSecretManager.java
  cdap-securestore-ext-gcp-secretstore/src/main/java/io/cdap/cdap/securestore/gcp/cloudsecretmanager/InvalidSecretException.java
  cdap-securestore-ext-gcp-secretstore/src/main/java/io/cdap/cdap/securestore/gcp/cloudsecretmanager/WrappedSecret.java
  cdap-securestore-ext-gcp-secretstore/src/main/resources/META-INF/services/io.cdap.cdap.securestore.spi.SecretManager
  cdap-securestore-ext-gcp-secretstore/src/test/java/io/cdap/cdap/securestore/gcp/cloudsecretmanager/GcpSecretManagerTest.java
  cdap-standalone/pom.xml
  pom.xml
Labels: build, 6.9

#14873 [CDAP-19610] TetheringAgent: track program updates for each peer
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/SubscriberState.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringProgramEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/MockTetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
Labels: build

#14925 [CDAP-20341] Make PAT auth strategy fetch credentials lazily and improve exception handling
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationConfigException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationStrategy.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/AuthenticationStrategyProvider.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/GitPATAuthenticationStrategy.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RefreshableCredentialsProvider.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlConfig.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
Labels: build

#14935 [Cherry-pick] Increasing stop wait timeout to fix flaky HangingWorkerTest ITN
  cdap-client/src/main/java/io/cdap/cdap/client/ProgramClient.java
Labels: build

#14934 [CDAP-19610] TetheringAgent should track program updates for each pee…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/SubscriberState.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClient.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringClientHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringProgramEventPublisher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringServerHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManager.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/MockTetheringServerHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringClientHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/TetheringServerHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/TetheringAgentServiceMain.java
Labels: build

#14937 Cherry pick 14908
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiator.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/plugin/PluginInstantiatorTest.java
Labels: build, 6.7

#14938 Fixing updateAll and deleteAll spi methods
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#14939 [CDAP-19539] Fail tethering profile creation if peer name is invalid
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/runtime/spi/provisioner/TetheringConf.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/tethering/runtime/spi/runtimejob/TetheringRuntimeJobManagerTest.java
Labels: build

#14917 [CDAP-20343] Implement RepositoryManager#getFileHash()
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlConfig.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/LocalGitServer.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
Labels: build, 6.9

#14941 fix(CDAP-20354): return correct errors for remote repo validation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RemoteRepositoryValidationException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
Labels: build, 6.9

#14945 Adding guava dependency in e2e profile for tethering and k8s tests.
  cdap-e2e-tests/pom.xml
  cdap-kubernetes/pom.xml
Labels: build

#14911 feat(CDAP-20250): push app to linked repository
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ApplicationClientTestRun.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PushAppRequest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/CommitMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/NoChangesToPushException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManagerFactory.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlModule.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/UnexpectedRepositoryChangesException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushFailureException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
Labels: build, 6.9

#14960 fix(CDAP-20405): fix bug introduced by updated ApplicationDetail constructor
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationDetail.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/ApplicationRecord.java
Labels: build, 6.9

#14961 chore(CDAP-20406): moved RemoteTaskExecutor and related classes to cdap-common
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteConfigurator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/RemoteProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/service/http/BasicSystemHttpServiceContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutor.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RunnableTaskLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RunnableTaskModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskDetails.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutorTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/RunnableTaskLauncherTest.java
Labels: build, 6.9

#14928 [CDAP-20367] Pull Application Operation Runner Implementation
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PullAppResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PullFailureException.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
Labels: build, 6.9

#14963 fix(CDAP-20411): Inject DiscoveryService in RunnableTask and avoid calling MasterEnvironments
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/RemoteConfiguratorTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/ConfiguratorTaskTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/SystemAppTaskTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerMetricsTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RunnableTaskLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RunnableTaskModule.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutorTest.java
  cdap-common/src/test/java/io/cdap/cdap/common/internal/remote/RunnableTaskLauncherTest.java
Labels: build, 6.9
