Repository cdapio/cdap, pull requests merged in 2023-09, with the labels that each got.

#15308 fix(CDAP-20794): use Spanner null values for Spanner DB when the field value is null, also use where clause when the keyRange is not prefixed
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTable.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableTest.java
Labels: build

#15304 [CDAP-20790] Enable routing requests through InternalRouterService
  cdap-app-fabric/src/main/java/io/cdap/cdap/master/environment/k8s/MasterEnvironmentMain.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/distributed/k8s/SparkContainerDriverLauncher.java
Labels: build, 6.10

#15285 [CDAP-20764] Enable creation of Load Balancer services
  cdap-kubernetes/pom.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryService.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/discovery/KubeDiscoveryServiceTest.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
Labels: build, 6.10

#15313 [CDAP-20763] Allow disabling the internal router service
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandlerTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
Labels: build, 6.10

#15311 [CDAP-20790] Localize cConf as a configmap and support use of the internal router in workers
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceLauncher.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/ExtendedTwillPreparer.java
Labels: build, 6.10

#15318 [CDAP-20807] Fix NoSuchMethodError in GeneratedMessageV3 for static clusters with managed instance groups due to library incompatibility.
  cdap-runtime-ext-dataproc/pom.xml
Labels: build

#15323 [CDAP-20807] Remove unneeded explicit dependencies
  cdap-runtime-ext-dataproc/pom.xml
Labels: build

#15322 [CDAP-20807][🍒 for 6.9] Fix NoSuchMethodError in GeneratedMessageV3 for static clusters with managed instance groups due to library incompatibility.
  cdap-runtime-ext-dataproc/pom.xml
Labels: build, 6.9

#15321 [CDAP-20807][🍒 for 6.8] Fix NoSuchMethodError in GeneratedMessageV3 for static clusters with managed instance groups due to library incompatibility.
  cdap-runtime-ext-dataproc/pom.xml
Labels: build, 6.8

#15325 Set project version to 6.9.2 in build.properties of release/6.9 branch
  cdap-api/src/main/resources/build.properties
  cdap-common/src/main/resources/build.properties
Labels: build

#15324 fix(CDAP-20587): revert the order by clause for the default runs scan, specify the ordering for case without version info
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: build, 6.9.3

#15326 Cherrypick/CDAP-20587
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: build, 6.9.3

#15327 [CDAP-20807] Update Guava version to match google libraries needs and ensure Errors (e.g. method not found) are properly propagated.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/pom.xml
Labels: build

#15329 Revert "Cherrypick/CDAP-20587"
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: build

#15330 Set version to 6.9.2 in VERSION files
  cdap-api/src/main/resources/build.properties
  cdap-cli/src/main/resources/VERSION
  cdap-common/src/main/resources/VERSION
  cdap-common/src/main/resources/build.properties
  cdap-distributions/VERSION
Labels: build

#15331 [Cherry-pick into 6.8][CDAP-20807] Update Guava version to match google libraries needs and ensure Errors (e.g. method not found) are properly propagated.
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/DeprovisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisionTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/task/ProvisioningTask.java
  cdap-runtime-ext-dataproc/pom.xml
Labels: build

#15317 CDAP-20803: API, DB and Proto Schema for Long Running Operation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationRunHttpHandler.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/OperationRunDetail.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/store/StoreDefinition.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationResource.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationResourceScopedError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationRun.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationRunStatus.java
Labels: build, 6.10

#15335 CDAP-20827 fix extra java opts executor clobbering in k8s mode
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitterTest.java
Labels: build, 6.10

#15339 CDAP-20827 fix extra java opts executor clobbering in k8s mode
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/spark/SparkConfig.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/AbstractSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/DistributedSparkSubmitter.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitter.java
  cdap-spark-core-base/src/test/java/io/cdap/cdap/app/runtime/spark/submit/MasterEnvironmentSparkSubmitterTest.java
Labels: build, 6.9.3
