Repository cdapio/cdap, pull requests merged in 2023-08, with the labels that each got.

#15241 Added very basic flow control to subscriber
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/events/StartProgramEventSubscriber.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/events/StartProgramEventSubscriberTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15264 Revert "[CDAP-20641] remove unnecessary lines from pipeline arguments"
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineArguments.java
Labels: build

#15263 Revert "[Cherry Pick] 6.9.2-CDAP-20641"
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/SmartWorkflow.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineArguments.java
Labels: build

#15258 [CDAP-20742] Create k8s SA on namespace creation
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/NamespaceHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdminTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/NamespaceHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/security/impersonation/DefaultUGIProviderTest.java
  cdap-cli-tests/src/test/java/io/cdap/cdap/cli/CLITestBase.java
  cdap-cli/src/main/java/io/cdap/cdap/cli/command/CreateNamespaceCommand.java
  cdap-common/src/main/java/io/cdap/cdap/common/namespace/NamespaceAdmin.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironmentTest.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/environment/MasterEnvironment.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/NamespaceConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/NamespaceMeta.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AuthorizationUtilTest.java
  cdap-unit-test/src/test/java/io/cdap/cdap/security/AuthorizationTest.java
Labels: build, 6.10

#15266 [CDAP-20682] Add config to enable/disable KubeJobCleaner
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build

#15269 [cherry-pick] [CDAP-20682] Add config to enable/disable KubeJobCleaner and refactor existing configs
  cdap-common/src/main/resources/cdap-default.xml
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build, 6.9.2

#15271 CDAP-20759: Wait for cluster label to reflect
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build

#15273 [Cherry-pick into 6.9] CDAP-20759: Wait for labels to be present on cluster before returning
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
Labels: build

#15275 [CDAP-20760] add hsts default values in cdap-default.xml
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15278 [Cherry Pick] 6.9.2-CDAP-20760
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15268 [CDAP-20757] Ignore empty Common Labels property set by UI
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/common/DataprocUtilsTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build, 6.9.2

#15279 [cherry-pick][CDAP-20757] Ignore empty Common Labels property set by UI
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/common/DataprocUtils.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/AbstractDataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/common/DataprocUtilsTest.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build, 6.9.2

#15274 [CDAP-20758] Set max netty direct memory
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: build

#15280 [CDAP-20758] Set max netty direct memory
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
Labels: build

#15260 [CDAP-20479] Add sidecar metadata service for credential provisioning
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DistributedPreviewManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceLauncher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternalTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/GcpMetadataTaskContext.java
Labels: build, 6.10

#15287 Fix netty max direct memory setting
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build

#15288 Fix netty mem develop
  cdap-app-templates/cdap-etl/cdap-data-streams-base/src/main/java/io/cdap/cdap/datastreams/DataStreamsSparkLauncher.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/ETLSpark.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build

#15293 Switch to root user in cdap-spark-core docker image for sufficient permissions
  cdap-spark-core3_2.12/src/k8s/Dockerfile
Labels: build

#15292 reducing the level of entities visible log to reduce noise
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
Labels: build

#15291 reducing the level of entities visible log to reduce noise
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/meta/RemotePrivilegesHandler.java
Labels: build

#15294 Support bundle script: fix help text
  cdap-support-bundle/bin/collect_support_bundle.md
  cdap-support-bundle/bin/collect_support_bundle.py
Labels: build

#15282 [cherry-pick][CDAP-19949] Add retries for sql tx connection failures
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/RetryingSqlTransactionRunner.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionException.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableRetryTest.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlStructuredTableTest.java
Labels: build

#15283 [CDAP-20722] [cherry-pick] Limit the number of idle connections and catch errors in aux calls
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStorageProvider.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunner.java
  cdap-data-fabric/src/test/java/io/cdap/cdap/spi/data/sql/SqlTransactionRunnerTest.java
  pom.xml
Labels: build

#15296 fix(CDAP-20786): should check Spanner schema equality after compatibility conversion
  cdap-storage-ext-spanner/src/main/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdmin.java
  cdap-storage-ext-spanner/src/test/java/io/cdap/cdap/storage/spanner/SpannerStructuredTableAdminTest.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/table/StructuredTableSchema.java
  cdap-storage-spi/src/test/java/io/cdap/cdap/spi/data/StructuredTableAdminTest.java
Labels: build

#15298 Enable feature flag for Wrangler filter pushdown by default
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9.2

#15299 Enable feature flag for Wrangler filter pushdown by default
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.9.2

#15276 [CDAP-20763] Create a new InternalRouter service to route worker requests
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/AbstractServiceRoutingHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/InternalRouterService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/InternalServiceRoutingHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/MockServiceHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeServiceRoutingTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
Labels: build, 6.10

#15305 CDAP-20791 fix master service startup on Hadoop
  cdap-master/src/main/java/io/cdap/cdap/data/runtime/main/MasterServiceMain.java
Labels: build, 6.10
