Repository cdapio/cdap, pull requests merged in 2023-12, with the labels that each got.

#15479 [Cherry-pick 6.10][CDAP-20911] Fix ClassCastException by adding a workaround for SPARK-46176
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/DatasetDataPipelineTest.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/Constants.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSparkPipelineDriver.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/OpaqueDatasetCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/function/TransformFunction.java
Labels: build

#15484 [CDAP-20915] Use exprEnc() instead of encoder() as latter is only available in Spark 3
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/OpaqueDatasetCollection.java
Labels: build

#15485 [Cherry-pic into 6.10][CDAP-20915] Use exprEnc() instead of encoder() as latter is only available in Spark 3
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollection.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/OpaqueDatasetCollection.java
Labels: build

#15428 Features for hub
  cdap-e2e-tests/src/e2e-test/features/Hub/DesignTime.feature
  cdap-e2e-tests/src/e2e-test/features/Hub/Runtime.feature
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/hub/runners/TestRunner.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/hub/runners/package-info.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/hub/stepsdesign/TestSetupHooks.java
  cdap-e2e-tests/src/e2e-test/java/io/cdap/cdap/hub/stepsdesign/package-info.java
  cdap-e2e-tests/src/e2e-test/resources/errorMessage.properties
  cdap-e2e-tests/src/e2e-test/resources/pluginDataCyAttributes.properties
  cdap-e2e-tests/src/e2e-test/resources/pluginParameters.properties
Labels: build

#15495 [CDAP-20920] Use spark partitions autotuning for predefined autoscaling policy
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: build

#15480 [CDAP-20910] Close class loaders to prevent memory leaks
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/ArtifactClassLoaderFactory.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/plugin/PluginClassLoader.java
  cdap-common/src/main/java/io/cdap/cdap/common/lang/PackageFilterClassLoader.java
  cdap-spark-core-base/src/main/java/io/cdap/cdap/app/runtime/spark/SparkProgramRuntimeProvider.java
Labels: build, 6.10

#15496 [Cherry-pick into 6.10][CDAP-20920] Use spark partitions autotuning for predefined autoscaling policy
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocClient.java
Labels: build

#15499 fix scm multi feature flag issue in sandbox
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15493 CDAP-20916: Add pull/push count metrics
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.10, multi_scm_op

#15482 CDAP-20914: Updated plugin missing error copytext
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: build

#15501 [🍒 ] Add Add pull/push count metrics from #15493
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
Labels: build, 6.10

#15502 [🍒 ] Updated plugin missing error copy text from #15482
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/spec/PipelineSpecGenerator.java
Labels: build

#15500 [🍒] fix scm multi feature flag issue in sandbox (from #15499)
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15505 Bugfix/cdap 20896 secure key validation and tooltip
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/SecureKeyId.java
Labels: build

#15506 [🍒 ] updated error message in securekeyid from #15505
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/SecureKeyId.java
Labels: build

#15503 CDAP-20852 : adding old spi for backward compatibility
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerInstantiator.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AccessControllerInstantiatorTest.java
Labels: build

#15498 CDAP-20918-add-extra-metadata
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperation.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/UpdateMultiSourceControlMetaReqeust.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PullAppResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppsResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PushAppTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build, 6.10, multi_scm_op

#15507 [🍒 ] CDAP-20918: Add lastsync time and commitid from #15498
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperation.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PushAppsOperationTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/UpdateMultiSourceControlMetaReqeust.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/RepositoryManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PullAppResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppMeta.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/PushAppsResponse.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/operationrunner/SourceControlOperationRunner.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/worker/PushAppTask.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/RepositoryManagerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/InMemorySourceControlOperationRunnerTest.java
  cdap-source-control/src/test/java/io/cdap/cdap/sourcecontrol/operationrunner/RemoteSourceControlOperationRunnerTest.java
Labels: build

#15504 [cherrypick][6.10]CDAP-20852 : adding old spi for backward compatibility
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/AccessControllerInstantiator.java
  cdap-security/src/test/java/io/cdap/cdap/security/authorization/AccessControllerInstantiatorTest.java
Labels: build

#15511 [CDAP-20924] Use internal router for creating remote clients when configured and using alternate factory method
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
Labels: build, 6.10

#15512 [Cherrypick][CDAP-20924] Use internal router for creating remote clients when configured and using alternate factory method
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteClientFactory.java
Labels: build, 6.10

#15513 [CDAP-20928] Disable SSL verification for internal clients in system services
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/services/AbstractServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/InternalRouterService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15515 [Cherrypick][CDAP-20928] Disable SSL verification for internal clients in system services
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/services/AbstractServiceDiscoverer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/InternalRouterService.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10
