Repository cdapio/cdap, pull requests merged in 2023-10, with the labels that each got.

#15342 Cherrypick/CDAP-20587
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
Labels: build, 6.9.3

#15312 [CDAP-20795] Create NamespaceWorkloadIdentity and GcpWorkloadIdentityHandler
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/AppFabricServiceRuntimeModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/namespace/DefaultNamespaceAdmin.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/AppFabricServer.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/GcpMetadataHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/RemoteCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/credential/guice/MasterCredentialProviderModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/DefaultNamespaceCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/GcpWorkloadIdentityUtil.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/NamespaceCredentialProviderService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/RemoteNamespaceCredentialProvider.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/credential/DefaultCredentialProviderServiceTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceCredentialProvider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/credential/NamespaceWorkloadIdentity.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/security/NamespacePermission.java
Labels: build

#15338 [CDAP-20826] Add label for CDAP install namespace in Kube Twill Preparer
  cdap-kubernetes/src/main/java/io/cdap/cdap/master/environment/k8s/KubeMasterEnvironment.java
Labels: build

#15348 [CDAP-20840] Check for empty LDAP password
  cdap-security/src/main/java/io/cdap/cdap/security/server/JAASLoginService.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalLDAPAuthenticationServerTest.java
Labels: build

#15349 [CDAP-20840] Check for empty LDAP password
  cdap-security/src/main/java/io/cdap/cdap/security/server/JAASLoginService.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalLDAPAuthenticationServerTest.java
Labels: build

#15320 Add operation run store methods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/OperationRunAlreadyExistsException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/OperationRunFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/OperationRunNotFoundException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/OperationRunStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operations/ScanOperationRunsRequest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operations/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operations/SqlOperationRunsStoreTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/internal/app/store/OperationRunDetail.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/element/EntityType.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/OperationRunId.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operationrun/OperationRun.java
  cdap-security/src/main/java/io/cdap/cdap/security/authorization/DefaultAccessEnforcer.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: build

#15350 [CDAP-20797] Ensures DefaultSystemProvisionerContext properties are (re)loaded when it is initialized
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
Labels: build, 6.10, 6.9.3

#15352 [CDAP-20841] Set default version of dataproc to 2.1
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisioner.java
  cdap-runtime-ext-dataproc/src/test/java/io/cdap/cdap/runtime/spi/provisioner/dataproc/DataprocProvisionerTest.java
Labels: build

#15355 [CDAP-20840] Check for empty LDAP password
  cdap-security/src/main/java/io/cdap/cdap/security/server/JAASLoginService.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalLDAPAuthenticationServerTest.java
Labels: build

#15354 [CDAP-20831] Forces task worker to restart if ongoing request is stuck
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
Labels: build, 6.10

#15363 [CDAP-20840] Check for empty LDAP password
  cdap-security/src/main/java/io/cdap/cdap/security/server/JAASLoginService.java
  cdap-security/src/test/java/io/cdap/cdap/security/server/ExternalLDAPAuthenticationServerTest.java
Labels: build

#15357 [CDAP-20824] Emit zero for flow-control launching metric if there is no inflight launching pipeline when appfabric starts
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ProgramNotificationSubscriberService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/RunRecordMonitorService.java
Labels: build, 6.10

#15367 [CDAP-20628] Auto install: fix pipeline JSON parsing
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/autoinstall/Spec.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/capability/AutoInstallTest.java
  cdap-app-fabric/src/test/resources/spec2.json
Labels: build

#15359 [CDAP-20820] Skip autoinstall if it's already done
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: build

#15370 [CDAP-20820] Skip autoinstall if it's already done
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
Labels: build

#15366 [CDAP-20846] Fetch artifacts from cache for tethered runs with pushdo…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
Labels: build

#15360 [CDAP-20792] Fix CDAP-20792 failure on shutdown
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
Labels: build

#15374 [CDAP-20846] Fetch artifacts from cache for tethered runs with pushdo…
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/InMemoryProgramRunDispatcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteIsolatedPluginFinder.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemotePluginFinder.java
Labels: build

#15373 [CDAP-20792] Fix CDAP-20792 failure on shutdown
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerServiceTest.java
Labels: build

#15368 CDAP-20809 Add LongRunningOperation interface
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/OperationHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/AbstractLongRunningOperationContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/LongRunningOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/LongRunningOperationContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationLifecycleManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunAlreadyExistsException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunDetail.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunNotFoundException.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/OperationRunStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/operation/ScanOperationRunsRequest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/OperationRunStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/operation/SqlOperationRunsStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationMeta.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationResource.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationResourceScopedError.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRun.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationRunStatus.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/operation/OperationType.java
Labels: build

#15371 [CDAP-20749] Set the GcpMetadataTaskContext before preview run
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/namespace/credential/handler/GcpWorkloadIdentityHttpHandler.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerMetricsTest.java
  cdap-common/pom.xml
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/java/io/cdap/cdap/common/utils/GcpMetadataTaskContextUtil.java
  cdap-credential-ext-gcp-wi/src/main/java/io/cdap/cdap/security/spi/credential/GcpWorkloadIdentityCredentialProvider.java
Labels: build

#15351 [cherry-pick] [CDAP-20797] Ensures DefaultSystemProvisionerContext properties are (re)loaded when it is initialized
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/provision/DefaultSystemProvisionerContext.java
Labels: build

#15336 add the internal marklatest api
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AbstractAppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/AppDeploymentInfo.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationDeployable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationRegistrationStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/ApplicationWithPrograms.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/deploy/pipeline/LocalArtifactLoaderStage.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/DefaultPreviewRunner.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/ApplicationMeta.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/bootstrap/executor/AppCreator.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/capability/CapabilityApplier.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/sysapp/SystemAppEnableExecutor.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/deploy/Specifications.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SystemProgramManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/AppFabricTestBase.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-gateway/src/main/java/io/cdap/cdap/gateway/router/ExpectedNumberOfAuditPolicyPaths.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/AppVersion.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/MarkLatestAppsRequest.java
Labels: build

#15340 add the internal updateGitMetadata api
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandlerInternal.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/DefaultStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/UpdateMultiSourceControlMetaReqeust.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/UpdateSourceControlMetaRequest.java
Labels: build, 6.10

#15377 [CDAP-20845] Enable the use of Messaging Service extensions - Part 3
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/guice/DistributedProgramContainerModule.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/preview/PreviewRunnerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/SystemAppTask.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/TaskWorkerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/sidecar/ArtifactLocalizerTwillRunnable.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerTwillRunnable.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/resources/cdap-default.xml
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AppFabricServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/ArtifactCacheServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/AuthenticationServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/LogsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetadataServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/MetricsServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/PreviewServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RouterServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/RuntimeServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SupportBundleServiceMain.java
  cdap-master/src/main/java/io/cdap/cdap/master/environment/k8s/SystemMetricsExporterServiceMain.java
  cdap-messaging-spi/src/main/java/io/cdap/cdap/messaging/spi/MessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/ClientMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/DelegatingMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/client/MessagingServiceExtensionLoader.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/distributed/LeaderElectionMessagingService.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/guice/MessagingServiceModule.java
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
Labels: build, 6.10

#15380 [CDAP-20861] Improve OAuth logging and error handling
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build, 6.10

#15381 [Cherry-pick] [CDAP-20861] Improve OAuth logging and error handling
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#15382 [CDAP-20845] Deprecate transactional feature in cdap-messaging-spi - Part 4
  cdap-messaging-spi/src/main/java/io/cdap/cdap/messaging/spi/MessagingService.java
  cdap-messaging-spi/src/main/java/io/cdap/cdap/messaging/spi/RollbackDetail.java
  cdap-messaging-spi/src/main/java/io/cdap/cdap/messaging/spi/StoreRequest.java
Labels: build, 6.10

#15388 [CDAP-20658] Remove unneeded DataFrame->RDD conversion
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchCollectionFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/BatchSQLEngineAdapter.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/DataframeCollectionFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/RDDCollectionFactory.java
  cdap-app-templates/cdap-etl/hydrator-spark-core-base/src/main/java/io/cdap/cdap/etl/spark/batch/SQLEngineCollection.java
Labels: build

#15379 CDAP-20862 Add ApplicationManager Helper class for SCM
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/LocalApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperation.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/sourcecontrol/RemoteApplicationManager.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/LocalApplicationDetailFetcher.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/ApplicationManagerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/sourcecontrol/PullAppsOperationTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/app/AppVersion.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/id/ApplicationId.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/ApplicationManager.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/SourceControlException.java
Labels: build, 6.10

#15390 [CDAP-20871] Reset concurrent request count in system worker when returning 429 response
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
Labels: build, 6.10

#15395 [CDAP-20871][Cherrypick] System worker capacity leak
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerHttpHandlerInternal.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/system/SystemWorkerServiceTest.java
Labels: build

#15393 [CDAP-20869] Fix closing message tables
  cdap-tms/src/main/java/io/cdap/cdap/messaging/service/CoreMessagingService.java
Labels: build, 6.10
