Repository cdapio/cdap, pull requests merged in 2024-04, with the labels that each got.

#15577 [CDAP-20835] Add retries for remote artifact and remote application calls
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/artifact/RemoteArtifactRepositoryReader.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteApplicationDetailFetcher.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/ArtifactHttpHandlerInternalTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/metadata/ApplicationDetailFetcherTest.java
Labels: build, 6.10

#15574 [CDAP-20819] Throw an exception in DefaultRuntimeJob when program fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/ProgramRunCompletionDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJobTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/ProgramRunFailureException.java
Labels: build, 6.10

#15579 [Cherry-pick][CDAP-20819] Throw an exception in DefaultRuntimeJob when program fails
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJob.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/ProgramRunCompletionDetails.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientService.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/distributed/runtimejob/DefaultRuntimeJobTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/monitor/RuntimeClientServiceTest.java
  cdap-runtime-ext-dataproc/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/DataprocJobMain.java
  cdap-runtime-spi/src/main/java/io/cdap/cdap/runtime/spi/runtimejob/ProgramRunFailureException.java
Labels: build, 6.10

#15518 [CDAP-20932] Decode principal name in git committer
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/PatAuthenticationStrategy.java
Labels: build, scm_updates

#15576 [CDAP-20834] Replace usage of printStack with logger
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
Labels: build, 6.10

#15581 [Cherry-pick][CDAP-20834] Replace usage of printStack with logger
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
Labels: build, 6.10

#15583 [Cherry-pick][CDAP-20987] OAuthHandler should return response details in the exception other than response code when request fails
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
Labels: build, 6.10

#15580 Add bitbucket cloud and server support
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/AuthConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PatConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/Provider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfig.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/PatAuthenticationStrategy.java
Labels: build, scm_updates

#15587 [CDAP-20984] Add 19 GCP regions to dataproc supported regions list in compute profile
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
Labels: build

#15589 [🍒 ][CDAP-20984] Add 19 regions to dataproc supported regions list in compute profile
  cdap-runtime-ext-dataproc/src/main/resources/gcp-dataproc.json
  cdap-runtime-ext-dataproc/src/main/resources/gcp-existing-dataproc.json
Labels: build

#15588 [CDAP-20980] Do not retry service exception in task workers
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutor.java
Labels: build

#15592 [🍒][CDAP-20980] Do not retry service exception in task workers
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutor.java
Labels: build

#15594 [🍒] Decode principal correctly in case internal auth is enabled
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/PatAuthenticationStrategy.java
Labels: build

#15598 [CDAP-20999] Encode schedule names in the schedule client
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteScheduleFetcher.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ScheduleClientTestRun.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ScheduleClient.java
Labels: build

#15596 [🍒] Add bitbucket cloud and server support
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/AuthConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/PatConfig.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/Provider.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/RepositoryConfig.java
  cdap-source-control/src/main/java/io/cdap/cdap/sourcecontrol/PatAuthenticationStrategy.java
Labels: build

#15600 [CDAP-20959] Don't upload Spark event logs for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
Labels: build

#15601 [CDAP-20959] Don't upload Spark event logs for tethered runs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/tethering/TetheringAgentService.java
Labels: build

#15551 [CDAP-20933] Fix k8s resource name cleaning logic
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparer.java
  cdap-kubernetes/src/test/java/io/cdap/cdap/k8s/runtime/KubeTwillPreparerTest.java
Labels: build

#15593 [CDAP-20990 ] Added Repo Source control metadata store methods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlNamespaceSourceControlMetadataTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlRepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlNamespaceSourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlRepositorySourceControlMetadataStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
Labels: build

#15585 [CDAP-20988] fix maxConcurrentRuns constraint in pipeline schedules
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConstraintContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraintTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
Labels: build, 6.10

#15602 [🍒 ] Added Repo Source control metadata store methods
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlNamespaceSourceControlMetadataTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlRepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlNamespaceSourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SqlRepositorySourceControlMetadataStoreTest.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/sourcecontrol/SourceControlMeta.java
Labels: build

#15606 [CDAP-20905] do not throw invalid macro exception because it skips failures when skip invalid macros is enabled
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#15607 [🍒][CDAP-20905] do not throw invalid macro exception because it skips failures when skip invalid macros is enabled
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#15524 Update twill version
  pom.xml
Labels: build

#15610 Cherrypick fix for CDAP-20913
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/DistributedProgramRuntimeService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/ProgramTwillApplication.java
  cdap-common/src/main/java/io/cdap/cdap/common/twill/TwillAppNames.java
  cdap-common/src/test/java/io/cdap/cdap/common/twill/TwillAppNamesTest.java
  cdap-kubernetes/src/main/java/io/cdap/cdap/k8s/runtime/KubeTwillRunnerService.java
  cdap-master-spi/src/main/java/io/cdap/cdap/master/spi/twill/ExtendedTwillApplication.java
  pom.xml
Labels: build

#15604 [🍒] fix maxConcurrentRuns (to 6.10)
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraint.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConstraintContext.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/runtime/schedule/constraint/ConcurrencyConstraintTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
Labels: build

#15613 [🍒][CDAP-20905] do not throw invalid macro exception because it skips failures when skip invalid macros is enabled
  cdap-app-templates/cdap-etl/cdap-etl-core/src/main/java/io/cdap/cdap/etl/common/AbstractServiceRetryableMacroEvaluator.java
Labels: build

#15619 [Cherry-pick][CDAP-20834] Replace usage of printStack with logger
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
Labels: build

#15284 [CDAP-20683] Propogate logs from System Worker to Pipeline Logs
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-common/src/main/java/io/cdap/cdap/common/logging/LoggingContextAccessor.java
Labels: build

#15612 [CDAP-21010] fix get application count metric to not count different versions as different application
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: build

#15614 [🍒][CDAP-20999] Encode schedule names in the schedule client
  cdap-app-fabric/src/main/java/io/cdap/cdap/metadata/RemoteScheduleFetcher.java
  cdap-client-tests/src/test/java/io/cdap/cdap/client/ScheduleClientTestRun.java
  cdap-client/src/main/java/io/cdap/cdap/client/ApplicationClient.java
  cdap-client/src/main/java/io/cdap/cdap/client/ScheduleClient.java
Labels: build

#15620 [🍒][CDAP-21010] fix get application count metric to not count different versions as different application
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/AppMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/AppMetadataStoreTest.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/common/MetricStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/nosql/NoSqlStructuredTable.java
  cdap-data-fabric/src/main/java/io/cdap/cdap/spi/data/sql/PostgreSqlStructuredTable.java
  cdap-storage-spi/src/main/java/io/cdap/cdap/spi/data/StructuredTable.java
Labels: build

#15615 [🍒][CDAP-20980] Do not retry service exception in task workers
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/RemoteTaskExecutor.java
Labels: build

#15618 [Cherry-pick][CDAP-20987] OAuthHandler should return response details in the exception other than response code when request fails
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
Labels: build

#15611 [CDAP-21006] Create OAuth Provider reusing existing secrets in GCP Secret Manager
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthProvider.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/OAuthServiceTest.java
Labels: build

#15621 [🍒][CDAP-21006] Create OAuth Provider reusing existing secrets in GCP Secret Manager
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthProvider.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/oauth/OAuthStore.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/main/java/io/cdap/cdap/datapipeline/service/OAuthHandler.java
  cdap-app-templates/cdap-etl/cdap-data-pipeline-base/src/test/java/io/cdap/cdap/datapipeline/OAuthServiceTest.java
Labels: build

#15627 PLUING-1755: Add feature flag for kryo serialization in wrangler
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build

#15625 [🍒][CDAP-20683] Propagate all exception details form system worker to appfabric when starting pipelines
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-common/src/main/java/io/cdap/cdap/common/logging/LoggingContextAccessor.java
Labels: build

#15624 [🍒][CDAP-20683] Propagate all exception details form system worker to appfabric when starting pipelines
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/runtime/distributed/remote/RemoteExecutionTwillRunnerService.java
  cdap-common/src/main/java/io/cdap/cdap/common/logging/LoggingContextAccessor.java
Labels: build

#15575 [CDAP-20832] Enable periodic restart when task workers are running concurrent requests
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build, 6.10

#15628 Revert "[CDAP-20832] Enable periodic restart when task workers are running concurrent requests"
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15631 [🍒][6.10][CDAP-20832] Enable periodic restart when task workers are running co…
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/worker/TaskWorkerServiceTest.java
  cdap-common/src/main/java/io/cdap/cdap/common/conf/Constants.java
  cdap-common/src/main/java/io/cdap/cdap/common/internal/remote/TaskWorkerHttpHandlerInternal.java
  cdap-common/src/main/resources/cdap-default.xml
Labels: build

#15584 [CDAP-20989] Add API implementations for Namespace and Repository Source Control Metadata
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/ScanSourceControlMetadataRequest.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/SourceControlMetadataFilter.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/app/store/Store.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/AppLifecycleHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/SourceControlManagementHttpHandler.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/gateway/handlers/util/SourceControlMetadataHelper.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/services/SourceControlManagementService.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/DefaultStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStore.java
  cdap-app-fabric/src/main/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStore.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/ApplicationLifecycleServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/SourceControlManagementServiceTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/AppLifecycleHttpHandlerTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/services/http/handlers/SourceControlManagementHttpHandlerTests.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NamespaceSourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlNamespaceSourceControlMetadataTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/NoSqlRepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/RepositorySourceControlMetadataStoreTest.java
  cdap-app-fabric/src/test/java/io/cdap/cdap/internal/app/store/SourceControlMetadataTestUtil.java
  cdap-common/src/main/java/io/cdap/cdap/common/SourceControlMetadataNotFoundException.java
  cdap-proto/src/main/java/io/cdap/cdap/proto/SourceControlMetadataRecord.java
Labels: build

#15629 [🍒] Add feature flag for kryo serialization in wrangler
  cdap-common/src/main/resources/cdap-default.xml
  cdap-features/src/main/java/io/cdap/cdap/features/Feature.java
Labels: build
